/*
** The author disclaims copyright to this source code.  In place of
** a legal notice, here is a blessing:
**
**    May you do good and not evil.
**    May you find forgiveness for yourself and forgive others.
**    May you share freely, never taking more than you give.
**
** @generated by syntaqlite-codegen — DO NOT EDIT
*/

#ifndef SYNTAQLITE_SQLITE_NODE_H
#define SYNTAQLITE_SQLITE_NODE_H

#include <stddef.h>
#include <stdint.h>

#include "syntaqlite/types.h"

#ifdef __cplusplus
extern "C" {
#endif

// ============ Value Enums ============

typedef enum SyntaqliteBool {
    SYNTAQLITE_BOOL_FALSE = 0,
    SYNTAQLITE_BOOL_TRUE = 1
} SyntaqliteBool;

typedef enum SyntaqliteLiteralType {
    SYNTAQLITE_LITERAL_TYPE_INTEGER = 0,
    SYNTAQLITE_LITERAL_TYPE_FLOAT = 1,
    SYNTAQLITE_LITERAL_TYPE_STRING = 2,
    SYNTAQLITE_LITERAL_TYPE_BLOB = 3,
    SYNTAQLITE_LITERAL_TYPE_NULL = 4,
    SYNTAQLITE_LITERAL_TYPE_CURRENT = 5,
    SYNTAQLITE_LITERAL_TYPE_QNUMBER = 6
} SyntaqliteLiteralType;

typedef enum SyntaqliteBinaryOp {
    SYNTAQLITE_BINARY_OP_PLUS = 0,
    SYNTAQLITE_BINARY_OP_MINUS = 1,
    SYNTAQLITE_BINARY_OP_STAR = 2,
    SYNTAQLITE_BINARY_OP_SLASH = 3,
    SYNTAQLITE_BINARY_OP_REM = 4,
    SYNTAQLITE_BINARY_OP_LT = 5,
    SYNTAQLITE_BINARY_OP_GT = 6,
    SYNTAQLITE_BINARY_OP_LE = 7,
    SYNTAQLITE_BINARY_OP_GE = 8,
    SYNTAQLITE_BINARY_OP_EQ = 9,
    SYNTAQLITE_BINARY_OP_NE = 10,
    SYNTAQLITE_BINARY_OP_AND = 11,
    SYNTAQLITE_BINARY_OP_OR = 12,
    SYNTAQLITE_BINARY_OP_BITAND = 13,
    SYNTAQLITE_BINARY_OP_BITOR = 14,
    SYNTAQLITE_BINARY_OP_LSHIFT = 15,
    SYNTAQLITE_BINARY_OP_RSHIFT = 16,
    SYNTAQLITE_BINARY_OP_CONCAT = 17,
    SYNTAQLITE_BINARY_OP_PTR = 18
} SyntaqliteBinaryOp;

typedef enum SyntaqliteUnaryOp {
    SYNTAQLITE_UNARY_OP_MINUS = 0,
    SYNTAQLITE_UNARY_OP_PLUS = 1,
    SYNTAQLITE_UNARY_OP_BITNOT = 2,
    SYNTAQLITE_UNARY_OP_NOT = 3
} SyntaqliteUnaryOp;

typedef enum SyntaqliteCompoundOp {
    SYNTAQLITE_COMPOUND_OP_UNION = 0,
    SYNTAQLITE_COMPOUND_OP_UNION_ALL = 1,
    SYNTAQLITE_COMPOUND_OP_INTERSECT = 2,
    SYNTAQLITE_COMPOUND_OP_EXCEPT = 3
} SyntaqliteCompoundOp;

typedef enum SyntaqliteIsOp {
    SYNTAQLITE_IS_OP_IS = 0,
    SYNTAQLITE_IS_OP_IS_NOT = 1,
    SYNTAQLITE_IS_OP_ISNULL = 2,
    SYNTAQLITE_IS_OP_NOTNULL = 3,
    SYNTAQLITE_IS_OP_IS_NOT_DISTINCT = 4,
    SYNTAQLITE_IS_OP_IS_DISTINCT = 5
} SyntaqliteIsOp;

typedef enum SyntaqliteForeignKeyAction {
    SYNTAQLITE_FOREIGN_KEY_ACTION_NO_ACTION = 0,
    SYNTAQLITE_FOREIGN_KEY_ACTION_SET_NULL = 1,
    SYNTAQLITE_FOREIGN_KEY_ACTION_SET_DEFAULT = 2,
    SYNTAQLITE_FOREIGN_KEY_ACTION_CASCADE = 3,
    SYNTAQLITE_FOREIGN_KEY_ACTION_RESTRICT = 4
} SyntaqliteForeignKeyAction;

typedef enum SyntaqliteGeneratedColumnStorage {
    SYNTAQLITE_GENERATED_COLUMN_STORAGE_VIRTUAL = 0,
    SYNTAQLITE_GENERATED_COLUMN_STORAGE_STORED = 1
} SyntaqliteGeneratedColumnStorage;

typedef enum SyntaqliteColumnConstraintKind {
    SYNTAQLITE_COLUMN_CONSTRAINT_KIND_DEFAULT = 0,
    SYNTAQLITE_COLUMN_CONSTRAINT_KIND_NOT_NULL = 1,
    SYNTAQLITE_COLUMN_CONSTRAINT_KIND_PRIMARY_KEY = 2,
    SYNTAQLITE_COLUMN_CONSTRAINT_KIND_UNIQUE = 3,
    SYNTAQLITE_COLUMN_CONSTRAINT_KIND_CHECK = 4,
    SYNTAQLITE_COLUMN_CONSTRAINT_KIND_REFERENCES = 5,
    SYNTAQLITE_COLUMN_CONSTRAINT_KIND_COLLATE = 6,
    SYNTAQLITE_COLUMN_CONSTRAINT_KIND_GENERATED = 7,
    SYNTAQLITE_COLUMN_CONSTRAINT_KIND_NULL = 8
} SyntaqliteColumnConstraintKind;

typedef enum SyntaqliteTableConstraintKind {
    SYNTAQLITE_TABLE_CONSTRAINT_KIND_PRIMARY_KEY = 0,
    SYNTAQLITE_TABLE_CONSTRAINT_KIND_UNIQUE = 1,
    SYNTAQLITE_TABLE_CONSTRAINT_KIND_CHECK = 2,
    SYNTAQLITE_TABLE_CONSTRAINT_KIND_FOREIGN_KEY = 3
} SyntaqliteTableConstraintKind;

typedef enum SyntaqliteMaterialized {
    SYNTAQLITE_MATERIALIZED_DEFAULT = 0,
    SYNTAQLITE_MATERIALIZED_MATERIALIZED = 1,
    SYNTAQLITE_MATERIALIZED_NOT_MATERIALIZED = 2
} SyntaqliteMaterialized;

typedef enum SyntaqliteConflictAction {
    SYNTAQLITE_CONFLICT_ACTION_DEFAULT = 0,
    SYNTAQLITE_CONFLICT_ACTION_ROLLBACK = 1,
    SYNTAQLITE_CONFLICT_ACTION_ABORT = 2,
    SYNTAQLITE_CONFLICT_ACTION_FAIL = 3,
    SYNTAQLITE_CONFLICT_ACTION_IGNORE = 4,
    SYNTAQLITE_CONFLICT_ACTION_REPLACE = 5
} SyntaqliteConflictAction;

typedef enum SyntaqliteRaiseType {
    SYNTAQLITE_RAISE_TYPE_IGNORE = 0,
    SYNTAQLITE_RAISE_TYPE_ROLLBACK = 1,
    SYNTAQLITE_RAISE_TYPE_ABORT = 2,
    SYNTAQLITE_RAISE_TYPE_FAIL = 3
} SyntaqliteRaiseType;

typedef enum SyntaqliteDropObjectType {
    SYNTAQLITE_DROP_OBJECT_TYPE_TABLE = 0,
    SYNTAQLITE_DROP_OBJECT_TYPE_INDEX = 1,
    SYNTAQLITE_DROP_OBJECT_TYPE_VIEW = 2,
    SYNTAQLITE_DROP_OBJECT_TYPE_TRIGGER = 3
} SyntaqliteDropObjectType;

typedef enum SyntaqliteAlterOp {
    SYNTAQLITE_ALTER_OP_RENAME_TABLE = 0,
    SYNTAQLITE_ALTER_OP_RENAME_COLUMN = 1,
    SYNTAQLITE_ALTER_OP_DROP_COLUMN = 2,
    SYNTAQLITE_ALTER_OP_ADD_COLUMN = 3
} SyntaqliteAlterOp;

typedef enum SyntaqliteTransactionType {
    SYNTAQLITE_TRANSACTION_TYPE_DEFERRED = 0,
    SYNTAQLITE_TRANSACTION_TYPE_IMMEDIATE = 1,
    SYNTAQLITE_TRANSACTION_TYPE_EXCLUSIVE = 2
} SyntaqliteTransactionType;

typedef enum SyntaqliteTransactionOp {
    SYNTAQLITE_TRANSACTION_OP_BEGIN = 0,
    SYNTAQLITE_TRANSACTION_OP_COMMIT = 1,
    SYNTAQLITE_TRANSACTION_OP_ROLLBACK = 2
} SyntaqliteTransactionOp;

typedef enum SyntaqliteSavepointOp {
    SYNTAQLITE_SAVEPOINT_OP_SAVEPOINT = 0,
    SYNTAQLITE_SAVEPOINT_OP_RELEASE = 1,
    SYNTAQLITE_SAVEPOINT_OP_ROLLBACK_TO = 2
} SyntaqliteSavepointOp;

typedef enum SyntaqliteSortOrder {
    SYNTAQLITE_SORT_ORDER_ASC = 0,
    SYNTAQLITE_SORT_ORDER_DESC = 1
} SyntaqliteSortOrder;

typedef enum SyntaqliteNullsOrder {
    SYNTAQLITE_NULLS_ORDER_NONE = 0,
    SYNTAQLITE_NULLS_ORDER_FIRST = 1,
    SYNTAQLITE_NULLS_ORDER_LAST = 2
} SyntaqliteNullsOrder;

typedef enum SyntaqliteJoinType {
    SYNTAQLITE_JOIN_TYPE_COMMA = 0,
    SYNTAQLITE_JOIN_TYPE_INNER = 1,
    SYNTAQLITE_JOIN_TYPE_LEFT = 2,
    SYNTAQLITE_JOIN_TYPE_RIGHT = 3,
    SYNTAQLITE_JOIN_TYPE_FULL = 4,
    SYNTAQLITE_JOIN_TYPE_CROSS = 5,
    SYNTAQLITE_JOIN_TYPE_NATURAL_INNER = 6,
    SYNTAQLITE_JOIN_TYPE_NATURAL_LEFT = 7,
    SYNTAQLITE_JOIN_TYPE_NATURAL_RIGHT = 8,
    SYNTAQLITE_JOIN_TYPE_NATURAL_FULL = 9
} SyntaqliteJoinType;

typedef enum SyntaqliteTriggerTiming {
    SYNTAQLITE_TRIGGER_TIMING_BEFORE = 0,
    SYNTAQLITE_TRIGGER_TIMING_AFTER = 1,
    SYNTAQLITE_TRIGGER_TIMING_INSTEAD_OF = 2
} SyntaqliteTriggerTiming;

typedef enum SyntaqliteTriggerEventType {
    SYNTAQLITE_TRIGGER_EVENT_TYPE_DELETE = 0,
    SYNTAQLITE_TRIGGER_EVENT_TYPE_INSERT = 1,
    SYNTAQLITE_TRIGGER_EVENT_TYPE_UPDATE = 2
} SyntaqliteTriggerEventType;

typedef enum SyntaqliteExplainMode {
    SYNTAQLITE_EXPLAIN_MODE_EXPLAIN = 0,
    SYNTAQLITE_EXPLAIN_MODE_QUERY_PLAN = 1
} SyntaqliteExplainMode;

typedef enum SyntaqlitePragmaForm {
    SYNTAQLITE_PRAGMA_FORM_BARE = 0,
    SYNTAQLITE_PRAGMA_FORM_EQ = 1,
    SYNTAQLITE_PRAGMA_FORM_CALL = 2
} SyntaqlitePragmaForm;

typedef enum SyntaqliteAnalyzeKind {
    SYNTAQLITE_ANALYZE_KIND_ANALYZE = 0,
    SYNTAQLITE_ANALYZE_KIND_REINDEX = 1
} SyntaqliteAnalyzeKind;

typedef enum SyntaqliteFrameType {
    SYNTAQLITE_FRAME_TYPE_NONE = 0,
    SYNTAQLITE_FRAME_TYPE_RANGE = 1,
    SYNTAQLITE_FRAME_TYPE_ROWS = 2,
    SYNTAQLITE_FRAME_TYPE_GROUPS = 3
} SyntaqliteFrameType;

typedef enum SyntaqliteFrameBoundType {
    SYNTAQLITE_FRAME_BOUND_TYPE_UNBOUNDED_PRECEDING = 0,
    SYNTAQLITE_FRAME_BOUND_TYPE_EXPR_PRECEDING = 1,
    SYNTAQLITE_FRAME_BOUND_TYPE_CURRENT_ROW = 2,
    SYNTAQLITE_FRAME_BOUND_TYPE_EXPR_FOLLOWING = 3,
    SYNTAQLITE_FRAME_BOUND_TYPE_UNBOUNDED_FOLLOWING = 4
} SyntaqliteFrameBoundType;

typedef enum SyntaqliteFrameExclude {
    SYNTAQLITE_FRAME_EXCLUDE_NONE = 0,
    SYNTAQLITE_FRAME_EXCLUDE_NO_OTHERS = 1,
    SYNTAQLITE_FRAME_EXCLUDE_CURRENT_ROW = 2,
    SYNTAQLITE_FRAME_EXCLUDE_GROUP = 3,
    SYNTAQLITE_FRAME_EXCLUDE_TIES = 4
} SyntaqliteFrameExclude;

// ============ Flags Types ============

typedef union SyntaqliteAggregateFunctionCallFlags {
    uint8_t raw;
    struct {
        uint8_t distinct : 1;
    };
} SyntaqliteAggregateFunctionCallFlags;

typedef union SyntaqliteCreateTableStmtFlags {
    uint8_t raw;
    struct {
        uint8_t without_rowid : 1;
        uint8_t strict : 1;
    };
} SyntaqliteCreateTableStmtFlags;

typedef union SyntaqliteFunctionCallFlags {
    uint8_t raw;
    struct {
        uint8_t distinct : 1;
        uint8_t star : 1;
    };
} SyntaqliteFunctionCallFlags;

typedef union SyntaqliteResultColumnFlags {
    uint8_t raw;
    struct {
        uint8_t star : 1;
    };
} SyntaqliteResultColumnFlags;

typedef union SyntaqliteSelectStmtFlags {
    uint8_t raw;
    struct {
        uint8_t distinct : 1;
    };
} SyntaqliteSelectStmtFlags;

// ============ Node Tags ============

typedef enum SyntaqliteNodeTag {
    SYNTAQLITE_NODE_NULL = 0,
    SYNTAQLITE_NODE_AGGREGATE_FUNCTION_CALL,
    SYNTAQLITE_NODE_CAST_EXPR,
    SYNTAQLITE_NODE_COLUMN_REF,
    SYNTAQLITE_NODE_COMPOUND_SELECT,
    SYNTAQLITE_NODE_SUBQUERY_EXPR,
    SYNTAQLITE_NODE_EXISTS_EXPR,
    SYNTAQLITE_NODE_IN_EXPR,
    SYNTAQLITE_NODE_IS_EXPR,
    SYNTAQLITE_NODE_BETWEEN_EXPR,
    SYNTAQLITE_NODE_LIKE_EXPR,
    SYNTAQLITE_NODE_CASE_EXPR,
    SYNTAQLITE_NODE_CASE_WHEN,
    SYNTAQLITE_NODE_CASE_WHEN_LIST,
    SYNTAQLITE_NODE_FOREIGN_KEY_CLAUSE,
    SYNTAQLITE_NODE_COLUMN_CONSTRAINT,
    SYNTAQLITE_NODE_COLUMN_CONSTRAINT_LIST,
    SYNTAQLITE_NODE_COLUMN_DEF,
    SYNTAQLITE_NODE_COLUMN_DEF_LIST,
    SYNTAQLITE_NODE_TABLE_CONSTRAINT,
    SYNTAQLITE_NODE_TABLE_CONSTRAINT_LIST,
    SYNTAQLITE_NODE_CREATE_TABLE_STMT,
    SYNTAQLITE_NODE_CTE_DEFINITION,
    SYNTAQLITE_NODE_CTE_LIST,
    SYNTAQLITE_NODE_WITH_CLAUSE,
    SYNTAQLITE_NODE_DELETE_STMT,
    SYNTAQLITE_NODE_SET_CLAUSE,
    SYNTAQLITE_NODE_SET_CLAUSE_LIST,
    SYNTAQLITE_NODE_UPDATE_STMT,
    SYNTAQLITE_NODE_INSERT_STMT,
    SYNTAQLITE_NODE_BINARY_EXPR,
    SYNTAQLITE_NODE_UNARY_EXPR,
    SYNTAQLITE_NODE_LITERAL,
    SYNTAQLITE_NODE_EXPR_LIST,
    SYNTAQLITE_NODE_FUNCTION_CALL,
    SYNTAQLITE_NODE_VARIABLE,
    SYNTAQLITE_NODE_COLLATE_EXPR,
    SYNTAQLITE_NODE_RAISE_EXPR,
    SYNTAQLITE_NODE_QUALIFIED_NAME,
    SYNTAQLITE_NODE_DROP_STMT,
    SYNTAQLITE_NODE_ALTER_TABLE_STMT,
    SYNTAQLITE_NODE_TRANSACTION_STMT,
    SYNTAQLITE_NODE_SAVEPOINT_STMT,
    SYNTAQLITE_NODE_RESULT_COLUMN,
    SYNTAQLITE_NODE_RESULT_COLUMN_LIST,
    SYNTAQLITE_NODE_SELECT_STMT,
    SYNTAQLITE_NODE_ORDERING_TERM,
    SYNTAQLITE_NODE_ORDER_BY_LIST,
    SYNTAQLITE_NODE_LIMIT_CLAUSE,
    SYNTAQLITE_NODE_TABLE_REF,
    SYNTAQLITE_NODE_SUBQUERY_TABLE_SOURCE,
    SYNTAQLITE_NODE_JOIN_CLAUSE,
    SYNTAQLITE_NODE_JOIN_PREFIX,
    SYNTAQLITE_NODE_TRIGGER_EVENT,
    SYNTAQLITE_NODE_TRIGGER_CMD_LIST,
    SYNTAQLITE_NODE_CREATE_TRIGGER_STMT,
    SYNTAQLITE_NODE_CREATE_VIRTUAL_TABLE_STMT,
    SYNTAQLITE_NODE_PRAGMA_STMT,
    SYNTAQLITE_NODE_ANALYZE_STMT,
    SYNTAQLITE_NODE_ATTACH_STMT,
    SYNTAQLITE_NODE_DETACH_STMT,
    SYNTAQLITE_NODE_VACUUM_STMT,
    SYNTAQLITE_NODE_EXPLAIN_STMT,
    SYNTAQLITE_NODE_CREATE_INDEX_STMT,
    SYNTAQLITE_NODE_CREATE_VIEW_STMT,
    SYNTAQLITE_NODE_VALUES_ROW_LIST,
    SYNTAQLITE_NODE_VALUES_CLAUSE,
    SYNTAQLITE_NODE_FRAME_BOUND,
    SYNTAQLITE_NODE_FRAME_SPEC,
    SYNTAQLITE_NODE_WINDOW_DEF,
    SYNTAQLITE_NODE_WINDOW_DEF_LIST,
    SYNTAQLITE_NODE_NAMED_WINDOW_DEF,
    SYNTAQLITE_NODE_NAMED_WINDOW_DEF_LIST,
    SYNTAQLITE_NODE_FILTER_OVER,
    SYNTAQLITE_NODE_COUNT
} SyntaqliteNodeTag;

// ============ Node Structs ============

typedef struct SyntaqliteAggregateFunctionCall {
    uint32_t tag;
    SyntaqliteSourceSpan func_name;
    SyntaqliteAggregateFunctionCallFlags flags;
    uint32_t args;
    uint32_t orderby;
    uint32_t filter_clause;
    uint32_t over_clause;
} SyntaqliteAggregateFunctionCall;

typedef struct SyntaqliteCastExpr {
    uint32_t tag;
    uint32_t expr;
    SyntaqliteSourceSpan type_name;
} SyntaqliteCastExpr;

typedef struct SyntaqliteColumnRef {
    uint32_t tag;
    SyntaqliteSourceSpan column;
    SyntaqliteSourceSpan table;
    SyntaqliteSourceSpan schema;
} SyntaqliteColumnRef;

typedef struct SyntaqliteCompoundSelect {
    uint32_t tag;
    SyntaqliteCompoundOp op;
    uint32_t left;
    uint32_t right;
} SyntaqliteCompoundSelect;

typedef struct SyntaqliteSubqueryExpr {
    uint32_t tag;
    uint32_t select;
} SyntaqliteSubqueryExpr;

typedef struct SyntaqliteExistsExpr {
    uint32_t tag;
    uint32_t select;
} SyntaqliteExistsExpr;

typedef struct SyntaqliteInExpr {
    uint32_t tag;
    SyntaqliteBool negated;
    uint32_t operand;
    uint32_t source;
} SyntaqliteInExpr;

typedef struct SyntaqliteIsExpr {
    uint32_t tag;
    SyntaqliteIsOp op;
    uint32_t left;
    uint32_t right;
} SyntaqliteIsExpr;

typedef struct SyntaqliteBetweenExpr {
    uint32_t tag;
    SyntaqliteBool negated;
    uint32_t operand;
    uint32_t low;
    uint32_t high;
} SyntaqliteBetweenExpr;

typedef struct SyntaqliteLikeExpr {
    uint32_t tag;
    SyntaqliteBool negated;
    uint32_t operand;
    uint32_t pattern;
    uint32_t escape;
} SyntaqliteLikeExpr;

typedef struct SyntaqliteCaseExpr {
    uint32_t tag;
    uint32_t operand;
    uint32_t else_expr;
    uint32_t whens;
} SyntaqliteCaseExpr;

typedef struct SyntaqliteCaseWhen {
    uint32_t tag;
    uint32_t when_expr;
    uint32_t then_expr;
} SyntaqliteCaseWhen;

// List of CaseWhen
typedef struct SyntaqliteCaseWhenList {
    uint32_t tag;
    uint32_t count;
    uint32_t children[];
} SyntaqliteCaseWhenList;

typedef struct SyntaqliteForeignKeyClause {
    uint32_t tag;
    SyntaqliteSourceSpan ref_table;
    uint32_t ref_columns;
    SyntaqliteForeignKeyAction on_delete;
    SyntaqliteForeignKeyAction on_update;
    SyntaqliteBool is_deferred;
} SyntaqliteForeignKeyClause;

typedef struct SyntaqliteColumnConstraint {
    uint32_t tag;
    SyntaqliteColumnConstraintKind kind;
    SyntaqliteSourceSpan constraint_name;
    SyntaqliteConflictAction onconf;
    SyntaqliteSortOrder sort_order;
    SyntaqliteBool is_autoincrement;
    SyntaqliteSourceSpan collation_name;
    SyntaqliteGeneratedColumnStorage generated_storage;
    uint32_t default_expr;
    uint32_t check_expr;
    uint32_t generated_expr;
    uint32_t fk_clause;
} SyntaqliteColumnConstraint;

// List of ColumnConstraint
typedef struct SyntaqliteColumnConstraintList {
    uint32_t tag;
    uint32_t count;
    uint32_t children[];
} SyntaqliteColumnConstraintList;

typedef struct SyntaqliteColumnDef {
    uint32_t tag;
    SyntaqliteSourceSpan column_name;
    SyntaqliteSourceSpan type_name;
    uint32_t constraints;
} SyntaqliteColumnDef;

// List of ColumnDef
typedef struct SyntaqliteColumnDefList {
    uint32_t tag;
    uint32_t count;
    uint32_t children[];
} SyntaqliteColumnDefList;

typedef struct SyntaqliteTableConstraint {
    uint32_t tag;
    SyntaqliteTableConstraintKind kind;
    SyntaqliteSourceSpan constraint_name;
    SyntaqliteConflictAction onconf;
    SyntaqliteBool is_autoincrement;
    uint32_t pk_columns;
    uint32_t fk_columns;
    uint32_t check_expr;
    uint32_t fk_clause;
} SyntaqliteTableConstraint;

// List of TableConstraint
typedef struct SyntaqliteTableConstraintList {
    uint32_t tag;
    uint32_t count;
    uint32_t children[];
} SyntaqliteTableConstraintList;

typedef struct SyntaqliteCreateTableStmt {
    uint32_t tag;
    SyntaqliteSourceSpan table_name;
    SyntaqliteSourceSpan schema;
    SyntaqliteBool is_temp;
    SyntaqliteBool if_not_exists;
    SyntaqliteCreateTableStmtFlags flags;
    uint32_t columns;
    uint32_t table_constraints;
    uint32_t as_select;
} SyntaqliteCreateTableStmt;

typedef struct SyntaqliteCteDefinition {
    uint32_t tag;
    SyntaqliteSourceSpan cte_name;
    SyntaqliteMaterialized materialized;
    uint32_t columns;
    uint32_t select;
} SyntaqliteCteDefinition;

// List of CteDefinition
typedef struct SyntaqliteCteList {
    uint32_t tag;
    uint32_t count;
    uint32_t children[];
} SyntaqliteCteList;

typedef struct SyntaqliteWithClause {
    uint32_t tag;
    SyntaqliteBool recursive;
    uint32_t ctes;
    uint32_t select;
} SyntaqliteWithClause;

typedef struct SyntaqliteDeleteStmt {
    uint32_t tag;
    uint32_t table;
    uint32_t where_clause;
} SyntaqliteDeleteStmt;

typedef struct SyntaqliteSetClause {
    uint32_t tag;
    SyntaqliteSourceSpan column;
    uint32_t columns;
    uint32_t value;
} SyntaqliteSetClause;

// List of SetClause
typedef struct SyntaqliteSetClauseList {
    uint32_t tag;
    uint32_t count;
    uint32_t children[];
} SyntaqliteSetClauseList;

typedef struct SyntaqliteUpdateStmt {
    uint32_t tag;
    SyntaqliteConflictAction conflict_action;
    uint32_t table;
    uint32_t setlist;
    uint32_t from_clause;
    uint32_t where_clause;
} SyntaqliteUpdateStmt;

typedef struct SyntaqliteInsertStmt {
    uint32_t tag;
    SyntaqliteConflictAction conflict_action;
    uint32_t table;
    uint32_t columns;
    uint32_t source;
} SyntaqliteInsertStmt;

typedef struct SyntaqliteBinaryExpr {
    uint32_t tag;
    SyntaqliteBinaryOp op;
    uint32_t left;
    uint32_t right;
} SyntaqliteBinaryExpr;

typedef struct SyntaqliteUnaryExpr {
    uint32_t tag;
    SyntaqliteUnaryOp op;
    uint32_t operand;
} SyntaqliteUnaryExpr;

typedef struct SyntaqliteLiteral {
    uint32_t tag;
    SyntaqliteLiteralType literal_type;
    SyntaqliteSourceSpan source;
} SyntaqliteLiteral;

// List of Expr
typedef struct SyntaqliteExprList {
    uint32_t tag;
    uint32_t count;
    uint32_t children[];
} SyntaqliteExprList;

typedef struct SyntaqliteFunctionCall {
    uint32_t tag;
    SyntaqliteSourceSpan func_name;
    SyntaqliteFunctionCallFlags flags;
    uint32_t args;
    uint32_t filter_clause;
    uint32_t over_clause;
} SyntaqliteFunctionCall;

typedef struct SyntaqliteVariable {
    uint32_t tag;
    SyntaqliteSourceSpan source;
} SyntaqliteVariable;

typedef struct SyntaqliteCollateExpr {
    uint32_t tag;
    uint32_t expr;
    SyntaqliteSourceSpan collation;
} SyntaqliteCollateExpr;

typedef struct SyntaqliteRaiseExpr {
    uint32_t tag;
    SyntaqliteRaiseType raise_type;
    uint32_t error_message;
} SyntaqliteRaiseExpr;

typedef struct SyntaqliteQualifiedName {
    uint32_t tag;
    SyntaqliteSourceSpan object_name;
    SyntaqliteSourceSpan schema;
} SyntaqliteQualifiedName;

typedef struct SyntaqliteDropStmt {
    uint32_t tag;
    SyntaqliteDropObjectType object_type;
    SyntaqliteBool if_exists;
    uint32_t target;
} SyntaqliteDropStmt;

typedef struct SyntaqliteAlterTableStmt {
    uint32_t tag;
    SyntaqliteAlterOp op;
    uint32_t target;
    SyntaqliteSourceSpan new_name;
    SyntaqliteSourceSpan old_name;
} SyntaqliteAlterTableStmt;

typedef struct SyntaqliteTransactionStmt {
    uint32_t tag;
    SyntaqliteTransactionOp op;
    SyntaqliteTransactionType trans_type;
} SyntaqliteTransactionStmt;

typedef struct SyntaqliteSavepointStmt {
    uint32_t tag;
    SyntaqliteSavepointOp op;
    SyntaqliteSourceSpan savepoint_name;
} SyntaqliteSavepointStmt;

typedef struct SyntaqliteResultColumn {
    uint32_t tag;
    SyntaqliteResultColumnFlags flags;
    SyntaqliteSourceSpan alias;
    uint32_t expr;
} SyntaqliteResultColumn;

// List of ResultColumn
typedef struct SyntaqliteResultColumnList {
    uint32_t tag;
    uint32_t count;
    uint32_t children[];
} SyntaqliteResultColumnList;

typedef struct SyntaqliteSelectStmt {
    uint32_t tag;
    SyntaqliteSelectStmtFlags flags;
    uint32_t columns;
    uint32_t from_clause;
    uint32_t where_clause;
    uint32_t groupby;
    uint32_t having;
    uint32_t orderby;
    uint32_t limit_clause;
    uint32_t window_clause;
} SyntaqliteSelectStmt;

typedef struct SyntaqliteOrderingTerm {
    uint32_t tag;
    uint32_t expr;
    SyntaqliteSortOrder sort_order;
    SyntaqliteNullsOrder nulls_order;
} SyntaqliteOrderingTerm;

// List of OrderingTerm
typedef struct SyntaqliteOrderByList {
    uint32_t tag;
    uint32_t count;
    uint32_t children[];
} SyntaqliteOrderByList;

typedef struct SyntaqliteLimitClause {
    uint32_t tag;
    uint32_t limit;
    uint32_t offset;
} SyntaqliteLimitClause;

typedef struct SyntaqliteTableRef {
    uint32_t tag;
    SyntaqliteSourceSpan table_name;
    SyntaqliteSourceSpan schema;
    SyntaqliteSourceSpan alias;
} SyntaqliteTableRef;

typedef struct SyntaqliteSubqueryTableSource {
    uint32_t tag;
    uint32_t select;
    SyntaqliteSourceSpan alias;
} SyntaqliteSubqueryTableSource;

typedef struct SyntaqliteJoinClause {
    uint32_t tag;
    SyntaqliteJoinType join_type;
    uint32_t left;
    uint32_t right;
    uint32_t on_expr;
    uint32_t using_columns;
} SyntaqliteJoinClause;

typedef struct SyntaqliteJoinPrefix {
    uint32_t tag;
    uint32_t source;
    SyntaqliteJoinType join_type;
} SyntaqliteJoinPrefix;

typedef struct SyntaqliteTriggerEvent {
    uint32_t tag;
    SyntaqliteTriggerEventType event_type;
    uint32_t columns;
} SyntaqliteTriggerEvent;

// List of Stmt
typedef struct SyntaqliteTriggerCmdList {
    uint32_t tag;
    uint32_t count;
    uint32_t children[];
} SyntaqliteTriggerCmdList;

typedef struct SyntaqliteCreateTriggerStmt {
    uint32_t tag;
    SyntaqliteSourceSpan trigger_name;
    SyntaqliteSourceSpan schema;
    SyntaqliteBool is_temp;
    SyntaqliteBool if_not_exists;
    SyntaqliteTriggerTiming timing;
    uint32_t event;
    uint32_t table;
    uint32_t when_expr;
    uint32_t body;
} SyntaqliteCreateTriggerStmt;

typedef struct SyntaqliteCreateVirtualTableStmt {
    uint32_t tag;
    SyntaqliteSourceSpan table_name;
    SyntaqliteSourceSpan schema;
    SyntaqliteSourceSpan module_name;
    SyntaqliteBool if_not_exists;
    SyntaqliteSourceSpan module_args;
} SyntaqliteCreateVirtualTableStmt;

typedef struct SyntaqlitePragmaStmt {
    uint32_t tag;
    SyntaqliteSourceSpan pragma_name;
    SyntaqliteSourceSpan schema;
    SyntaqliteSourceSpan value;
    SyntaqlitePragmaForm pragma_form;
} SyntaqlitePragmaStmt;

typedef struct SyntaqliteAnalyzeStmt {
    uint32_t tag;
    SyntaqliteSourceSpan target_name;
    SyntaqliteSourceSpan schema;
    SyntaqliteAnalyzeKind kind;
} SyntaqliteAnalyzeStmt;

typedef struct SyntaqliteAttachStmt {
    uint32_t tag;
    uint32_t filename;
    uint32_t db_name;
    uint32_t key;
} SyntaqliteAttachStmt;

typedef struct SyntaqliteDetachStmt {
    uint32_t tag;
    uint32_t db_name;
} SyntaqliteDetachStmt;

typedef struct SyntaqliteVacuumStmt {
    uint32_t tag;
    SyntaqliteSourceSpan schema;
    uint32_t into_expr;
} SyntaqliteVacuumStmt;

typedef struct SyntaqliteExplainStmt {
    uint32_t tag;
    SyntaqliteExplainMode explain_mode;
    uint32_t stmt;
} SyntaqliteExplainStmt;

typedef struct SyntaqliteCreateIndexStmt {
    uint32_t tag;
    SyntaqliteSourceSpan index_name;
    SyntaqliteSourceSpan schema;
    SyntaqliteSourceSpan table_name;
    SyntaqliteBool is_unique;
    SyntaqliteBool if_not_exists;
    uint32_t columns;
    uint32_t where_clause;
} SyntaqliteCreateIndexStmt;

typedef struct SyntaqliteCreateViewStmt {
    uint32_t tag;
    SyntaqliteSourceSpan view_name;
    SyntaqliteSourceSpan schema;
    SyntaqliteBool is_temp;
    SyntaqliteBool if_not_exists;
    uint32_t column_names;
    uint32_t select;
} SyntaqliteCreateViewStmt;

// List of ExprList
typedef struct SyntaqliteValuesRowList {
    uint32_t tag;
    uint32_t count;
    uint32_t children[];
} SyntaqliteValuesRowList;

typedef struct SyntaqliteValuesClause {
    uint32_t tag;
    uint32_t rows;
} SyntaqliteValuesClause;

typedef struct SyntaqliteFrameBound {
    uint32_t tag;
    SyntaqliteFrameBoundType bound_type;
    uint32_t expr;
} SyntaqliteFrameBound;

typedef struct SyntaqliteFrameSpec {
    uint32_t tag;
    SyntaqliteFrameType frame_type;
    SyntaqliteFrameExclude exclude;
    uint32_t start_bound;
    uint32_t end_bound;
} SyntaqliteFrameSpec;

typedef struct SyntaqliteWindowDef {
    uint32_t tag;
    SyntaqliteSourceSpan base_window_name;
    uint32_t partition_by;
    uint32_t orderby;
    uint32_t frame;
} SyntaqliteWindowDef;

// List of WindowDef
typedef struct SyntaqliteWindowDefList {
    uint32_t tag;
    uint32_t count;
    uint32_t children[];
} SyntaqliteWindowDefList;

typedef struct SyntaqliteNamedWindowDef {
    uint32_t tag;
    SyntaqliteSourceSpan window_name;
    uint32_t window_def;
} SyntaqliteNamedWindowDef;

// List of NamedWindowDef
typedef struct SyntaqliteNamedWindowDefList {
    uint32_t tag;
    uint32_t count;
    uint32_t children[];
} SyntaqliteNamedWindowDefList;

typedef struct SyntaqliteFilterOver {
    uint32_t tag;
    uint32_t filter_expr;
    uint32_t over_def;
    SyntaqliteSourceSpan over_name;
} SyntaqliteFilterOver;

// ============ Node Union ============

typedef union SyntaqliteNode {
    uint32_t tag;
    SyntaqliteAggregateFunctionCall aggregate_function_call;
    SyntaqliteCastExpr cast_expr;
    SyntaqliteColumnRef column_ref;
    SyntaqliteCompoundSelect compound_select;
    SyntaqliteSubqueryExpr subquery_expr;
    SyntaqliteExistsExpr exists_expr;
    SyntaqliteInExpr in_expr;
    SyntaqliteIsExpr is_expr;
    SyntaqliteBetweenExpr between_expr;
    SyntaqliteLikeExpr like_expr;
    SyntaqliteCaseExpr case_expr;
    SyntaqliteCaseWhen case_when;
    SyntaqliteCaseWhenList case_when_list;
    SyntaqliteForeignKeyClause foreign_key_clause;
    SyntaqliteColumnConstraint column_constraint;
    SyntaqliteColumnConstraintList column_constraint_list;
    SyntaqliteColumnDef column_def;
    SyntaqliteColumnDefList column_def_list;
    SyntaqliteTableConstraint table_constraint;
    SyntaqliteTableConstraintList table_constraint_list;
    SyntaqliteCreateTableStmt create_table_stmt;
    SyntaqliteCteDefinition cte_definition;
    SyntaqliteCteList cte_list;
    SyntaqliteWithClause with_clause;
    SyntaqliteDeleteStmt delete_stmt;
    SyntaqliteSetClause set_clause;
    SyntaqliteSetClauseList set_clause_list;
    SyntaqliteUpdateStmt update_stmt;
    SyntaqliteInsertStmt insert_stmt;
    SyntaqliteBinaryExpr binary_expr;
    SyntaqliteUnaryExpr unary_expr;
    SyntaqliteLiteral literal;
    SyntaqliteExprList expr_list;
    SyntaqliteFunctionCall function_call;
    SyntaqliteVariable variable;
    SyntaqliteCollateExpr collate_expr;
    SyntaqliteRaiseExpr raise_expr;
    SyntaqliteQualifiedName qualified_name;
    SyntaqliteDropStmt drop_stmt;
    SyntaqliteAlterTableStmt alter_table_stmt;
    SyntaqliteTransactionStmt transaction_stmt;
    SyntaqliteSavepointStmt savepoint_stmt;
    SyntaqliteResultColumn result_column;
    SyntaqliteResultColumnList result_column_list;
    SyntaqliteSelectStmt select_stmt;
    SyntaqliteOrderingTerm ordering_term;
    SyntaqliteOrderByList order_by_list;
    SyntaqliteLimitClause limit_clause;
    SyntaqliteTableRef table_ref;
    SyntaqliteSubqueryTableSource subquery_table_source;
    SyntaqliteJoinClause join_clause;
    SyntaqliteJoinPrefix join_prefix;
    SyntaqliteTriggerEvent trigger_event;
    SyntaqliteTriggerCmdList trigger_cmd_list;
    SyntaqliteCreateTriggerStmt create_trigger_stmt;
    SyntaqliteCreateVirtualTableStmt create_virtual_table_stmt;
    SyntaqlitePragmaStmt pragma_stmt;
    SyntaqliteAnalyzeStmt analyze_stmt;
    SyntaqliteAttachStmt attach_stmt;
    SyntaqliteDetachStmt detach_stmt;
    SyntaqliteVacuumStmt vacuum_stmt;
    SyntaqliteExplainStmt explain_stmt;
    SyntaqliteCreateIndexStmt create_index_stmt;
    SyntaqliteCreateViewStmt create_view_stmt;
    SyntaqliteValuesRowList values_row_list;
    SyntaqliteValuesClause values_clause;
    SyntaqliteFrameBound frame_bound;
    SyntaqliteFrameSpec frame_spec;
    SyntaqliteWindowDef window_def;
    SyntaqliteWindowDefList window_def_list;
    SyntaqliteNamedWindowDef named_window_def;
    SyntaqliteNamedWindowDefList named_window_def_list;
    SyntaqliteFilterOver filter_over;
} SyntaqliteNode;

// ============ Abstract Type: Select ============

typedef union SyntaqliteSelect {
    uint32_t tag;
    SyntaqliteSelectStmt select_stmt;
    SyntaqliteCompoundSelect compound_select;
    SyntaqliteWithClause with_clause;
    SyntaqliteValuesClause values_clause;
} SyntaqliteSelect;

static inline int syntaqlite_is_select(SyntaqliteNodeTag tag) {
    switch (tag) {
        case SYNTAQLITE_NODE_SELECT_STMT: return 1;
        case SYNTAQLITE_NODE_COMPOUND_SELECT: return 1;
        case SYNTAQLITE_NODE_WITH_CLAUSE: return 1;
        case SYNTAQLITE_NODE_VALUES_CLAUSE: return 1;
        default: return 0;
    }
}

static inline const SyntaqliteSelectStmt* syntaqlite_select_as_select_stmt(const SyntaqliteSelect* node) {
    return node->tag == SYNTAQLITE_NODE_SELECT_STMT ? &node->select_stmt : NULL;
}

static inline const SyntaqliteCompoundSelect* syntaqlite_select_as_compound_select(const SyntaqliteSelect* node) {
    return node->tag == SYNTAQLITE_NODE_COMPOUND_SELECT ? &node->compound_select : NULL;
}

static inline const SyntaqliteWithClause* syntaqlite_select_as_with_clause(const SyntaqliteSelect* node) {
    return node->tag == SYNTAQLITE_NODE_WITH_CLAUSE ? &node->with_clause : NULL;
}

static inline const SyntaqliteValuesClause* syntaqlite_select_as_values_clause(const SyntaqliteSelect* node) {
    return node->tag == SYNTAQLITE_NODE_VALUES_CLAUSE ? &node->values_clause : NULL;
}

// ============ Abstract Type: InExprSource ============

typedef union SyntaqliteInExprSource {
    uint32_t tag;
    SyntaqliteExprList expr_list;
    SyntaqliteSubqueryExpr subquery_expr;
} SyntaqliteInExprSource;

static inline int syntaqlite_is_in_expr_source(SyntaqliteNodeTag tag) {
    switch (tag) {
        case SYNTAQLITE_NODE_EXPR_LIST: return 1;
        case SYNTAQLITE_NODE_SUBQUERY_EXPR: return 1;
        default: return 0;
    }
}

static inline const SyntaqliteExprList* syntaqlite_in_expr_source_as_expr_list(const SyntaqliteInExprSource* node) {
    return node->tag == SYNTAQLITE_NODE_EXPR_LIST ? &node->expr_list : NULL;
}

static inline const SyntaqliteSubqueryExpr* syntaqlite_in_expr_source_as_subquery_expr(const SyntaqliteInExprSource* node) {
    return node->tag == SYNTAQLITE_NODE_SUBQUERY_EXPR ? &node->subquery_expr : NULL;
}

// ============ Abstract Type: Expr ============

typedef union SyntaqliteExpr {
    uint32_t tag;
    SyntaqliteBinaryExpr binary_expr;
    SyntaqliteUnaryExpr unary_expr;
    SyntaqliteLiteral literal;
    SyntaqliteColumnRef column_ref;
    SyntaqliteVariable variable;
    SyntaqliteFunctionCall function_call;
    SyntaqliteAggregateFunctionCall aggregate_function_call;
    SyntaqliteCastExpr cast_expr;
    SyntaqliteCollateExpr collate_expr;
    SyntaqliteCaseExpr case_expr;
    SyntaqliteIsExpr is_expr;
    SyntaqliteBetweenExpr between_expr;
    SyntaqliteLikeExpr like_expr;
    SyntaqliteInExpr in_expr;
    SyntaqliteSubqueryExpr subquery_expr;
    SyntaqliteExistsExpr exists_expr;
    SyntaqliteRaiseExpr raise_expr;
} SyntaqliteExpr;

static inline int syntaqlite_is_expr(SyntaqliteNodeTag tag) {
    switch (tag) {
        case SYNTAQLITE_NODE_BINARY_EXPR: return 1;
        case SYNTAQLITE_NODE_UNARY_EXPR: return 1;
        case SYNTAQLITE_NODE_LITERAL: return 1;
        case SYNTAQLITE_NODE_COLUMN_REF: return 1;
        case SYNTAQLITE_NODE_VARIABLE: return 1;
        case SYNTAQLITE_NODE_FUNCTION_CALL: return 1;
        case SYNTAQLITE_NODE_AGGREGATE_FUNCTION_CALL: return 1;
        case SYNTAQLITE_NODE_CAST_EXPR: return 1;
        case SYNTAQLITE_NODE_COLLATE_EXPR: return 1;
        case SYNTAQLITE_NODE_CASE_EXPR: return 1;
        case SYNTAQLITE_NODE_IS_EXPR: return 1;
        case SYNTAQLITE_NODE_BETWEEN_EXPR: return 1;
        case SYNTAQLITE_NODE_LIKE_EXPR: return 1;
        case SYNTAQLITE_NODE_IN_EXPR: return 1;
        case SYNTAQLITE_NODE_SUBQUERY_EXPR: return 1;
        case SYNTAQLITE_NODE_EXISTS_EXPR: return 1;
        case SYNTAQLITE_NODE_RAISE_EXPR: return 1;
        default: return 0;
    }
}

static inline const SyntaqliteBinaryExpr* syntaqlite_expr_as_binary_expr(const SyntaqliteExpr* node) {
    return node->tag == SYNTAQLITE_NODE_BINARY_EXPR ? &node->binary_expr : NULL;
}

static inline const SyntaqliteUnaryExpr* syntaqlite_expr_as_unary_expr(const SyntaqliteExpr* node) {
    return node->tag == SYNTAQLITE_NODE_UNARY_EXPR ? &node->unary_expr : NULL;
}

static inline const SyntaqliteLiteral* syntaqlite_expr_as_literal(const SyntaqliteExpr* node) {
    return node->tag == SYNTAQLITE_NODE_LITERAL ? &node->literal : NULL;
}

static inline const SyntaqliteColumnRef* syntaqlite_expr_as_column_ref(const SyntaqliteExpr* node) {
    return node->tag == SYNTAQLITE_NODE_COLUMN_REF ? &node->column_ref : NULL;
}

static inline const SyntaqliteVariable* syntaqlite_expr_as_variable(const SyntaqliteExpr* node) {
    return node->tag == SYNTAQLITE_NODE_VARIABLE ? &node->variable : NULL;
}

static inline const SyntaqliteFunctionCall* syntaqlite_expr_as_function_call(const SyntaqliteExpr* node) {
    return node->tag == SYNTAQLITE_NODE_FUNCTION_CALL ? &node->function_call : NULL;
}

static inline const SyntaqliteAggregateFunctionCall* syntaqlite_expr_as_aggregate_function_call(const SyntaqliteExpr* node) {
    return node->tag == SYNTAQLITE_NODE_AGGREGATE_FUNCTION_CALL ? &node->aggregate_function_call : NULL;
}

static inline const SyntaqliteCastExpr* syntaqlite_expr_as_cast_expr(const SyntaqliteExpr* node) {
    return node->tag == SYNTAQLITE_NODE_CAST_EXPR ? &node->cast_expr : NULL;
}

static inline const SyntaqliteCollateExpr* syntaqlite_expr_as_collate_expr(const SyntaqliteExpr* node) {
    return node->tag == SYNTAQLITE_NODE_COLLATE_EXPR ? &node->collate_expr : NULL;
}

static inline const SyntaqliteCaseExpr* syntaqlite_expr_as_case_expr(const SyntaqliteExpr* node) {
    return node->tag == SYNTAQLITE_NODE_CASE_EXPR ? &node->case_expr : NULL;
}

static inline const SyntaqliteIsExpr* syntaqlite_expr_as_is_expr(const SyntaqliteExpr* node) {
    return node->tag == SYNTAQLITE_NODE_IS_EXPR ? &node->is_expr : NULL;
}

static inline const SyntaqliteBetweenExpr* syntaqlite_expr_as_between_expr(const SyntaqliteExpr* node) {
    return node->tag == SYNTAQLITE_NODE_BETWEEN_EXPR ? &node->between_expr : NULL;
}

static inline const SyntaqliteLikeExpr* syntaqlite_expr_as_like_expr(const SyntaqliteExpr* node) {
    return node->tag == SYNTAQLITE_NODE_LIKE_EXPR ? &node->like_expr : NULL;
}

static inline const SyntaqliteInExpr* syntaqlite_expr_as_in_expr(const SyntaqliteExpr* node) {
    return node->tag == SYNTAQLITE_NODE_IN_EXPR ? &node->in_expr : NULL;
}

static inline const SyntaqliteSubqueryExpr* syntaqlite_expr_as_subquery_expr(const SyntaqliteExpr* node) {
    return node->tag == SYNTAQLITE_NODE_SUBQUERY_EXPR ? &node->subquery_expr : NULL;
}

static inline const SyntaqliteExistsExpr* syntaqlite_expr_as_exists_expr(const SyntaqliteExpr* node) {
    return node->tag == SYNTAQLITE_NODE_EXISTS_EXPR ? &node->exists_expr : NULL;
}

static inline const SyntaqliteRaiseExpr* syntaqlite_expr_as_raise_expr(const SyntaqliteExpr* node) {
    return node->tag == SYNTAQLITE_NODE_RAISE_EXPR ? &node->raise_expr : NULL;
}

// ============ Abstract Type: Stmt ============

typedef union SyntaqliteStmt {
    uint32_t tag;
    SyntaqliteSelectStmt select_stmt;
    SyntaqliteCompoundSelect compound_select;
    SyntaqliteValuesClause values_clause;
    SyntaqliteWithClause with_clause;
    SyntaqliteInsertStmt insert_stmt;
    SyntaqliteUpdateStmt update_stmt;
    SyntaqliteDeleteStmt delete_stmt;
    SyntaqliteCreateTableStmt create_table_stmt;
    SyntaqliteCreateIndexStmt create_index_stmt;
    SyntaqliteCreateViewStmt create_view_stmt;
    SyntaqliteCreateTriggerStmt create_trigger_stmt;
    SyntaqliteCreateVirtualTableStmt create_virtual_table_stmt;
    SyntaqliteDropStmt drop_stmt;
    SyntaqliteAlterTableStmt alter_table_stmt;
    SyntaqliteTransactionStmt transaction_stmt;
    SyntaqliteSavepointStmt savepoint_stmt;
    SyntaqlitePragmaStmt pragma_stmt;
    SyntaqliteAnalyzeStmt analyze_stmt;
    SyntaqliteAttachStmt attach_stmt;
    SyntaqliteDetachStmt detach_stmt;
    SyntaqliteVacuumStmt vacuum_stmt;
    SyntaqliteExplainStmt explain_stmt;
} SyntaqliteStmt;

static inline int syntaqlite_is_stmt(SyntaqliteNodeTag tag) {
    switch (tag) {
        case SYNTAQLITE_NODE_SELECT_STMT: return 1;
        case SYNTAQLITE_NODE_COMPOUND_SELECT: return 1;
        case SYNTAQLITE_NODE_VALUES_CLAUSE: return 1;
        case SYNTAQLITE_NODE_WITH_CLAUSE: return 1;
        case SYNTAQLITE_NODE_INSERT_STMT: return 1;
        case SYNTAQLITE_NODE_UPDATE_STMT: return 1;
        case SYNTAQLITE_NODE_DELETE_STMT: return 1;
        case SYNTAQLITE_NODE_CREATE_TABLE_STMT: return 1;
        case SYNTAQLITE_NODE_CREATE_INDEX_STMT: return 1;
        case SYNTAQLITE_NODE_CREATE_VIEW_STMT: return 1;
        case SYNTAQLITE_NODE_CREATE_TRIGGER_STMT: return 1;
        case SYNTAQLITE_NODE_CREATE_VIRTUAL_TABLE_STMT: return 1;
        case SYNTAQLITE_NODE_DROP_STMT: return 1;
        case SYNTAQLITE_NODE_ALTER_TABLE_STMT: return 1;
        case SYNTAQLITE_NODE_TRANSACTION_STMT: return 1;
        case SYNTAQLITE_NODE_SAVEPOINT_STMT: return 1;
        case SYNTAQLITE_NODE_PRAGMA_STMT: return 1;
        case SYNTAQLITE_NODE_ANALYZE_STMT: return 1;
        case SYNTAQLITE_NODE_ATTACH_STMT: return 1;
        case SYNTAQLITE_NODE_DETACH_STMT: return 1;
        case SYNTAQLITE_NODE_VACUUM_STMT: return 1;
        case SYNTAQLITE_NODE_EXPLAIN_STMT: return 1;
        default: return 0;
    }
}

static inline const SyntaqliteSelectStmt* syntaqlite_stmt_as_select_stmt(const SyntaqliteStmt* node) {
    return node->tag == SYNTAQLITE_NODE_SELECT_STMT ? &node->select_stmt : NULL;
}

static inline const SyntaqliteCompoundSelect* syntaqlite_stmt_as_compound_select(const SyntaqliteStmt* node) {
    return node->tag == SYNTAQLITE_NODE_COMPOUND_SELECT ? &node->compound_select : NULL;
}

static inline const SyntaqliteValuesClause* syntaqlite_stmt_as_values_clause(const SyntaqliteStmt* node) {
    return node->tag == SYNTAQLITE_NODE_VALUES_CLAUSE ? &node->values_clause : NULL;
}

static inline const SyntaqliteWithClause* syntaqlite_stmt_as_with_clause(const SyntaqliteStmt* node) {
    return node->tag == SYNTAQLITE_NODE_WITH_CLAUSE ? &node->with_clause : NULL;
}

static inline const SyntaqliteInsertStmt* syntaqlite_stmt_as_insert_stmt(const SyntaqliteStmt* node) {
    return node->tag == SYNTAQLITE_NODE_INSERT_STMT ? &node->insert_stmt : NULL;
}

static inline const SyntaqliteUpdateStmt* syntaqlite_stmt_as_update_stmt(const SyntaqliteStmt* node) {
    return node->tag == SYNTAQLITE_NODE_UPDATE_STMT ? &node->update_stmt : NULL;
}

static inline const SyntaqliteDeleteStmt* syntaqlite_stmt_as_delete_stmt(const SyntaqliteStmt* node) {
    return node->tag == SYNTAQLITE_NODE_DELETE_STMT ? &node->delete_stmt : NULL;
}

static inline const SyntaqliteCreateTableStmt* syntaqlite_stmt_as_create_table_stmt(const SyntaqliteStmt* node) {
    return node->tag == SYNTAQLITE_NODE_CREATE_TABLE_STMT ? &node->create_table_stmt : NULL;
}

static inline const SyntaqliteCreateIndexStmt* syntaqlite_stmt_as_create_index_stmt(const SyntaqliteStmt* node) {
    return node->tag == SYNTAQLITE_NODE_CREATE_INDEX_STMT ? &node->create_index_stmt : NULL;
}

static inline const SyntaqliteCreateViewStmt* syntaqlite_stmt_as_create_view_stmt(const SyntaqliteStmt* node) {
    return node->tag == SYNTAQLITE_NODE_CREATE_VIEW_STMT ? &node->create_view_stmt : NULL;
}

static inline const SyntaqliteCreateTriggerStmt* syntaqlite_stmt_as_create_trigger_stmt(const SyntaqliteStmt* node) {
    return node->tag == SYNTAQLITE_NODE_CREATE_TRIGGER_STMT ? &node->create_trigger_stmt : NULL;
}

static inline const SyntaqliteCreateVirtualTableStmt* syntaqlite_stmt_as_create_virtual_table_stmt(const SyntaqliteStmt* node) {
    return node->tag == SYNTAQLITE_NODE_CREATE_VIRTUAL_TABLE_STMT ? &node->create_virtual_table_stmt : NULL;
}

static inline const SyntaqliteDropStmt* syntaqlite_stmt_as_drop_stmt(const SyntaqliteStmt* node) {
    return node->tag == SYNTAQLITE_NODE_DROP_STMT ? &node->drop_stmt : NULL;
}

static inline const SyntaqliteAlterTableStmt* syntaqlite_stmt_as_alter_table_stmt(const SyntaqliteStmt* node) {
    return node->tag == SYNTAQLITE_NODE_ALTER_TABLE_STMT ? &node->alter_table_stmt : NULL;
}

static inline const SyntaqliteTransactionStmt* syntaqlite_stmt_as_transaction_stmt(const SyntaqliteStmt* node) {
    return node->tag == SYNTAQLITE_NODE_TRANSACTION_STMT ? &node->transaction_stmt : NULL;
}

static inline const SyntaqliteSavepointStmt* syntaqlite_stmt_as_savepoint_stmt(const SyntaqliteStmt* node) {
    return node->tag == SYNTAQLITE_NODE_SAVEPOINT_STMT ? &node->savepoint_stmt : NULL;
}

static inline const SyntaqlitePragmaStmt* syntaqlite_stmt_as_pragma_stmt(const SyntaqliteStmt* node) {
    return node->tag == SYNTAQLITE_NODE_PRAGMA_STMT ? &node->pragma_stmt : NULL;
}

static inline const SyntaqliteAnalyzeStmt* syntaqlite_stmt_as_analyze_stmt(const SyntaqliteStmt* node) {
    return node->tag == SYNTAQLITE_NODE_ANALYZE_STMT ? &node->analyze_stmt : NULL;
}

static inline const SyntaqliteAttachStmt* syntaqlite_stmt_as_attach_stmt(const SyntaqliteStmt* node) {
    return node->tag == SYNTAQLITE_NODE_ATTACH_STMT ? &node->attach_stmt : NULL;
}

static inline const SyntaqliteDetachStmt* syntaqlite_stmt_as_detach_stmt(const SyntaqliteStmt* node) {
    return node->tag == SYNTAQLITE_NODE_DETACH_STMT ? &node->detach_stmt : NULL;
}

static inline const SyntaqliteVacuumStmt* syntaqlite_stmt_as_vacuum_stmt(const SyntaqliteStmt* node) {
    return node->tag == SYNTAQLITE_NODE_VACUUM_STMT ? &node->vacuum_stmt : NULL;
}

static inline const SyntaqliteExplainStmt* syntaqlite_stmt_as_explain_stmt(const SyntaqliteStmt* node) {
    return node->tag == SYNTAQLITE_NODE_EXPLAIN_STMT ? &node->explain_stmt : NULL;
}

// ============ Abstract Type: TableSource ============

typedef union SyntaqliteTableSource {
    uint32_t tag;
    SyntaqliteTableRef table_ref;
    SyntaqliteSubqueryTableSource subquery_table_source;
    SyntaqliteJoinClause join_clause;
    SyntaqliteJoinPrefix join_prefix;
} SyntaqliteTableSource;

static inline int syntaqlite_is_table_source(SyntaqliteNodeTag tag) {
    switch (tag) {
        case SYNTAQLITE_NODE_TABLE_REF: return 1;
        case SYNTAQLITE_NODE_SUBQUERY_TABLE_SOURCE: return 1;
        case SYNTAQLITE_NODE_JOIN_CLAUSE: return 1;
        case SYNTAQLITE_NODE_JOIN_PREFIX: return 1;
        default: return 0;
    }
}

static inline const SyntaqliteTableRef* syntaqlite_table_source_as_table_ref(const SyntaqliteTableSource* node) {
    return node->tag == SYNTAQLITE_NODE_TABLE_REF ? &node->table_ref : NULL;
}

static inline const SyntaqliteSubqueryTableSource* syntaqlite_table_source_as_subquery_table_source(const SyntaqliteTableSource* node) {
    return node->tag == SYNTAQLITE_NODE_SUBQUERY_TABLE_SOURCE ? &node->subquery_table_source : NULL;
}

static inline const SyntaqliteJoinClause* syntaqlite_table_source_as_join_clause(const SyntaqliteTableSource* node) {
    return node->tag == SYNTAQLITE_NODE_JOIN_CLAUSE ? &node->join_clause : NULL;
}

static inline const SyntaqliteJoinPrefix* syntaqlite_table_source_as_join_prefix(const SyntaqliteTableSource* node) {
    return node->tag == SYNTAQLITE_NODE_JOIN_PREFIX ? &node->join_prefix : NULL;
}

#ifdef __cplusplus
}
#endif

#endif  // SYNTAQLITE_SQLITE_NODE_H
