// Copyright 2025 The syntaqlite Authors. All rights reserved.
// Licensed under the Apache License, Version 2.0.

//! Dialect handle, semantic role types, and function catalog types.

use std::sync::Arc;

use syntaqlite_syntax::any::AnyGrammar;

#[cfg(feature = "dynload")]
use libloading;
pub(crate) use syntaqlite_syntax::util::SqliteVersion;

// ── Semantic role types (re-exported from syntaqlite-common) ─────────────────

pub use syntaqlite_common::roles::{FIELD_ABSENT, FieldIdx, RelationKind, SemanticRole};

// ── Function catalog types ────────────────────────────────────────────────────

/// Category of a built-in function.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub(crate) enum FunctionCategory {
    Scalar,
    Aggregate,
    Window,
    /// Table-valued function — valid in FROM clauses.
    TableValued,
}

/// Whether a cflag enables or omits the function.
///
/// `#[repr(u8)]` with `Enable=0, Omit=1` matches the C ABI
/// (`0=Enable, 1=Omit` in `SyntaqliteAvailabilityRule.cflag_polarity`),
/// which allows [`AvailabilityRule`] to be cast directly from C data.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub(crate) enum CflagPolarity {
    /// Function requires the cflag to be set (`SQLITE_ENABLE`_*).
    Enable = 0,
    /// Function is omitted when the cflag is set (`SQLITE_OMIT`_*).
    Omit = 1,
}

/// Metadata about a built-in function.
#[derive(Debug, Clone, Copy)]
pub(crate) struct FunctionInfo<'a> {
    /// Function name (lowercase).
    pub name: &'a str,
    /// Supported arities. Negative values indicate variadic:
    /// -1 = any number of args, -N = at least N-1 args.
    pub arities: &'a [i16],
    /// Function category.
    pub category: FunctionCategory,
}

/// A version/cflag availability rule for a function.
#[derive(Debug, Clone, Copy)]
pub(crate) struct AvailabilityRule {
    /// Minimum `SQLite` version (inclusive).
    pub since: SqliteVersion,
    /// Maximum `SQLite` version (exclusive). `None` means no upper bound.
    pub until: Option<SqliteVersion>,
    /// Cflag bit index, or `u32::MAX` if no cflag required.
    pub cflag_index: u32,
    /// Polarity of the cflag constraint.
    pub cflag_polarity: CflagPolarity,
}

/// A function entry combining metadata with availability rules.
#[derive(Debug, Clone, Copy)]
pub(crate) struct FunctionEntry<'a> {
    pub info: FunctionInfo<'a>,
    pub availability: &'a [AvailabilityRule],
}

/// Check whether a function entry is available for the given dialect config.
///
/// A function is available if at least one of its availability rules passes.
/// Each rule checks:
/// - version range (`since`/`until`)
/// - cflag constraint: for `Enable` polarity the cflag must be set; for
///   `Omit` polarity the cflag must be clear. Rules with `cflag_index ==
///   u32::MAX` have no cflag constraint.
pub(crate) fn is_function_available(entry: &FunctionEntry<'_>, dialect: &AnyDialect) -> bool {
    let cflags = dialect.cflags();
    entry.availability.iter().any(|rule| {
        if dialect.version() < rule.since {
            return false;
        }
        if let Some(until) = rule.until
            && dialect.version() >= until
        {
            return false;
        }
        if rule.cflag_index != u32::MAX {
            let flag_set = cflags.has_index(rule.cflag_index);
            match rule.cflag_polarity {
                CflagPolarity::Enable => {
                    if !flag_set {
                        return false;
                    }
                }
                CflagPolarity::Omit => {
                    if flag_set {
                        return false;
                    }
                }
            }
        }
        true
    })
}

// ── TypedDialect trait ───────────────────────────────────────────────────────

/// Marker trait for typed dialect handles.
///
/// Mirrors [`syntaqlite_syntax::typed::TypedGrammar`]: every dialect has a
/// concrete `Dialect` struct (generated by codegen) that implements this trait
/// and wraps an [`AnyDialect`].
///
/// Most infrastructure accepts [`AnyDialect`] directly. Use the typed dialect
/// handle when you need access to the grammar's typed AST node types.
pub trait TypedDialect: Into<AnyDialect> + Clone + 'static {}

// ── AnyDialect ───────────────────────────────────────────────────────────────

/// Runtime type-erased dialect handle.
///
/// Pairs a configurable grammar handle ([`AnyGrammar`]) with a pointer to the
/// dialect's static data ([`ffi::CDialectTemplate`]: formatter tables + semantic
/// roles), mirroring how [`AnyGrammar`] pairs a configurable `CGrammar` with a
/// pointer to the static `CGrammarTemplate`.
///
/// For the built-in `SQLite` dialect, obtain via `crate::sqlite_dialect()` or
/// `Dialect::new().erase()`. For dynamically loaded dialects use [`AnyDialect::load`].
#[derive(Clone)]
pub struct AnyDialect {
    grammar: AnyGrammar,
    /// Pointer to the static `SyntaqliteDialect` C struct for this dialect.
    /// For built-in dialects this points to a symbol in the binary; for
    /// dynamically loaded dialects the library is kept alive via `_keep_alive`.
    data: *const ffi::CDialectTemplate,
    /// Rust-side cflag set (all 42 flags, u64 bitset). Distinct from the
    /// C-ABI `SqliteSyntaxFlags` stored in the grammar — this covers
    /// non-parser flags like `SQLITE_ENABLE_MATH_FUNCTIONS`.
    ext_cflags: crate::util::SqliteFlags,
    /// Keeps a dynamically loaded library alive for the lifetime of this handle.
    /// `None` for built-in dialects.
    _keep_alive: Option<Arc<dyn Send + Sync>>,
}

// SAFETY: AnyDialect holds a pointer to immutable static C data and an
// Arc-guarded library handle; both are safe to send and share across threads.
unsafe impl Send for AnyDialect {}
// SAFETY: same as Send above.
unsafe impl Sync for AnyDialect {}

impl AnyDialect {
    /// Construct from a pointer to the dialect's static data.
    ///
    /// Derives the grammar handle from the `grammar` field embedded in the
    /// template, so callers do not need to extract it separately.
    ///
    /// # Safety
    ///
    /// `data` must point to a valid [`ffi::CDialectTemplate`] that lives at least as
    /// long as this `AnyDialect` (and all its clones). For built-in dialects
    /// `data` is a `'static` C symbol.
    pub(crate) unsafe fn from_data(data: *const ffi::CDialectTemplate) -> Self {
        // SAFETY: caller guarantees data is valid.
        let grammar = unsafe { (*data).any_grammar() };
        AnyDialect {
            grammar,
            data,
            ext_cflags: crate::util::SqliteFlags::default(),
            _keep_alive: None,
        }
    }

    /// Return a reference to the static dialect template.
    #[inline]
    fn template(&self) -> &'static ffi::CDialectTemplate {
        // SAFETY: data is valid for 'static (built-in) or kept alive via _keep_alive (dynload).
        unsafe { &*self.data }
    }

    /// The grammar handle for this dialect.
    pub fn grammar(&self) -> &AnyGrammar {
        &self.grammar
    }

    /// The semantic role table for this dialect, indexed by node tag.
    pub(crate) fn roles(&self) -> &'static [SemanticRole] {
        // SAFETY: template() is valid for the lifetime of self.
        unsafe { self.template().roles() }
    }

    /// Whether this dialect has formatter data.
    pub(crate) fn has_fmt_data(&self) -> bool {
        self.template().has_fmt_data()
    }

    /// Read the packed `fmt_dispatch` entry for a node tag.
    pub(crate) fn fmt_dispatch(
        &self,
        tag: syntaqlite_syntax::any::AnyNodeTag,
    ) -> Option<(&[u8], usize)> {
        // SAFETY: template() is valid.
        unsafe { self.template().fmt_dispatch(u32::from(tag) as usize) }
    }

    /// Look up a string from the fmt string table by index (CSR encoding).
    #[inline]
    pub(crate) fn fmt_string(&self, idx: u16) -> &'static str {
        // SAFETY: template() is valid; idx is bounds-checked at codegen time.
        unsafe { self.template().fmt_string(idx as usize) }
    }

    /// Look up a value in the enum display table.
    pub(crate) fn fmt_enum_display_val(&self, idx: usize) -> u16 {
        // SAFETY: template() is valid; idx is bounds-checked at codegen time.
        unsafe { self.template().fmt_enum_display_val(idx) }
    }

    /// Return a copy of this dialect targeting a specific `SQLite` version.
    #[must_use]
    pub fn with_version(mut self, version: SqliteVersion) -> Self {
        self.grammar = self.grammar.with_version(version);
        self
    }

    /// Return a copy of this dialect with the given compile-time flags.
    ///
    /// ```rust,ignore
    /// use syntaqlite::util::{SqliteFlag, SqliteFlags};
    /// let dialect = syntaqlite::sqlite_dialect()
    ///     .with_cflags(SqliteFlags::default().with(SqliteFlag::EnableMathFunctions));
    /// ```
    #[must_use]
    pub fn with_cflags(mut self, flags: crate::util::SqliteFlags) -> Self {
        self.ext_cflags = flags;
        self.grammar = self.grammar.with_cflags(flags.into());
        self
    }

    /// Active compile-time compatibility flags set on this dialect.
    pub fn cflags(&self) -> crate::util::SqliteFlags {
        self.ext_cflags
    }

    /// Target `SQLite` version configured on this dialect's grammar handle.
    pub fn version(&self) -> SqliteVersion {
        self.grammar.version()
    }

    /// C-parser compile-time compatibility flags (parser flags, indices 0–21).
    pub fn syntax_cflags(&self) -> syntaqlite_syntax::util::SqliteSyntaxFlags {
        self.grammar.cflags()
    }

    /// Load a dialect from a shared library (`.so` / `.dylib` / `.dll`).
    ///
    /// Resolves the single `syntaqlite_<name>_dialect` symbol (or
    /// `syntaqlite_dialect` when `name` is `None`), which returns a pointer to
    /// a `SyntaqliteDialect` struct bundling grammar + all data arrays.
    /// Returns an error if the symbol is absent or the library cannot be opened.
    ///
    /// Dropping the last clone of the returned handle unloads the library.
    #[cfg(feature = "dynload")]
    pub fn load(path: &str, name: Option<&str>) -> Result<Self, String> {
        // SAFETY: We keep `lib` alive in an `Arc` so the data pointer returned
        // by the dialect symbol lives as long as this `AnyDialect`.
        let lib = unsafe {
            libloading::Library::new(path).map_err(|e| format!("failed to load {path:?}: {e}"))?
        };

        let sym: String = match name {
            Some(n) => format!("syntaqlite_{n}_dialect"),
            None => "syntaqlite_dialect".to_string(),
        };

        // Resolve the single dialect symbol and call it to get the data pointer.
        // SAFETY: symbol is called immediately; the pointer it returns lives in
        // the library which we keep alive via `keep_alive` below.
        let data: *const ffi::CDialectTemplate = unsafe {
            let func: libloading::Symbol<
                '_,
                unsafe extern "C" fn() -> *const ffi::CDialectTemplate,
            > = lib
                .get(sym.as_bytes())
                .map_err(|e| format!("symbol {sym:?} not found in {path:?}: {e}"))?;
            func()
        };

        // SAFETY: data is valid and kept alive by `keep_alive` below.
        let grammar = unsafe { (*data).any_grammar() };

        let keep_alive: Arc<dyn Send + Sync> = Arc::new(lib);
        Ok(AnyDialect {
            grammar,
            data,
            ext_cflags: crate::util::SqliteFlags::default(),
            _keep_alive: Some(keep_alive),
        })
    }
}

impl std::ops::Deref for AnyDialect {
    type Target = AnyGrammar;
    fn deref(&self) -> &AnyGrammar {
        &self.grammar
    }
}

impl std::ops::DerefMut for AnyDialect {
    fn deref_mut(&mut self) -> &mut AnyGrammar {
        &mut self.grammar
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    #[cfg(feature = "sqlite")]
    fn dialect_has_roles() {
        let d = crate::sqlite::dialect::any_dialect();
        assert!(!d.roles().is_empty());
    }

    #[test]
    #[cfg(feature = "sqlite")]
    fn dialect_has_fmt_data() {
        let d = crate::sqlite::dialect::any_dialect();
        assert!(d.has_fmt_data());
    }

    #[test]
    fn semantic_role_variants_exist() {
        let _ = SemanticRole::Transparent;
        let _ = SemanticRole::DefineTable {
            name: 0,
            columns: FIELD_ABSENT,
            select: FIELD_ABSENT,
        };
        let _ = SemanticRole::DefineView {
            name: 0,
            columns: FIELD_ABSENT,
            select: 1,
        };
        let _ = SemanticRole::DefineFunction {
            name: 0,
            args: FIELD_ABSENT,
            return_type: FIELD_ABSENT,
        };
        let _ = SemanticRole::ReturnSpec {
            columns: FIELD_ABSENT,
        };
        let _ = SemanticRole::Import { module: 0 };
    }

    #[test]
    fn field_idx_is_u8() {
        let _: FieldIdx = 42u8;
    }
}

// ── ffi ───────────────────────────────────────────────────────────────────────

pub(crate) mod ffi {
    use syntaqlite_syntax::any::AnyGrammar;

    use crate::dialect::SemanticRole;

    /// C-ABI mirror of the `SyntaqliteDialect` struct emitted by dialect codegen.
    ///
    /// Bundles the default grammar handle with all static formatter and semantic-role
    /// arrays. A single `syntaqlite_<name>_dialect()` extern "C" function returns a
    /// pointer to a static instance of this struct — analogous to how grammar codegen
    /// emits `syntaqlite_<name>_grammar()` returning `SyntaqliteGrammar`.
    ///
    /// Field order and types must exactly match the C `SyntaqliteDialect` typedef
    /// emitted in the generated `dialect.c`. All fields are private; use the
    /// provided methods to access the data safely.
    #[repr(C)]
    pub(crate) struct CDialectTemplate {
        grammar: syntaqlite_syntax::typed::CGrammar,
        fmt_str_data: *const u8,
        fmt_str_offsets: *const u32,
        fmt_str_count: u32,
        fmt_enum_display: *const u16,
        fmt_enum_display_count: u32,
        fmt_ops: *const u8,
        fmt_ops_count: u32,
        fmt_dispatch: *const u32,
        fmt_dispatch_count: u32,
        roles_data: *const u8,
        roles_count: u32,
    }

    // SAFETY: CDialectTemplate contains only pointers to immutable static C data.
    unsafe impl Send for CDialectTemplate {}
    // SAFETY: same as Send above.
    unsafe impl Sync for CDialectTemplate {}

    impl CDialectTemplate {
        /// Construct an [`AnyGrammar`] from the grammar handle embedded in this template.
        ///
        /// # Safety
        /// `self` must be a valid, fully-initialized `CDialectTemplate`.
        pub(crate) unsafe fn any_grammar(&self) -> AnyGrammar {
            // SAFETY: caller guarantees self is valid.
            unsafe { AnyGrammar::new(self.grammar) }
        }

        /// The semantic role table for this dialect, indexed by node tag.
        ///
        /// # Safety
        /// `self` must be a valid, fully-initialized `CDialectTemplate`.
        pub(crate) unsafe fn roles(&self) -> &'static [SemanticRole] {
            // SAFETY: roles_data points to roles_count valid SemanticRole values in static storage.
            unsafe {
                std::slice::from_raw_parts(
                    self.roles_data as *const SemanticRole,
                    self.roles_count as usize,
                )
            }
        }

        /// Whether this template has formatter data.
        pub(crate) fn has_fmt_data(&self) -> bool {
            self.fmt_str_count > 0
        }

        /// Read the packed `fmt_dispatch` entry for a node-tag index.
        ///
        /// Returns `(opcode_slice, op_count)` or `None` if the tag is out of range
        /// or has no dispatch entry.
        ///
        /// # Safety
        /// `self` must be a valid, fully-initialized `CDialectTemplate`.
        pub(crate) unsafe fn fmt_dispatch(&self, tag_idx: usize) -> Option<(&[u8], usize)> {
            if tag_idx >= self.fmt_dispatch_count as usize {
                return None;
            }
            // SAFETY: tag_idx < fmt_dispatch_count; fmt_dispatch is valid for that range.
            let packed = unsafe { *self.fmt_dispatch.add(tag_idx) };
            let offset = (packed >> 16) as u16;
            let length = (packed & 0xFFFF) as u16;
            if offset == 0xFFFF {
                return None;
            }
            let byte_offset = offset as usize * 6;
            let byte_len = length as usize * 6;
            // SAFETY: dispatch entries are bounds-checked at codegen time.
            let slice =
                unsafe { std::slice::from_raw_parts(self.fmt_ops.add(byte_offset), byte_len) };
            Some((slice, length as usize))
        }

        /// Look up a string from the fmt string table by index (CSR encoding).
        ///
        /// # Safety
        /// `self` must be a valid template and `idx` must be in bounds.
        pub(crate) unsafe fn fmt_string(&self, idx: usize) -> &'static str {
            // SAFETY: offsets has fmt_str_count+1 entries; fmt_str_data covers the range.
            let (start, end) = unsafe {
                (
                    *self.fmt_str_offsets.add(idx) as usize,
                    *self.fmt_str_offsets.add(idx + 1) as usize,
                )
            };
            // SAFETY: bytes are valid UTF-8 by codegen construction.
            unsafe {
                std::str::from_utf8_unchecked(std::slice::from_raw_parts(
                    self.fmt_str_data.add(start),
                    end - start,
                ))
            }
        }

        /// Look up a value in the enum display table.
        ///
        /// # Safety
        /// `self` must be valid and `idx` must be in bounds.
        pub(crate) unsafe fn fmt_enum_display_val(&self, idx: usize) -> u16 {
            // SAFETY: callers pass indices checked at codegen time.
            unsafe { *self.fmt_enum_display.add(idx) }
        }
    }
}
