// Copyright 2025 The syntaqlite Authors. All rights reserved.
// Licensed under the Apache License, Version 2.0.

//! Typed wrappers around the dialect-agnostic base parser and tokenizer.
//!
//! This module provides generic types parameterized over node types (via
//! [`DialectNodeType`]) and token types (via [`DialectTokenType`]), enabling
//! any dialect to build ergonomic typed APIs.

use std::ops::Range;

use super::incremental::{RawIncrementalCursor, RawIncrementalParser, RawIncrementalParserBuilder};
use super::session::{ParseError, RawNodeReader, RawParser, RawParserBuilder, RawStatementCursor};
use super::tokenizer::{RawTokenCursor, RawTokenizer};
pub use syntaqlite_parser::dialect_traits::{DialectNodeType, DialectTokenType};
use syntaqlite_parser::nodes::NodeId;

// ── TypedParser ──────────────────────────────────────────────────────────

/// A generic parser wrapping [`RawParser`], pre-bound to a dialect.
///
/// The node type `N` is chosen at the `parse()` call site, so a single
/// `TypedParser` instance can be shared across node types.
#[doc(hidden)]
pub struct TypedParser<'d> {
    inner: RawParser<'d>,
}

// SAFETY: RawParser is Send; TypedParser is a thin wrapper.
unsafe impl<'d> Send for TypedParser<'d> {}

impl<'d> TypedParser<'d> {
    /// Create a parser bound to the given dialect.
    pub fn new(dialect: &'d crate::dialect::Dialect<'d>) -> Self {
        Self::builder(dialect).build()
    }

    /// Create a builder for more detailed configuration.
    pub fn builder(dialect: &'d crate::dialect::Dialect<'d>) -> TypedParserBuilder<'d> {
        TypedParserBuilder {
            inner: RawParser::builder(dialect),
        }
    }

    /// Bind source text and return a [`TypedStatementCursor`].
    ///
    /// `N` is inferred from the return type (e.g. the dialect's `Stmt<'a>`).
    pub fn parse<'a, N: DialectNodeType<'a>>(
        &'a mut self,
        source: &'a str,
    ) -> TypedStatementCursor<'a, N> {
        TypedStatementCursor::new(self.inner.parse(source))
    }

    /// Zero-copy variant: bind a null-terminated source.
    pub fn parse_cstr<'a, N: DialectNodeType<'a>>(
        &'a mut self,
        source: &'a std::ffi::CStr,
    ) -> TypedStatementCursor<'a, N> {
        TypedStatementCursor::new(self.inner.parse_cstr(source))
    }
}

// ── TypedParserBuilder ────────────────────────────────────────────────────

/// Builder for [`TypedParser`].
#[doc(hidden)]
pub struct TypedParserBuilder<'d> {
    inner: RawParserBuilder<'d>,
}

impl<'d> TypedParserBuilder<'d> {
    /// Enable parser trace output.
    pub fn trace(mut self, enable: bool) -> Self {
        self.inner = self.inner.trace(enable);
        self
    }

    /// Collect token positions during parsing.
    pub fn collect_tokens(mut self, enable: bool) -> Self {
        self.inner = self.inner.collect_tokens(enable);
        self
    }

    /// Set dialect config for version/cflag-gated parsing.
    pub fn dialect_config(
        mut self,
        config: syntaqlite_parser::dialect::ffi::DialectConfig,
    ) -> Self {
        self.inner = self.inner.dialect_config(config);
        self
    }

    /// Build the parser.
    pub fn build(self) -> TypedParser<'d> {
        TypedParser {
            inner: self.inner.build(),
        }
    }
}

// ── TypedStatementCursor ────────────────────────────────────────────────

/// A generic streaming cursor over parsed SQL statements.
///
/// Yields nodes of type `N` (must implement [`DialectNodeType`]) by resolving
/// [`NodeRef`](crate::ext::NodeRef) from the underlying [`RawStatementCursor`].
///
/// # Type parameter
/// - `N: DialectNodeType<'a>` — the typed node type (generated by codegen for each dialect)
///
/// # Example
///
/// ```ignore
/// // For a dialect with a custom Node enum:
/// let mut cursor = TypedStatementCursor::<MyNode>::new(raw_cursor);
/// while let Some(result) = cursor.next_statement() {
///     let node = result?;
///     // Process MyNode...
/// }
/// ```
#[doc(hidden)]
pub struct TypedStatementCursor<'a, N: DialectNodeType<'a>> {
    inner: RawStatementCursor<'a>,
    _phantom: std::marker::PhantomData<N>,
}

impl<'a, N: DialectNodeType<'a>> TypedStatementCursor<'a, N> {
    /// Create a typed cursor from a raw cursor.
    pub fn new(inner: RawStatementCursor<'a>) -> Self {
        TypedStatementCursor {
            inner,
            _phantom: std::marker::PhantomData,
        }
    }

    /// Parse the next SQL statement and return a typed AST node.
    ///
    /// Returns:
    /// - `Some(Ok(node))` — successfully parsed and resolved statement.
    /// - `Some(Err(e))` — syntax error; call again to continue with subsequent statements.
    /// - `None` — all input has been consumed.
    pub fn next_statement(&mut self) -> Option<Result<N, ParseError>> {
        self.inner.next_statement().map(|result| {
            result.and_then(|node_ref| {
                let node_id = node_ref.id();
                node_ref.as_typed().ok_or_else(|| ParseError {
                    message: "failed to resolve typed AST node".to_string(),
                    offset: None,
                    length: None,
                    root: Some(node_id),
                })
            })
        })
    }

    /// Get a reference to the embedded [`RawNodeReader`].
    pub fn reader(&self) -> &RawNodeReader<'a> {
        self.inner.reader()
    }

    /// The source text bound to this cursor.
    pub fn source(&self) -> &'a str {
        self.inner.source()
    }

    /// Dump an AST node tree as indented text.
    pub fn dump_node(&self, id: NodeId, out: &mut String, indent: usize) {
        self.inner.dump_node(id, out, indent)
    }
}

impl<'a, N: DialectNodeType<'a>> Iterator for TypedStatementCursor<'a, N> {
    type Item = Result<N, ParseError>;

    fn next(&mut self) -> Option<Self::Item> {
        self.next_statement()
    }
}

// ── TypedToken ──────────────────────────────────────────────────────────

/// A generic typed token with a dialect-specific token type variant and source text.
///
/// # Type parameter
/// - `T: DialectTokenType` — the dialect's token type enum (generated by codegen)
#[derive(Debug, Clone, Copy)]
#[doc(hidden)]
pub struct TypedToken<'a, T: DialectTokenType> {
    /// The typed token kind.
    pub kind: T,
    /// The text of the token (a slice of the source).
    pub text: &'a str,
}

// ── TypedTokenizer ──────────────────────────────────────────────────────

/// A generic tokenizer for any dialect, yielding [`TypedToken`]s.
///
/// # Type parameter
/// - `T: DialectTokenType` — the dialect's token type (generated by codegen)
///
/// # Example
///
/// ```ignore
/// // For a custom dialect:
/// let mut tokenizer = TypedTokenizer::<MyTokenType>::new();
/// for token in tokenizer.tokenize("SELECT 1") {
///     println!("{:?}: {:?}", token.kind, token.text);
/// }
/// ```
#[doc(hidden)]
pub struct TypedTokenizer<'d, T: DialectTokenType> {
    inner: RawTokenizer<'d>,
    _phantom: std::marker::PhantomData<T>,
}

// SAFETY: RawTokenizer is Send, and TypedTokenizer is a thin wrapper.
unsafe impl<'d, T: DialectTokenType> Send for TypedTokenizer<'d, T> {}

impl<'d, T: DialectTokenType> TypedTokenizer<'d, T> {
    /// Create a tokenizer with default configuration.
    pub fn new(dialect: &'d crate::dialect::Dialect<'d>) -> Self {
        Self::builder(dialect).build()
    }

    /// Create a builder for configuring the tokenizer before construction.
    pub fn builder(dialect: &'d crate::dialect::Dialect<'d>) -> TypedTokenizerBuilder<'d, T> {
        TypedTokenizerBuilder {
            inner: RawTokenizer::builder(*dialect),
            _phantom: std::marker::PhantomData,
        }
    }

    /// Bind source text and return a [`TypedTokenCursor`] for iterating typed tokens.
    pub fn tokenize<'a>(&'a mut self, source: &'a str) -> TypedTokenCursor<'a, T> {
        TypedTokenCursor {
            inner: self.inner.tokenize(source),
            _phantom: std::marker::PhantomData,
        }
    }

    /// Zero-copy variant: bind a null-terminated source and return a [`TypedTokenCursor`].
    pub fn tokenize_cstr<'a>(&'a mut self, source: &'a std::ffi::CStr) -> TypedTokenCursor<'a, T> {
        TypedTokenCursor {
            inner: self.inner.tokenize_cstr(source),
            _phantom: std::marker::PhantomData,
        }
    }
}

// ── TypedTokenizerBuilder ────────────────────────────────────────────────

/// Builder for configuring a [`TypedTokenizer<'d, T>`] before construction.
#[doc(hidden)]
pub struct TypedTokenizerBuilder<'d, T: DialectTokenType> {
    inner: crate::parser::tokenizer::RawTokenizerBuilder<'d>,
    _phantom: std::marker::PhantomData<T>,
}

impl<'d, T: DialectTokenType> TypedTokenizerBuilder<'d, T> {
    /// Set dialect config for version/cflag-gated tokenization.
    pub fn dialect_config(
        mut self,
        config: syntaqlite_parser::dialect::ffi::DialectConfig,
    ) -> Self {
        self.inner = self.inner.dialect_config(config);
        self
    }

    /// Build the tokenizer.
    pub fn build(self) -> TypedTokenizer<'d, T> {
        TypedTokenizer {
            inner: self.inner.build(),
            _phantom: std::marker::PhantomData,
        }
    }
}

// ── TypedTokenCursor ────────────────────────────────────────────────────

/// A generic cursor yielding [`TypedToken`]s of dialect-specific type `T`.
///
/// Skips tokens with unknown type ordinals (which shouldn't occur with
/// a well-formed dialect, but is handled defensively).
pub struct TypedTokenCursor<'a, T: DialectTokenType> {
    inner: RawTokenCursor<'a>,
    _phantom: std::marker::PhantomData<T>,
}

impl<'a, T: DialectTokenType> Iterator for TypedTokenCursor<'a, T> {
    type Item = TypedToken<'a, T>;

    fn next(&mut self) -> Option<Self::Item> {
        loop {
            let raw = self.inner.next()?;
            if let Some(kind) = T::from_token_type(raw.token_type) {
                return Some(TypedToken {
                    kind,
                    text: raw.text,
                });
            }
            // Skip tokens with unknown type ordinals.
        }
    }
}

// ── TypedIncrementalParser ───────────────────────────────────────────────

/// A generic incremental parser wrapping [`RawIncrementalParser`], pre-bound
/// to a dialect.
///
/// Feeds tokens one at a time via [`TypedIncrementalCursor`]. Generic over
/// both the node type `N` (for typed AST results) and the token type `T`
/// (for typed `feed_token` calls).
#[doc(hidden)]
pub struct TypedIncrementalParser<'d> {
    inner: RawIncrementalParser<'d>,
}

// SAFETY: RawIncrementalParser is Send; TypedIncrementalParser is a thin wrapper.
unsafe impl<'d> Send for TypedIncrementalParser<'d> {}

impl<'d> TypedIncrementalParser<'d> {
    /// Create a parser bound to the given dialect.
    pub fn new(dialect: &'d crate::dialect::Dialect<'d>) -> Self {
        Self::builder(dialect).build()
    }

    /// Create a builder for more detailed configuration.
    pub fn builder(dialect: &'d crate::dialect::Dialect<'d>) -> TypedIncrementalParserBuilder<'d> {
        TypedIncrementalParserBuilder {
            inner: RawIncrementalParser::builder(dialect),
        }
    }

    /// Bind source text and return a [`TypedIncrementalCursor`] for token feeding.
    ///
    /// `N` and `T` are inferred from the call site.
    pub fn feed<'a, N, T>(&'a mut self, source: &'a str) -> TypedIncrementalCursor<'a, N, T>
    where
        N: DialectNodeType<'a>,
        T: DialectTokenType,
    {
        TypedIncrementalCursor {
            inner: self.inner.feed(source),
            last_root: None,
            _phantom: std::marker::PhantomData,
        }
    }

    /// Zero-copy variant: bind a null-terminated source.
    pub fn feed_cstr<'a, N, T>(
        &'a mut self,
        source: &'a std::ffi::CStr,
    ) -> TypedIncrementalCursor<'a, N, T>
    where
        N: DialectNodeType<'a>,
        T: DialectTokenType,
    {
        TypedIncrementalCursor {
            inner: self.inner.feed_cstr(source),
            last_root: None,
            _phantom: std::marker::PhantomData,
        }
    }
}

// ── TypedIncrementalParserBuilder ────────────────────────────────────────

/// Builder for [`TypedIncrementalParser`].
#[doc(hidden)]
pub struct TypedIncrementalParserBuilder<'d> {
    inner: RawIncrementalParserBuilder<'d>,
}

impl<'d> TypedIncrementalParserBuilder<'d> {
    /// Enable parser trace output.
    pub fn trace(mut self, enable: bool) -> Self {
        self.inner = self.inner.trace(enable);
        self
    }

    /// Collect non-whitespace token positions during parsing.
    pub fn collect_tokens(mut self, enable: bool) -> Self {
        self.inner = self.inner.collect_tokens(enable);
        self
    }

    /// Set dialect config for version/cflag-gated parsing.
    pub fn dialect_config(
        mut self,
        config: syntaqlite_parser::dialect::ffi::DialectConfig,
    ) -> Self {
        self.inner = self.inner.dialect_config(config);
        self
    }

    /// Build the incremental parser.
    pub fn build(self) -> TypedIncrementalParser<'d> {
        TypedIncrementalParser {
            inner: self.inner.build(),
        }
    }
}

// ── TypedIncrementalCursor ───────────────────────────────────────────────

/// A generic cursor for token-by-token incremental parsing.
///
/// - `N: DialectNodeType<'a>` — the typed node returned by `feed_token` / `finish`.
/// - `T: DialectTokenType` — the typed token fed via `feed_token`.
///
/// After calling `finish()`, no further methods may be called.
#[doc(hidden)]
pub struct TypedIncrementalCursor<'a, N, T> {
    inner: RawIncrementalCursor<'a>,
    last_root: Option<crate::parser::session::NodeRef<'a>>,
    _phantom: std::marker::PhantomData<fn(T) -> N>,
}

impl<'a, N, T> TypedIncrementalCursor<'a, N, T>
where
    N: DialectNodeType<'a>,
    T: DialectTokenType,
{
    /// Feed a typed token to the parser.
    ///
    /// Returns `Ok(Some(node))` when a statement completes, `Ok(None)` to
    /// keep going, or `Err` on parse error.
    pub fn feed_token(
        &mut self,
        token_type: T,
        span: Range<usize>,
    ) -> Result<Option<N>, ParseError> {
        match self.inner.feed_token(token_type.into(), span)? {
            None => Ok(None),
            Some(id) => {
                let node_ref = self.inner.node_ref(id);
                self.last_root = Some(node_ref);
                let node = node_ref.as_typed::<N>().ok_or_else(|| ParseError {
                    message: "failed to resolve typed AST node".to_string(),
                    offset: None,
                    length: None,
                    root: Some(id),
                })?;
                Ok(Some(node))
            }
        }
    }

    /// Signal end of input.
    ///
    /// Returns `Ok(Some(node))` if a final statement completed, `Ok(None)`
    /// if there was nothing pending, or `Err` on parse error.
    ///
    /// No further methods may be called after `finish()`.
    pub fn finish(&mut self) -> Result<Option<N>, ParseError> {
        match self.inner.finish()? {
            None => Ok(None),
            Some(id) => {
                let node_ref = self.inner.node_ref(id);
                self.last_root = Some(node_ref);
                let node = node_ref.as_typed::<N>().ok_or_else(|| ParseError {
                    message: "failed to resolve typed AST node".to_string(),
                    offset: None,
                    length: None,
                    root: Some(id),
                })?;
                Ok(Some(node))
            }
        }
    }

    /// Return the [`NodeRef`] for the last completed statement (from the most
    /// recent successful `feed_token` or `finish` call).
    pub fn root(&self) -> Option<crate::parser::session::NodeRef<'a>> {
        self.last_root
    }

    /// Return terminal token IDs valid at the current parser state, as raw u32 ordinals.
    pub fn expected_tokens(&self) -> Vec<u32> {
        self.inner.expected_tokens()
    }

    /// Return the semantic completion context at the current parser state.
    pub fn completion_context(&self) -> u32 {
        self.inner.completion_context()
    }

    /// Return the number of nodes currently in the parser arena.
    pub fn node_count(&self) -> u32 {
        self.inner.node_count()
    }

    /// Mark subsequent fed tokens as inside a macro expansion.
    pub fn begin_macro(&mut self, call_offset: u32, call_length: u32) {
        self.inner.begin_macro(call_offset, call_length)
    }

    /// End the innermost macro expansion region.
    pub fn end_macro(&mut self) {
        self.inner.end_macro()
    }

    /// Get a reference to the embedded [`RawNodeReader`].
    pub fn reader(&self) -> &RawNodeReader<'a> {
        self.inner.reader()
    }

    /// Return all comments captured during parsing.
    pub fn comments(&self) -> &[syntaqlite_parser::parser::Comment] {
        self.inner.comments()
    }

    /// Return all macro regions recorded via `begin_macro`/`end_macro`.
    pub fn macro_regions(&self) -> &[syntaqlite_parser::parser::MacroRegion] {
        self.inner.macro_regions()
    }
}
