// Copyright 2025 The syntaqlite Authors. All rights reserved.
// Licensed under the Apache License, Version 2.0.
// @generated by sqlite-extract — DO NOT EDIT

/// Cflag metadata: (name, index, min_version, category).
///
/// `index` is the group-local bit index in `Cflags` (matches `SYNQ_CFLAG_IDX_*` constants).
///
/// `min_version` is the encoded SQLite version integer at which this cflag
/// first appears in the amalgamation source. Zero = not observed.
///
/// `category` groups flags by feature area for UI presentation:
/// "parser", "functions", "vtable", "extensions".
pub(crate) const CFLAG_TABLE: &[(&str, u32, i32, &str)] = &[
    ("SQLITE_OMIT_ALTERTABLE", 0, 0, "parser"),
    ("SQLITE_OMIT_ANALYZE", 1, 0, "parser"),
    ("SQLITE_OMIT_ATTACH", 2, 0, "parser"),
    ("SQLITE_OMIT_AUTOINCREMENT", 3, 0, "parser"),
    ("SQLITE_OMIT_CAST", 4, 0, "parser"),
    ("SQLITE_OMIT_COMPOUND_SELECT", 5, 0, "parser"),
    ("SQLITE_OMIT_CTE", 6, 0, "parser"),
    ("SQLITE_OMIT_EXPLAIN", 7, 0, "parser"),
    ("SQLITE_OMIT_FOREIGN_KEY", 8, 0, "parser"),
    ("SQLITE_OMIT_GENERATED_COLUMNS", 9, 0, "parser"),
    ("SQLITE_OMIT_PRAGMA", 10, 0, "parser"),
    ("SQLITE_OMIT_REINDEX", 11, 0, "parser"),
    ("SQLITE_OMIT_RETURNING", 12, 0, "parser"),
    ("SQLITE_OMIT_SUBQUERY", 13, 0, "parser"),
    ("SQLITE_OMIT_TEMPDB", 14, 0, "parser"),
    ("SQLITE_OMIT_TRIGGER", 15, 0, "parser"),
    ("SQLITE_OMIT_VACUUM", 16, 0, "parser"),
    ("SQLITE_OMIT_VIEW", 17, 0, "parser"),
    ("SQLITE_OMIT_VIRTUALTABLE", 18, 0, "parser"),
    ("SQLITE_OMIT_WINDOWFUNC", 19, 3030001, "parser"),
    (
        "SQLITE_ENABLE_ORDERED_SET_AGGREGATES",
        20,
        3047002,
        "parser",
    ),
    ("SQLITE_ENABLE_UPDATE_DELETE_LIMIT", 21, 0, "parser"),
];
