// Copyright 2025 The syntaqlite Authors. All rights reserved.
// Licensed under the Apache License, Version 2.0.
//
// @generated by syntaqlite-buildtools — DO NOT EDIT

use std::sync::LazyLock;

use syntaqlite_syntax::typed::Grammar;
use syntaqlite_syntax::util::SqliteVersion;

use crate::dialect::{AnyDialect, TypedDialect};
use crate::util::SqliteFlags;

/// The typed dialect handle.
///
/// Wraps an [`AnyDialect`] and implements [`TypedDialect`]. Obtain via [`dialect()`];
/// configure with [`with_version`](Self::with_version) and [`with_cflags`](Self::with_cflags).
#[derive(Clone)]
pub struct Dialect {
    raw: AnyDialect,
}

impl Dialect {
    /// Returns a new default dialect handle.
    pub fn new() -> Self {
        dialect()
    }

    /// Erase to an [`AnyDialect`].
    pub fn erase(self) -> AnyDialect {
        self.raw
    }

    /// Return the typed grammar handle for this dialect.
    pub fn grammar(&self) -> Grammar {
        Grammar::from_raw(self.raw.grammar().clone())
    }

    /// Return a copy targeting a specific `SQLite` version.
    #[must_use]
    pub fn with_version(self, version: SqliteVersion) -> Self {
        Dialect { raw: self.raw.with_version(version) }
    }

    /// Return a copy with the given compile-time flags.
    #[must_use]
    pub fn with_cflags(self, flags: SqliteFlags) -> Self {
        Dialect { raw: self.raw.with_cflags(flags) }
    }
}

impl Default for Dialect {
    fn default() -> Self {
        Self::new()
    }
}

impl TypedDialect for Dialect {}

impl From<Dialect> for AnyDialect {
    fn from(d: Dialect) -> AnyDialect {
        d.raw
    }
}

impl std::ops::Deref for Dialect {
    type Target = AnyDialect;
    fn deref(&self) -> &AnyDialect {
        &self.raw
    }
}

impl std::ops::DerefMut for Dialect {
    fn deref_mut(&mut self) -> &mut AnyDialect {
        &mut self.raw
    }
}

static DIALECT: LazyLock<AnyDialect> = LazyLock::new(|| {
    // SAFETY: syntaqlite_sqlite_dialect() returns a pointer to a valid static SyntaqliteDialectTemplate
    // struct compiled into the binary. The data lives for the entire program lifetime.
    unsafe { AnyDialect::from_data(ffi::syntaqlite_sqlite_dialect()) }
});

/// Returns the type-erased dialect handle (cached).
pub(crate) fn any_dialect() -> AnyDialect {
    DIALECT.clone()
}

/// Returns the typed dialect handle.
pub(crate) fn dialect() -> Dialect {
    Dialect { raw: any_dialect() }
}

// ── ffi ───────────────────────────────────────────────────────────────────────

mod ffi {
    use crate::dialect::CDialectTemplate;

    unsafe extern "C" {
        pub(super) fn syntaqlite_sqlite_dialect() -> *const CDialectTemplate;
    }
}
