// Copyright 2025 The syntaqlite Authors. All rights reserved.
// Licensed under the Apache License, Version 2.0.
//
// @generated by syntaqlite-buildtools — DO NOT EDIT

#![allow(clippy::struct_field_names)]

use crate::ast::{AnyNodeId, ArenaNode, SourceSpan};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u32)]
pub(crate) enum Bool {
    #[expect(dead_code)] // Populated from C FFI
    False = 0,
    True = 1,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct AggregateFunctionCall {
    pub(crate) tag: u32,
    pub(crate) func_name: SourceSpan,
    pub(crate) flags: super::ast::AggregateFunctionCallFlags,
    pub(crate) args: AnyNodeId,
    pub(crate) orderby: AnyNodeId,
    pub(crate) filter_clause: AnyNodeId,
    pub(crate) over_clause: AnyNodeId,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct OrderedSetFunctionCall {
    pub(crate) tag: u32,
    pub(crate) func_name: SourceSpan,
    pub(crate) flags: super::ast::AggregateFunctionCallFlags,
    pub(crate) args: AnyNodeId,
    pub(crate) orderby_expr: AnyNodeId,
    pub(crate) filter_clause: AnyNodeId,
    pub(crate) over_clause: AnyNodeId,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct CastExpr {
    pub(crate) tag: u32,
    pub(crate) expr: AnyNodeId,
    pub(crate) type_name: SourceSpan,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct ColumnRef {
    pub(crate) tag: u32,
    pub(crate) column: SourceSpan,
    pub(crate) table: SourceSpan,
    pub(crate) schema: SourceSpan,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct CompoundSelect {
    pub(crate) tag: u32,
    pub(crate) op: super::ast::CompoundOp,
    pub(crate) left: AnyNodeId,
    pub(crate) right: AnyNodeId,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct SubqueryExpr {
    pub(crate) tag: u32,
    pub(crate) select: AnyNodeId,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct ExistsExpr {
    pub(crate) tag: u32,
    pub(crate) select: AnyNodeId,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct InExpr {
    pub(crate) tag: u32,
    pub(crate) negated: Bool,
    pub(crate) operand: AnyNodeId,
    pub(crate) source: AnyNodeId,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct IsExpr {
    pub(crate) tag: u32,
    pub(crate) op: super::ast::IsOp,
    pub(crate) left: AnyNodeId,
    pub(crate) right: AnyNodeId,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct BetweenExpr {
    pub(crate) tag: u32,
    pub(crate) negated: Bool,
    pub(crate) operand: AnyNodeId,
    pub(crate) low: AnyNodeId,
    pub(crate) high: AnyNodeId,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct LikeExpr {
    pub(crate) tag: u32,
    pub(crate) negated: Bool,
    pub(crate) keyword: super::ast::LikeKeyword,
    pub(crate) operand: AnyNodeId,
    pub(crate) pattern: AnyNodeId,
    pub(crate) escape: AnyNodeId,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct CaseExpr {
    pub(crate) tag: u32,
    pub(crate) operand: AnyNodeId,
    pub(crate) else_expr: AnyNodeId,
    pub(crate) whens: AnyNodeId,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct CaseWhen {
    pub(crate) tag: u32,
    pub(crate) when_expr: AnyNodeId,
    pub(crate) then_expr: AnyNodeId,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct ForeignKeyClause {
    pub(crate) tag: u32,
    pub(crate) ref_table: SourceSpan,
    pub(crate) ref_columns: AnyNodeId,
    pub(crate) on_delete: super::ast::ForeignKeyAction,
    pub(crate) on_update: super::ast::ForeignKeyAction,
    pub(crate) is_deferred: Bool,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct ColumnConstraint {
    pub(crate) tag: u32,
    pub(crate) kind: super::ast::ColumnConstraintType,
    pub(crate) constraint_name: SourceSpan,
    pub(crate) onconf: super::ast::ConflictAction,
    pub(crate) sort_order: super::ast::SortOrder,
    pub(crate) is_autoincrement: Bool,
    pub(crate) collation_name: SourceSpan,
    pub(crate) generated_storage: super::ast::GeneratedColumnStorage,
    pub(crate) default_expr: AnyNodeId,
    pub(crate) check_expr: AnyNodeId,
    pub(crate) generated_expr: AnyNodeId,
    pub(crate) fk_clause: AnyNodeId,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct ColumnDef {
    pub(crate) tag: u32,
    pub(crate) column_name: AnyNodeId,
    pub(crate) type_name: SourceSpan,
    pub(crate) constraints: AnyNodeId,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct TableConstraint {
    pub(crate) tag: u32,
    pub(crate) kind: super::ast::TableConstraintType,
    pub(crate) constraint_name: SourceSpan,
    pub(crate) onconf: super::ast::ConflictAction,
    pub(crate) is_autoincrement: Bool,
    pub(crate) pk_columns: AnyNodeId,
    pub(crate) fk_columns: AnyNodeId,
    pub(crate) check_expr: AnyNodeId,
    pub(crate) fk_clause: AnyNodeId,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct CreateTableStmt {
    pub(crate) tag: u32,
    pub(crate) table_name: SourceSpan,
    pub(crate) schema: SourceSpan,
    pub(crate) is_temp: Bool,
    pub(crate) if_not_exists: Bool,
    pub(crate) flags: super::ast::CreateTableStmtFlags,
    pub(crate) columns: AnyNodeId,
    pub(crate) table_constraints: AnyNodeId,
    pub(crate) as_select: AnyNodeId,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct CteDefinition {
    pub(crate) tag: u32,
    pub(crate) cte_name: SourceSpan,
    pub(crate) materialized: super::ast::Materialized,
    pub(crate) columns: AnyNodeId,
    pub(crate) select: AnyNodeId,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct WithClause {
    pub(crate) tag: u32,
    pub(crate) recursive: Bool,
    pub(crate) ctes: AnyNodeId,
    pub(crate) select: AnyNodeId,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct UpsertClause {
    pub(crate) tag: u32,
    pub(crate) columns: AnyNodeId,
    pub(crate) target_where: AnyNodeId,
    pub(crate) action: super::ast::UpsertAction,
    pub(crate) setlist: AnyNodeId,
    pub(crate) update_where: AnyNodeId,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct DeleteStmt {
    pub(crate) tag: u32,
    pub(crate) table: AnyNodeId,
    pub(crate) where_clause: AnyNodeId,
    pub(crate) orderby: AnyNodeId,
    pub(crate) limit_clause: AnyNodeId,
    pub(crate) returning: AnyNodeId,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct SetClause {
    pub(crate) tag: u32,
    pub(crate) column: SourceSpan,
    pub(crate) columns: AnyNodeId,
    pub(crate) value: AnyNodeId,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct UpdateStmt {
    pub(crate) tag: u32,
    pub(crate) conflict_action: super::ast::ConflictAction,
    pub(crate) table: AnyNodeId,
    pub(crate) setlist: AnyNodeId,
    pub(crate) from_clause: AnyNodeId,
    pub(crate) where_clause: AnyNodeId,
    pub(crate) orderby: AnyNodeId,
    pub(crate) limit_clause: AnyNodeId,
    pub(crate) returning: AnyNodeId,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct InsertStmt {
    pub(crate) tag: u32,
    pub(crate) conflict_action: super::ast::ConflictAction,
    pub(crate) table: AnyNodeId,
    pub(crate) columns: AnyNodeId,
    pub(crate) source: AnyNodeId,
    pub(crate) upsert: AnyNodeId,
    pub(crate) returning: AnyNodeId,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct BinaryExpr {
    pub(crate) tag: u32,
    pub(crate) op: super::ast::BinaryOp,
    pub(crate) left: AnyNodeId,
    pub(crate) right: AnyNodeId,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct UnaryExpr {
    pub(crate) tag: u32,
    pub(crate) op: super::ast::UnaryOp,
    pub(crate) operand: AnyNodeId,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct Literal {
    pub(crate) tag: u32,
    pub(crate) literal_type: super::ast::LiteralType,
    pub(crate) source: SourceSpan,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct IdentName {
    pub(crate) tag: u32,
    pub(crate) source: SourceSpan,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct Error {
    pub(crate) tag: u32,
    pub(crate) source: SourceSpan,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct FunctionCall {
    pub(crate) tag: u32,
    pub(crate) func_name: SourceSpan,
    pub(crate) flags: super::ast::FunctionCallFlags,
    pub(crate) args: AnyNodeId,
    pub(crate) filter_clause: AnyNodeId,
    pub(crate) over_clause: AnyNodeId,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct Variable {
    pub(crate) tag: u32,
    pub(crate) source: SourceSpan,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct CollateExpr {
    pub(crate) tag: u32,
    pub(crate) expr: AnyNodeId,
    pub(crate) collation: SourceSpan,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct RaiseExpr {
    pub(crate) tag: u32,
    pub(crate) raise_type: super::ast::RaiseType,
    pub(crate) error_message: AnyNodeId,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct QualifiedName {
    pub(crate) tag: u32,
    pub(crate) object_name: AnyNodeId,
    pub(crate) schema: AnyNodeId,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct DropStmt {
    pub(crate) tag: u32,
    pub(crate) object_type: super::ast::DropObjectType,
    pub(crate) if_exists: Bool,
    pub(crate) target: AnyNodeId,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct AlterTableStmt {
    pub(crate) tag: u32,
    pub(crate) op: super::ast::AlterOp,
    pub(crate) target: AnyNodeId,
    pub(crate) new_name: AnyNodeId,
    pub(crate) old_name: AnyNodeId,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct TransactionStmt {
    pub(crate) tag: u32,
    pub(crate) op: super::ast::TransactionOp,
    pub(crate) trans_type: super::ast::TransactionType,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct SavepointStmt {
    pub(crate) tag: u32,
    pub(crate) op: super::ast::SavepointOp,
    pub(crate) savepoint_name: AnyNodeId,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct ResultColumn {
    pub(crate) tag: u32,
    pub(crate) flags: super::ast::ResultColumnFlags,
    pub(crate) alias: AnyNodeId,
    pub(crate) expr: AnyNodeId,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct SelectStmt {
    pub(crate) tag: u32,
    pub(crate) flags: super::ast::SelectStmtFlags,
    pub(crate) columns: AnyNodeId,
    pub(crate) from_clause: AnyNodeId,
    pub(crate) where_clause: AnyNodeId,
    pub(crate) groupby: AnyNodeId,
    pub(crate) having: AnyNodeId,
    pub(crate) orderby: AnyNodeId,
    pub(crate) limit_clause: AnyNodeId,
    pub(crate) window_clause: AnyNodeId,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct OrderingTerm {
    pub(crate) tag: u32,
    pub(crate) expr: AnyNodeId,
    pub(crate) sort_order: super::ast::SortOrder,
    pub(crate) nulls_order: super::ast::NullsOrder,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct LimitClause {
    pub(crate) tag: u32,
    pub(crate) limit: AnyNodeId,
    pub(crate) offset: AnyNodeId,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct TableRef {
    pub(crate) tag: u32,
    pub(crate) table_name: SourceSpan,
    pub(crate) schema: SourceSpan,
    pub(crate) alias: AnyNodeId,
    pub(crate) args: AnyNodeId,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct SubqueryTableSource {
    pub(crate) tag: u32,
    pub(crate) select: AnyNodeId,
    pub(crate) alias: AnyNodeId,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct JoinClause {
    pub(crate) tag: u32,
    pub(crate) join_type: super::ast::JoinType,
    pub(crate) left: AnyNodeId,
    pub(crate) right: AnyNodeId,
    pub(crate) on_expr: AnyNodeId,
    pub(crate) using_columns: AnyNodeId,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct JoinPrefix {
    pub(crate) tag: u32,
    pub(crate) source: AnyNodeId,
    pub(crate) join_type: super::ast::JoinType,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct TriggerEvent {
    pub(crate) tag: u32,
    pub(crate) event_type: super::ast::TriggerEventType,
    pub(crate) columns: AnyNodeId,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct CreateTriggerStmt {
    pub(crate) tag: u32,
    pub(crate) trigger_name: SourceSpan,
    pub(crate) schema: SourceSpan,
    pub(crate) is_temp: Bool,
    pub(crate) if_not_exists: Bool,
    pub(crate) timing: super::ast::TriggerTiming,
    pub(crate) event: AnyNodeId,
    pub(crate) table: AnyNodeId,
    pub(crate) when_expr: AnyNodeId,
    pub(crate) body: AnyNodeId,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct CreateVirtualTableStmt {
    pub(crate) tag: u32,
    pub(crate) table_name: SourceSpan,
    pub(crate) schema: SourceSpan,
    pub(crate) module_name: SourceSpan,
    pub(crate) if_not_exists: Bool,
    pub(crate) module_args: SourceSpan,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct PragmaStmt {
    pub(crate) tag: u32,
    pub(crate) pragma_name: SourceSpan,
    pub(crate) schema: SourceSpan,
    pub(crate) value: SourceSpan,
    pub(crate) pragma_form: super::ast::PragmaForm,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct AnalyzeOrReindexStmt {
    pub(crate) tag: u32,
    pub(crate) target_name: SourceSpan,
    pub(crate) schema: SourceSpan,
    pub(crate) kind: super::ast::AnalyzeOrReindexOp,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct AttachStmt {
    pub(crate) tag: u32,
    pub(crate) filename: AnyNodeId,
    pub(crate) db_name: AnyNodeId,
    pub(crate) key: AnyNodeId,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct DetachStmt {
    pub(crate) tag: u32,
    pub(crate) db_name: AnyNodeId,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct VacuumStmt {
    pub(crate) tag: u32,
    pub(crate) schema: SourceSpan,
    pub(crate) filename: AnyNodeId,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct ExplainStmt {
    pub(crate) tag: u32,
    pub(crate) explain_mode: super::ast::ExplainMode,
    pub(crate) stmt: AnyNodeId,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct CreateIndexStmt {
    pub(crate) tag: u32,
    pub(crate) index_name: SourceSpan,
    pub(crate) schema: SourceSpan,
    pub(crate) table_name: SourceSpan,
    pub(crate) is_unique: Bool,
    pub(crate) if_not_exists: Bool,
    pub(crate) columns: AnyNodeId,
    pub(crate) where_clause: AnyNodeId,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct CreateViewStmt {
    pub(crate) tag: u32,
    pub(crate) view_name: SourceSpan,
    pub(crate) schema: SourceSpan,
    pub(crate) is_temp: Bool,
    pub(crate) if_not_exists: Bool,
    pub(crate) column_names: AnyNodeId,
    pub(crate) select: AnyNodeId,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct ValuesClause {
    pub(crate) tag: u32,
    pub(crate) rows: AnyNodeId,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct FrameBound {
    pub(crate) tag: u32,
    pub(crate) bound_type: super::ast::FrameBoundType,
    pub(crate) expr: AnyNodeId,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct FrameSpec {
    pub(crate) tag: u32,
    pub(crate) frame_type: super::ast::FrameType,
    pub(crate) exclude: super::ast::FrameExclude,
    pub(crate) start_bound: AnyNodeId,
    pub(crate) end_bound: AnyNodeId,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct WindowDef {
    pub(crate) tag: u32,
    pub(crate) base_window_name: SourceSpan,
    pub(crate) partition_by: AnyNodeId,
    pub(crate) orderby: AnyNodeId,
    pub(crate) frame: AnyNodeId,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct NamedWindowDef {
    pub(crate) tag: u32,
    pub(crate) window_name: SourceSpan,
    pub(crate) window_def: AnyNodeId,
}

#[derive(Debug, Clone)]
#[repr(C)]
pub(crate) struct FilterOver {
    pub(crate) tag: u32,
    pub(crate) filter_expr: AnyNodeId,
    pub(crate) over_def: AnyNodeId,
    pub(crate) over_name: SourceSpan,
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for AggregateFunctionCall {
    const TAG: u32 = 1;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for OrderedSetFunctionCall {
    const TAG: u32 = 2;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for CastExpr {
    const TAG: u32 = 3;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for ColumnRef {
    const TAG: u32 = 4;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for CompoundSelect {
    const TAG: u32 = 5;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for SubqueryExpr {
    const TAG: u32 = 6;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for ExistsExpr {
    const TAG: u32 = 7;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for InExpr {
    const TAG: u32 = 8;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for IsExpr {
    const TAG: u32 = 9;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for BetweenExpr {
    const TAG: u32 = 10;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for LikeExpr {
    const TAG: u32 = 11;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for CaseExpr {
    const TAG: u32 = 12;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for CaseWhen {
    const TAG: u32 = 13;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for ForeignKeyClause {
    const TAG: u32 = 15;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for ColumnConstraint {
    const TAG: u32 = 16;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for ColumnDef {
    const TAG: u32 = 18;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for TableConstraint {
    const TAG: u32 = 20;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for CreateTableStmt {
    const TAG: u32 = 22;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for CteDefinition {
    const TAG: u32 = 23;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for WithClause {
    const TAG: u32 = 25;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for UpsertClause {
    const TAG: u32 = 26;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for DeleteStmt {
    const TAG: u32 = 28;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for SetClause {
    const TAG: u32 = 29;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for UpdateStmt {
    const TAG: u32 = 31;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for InsertStmt {
    const TAG: u32 = 32;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for BinaryExpr {
    const TAG: u32 = 33;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for UnaryExpr {
    const TAG: u32 = 34;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for Literal {
    const TAG: u32 = 35;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for IdentName {
    const TAG: u32 = 36;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for Error {
    const TAG: u32 = 37;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for FunctionCall {
    const TAG: u32 = 39;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for Variable {
    const TAG: u32 = 40;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for CollateExpr {
    const TAG: u32 = 41;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for RaiseExpr {
    const TAG: u32 = 42;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for QualifiedName {
    const TAG: u32 = 43;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for DropStmt {
    const TAG: u32 = 44;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for AlterTableStmt {
    const TAG: u32 = 45;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for TransactionStmt {
    const TAG: u32 = 46;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for SavepointStmt {
    const TAG: u32 = 47;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for ResultColumn {
    const TAG: u32 = 48;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for SelectStmt {
    const TAG: u32 = 50;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for OrderingTerm {
    const TAG: u32 = 51;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for LimitClause {
    const TAG: u32 = 53;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for TableRef {
    const TAG: u32 = 54;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for SubqueryTableSource {
    const TAG: u32 = 55;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for JoinClause {
    const TAG: u32 = 56;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for JoinPrefix {
    const TAG: u32 = 57;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for TriggerEvent {
    const TAG: u32 = 58;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for CreateTriggerStmt {
    const TAG: u32 = 60;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for CreateVirtualTableStmt {
    const TAG: u32 = 61;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for PragmaStmt {
    const TAG: u32 = 62;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for AnalyzeOrReindexStmt {
    const TAG: u32 = 63;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for AttachStmt {
    const TAG: u32 = 64;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for DetachStmt {
    const TAG: u32 = 65;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for VacuumStmt {
    const TAG: u32 = 66;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for ExplainStmt {
    const TAG: u32 = 67;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for CreateIndexStmt {
    const TAG: u32 = 68;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for CreateViewStmt {
    const TAG: u32 = 69;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for ValuesClause {
    const TAG: u32 = 71;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for FrameBound {
    const TAG: u32 = 72;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for FrameSpec {
    const TAG: u32 = 73;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for WindowDef {
    const TAG: u32 = 74;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for NamedWindowDef {
    const TAG: u32 = 76;
}

// SAFETY: TAG matches the value the C parser writes into the `tag` field.
unsafe impl ArenaNode for FilterOver {
    const TAG: u32 = 78;
}
