use std::env;
use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let csrc = manifest_dir.join("csrc");

    // Hand-written C sources — compiled with strict warnings.
    cc::Build::new()
        .file(csrc.join("sqlite_tokenize.c"))
        .file(csrc.join("sqlite_keyword.c"))
        .file(csrc.join("arena.c"))
        .file(csrc.join("tokenizer.c"))
        .file(csrc.join("parser.c"))
        .include(&manifest_dir)
        .include(manifest_dir.join("include"))
        .compile("syntaqlite_parser");

    // Lemon-generated parser — compiled separately with relaxed warnings
    // because the autogenerated grammar actions mix void* and uint32_t
    // (ParseTOKENTYPE is void*, but node IDs are uint32_t).
    cc::Build::new()
        .file(csrc.join("sqlite_parse.c"))
        .include(&manifest_dir)
        .include(manifest_dir.join("include"))
        .flag("-Wno-int-conversion")
        .flag("-Wno-void-pointer-to-int-cast")
        .flag("-Wno-unused-variable")
        .flag("-Wno-unused-parameter")
        .flag("-Wno-comment")
        .compile("syntaqlite_lemon");

    println!("cargo:rerun-if-changed=csrc/sqlite_tokenize.c");
    println!("cargo:rerun-if-changed=csrc/sqlite_keyword.c");
    println!("cargo:rerun-if-changed=csrc/sqlite_compat.h");
    println!("cargo:rerun-if-changed=include/syntaqlite/tokens.h");
    println!("cargo:rerun-if-changed=csrc/sqlite_keyword.h");
    println!("cargo:rerun-if-changed=csrc/sqlite_keyword_tables.h");
    println!("cargo:rerun-if-changed=csrc/ast_builder.h");
    println!("cargo:rerun-if-changed=csrc/arena.c");
    println!("cargo:rerun-if-changed=csrc/arena.h");
    println!("cargo:rerun-if-changed=csrc/tokenizer.c");
    println!("cargo:rerun-if-changed=csrc/parser.c");
    println!("cargo:rerun-if-changed=csrc/parser.h");
    println!("cargo:rerun-if-changed=csrc/sqlite_parser.h");
    println!("cargo:rerun-if-changed=csrc/sqlite_parse.c");
    println!("cargo:rerun-if-changed=csrc/sqlite_parse_data.h");
    println!("cargo:rerun-if-changed=csrc/sqlite_tokenize.h");
    println!("cargo:rerun-if-changed=csrc/vec.h");
    println!("cargo:rerun-if-changed=include/syntaqlite/config.h");
    println!("cargo:rerun-if-changed=include/syntaqlite/parser.h");
    println!("cargo:rerun-if-changed=include/syntaqlite/tokenizer.h");
    println!("cargo:rerun-if-changed=include/syntaqlite/node.h");
}
