use std::env;
use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let csrc = manifest_dir.join("csrc");
    let runtime_dir = manifest_dir.join("../syntaqlite-runtime");
    let runtime_csrc = runtime_dir.join("csrc");

    // Engine sources (from runtime crate) — generic parser/tokenizer engine
    // plus the SQLite tokenizer and keyword code (not dialect-customizable).
    cc::Build::new()
        .file(runtime_csrc.join("arena.c"))
        .file(runtime_csrc.join("tokenizer.c"))
        .file(runtime_csrc.join("parser.c"))
        .file(runtime_csrc.join("sqlite_tokenize.c"))
        .file(runtime_csrc.join("sqlite_keyword.c"))
        .include(&runtime_dir)                  // for csrc/arena.h, csrc/parser.h, etc.
        .include(runtime_dir.join("include"))    // for syntaqlite/config.h, types.h, parser.h
        .include(&manifest_dir)                  // for dialect csrc/ headers
        .include(manifest_dir.join("include"))   // for dialect include/ headers
        .compile("syntaqlite_engine");

    // Dialect sources (dialect glue).
    cc::Build::new()
        .file(csrc.join("dialect.c"))
        .include(&runtime_dir)
        .include(runtime_dir.join("include"))
        .include(&manifest_dir)
        .include(manifest_dir.join("include"))
        .compile("syntaqlite_dialect");

    // Lemon-generated parser — compiled with inline data header and relaxed
    // warnings because the autogenerated grammar actions mix void* and uint32_t
    // (ParseTOKENTYPE is void*, but node IDs are uint32_t).
    cc::Build::new()
        .file(runtime_csrc.join("sqlite_parse.c"))
        .include(&runtime_dir)
        .include(runtime_dir.join("include"))
        .include(&manifest_dir)
        .include(manifest_dir.join("include"))
        .define("SYNTAQLITE_INLINE_PARSER_DATA_HEADER", Some(r#""csrc/dialect_parse.h""#))
        .flag("-Wno-int-conversion")
        .flag("-Wno-void-pointer-to-int-cast")
        .flag("-Wno-unused-variable")
        .flag("-Wno-unused-parameter")
        .flag("-Wno-comment")
        .compile("syntaqlite_lemon");

    // Engine (runtime) sources
    println!("cargo:rerun-if-changed=../syntaqlite-runtime/csrc/arena.c");
    println!("cargo:rerun-if-changed=../syntaqlite-runtime/csrc/arena.h");
    println!("cargo:rerun-if-changed=../syntaqlite-runtime/csrc/vec.h");
    println!("cargo:rerun-if-changed=../syntaqlite-runtime/csrc/parser.c");
    println!("cargo:rerun-if-changed=../syntaqlite-runtime/csrc/parser.h");
    println!("cargo:rerun-if-changed=../syntaqlite-runtime/csrc/tokenizer.c");
    // dialect.h was removed — parser vtable is now in syntaqlite/dialect.h
    println!("cargo:rerun-if-changed=../syntaqlite-runtime/csrc/sqlite_tokenize.c");
    println!("cargo:rerun-if-changed=../syntaqlite-runtime/csrc/sqlite_tokenize.h");
    println!("cargo:rerun-if-changed=../syntaqlite-runtime/csrc/sqlite_keyword.c");
    println!("cargo:rerun-if-changed=../syntaqlite-runtime/csrc/sqlite_keyword.h");
    println!("cargo:rerun-if-changed=../syntaqlite-runtime/csrc/sqlite_keyword_tables.h");
    println!("cargo:rerun-if-changed=../syntaqlite-runtime/csrc/sqlite_compat.h");
    println!("cargo:rerun-if-changed=../syntaqlite-runtime/csrc/sqlite_parse.c");
    println!("cargo:rerun-if-changed=../syntaqlite-runtime/csrc/sqlite_parser.h");
    println!("cargo:rerun-if-changed=../syntaqlite-runtime/include/syntaqlite/config.h");
    println!("cargo:rerun-if-changed=../syntaqlite-runtime/include/syntaqlite/parser.h");
    println!("cargo:rerun-if-changed=../syntaqlite-runtime/include/syntaqlite/tokenizer.h");
    println!("cargo:rerun-if-changed=../syntaqlite-runtime/include/syntaqlite/types.h");

    // Dialect sources
    println!("cargo:rerun-if-changed=csrc/dialect.c");
    println!("cargo:rerun-if-changed=csrc/dialect_meta.h");
    println!("cargo:rerun-if-changed=csrc/dialect_fmt.h");
    println!("cargo:rerun-if-changed=../syntaqlite-runtime/include/syntaqlite/dialect.h");
    println!("cargo:rerun-if-changed=csrc/dialect_grammar_types.h");
    println!("cargo:rerun-if-changed=csrc/dialect_builder.h");
    println!("cargo:rerun-if-changed=csrc/dialect_parse.h");
    println!("cargo:rerun-if-changed=include/syntaqlite/sqlite_tokens.h");
    println!("cargo:rerun-if-changed=include/syntaqlite/sqlite_node.h");
    println!("cargo:rerun-if-changed=include/syntaqlite/sqlite.h");
}
