// Copyright 2025 The syntaqlite Authors. All rights reserved.
// Licensed under the Apache License, Version 2.0.
//
// @generated by syntaqlite-buildtools — DO NOT EDIT

#ifndef SYNTAQLITE_SQLITE_DIALECT_BUILDER_H
#define SYNTAQLITE_SQLITE_DIALECT_BUILDER_H

#include "syntaqlite_dialect/ast_builder.h"
#include "syntaqlite_dialect/dialect_types.h"
#include "syntaqlite_sqlite/sqlite_node.h"

#ifdef __cplusplus
extern "C" {
#endif

// ============ Builder Functions ============

static inline uint32_t synq_parse_aggregate_function_call(
    SynqParseCtx *ctx,
    SyntaqliteSourceSpan func_name,
    SyntaqliteAggregateFunctionCallFlags flags,
    uint32_t args,
    uint32_t orderby,
    uint32_t filter_clause,
    uint32_t over_clause
) {
    SyntaqliteAggregateFunctionCall _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_AGGREGATE_FUNCTION_CALL;
    _node.func_name = func_name;
    _node.flags = flags;
    _node.args = args;
    _node.orderby = orderby;
    _node.filter_clause = filter_clause;
    _node.over_clause = over_clause;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteAggregateFunctionCall));
}

static inline uint32_t synq_parse_ordered_set_function_call(
    SynqParseCtx *ctx,
    SyntaqliteSourceSpan func_name,
    SyntaqliteAggregateFunctionCallFlags flags,
    uint32_t args,
    uint32_t orderby_expr,
    uint32_t filter_clause,
    uint32_t over_clause
) {
    SyntaqliteOrderedSetFunctionCall _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_ORDERED_SET_FUNCTION_CALL;
    _node.func_name = func_name;
    _node.flags = flags;
    _node.args = args;
    _node.orderby_expr = orderby_expr;
    _node.filter_clause = filter_clause;
    _node.over_clause = over_clause;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteOrderedSetFunctionCall));
}

static inline uint32_t synq_parse_cast_expr(
    SynqParseCtx *ctx,
    uint32_t expr,
    SyntaqliteSourceSpan type_name
) {
    SyntaqliteCastExpr _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_CAST_EXPR;
    _node.expr = expr;
    _node.type_name = type_name;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteCastExpr));
}

static inline uint32_t synq_parse_column_ref(
    SynqParseCtx *ctx,
    SyntaqliteSourceSpan column,
    SyntaqliteSourceSpan table,
    SyntaqliteSourceSpan schema
) {
    SyntaqliteColumnRef _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_COLUMN_REF;
    _node.column = column;
    _node.table = table;
    _node.schema = schema;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteColumnRef));
}

static inline uint32_t synq_parse_compound_select(
    SynqParseCtx *ctx,
    SyntaqliteCompoundOp op,
    uint32_t left,
    uint32_t right
) {
    SyntaqliteCompoundSelect _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_COMPOUND_SELECT;
    _node.op = op;
    _node.left = left;
    _node.right = right;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteCompoundSelect));
}

static inline uint32_t synq_parse_subquery_expr(
    SynqParseCtx *ctx,
    uint32_t select
) {
    SyntaqliteSubqueryExpr _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_SUBQUERY_EXPR;
    _node.select = select;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteSubqueryExpr));
}

static inline uint32_t synq_parse_exists_expr(
    SynqParseCtx *ctx,
    uint32_t select
) {
    SyntaqliteExistsExpr _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_EXISTS_EXPR;
    _node.select = select;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteExistsExpr));
}

static inline uint32_t synq_parse_in_expr(
    SynqParseCtx *ctx,
    SyntaqliteBool negated,
    uint32_t operand,
    uint32_t source
) {
    SyntaqliteInExpr _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_IN_EXPR;
    _node.negated = negated;
    _node.operand = operand;
    _node.source = source;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteInExpr));
}

static inline uint32_t synq_parse_is_expr(
    SynqParseCtx *ctx,
    SyntaqliteIsOp op,
    uint32_t left,
    uint32_t right
) {
    SyntaqliteIsExpr _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_IS_EXPR;
    _node.op = op;
    _node.left = left;
    _node.right = right;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteIsExpr));
}

static inline uint32_t synq_parse_between_expr(
    SynqParseCtx *ctx,
    SyntaqliteBool negated,
    uint32_t operand,
    uint32_t low,
    uint32_t high
) {
    SyntaqliteBetweenExpr _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_BETWEEN_EXPR;
    _node.negated = negated;
    _node.operand = operand;
    _node.low = low;
    _node.high = high;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteBetweenExpr));
}

static inline uint32_t synq_parse_like_expr(
    SynqParseCtx *ctx,
    SyntaqliteBool negated,
    uint32_t operand,
    uint32_t pattern,
    uint32_t escape
) {
    SyntaqliteLikeExpr _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_LIKE_EXPR;
    _node.negated = negated;
    _node.operand = operand;
    _node.pattern = pattern;
    _node.escape = escape;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteLikeExpr));
}

static inline uint32_t synq_parse_case_expr(
    SynqParseCtx *ctx,
    uint32_t operand,
    uint32_t else_expr,
    uint32_t whens
) {
    SyntaqliteCaseExpr _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_CASE_EXPR;
    _node.operand = operand;
    _node.else_expr = else_expr;
    _node.whens = whens;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteCaseExpr));
}

static inline uint32_t synq_parse_case_when(
    SynqParseCtx *ctx,
    uint32_t when_expr,
    uint32_t then_expr
) {
    SyntaqliteCaseWhen _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_CASE_WHEN;
    _node.when_expr = when_expr;
    _node.then_expr = then_expr;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteCaseWhen));
}

static inline uint32_t synq_parse_foreign_key_clause(
    SynqParseCtx *ctx,
    SyntaqliteSourceSpan ref_table,
    uint32_t ref_columns,
    SyntaqliteForeignKeyAction on_delete,
    SyntaqliteForeignKeyAction on_update,
    SyntaqliteBool is_deferred
) {
    SyntaqliteForeignKeyClause _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_FOREIGN_KEY_CLAUSE;
    _node.ref_table = ref_table;
    _node.ref_columns = ref_columns;
    _node.on_delete = on_delete;
    _node.on_update = on_update;
    _node.is_deferred = is_deferred;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteForeignKeyClause));
}

static inline uint32_t synq_parse_column_constraint(
    SynqParseCtx *ctx,
    SyntaqliteColumnConstraintType kind,
    SyntaqliteSourceSpan constraint_name,
    SyntaqliteConflictAction onconf,
    SyntaqliteSortOrder sort_order,
    SyntaqliteBool is_autoincrement,
    SyntaqliteSourceSpan collation_name,
    SyntaqliteGeneratedColumnStorage generated_storage,
    uint32_t default_expr,
    uint32_t check_expr,
    uint32_t generated_expr,
    uint32_t fk_clause
) {
    SyntaqliteColumnConstraint _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_COLUMN_CONSTRAINT;
    _node.kind = kind;
    _node.constraint_name = constraint_name;
    _node.onconf = onconf;
    _node.sort_order = sort_order;
    _node.is_autoincrement = is_autoincrement;
    _node.collation_name = collation_name;
    _node.generated_storage = generated_storage;
    _node.default_expr = default_expr;
    _node.check_expr = check_expr;
    _node.generated_expr = generated_expr;
    _node.fk_clause = fk_clause;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteColumnConstraint));
}

static inline uint32_t synq_parse_column_def(
    SynqParseCtx *ctx,
    uint32_t column_name,
    SyntaqliteSourceSpan type_name,
    uint32_t constraints
) {
    SyntaqliteColumnDef _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_COLUMN_DEF;
    _node.column_name = column_name;
    _node.type_name = type_name;
    _node.constraints = constraints;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteColumnDef));
}

static inline uint32_t synq_parse_table_constraint(
    SynqParseCtx *ctx,
    SyntaqliteTableConstraintType kind,
    SyntaqliteSourceSpan constraint_name,
    SyntaqliteConflictAction onconf,
    SyntaqliteBool is_autoincrement,
    uint32_t pk_columns,
    uint32_t fk_columns,
    uint32_t check_expr,
    uint32_t fk_clause
) {
    SyntaqliteTableConstraint _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_TABLE_CONSTRAINT;
    _node.kind = kind;
    _node.constraint_name = constraint_name;
    _node.onconf = onconf;
    _node.is_autoincrement = is_autoincrement;
    _node.pk_columns = pk_columns;
    _node.fk_columns = fk_columns;
    _node.check_expr = check_expr;
    _node.fk_clause = fk_clause;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteTableConstraint));
}

static inline uint32_t synq_parse_create_table_stmt(
    SynqParseCtx *ctx,
    SyntaqliteSourceSpan table_name,
    SyntaqliteSourceSpan schema,
    SyntaqliteBool is_temp,
    SyntaqliteBool if_not_exists,
    SyntaqliteCreateTableStmtFlags flags,
    uint32_t columns,
    uint32_t table_constraints,
    uint32_t as_select
) {
    SyntaqliteCreateTableStmt _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_CREATE_TABLE_STMT;
    _node.table_name = table_name;
    _node.schema = schema;
    _node.is_temp = is_temp;
    _node.if_not_exists = if_not_exists;
    _node.flags = flags;
    _node.columns = columns;
    _node.table_constraints = table_constraints;
    _node.as_select = as_select;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteCreateTableStmt));
}

static inline uint32_t synq_parse_cte_definition(
    SynqParseCtx *ctx,
    SyntaqliteSourceSpan cte_name,
    SyntaqliteMaterialized materialized,
    uint32_t columns,
    uint32_t select
) {
    SyntaqliteCteDefinition _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_CTE_DEFINITION;
    _node.cte_name = cte_name;
    _node.materialized = materialized;
    _node.columns = columns;
    _node.select = select;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteCteDefinition));
}

static inline uint32_t synq_parse_with_clause(
    SynqParseCtx *ctx,
    SyntaqliteBool recursive,
    uint32_t ctes,
    uint32_t select
) {
    SyntaqliteWithClause _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_WITH_CLAUSE;
    _node.recursive = recursive;
    _node.ctes = ctes;
    _node.select = select;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteWithClause));
}

static inline uint32_t synq_parse_delete_stmt(
    SynqParseCtx *ctx,
    uint32_t table,
    uint32_t where_clause,
    uint32_t orderby,
    uint32_t limit_clause
) {
    SyntaqliteDeleteStmt _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_DELETE_STMT;
    _node.table = table;
    _node.where_clause = where_clause;
    _node.orderby = orderby;
    _node.limit_clause = limit_clause;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteDeleteStmt));
}

static inline uint32_t synq_parse_set_clause(
    SynqParseCtx *ctx,
    SyntaqliteSourceSpan column,
    uint32_t columns,
    uint32_t value
) {
    SyntaqliteSetClause _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_SET_CLAUSE;
    _node.column = column;
    _node.columns = columns;
    _node.value = value;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteSetClause));
}

static inline uint32_t synq_parse_update_stmt(
    SynqParseCtx *ctx,
    SyntaqliteConflictAction conflict_action,
    uint32_t table,
    uint32_t setlist,
    uint32_t from_clause,
    uint32_t where_clause,
    uint32_t orderby,
    uint32_t limit_clause
) {
    SyntaqliteUpdateStmt _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_UPDATE_STMT;
    _node.conflict_action = conflict_action;
    _node.table = table;
    _node.setlist = setlist;
    _node.from_clause = from_clause;
    _node.where_clause = where_clause;
    _node.orderby = orderby;
    _node.limit_clause = limit_clause;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteUpdateStmt));
}

static inline uint32_t synq_parse_insert_stmt(
    SynqParseCtx *ctx,
    SyntaqliteConflictAction conflict_action,
    uint32_t table,
    uint32_t columns,
    uint32_t source
) {
    SyntaqliteInsertStmt _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_INSERT_STMT;
    _node.conflict_action = conflict_action;
    _node.table = table;
    _node.columns = columns;
    _node.source = source;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteInsertStmt));
}

static inline uint32_t synq_parse_binary_expr(
    SynqParseCtx *ctx,
    SyntaqliteBinaryOp op,
    uint32_t left,
    uint32_t right
) {
    SyntaqliteBinaryExpr _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_BINARY_EXPR;
    _node.op = op;
    _node.left = left;
    _node.right = right;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteBinaryExpr));
}

static inline uint32_t synq_parse_unary_expr(
    SynqParseCtx *ctx,
    SyntaqliteUnaryOp op,
    uint32_t operand
) {
    SyntaqliteUnaryExpr _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_UNARY_EXPR;
    _node.op = op;
    _node.operand = operand;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteUnaryExpr));
}

static inline uint32_t synq_parse_literal(
    SynqParseCtx *ctx,
    SyntaqliteLiteralType literal_type,
    SyntaqliteSourceSpan source
) {
    SyntaqliteLiteral _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_LITERAL;
    _node.literal_type = literal_type;
    _node.source = source;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteLiteral));
}

static inline uint32_t synq_parse_ident_name(
    SynqParseCtx *ctx,
    SyntaqliteSourceSpan source
) {
    SyntaqliteIdentName _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_IDENT_NAME;
    _node.source = source;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteIdentName));
}

static inline uint32_t synq_parse_error(
    SynqParseCtx *ctx,
    SyntaqliteSourceSpan source
) {
    SyntaqliteError _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_ERROR;
    _node.source = source;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteError));
}

static inline uint32_t synq_parse_function_call(
    SynqParseCtx *ctx,
    SyntaqliteSourceSpan func_name,
    SyntaqliteFunctionCallFlags flags,
    uint32_t args,
    uint32_t filter_clause,
    uint32_t over_clause
) {
    SyntaqliteFunctionCall _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_FUNCTION_CALL;
    _node.func_name = func_name;
    _node.flags = flags;
    _node.args = args;
    _node.filter_clause = filter_clause;
    _node.over_clause = over_clause;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteFunctionCall));
}

static inline uint32_t synq_parse_variable(
    SynqParseCtx *ctx,
    SyntaqliteSourceSpan source
) {
    SyntaqliteVariable _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_VARIABLE;
    _node.source = source;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteVariable));
}

static inline uint32_t synq_parse_collate_expr(
    SynqParseCtx *ctx,
    uint32_t expr,
    SyntaqliteSourceSpan collation
) {
    SyntaqliteCollateExpr _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_COLLATE_EXPR;
    _node.expr = expr;
    _node.collation = collation;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteCollateExpr));
}

static inline uint32_t synq_parse_raise_expr(
    SynqParseCtx *ctx,
    SyntaqliteRaiseType raise_type,
    uint32_t error_message
) {
    SyntaqliteRaiseExpr _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_RAISE_EXPR;
    _node.raise_type = raise_type;
    _node.error_message = error_message;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteRaiseExpr));
}

static inline uint32_t synq_parse_qualified_name(
    SynqParseCtx *ctx,
    uint32_t object_name,
    uint32_t schema
) {
    SyntaqliteQualifiedName _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_QUALIFIED_NAME;
    _node.object_name = object_name;
    _node.schema = schema;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteQualifiedName));
}

static inline uint32_t synq_parse_drop_stmt(
    SynqParseCtx *ctx,
    SyntaqliteDropObjectType object_type,
    SyntaqliteBool if_exists,
    uint32_t target
) {
    SyntaqliteDropStmt _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_DROP_STMT;
    _node.object_type = object_type;
    _node.if_exists = if_exists;
    _node.target = target;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteDropStmt));
}

static inline uint32_t synq_parse_alter_table_stmt(
    SynqParseCtx *ctx,
    SyntaqliteAlterOp op,
    uint32_t target,
    uint32_t new_name,
    uint32_t old_name
) {
    SyntaqliteAlterTableStmt _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_ALTER_TABLE_STMT;
    _node.op = op;
    _node.target = target;
    _node.new_name = new_name;
    _node.old_name = old_name;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteAlterTableStmt));
}

static inline uint32_t synq_parse_transaction_stmt(
    SynqParseCtx *ctx,
    SyntaqliteTransactionOp op,
    SyntaqliteTransactionType trans_type
) {
    SyntaqliteTransactionStmt _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_TRANSACTION_STMT;
    _node.op = op;
    _node.trans_type = trans_type;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteTransactionStmt));
}

static inline uint32_t synq_parse_savepoint_stmt(
    SynqParseCtx *ctx,
    SyntaqliteSavepointOp op,
    uint32_t savepoint_name
) {
    SyntaqliteSavepointStmt _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_SAVEPOINT_STMT;
    _node.op = op;
    _node.savepoint_name = savepoint_name;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteSavepointStmt));
}

static inline uint32_t synq_parse_result_column(
    SynqParseCtx *ctx,
    SyntaqliteResultColumnFlags flags,
    uint32_t alias,
    uint32_t expr
) {
    SyntaqliteResultColumn _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_RESULT_COLUMN;
    _node.flags = flags;
    _node.alias = alias;
    _node.expr = expr;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteResultColumn));
}

static inline uint32_t synq_parse_select_stmt(
    SynqParseCtx *ctx,
    SyntaqliteSelectStmtFlags flags,
    uint32_t columns,
    uint32_t from_clause,
    uint32_t where_clause,
    uint32_t groupby,
    uint32_t having,
    uint32_t orderby,
    uint32_t limit_clause,
    uint32_t window_clause
) {
    SyntaqliteSelectStmt _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_SELECT_STMT;
    _node.flags = flags;
    _node.columns = columns;
    _node.from_clause = from_clause;
    _node.where_clause = where_clause;
    _node.groupby = groupby;
    _node.having = having;
    _node.orderby = orderby;
    _node.limit_clause = limit_clause;
    _node.window_clause = window_clause;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteSelectStmt));
}

static inline uint32_t synq_parse_ordering_term(
    SynqParseCtx *ctx,
    uint32_t expr,
    SyntaqliteSortOrder sort_order,
    SyntaqliteNullsOrder nulls_order
) {
    SyntaqliteOrderingTerm _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_ORDERING_TERM;
    _node.expr = expr;
    _node.sort_order = sort_order;
    _node.nulls_order = nulls_order;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteOrderingTerm));
}

static inline uint32_t synq_parse_limit_clause(
    SynqParseCtx *ctx,
    uint32_t limit,
    uint32_t offset
) {
    SyntaqliteLimitClause _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_LIMIT_CLAUSE;
    _node.limit = limit;
    _node.offset = offset;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteLimitClause));
}

static inline uint32_t synq_parse_table_ref(
    SynqParseCtx *ctx,
    SyntaqliteSourceSpan table_name,
    SyntaqliteSourceSpan schema,
    uint32_t alias
) {
    SyntaqliteTableRef _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_TABLE_REF;
    _node.table_name = table_name;
    _node.schema = schema;
    _node.alias = alias;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteTableRef));
}

static inline uint32_t synq_parse_subquery_table_source(
    SynqParseCtx *ctx,
    uint32_t select,
    uint32_t alias
) {
    SyntaqliteSubqueryTableSource _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_SUBQUERY_TABLE_SOURCE;
    _node.select = select;
    _node.alias = alias;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteSubqueryTableSource));
}

static inline uint32_t synq_parse_join_clause(
    SynqParseCtx *ctx,
    SyntaqliteJoinType join_type,
    uint32_t left,
    uint32_t right,
    uint32_t on_expr,
    uint32_t using_columns
) {
    SyntaqliteJoinClause _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_JOIN_CLAUSE;
    _node.join_type = join_type;
    _node.left = left;
    _node.right = right;
    _node.on_expr = on_expr;
    _node.using_columns = using_columns;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteJoinClause));
}

static inline uint32_t synq_parse_join_prefix(
    SynqParseCtx *ctx,
    uint32_t source,
    SyntaqliteJoinType join_type
) {
    SyntaqliteJoinPrefix _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_JOIN_PREFIX;
    _node.source = source;
    _node.join_type = join_type;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteJoinPrefix));
}

static inline uint32_t synq_parse_trigger_event(
    SynqParseCtx *ctx,
    SyntaqliteTriggerEventType event_type,
    uint32_t columns
) {
    SyntaqliteTriggerEvent _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_TRIGGER_EVENT;
    _node.event_type = event_type;
    _node.columns = columns;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteTriggerEvent));
}

static inline uint32_t synq_parse_create_trigger_stmt(
    SynqParseCtx *ctx,
    SyntaqliteSourceSpan trigger_name,
    SyntaqliteSourceSpan schema,
    SyntaqliteBool is_temp,
    SyntaqliteBool if_not_exists,
    SyntaqliteTriggerTiming timing,
    uint32_t event,
    uint32_t table,
    uint32_t when_expr,
    uint32_t body
) {
    SyntaqliteCreateTriggerStmt _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_CREATE_TRIGGER_STMT;
    _node.trigger_name = trigger_name;
    _node.schema = schema;
    _node.is_temp = is_temp;
    _node.if_not_exists = if_not_exists;
    _node.timing = timing;
    _node.event = event;
    _node.table = table;
    _node.when_expr = when_expr;
    _node.body = body;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteCreateTriggerStmt));
}

static inline uint32_t synq_parse_create_virtual_table_stmt(
    SynqParseCtx *ctx,
    SyntaqliteSourceSpan table_name,
    SyntaqliteSourceSpan schema,
    SyntaqliteSourceSpan module_name,
    SyntaqliteBool if_not_exists,
    SyntaqliteSourceSpan module_args
) {
    SyntaqliteCreateVirtualTableStmt _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_CREATE_VIRTUAL_TABLE_STMT;
    _node.table_name = table_name;
    _node.schema = schema;
    _node.module_name = module_name;
    _node.if_not_exists = if_not_exists;
    _node.module_args = module_args;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteCreateVirtualTableStmt));
}

static inline uint32_t synq_parse_pragma_stmt(
    SynqParseCtx *ctx,
    SyntaqliteSourceSpan pragma_name,
    SyntaqliteSourceSpan schema,
    SyntaqliteSourceSpan value,
    SyntaqlitePragmaForm pragma_form
) {
    SyntaqlitePragmaStmt _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_PRAGMA_STMT;
    _node.pragma_name = pragma_name;
    _node.schema = schema;
    _node.value = value;
    _node.pragma_form = pragma_form;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqlitePragmaStmt));
}

static inline uint32_t synq_parse_analyze_or_reindex_stmt(
    SynqParseCtx *ctx,
    SyntaqliteSourceSpan target_name,
    SyntaqliteSourceSpan schema,
    SyntaqliteAnalyzeOrReindexOp kind
) {
    SyntaqliteAnalyzeOrReindexStmt _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_ANALYZE_OR_REINDEX_STMT;
    _node.target_name = target_name;
    _node.schema = schema;
    _node.kind = kind;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteAnalyzeOrReindexStmt));
}

static inline uint32_t synq_parse_attach_stmt(
    SynqParseCtx *ctx,
    uint32_t filename,
    uint32_t db_name,
    uint32_t key
) {
    SyntaqliteAttachStmt _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_ATTACH_STMT;
    _node.filename = filename;
    _node.db_name = db_name;
    _node.key = key;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteAttachStmt));
}

static inline uint32_t synq_parse_detach_stmt(
    SynqParseCtx *ctx,
    uint32_t db_name
) {
    SyntaqliteDetachStmt _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_DETACH_STMT;
    _node.db_name = db_name;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteDetachStmt));
}

static inline uint32_t synq_parse_vacuum_stmt(
    SynqParseCtx *ctx,
    SyntaqliteSourceSpan schema,
    uint32_t filename
) {
    SyntaqliteVacuumStmt _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_VACUUM_STMT;
    _node.schema = schema;
    _node.filename = filename;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteVacuumStmt));
}

static inline uint32_t synq_parse_explain_stmt(
    SynqParseCtx *ctx,
    SyntaqliteExplainMode explain_mode,
    uint32_t stmt
) {
    SyntaqliteExplainStmt _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_EXPLAIN_STMT;
    _node.explain_mode = explain_mode;
    _node.stmt = stmt;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteExplainStmt));
}

static inline uint32_t synq_parse_create_index_stmt(
    SynqParseCtx *ctx,
    SyntaqliteSourceSpan index_name,
    SyntaqliteSourceSpan schema,
    SyntaqliteSourceSpan table_name,
    SyntaqliteBool is_unique,
    SyntaqliteBool if_not_exists,
    uint32_t columns,
    uint32_t where_clause
) {
    SyntaqliteCreateIndexStmt _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_CREATE_INDEX_STMT;
    _node.index_name = index_name;
    _node.schema = schema;
    _node.table_name = table_name;
    _node.is_unique = is_unique;
    _node.if_not_exists = if_not_exists;
    _node.columns = columns;
    _node.where_clause = where_clause;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteCreateIndexStmt));
}

static inline uint32_t synq_parse_create_view_stmt(
    SynqParseCtx *ctx,
    SyntaqliteSourceSpan view_name,
    SyntaqliteSourceSpan schema,
    SyntaqliteBool is_temp,
    SyntaqliteBool if_not_exists,
    uint32_t column_names,
    uint32_t select
) {
    SyntaqliteCreateViewStmt _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_CREATE_VIEW_STMT;
    _node.view_name = view_name;
    _node.schema = schema;
    _node.is_temp = is_temp;
    _node.if_not_exists = if_not_exists;
    _node.column_names = column_names;
    _node.select = select;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteCreateViewStmt));
}

static inline uint32_t synq_parse_values_clause(
    SynqParseCtx *ctx,
    uint32_t rows
) {
    SyntaqliteValuesClause _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_VALUES_CLAUSE;
    _node.rows = rows;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteValuesClause));
}

static inline uint32_t synq_parse_frame_bound(
    SynqParseCtx *ctx,
    SyntaqliteFrameBoundType bound_type,
    uint32_t expr
) {
    SyntaqliteFrameBound _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_FRAME_BOUND;
    _node.bound_type = bound_type;
    _node.expr = expr;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteFrameBound));
}

static inline uint32_t synq_parse_frame_spec(
    SynqParseCtx *ctx,
    SyntaqliteFrameType frame_type,
    SyntaqliteFrameExclude exclude,
    uint32_t start_bound,
    uint32_t end_bound
) {
    SyntaqliteFrameSpec _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_FRAME_SPEC;
    _node.frame_type = frame_type;
    _node.exclude = exclude;
    _node.start_bound = start_bound;
    _node.end_bound = end_bound;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteFrameSpec));
}

static inline uint32_t synq_parse_window_def(
    SynqParseCtx *ctx,
    SyntaqliteSourceSpan base_window_name,
    uint32_t partition_by,
    uint32_t orderby,
    uint32_t frame
) {
    SyntaqliteWindowDef _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_WINDOW_DEF;
    _node.base_window_name = base_window_name;
    _node.partition_by = partition_by;
    _node.orderby = orderby;
    _node.frame = frame;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteWindowDef));
}

static inline uint32_t synq_parse_named_window_def(
    SynqParseCtx *ctx,
    SyntaqliteSourceSpan window_name,
    uint32_t window_def
) {
    SyntaqliteNamedWindowDef _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_NAMED_WINDOW_DEF;
    _node.window_name = window_name;
    _node.window_def = window_def;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteNamedWindowDef));
}

static inline uint32_t synq_parse_filter_over(
    SynqParseCtx *ctx,
    uint32_t filter_expr,
    uint32_t over_def,
    SyntaqliteSourceSpan over_name
) {
    SyntaqliteFilterOver _node;
    memset(&_node, 0, sizeof(_node));
    _node.tag = SYNTAQLITE_NODE_FILTER_OVER;
    _node.filter_expr = filter_expr;
    _node.over_def = over_def;
    _node.over_name = over_name;
    return synq_parse_build(ctx, &_node, (uint32_t)sizeof(SyntaqliteFilterOver));
}

static inline uint32_t synq_parse_case_when_list(
    SynqParseCtx *ctx,
    uint32_t list_id,
    uint32_t child
) {
    return synq_parse_list_append(ctx, SYNTAQLITE_NODE_CASE_WHEN_LIST, list_id, child);
}

static inline uint32_t synq_parse_column_constraint_list(
    SynqParseCtx *ctx,
    uint32_t list_id,
    uint32_t child
) {
    return synq_parse_list_append(ctx, SYNTAQLITE_NODE_COLUMN_CONSTRAINT_LIST, list_id, child);
}

static inline uint32_t synq_parse_column_def_list(
    SynqParseCtx *ctx,
    uint32_t list_id,
    uint32_t child
) {
    return synq_parse_list_append(ctx, SYNTAQLITE_NODE_COLUMN_DEF_LIST, list_id, child);
}

static inline uint32_t synq_parse_table_constraint_list(
    SynqParseCtx *ctx,
    uint32_t list_id,
    uint32_t child
) {
    return synq_parse_list_append(ctx, SYNTAQLITE_NODE_TABLE_CONSTRAINT_LIST, list_id, child);
}

static inline uint32_t synq_parse_cte_list(
    SynqParseCtx *ctx,
    uint32_t list_id,
    uint32_t child
) {
    return synq_parse_list_append(ctx, SYNTAQLITE_NODE_CTE_LIST, list_id, child);
}

static inline uint32_t synq_parse_set_clause_list(
    SynqParseCtx *ctx,
    uint32_t list_id,
    uint32_t child
) {
    return synq_parse_list_append(ctx, SYNTAQLITE_NODE_SET_CLAUSE_LIST, list_id, child);
}

static inline uint32_t synq_parse_expr_list(
    SynqParseCtx *ctx,
    uint32_t list_id,
    uint32_t child
) {
    return synq_parse_list_append(ctx, SYNTAQLITE_NODE_EXPR_LIST, list_id, child);
}

static inline uint32_t synq_parse_result_column_list(
    SynqParseCtx *ctx,
    uint32_t list_id,
    uint32_t child
) {
    return synq_parse_list_append(ctx, SYNTAQLITE_NODE_RESULT_COLUMN_LIST, list_id, child);
}

static inline uint32_t synq_parse_order_by_list(
    SynqParseCtx *ctx,
    uint32_t list_id,
    uint32_t child
) {
    return synq_parse_list_append(ctx, SYNTAQLITE_NODE_ORDER_BY_LIST, list_id, child);
}

static inline uint32_t synq_parse_trigger_cmd_list(
    SynqParseCtx *ctx,
    uint32_t list_id,
    uint32_t child
) {
    return synq_parse_list_append(ctx, SYNTAQLITE_NODE_TRIGGER_CMD_LIST, list_id, child);
}

static inline uint32_t synq_parse_values_row_list(
    SynqParseCtx *ctx,
    uint32_t list_id,
    uint32_t child
) {
    return synq_parse_list_append(ctx, SYNTAQLITE_NODE_VALUES_ROW_LIST, list_id, child);
}

static inline uint32_t synq_parse_window_def_list(
    SynqParseCtx *ctx,
    uint32_t list_id,
    uint32_t child
) {
    return synq_parse_list_append(ctx, SYNTAQLITE_NODE_WINDOW_DEF_LIST, list_id, child);
}

static inline uint32_t synq_parse_named_window_def_list(
    SynqParseCtx *ctx,
    uint32_t list_id,
    uint32_t child
) {
    return synq_parse_list_append(ctx, SYNTAQLITE_NODE_NAMED_WINDOW_DEF_LIST, list_id, child);
}

#ifdef __cplusplus
}
#endif

#endif  // SYNTAQLITE_SQLITE_DIALECT_BUILDER_H
