// Copyright 2025 The syntaqlite Authors. All rights reserved.
// Licensed under the Apache License, Version 2.0.
//
// @generated by syntaqlite-buildtools — DO NOT EDIT

#include "syntaqlite/parser.h"
#include "syntaqlite_sqlite/sqlite_tokens.h"
#include "csrc/sqlite/dialect_meta.h"
#include "csrc/sqlite/dialect_tokens.h"
#include "csrc/sqlite/sqlite_parse.h"
#include "csrc/sqlite/sqlite_tokenize.h"

extern const char synq_sqlite_zKWText[];
extern const unsigned short int synq_sqlite_aKWOffset[];
extern const unsigned char synq_sqlite_aKWLen[];
extern const unsigned char synq_sqlite_aKWCode[];
extern const unsigned int synq_sqlite_nKeyword;

// ============ sqlite grammar descriptor ============


static const SyntaqliteGrammarTemplate SQLITE_GRAMMAR = {
    .name = "sqlite",

    // AST metadata
    .node_count = sizeof(ast_meta_node_names) / sizeof(ast_meta_node_names[0]),
    .node_names = ast_meta_node_names,
    .field_meta = ast_meta_field_meta,
    .field_meta_counts = ast_meta_field_meta_counts,
    .list_tags = ast_meta_list_tags,

    // Parser lifecycle
    .parser_alloc = SynqSqliteParseAlloc,
    .parser_init = SynqSqliteParseInit,
    .parser_finalize = SynqSqliteParseFinalize,
    .parser_free = SynqSqliteParseFree,
    .parser_feed = SynqSqliteParse,
#ifndef NDEBUG
    .parser_trace = SynqSqliteParseTrace,
#endif
    .parser_expected_tokens = SynqSqliteParseExpectedTokens,
    .parser_completion_context = SynqSqliteParseCompletionContext,

    // Tokenizer
    .get_token = SynqSqliteGetToken,

    // Keyword table
    .keyword_text = synq_sqlite_zKWText,
    .keyword_offsets = synq_sqlite_aKWOffset,
    .keyword_lens = synq_sqlite_aKWLen,
    .keyword_codes = synq_sqlite_aKWCode,
    .keyword_count = &synq_sqlite_nKeyword,

    // Token metadata
    .token_categories = token_categories,
    .token_type_count = TOKEN_TYPE_COUNT,
};

// ============ Default grammar handle ============


static const SyntaqliteGrammar SQLITE_GRAMMAR_DEFAULT =
    SYNQ_GRAMMAR_DEFAULT(&SQLITE_GRAMMAR);

// ============ Public API ============


SyntaqliteGrammar syntaqlite_sqlite_grammar(void) {
  return SQLITE_GRAMMAR_DEFAULT;
}
