// Copyright 2025 The syntaqlite Authors. All rights reserved.
// Licensed under the Apache License, Version 2.0.

//! Stage 1: Generate the `base_files_tables.rs` include file.
//!
//! Scans the parser-actions and parser-nodes directories and produces a Rust
//! source file containing `include_str!` entries for each `.y` and `.synq` file.

use std::fs;
use std::path::Path;

/// Generate the Rust source for `base_files_tables.rs`.
///
/// `codegen_crate_dir` is the path to the `syntaqlite-buildtools` crate root
/// (i.e. `CARGO_MANIFEST_DIR` at compile time). All `include_str!` paths
/// are emitted relative to it.
pub fn generate_base_files_tables(
    actions_dir: &Path,
    nodes_dir: &Path,
    codegen_crate_dir: &Path,
) -> Result<String, String> {
    let y_files = collect_sorted_files(actions_dir, "y")?;
    let synq_files = collect_sorted_files(nodes_dir, "synq")?;

    let codegen_abs = codegen_crate_dir
        .canonicalize()
        .map_err(|e| format!("canonicalizing {}: {e}", codegen_crate_dir.display()))?;
    let actions_abs = actions_dir
        .canonicalize()
        .map_err(|e| format!("canonicalizing {}: {e}", actions_dir.display()))?;
    let nodes_abs = nodes_dir
        .canonicalize()
        .map_err(|e| format!("canonicalizing {}: {e}", nodes_dir.display()))?;

    let actions_rel = relative_path(&codegen_abs, &actions_abs)?;
    let nodes_rel = relative_path(&codegen_abs, &nodes_abs)?;

    let mut out = String::new();
    out.push_str("// @generated by sqlite-extract — DO NOT EDIT\n\n");

    // BASE_Y_FILES
    out.push_str("const BASE_Y_FILES: &[(&str, &str)] = &[\n");
    for name in &y_files {
        out.push_str(&format!(
            "    ({name:?}, include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{actions_rel}/{name}\"))),\n"
        ));
    }
    out.push_str("];\n\n");

    // BASE_SYNQ_FILES
    out.push_str("const BASE_SYNQ_FILES: &[(&str, &str)] = &[\n");
    for name in &synq_files {
        out.push_str(&format!(
            "    ({name:?}, include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{nodes_rel}/{name}\"))),\n"
        ));
    }
    out.push_str("];\n");

    Ok(out)
}

/// Collect file names with a given extension from a directory, sorted alphabetically.
fn collect_sorted_files(dir: &Path, ext: &str) -> Result<Vec<String>, String> {
    if !dir.is_dir() {
        return Err(format!("{} is not a directory", dir.display()));
    }

    let mut names: Vec<String> = fs::read_dir(dir)
        .map_err(|e| format!("reading {}: {e}", dir.display()))?
        .filter_map(|entry| {
            let path = entry.ok()?.path();
            if path.extension()?.to_str()? == ext {
                Some(path.file_name()?.to_str()?.to_string())
            } else {
                None
            }
        })
        .collect();
    names.sort();
    Ok(names)
}

/// Compute a relative path from `base` to `target`.
///
/// Both paths must be absolute (canonicalized). Returns a string like
/// `../syntaqlite/parser-actions`.
fn relative_path(base: &Path, target: &Path) -> Result<String, String> {
    // Find the common prefix.
    let base_components: Vec<_> = base.components().collect();
    let target_components: Vec<_> = target.components().collect();

    let common_len = base_components
        .iter()
        .zip(target_components.iter())
        .take_while(|(a, b)| a == b)
        .count();

    if common_len == 0 {
        return Err(format!(
            "no common prefix between {} and {}",
            base.display(),
            target.display()
        ));
    }

    // Go up from base to common ancestor, then down to target.
    let ups = base_components.len() - common_len;
    let mut parts: Vec<String> = (0..ups).map(|_| "..".to_string()).collect();
    for comp in &target_components[common_len..] {
        parts.push(comp.as_os_str().to_string_lossy().to_string());
    }

    Ok(parts.join("/"))
}

/// Write the generated base_files_tables.rs to the output path.
pub fn write_base_files_tables(
    actions_dir: &Path,
    nodes_dir: &Path,
    codegen_crate_dir: &Path,
    output_path: &Path,
) -> Result<(), String> {
    let content = generate_base_files_tables(actions_dir, nodes_dir, codegen_crate_dir)?;
    if let Some(parent) = output_path.parent() {
        fs::create_dir_all(parent).map_err(|e| format!("creating {}: {e}", parent.display()))?;
    }
    fs::write(output_path, &content).map_err(|e| format!("writing {}: {e}", output_path.display()))
}
