// Copyright 2025 The syntaqlite Authors. All rights reserved.
// Licensed under the Apache License, Version 2.0.

use std::fs;
use std::path::{Path, PathBuf};

use clap::Subcommand;

/// SQLite-specific codegen CLI subcommands.
///
/// Flattened into the top-level `Command` enum so the CLI interface is unchanged.
#[derive(Subcommand)]
pub(crate) enum CodegenCommand {
    /// Run the full codegen pipeline (grammar extraction, parser generation,
    /// tokenizer extraction, keyword hash, AST metadata, Rust bindings).
    Codegen {
        #[arg(long, required = true)]
        actions_dir: String,
        #[arg(long, required = true)]
        nodes_dir: String,
        /// Crate root for the dialect crate (e.g. `syntaqlite-parser-sqlite`).
        /// C sources land in `<dialect-crate>/csrc/sqlite/` and Rust dialect
        /// modules in `<dialect-crate>/src/`.
        #[arg(long, default_value = "syntaqlite-parser-sqlite")]
        dialect_crate: String,
        /// Crate root for the shared parser crate (e.g. `syntaqlite-parser`).
        /// Shared Rust modules (ast_traits.rs, functions_catalog.rs) and the
        /// shared C tokens header land here.
        #[arg(long, default_value = "syntaqlite-parser")]
        shared_crate: String,
        /// Path to write the internal SQLite wrappers.rs (e.g.
        /// `syntaqlite/src/sqlite/wrappers.rs`). When omitted, the file is
        /// not written (preserving the previous hand-edited copy).
        #[arg(long)]
        wrappers_out: Option<String>,
    },
    /// Produce C amalgamation files (single-file compilation units).
    Amalgamate {
        /// Dialect name (e.g. "sqlite").
        #[arg(long, required = true)]
        dialect: String,
        /// Path to the syntaqlite crate root (for engine C sources).
        #[arg(long, required = true)]
        runtime_dir: String,
        /// Path to the dialect crate root (e.g. syntaqlite/).
        #[arg(long, required = true)]
        dialect_dir: String,
        /// Output directory for generated files.
        #[arg(long, required = true)]
        output_dir: String,
        /// Emit only the runtime amalgamation.
        #[arg(long)]
        runtime_only: bool,
        /// Emit only the dialect amalgamation (references runtime header).
        #[arg(long)]
        dialect_only: bool,
    },
    // Hidden subcommands for codegen subprocess support.
    // generate_parser() and generate_keyword_hash() spawn current_exe() with
    // these subcommands. They must be present in any binary that calls codegen.
    #[command(hide = true)]
    Lemon {
        #[arg(trailing_var_arg = true, allow_hyphen_values = true)]
        args: Vec<String>,
    },
    #[command(hide = true)]
    Mkkeyword {
        #[arg(trailing_var_arg = true, allow_hyphen_values = true)]
        args: Vec<String>,
    },
}

/// Dispatch a SQLite codegen subcommand. Called from `run()` in lib.rs.
pub(crate) fn dispatch(command: CodegenCommand) -> Result<(), String> {
    match command {
        CodegenCommand::Codegen {
            actions_dir,
            nodes_dir,
            dialect_crate,
            shared_crate,
            wrappers_out,
        } => handle_codegen(
            &actions_dir,
            &nodes_dir,
            &dialect_crate,
            &shared_crate,
            wrappers_out.as_deref(),
        ),
        CodegenCommand::Amalgamate {
            dialect,
            runtime_dir,
            dialect_dir,
            output_dir,
            runtime_only,
            dialect_only,
        } => handle_amalgamate(
            &dialect,
            &runtime_dir,
            &dialect_dir,
            &output_dir,
            runtime_only,
            dialect_only,
        ),
        CodegenCommand::Lemon { args } => syntaqlite_buildtools::run_lemon(&args),
        CodegenCommand::Mkkeyword { args } => syntaqlite_buildtools::run_mkkeyword(&args),
    }
}

use crate::fs_util::{ensure_dir, write_file};

/// Delete any .c/.h files in `dir` whose first 512 bytes contain the autogenerated marker.
fn clean_generated_files(dir: &Path) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        let ext = path.extension().and_then(|e| e.to_str()).unwrap_or("");
        if ext != "c" && ext != "h" {
            continue;
        }
        let Ok(content) = fs::read_to_string(&path) else {
            continue;
        };
        let prefix = &content[..content.len().min(512)];
        if prefix.contains(syntaqlite_buildtools::codegen_api::AUTOGENERATED_MARKER) {
            let _ = fs::remove_file(&path);
        }
    }
}

fn handle_codegen(
    actions_dir: &str,
    nodes_dir: &str,
    dialect_crate_dir: &str,
    shared_crate_dir: &str,
    wrappers_out: Option<&str>,
) -> Result<(), String> {
    use syntaqlite_buildtools::codegen_api::{
        CodegenRequest, DialectNaming, generate_codegen_artifacts, read_named_files_from_dir,
    };
    use syntaqlite_buildtools::output_resolver::OutputLayout;

    let dialect = DialectNaming::new("sqlite");
    let y_files = read_named_files_from_dir(actions_dir, "y")?;
    let synq_files = read_named_files_from_dir(nodes_dir, "synq")?;

    let layout = OutputLayout::for_sqlite(
        Path::new("."),
        dialect_crate_dir,
        shared_crate_dir,
        dialect.name(),
        &dialect.include_dir_name(),
        wrappers_out,
    );

    let artifacts = {
        let no_keywords: Vec<String> = Vec::new();
        let request = CodegenRequest {
            dialect: &dialect,
            y_files: &y_files,
            synq_files: &synq_files,
            extra_keywords: &no_keywords,
            parser_symbol_prefix: None,
            include_rust: true,
            crate_name: Some("syntaqlite_parser"),
            base_synq_files: None,
            open_for_extension: true,
            dialect_c_includes: layout.c_includes(),
            internal_wrappers: true,
        };
        generate_codegen_artifacts(&request)?
    };

    // Clean stale generated C/H files from C output directories.
    let csrc_dir = Path::new(dialect_crate_dir).join("csrc/sqlite");
    let include_dir =
        Path::new(dialect_crate_dir).join(format!("include/{}", dialect.include_dir_name()));
    let shared_include_dir =
        Path::new(shared_crate_dir).join(format!("include/{}", dialect.include_dir_name()));
    for dir in [&csrc_dir, &include_dir, &shared_include_dir] {
        if dir.is_dir() {
            clean_generated_files(dir);
        }
    }

    layout.write_codegen_artifacts(
        &dialect,
        artifacts,
        &|dir| ensure_dir(dir, "output directory"),
        &|path, content| write_file(path, content),
    )?;

    Ok(())
}

fn write_amalgamation_outputs(
    out: &Path,
    header_name: &str,
    source_name: &str,
    result: &syntaqlite_buildtools::amalgamate::AmalgamateOutput,
) -> Result<(), String> {
    write_file(&out.join(header_name), &result.header)?;
    write_file(&out.join(source_name), &result.source)?;
    if let Some(ext) = &result.ext_header {
        write_file(&out.join("syntaqlite_dialect.h"), ext)?;
    }
    Ok(())
}

fn handle_amalgamate(
    dialect: &str,
    runtime_dir: &str,
    dialect_dir: &str,
    output_dir: &str,
    runtime_only: bool,
    dialect_only: bool,
) -> Result<(), String> {
    use syntaqlite_buildtools::amalgamate;

    let out = Path::new(output_dir);
    ensure_dir(out, "output directory")?;

    let runtime = PathBuf::from(runtime_dir);
    let dialect_path = PathBuf::from(dialect_dir);

    if runtime_only {
        let result = amalgamate::amalgamate_runtime(&runtime)?;
        write_amalgamation_outputs(out, "syntaqlite_runtime.h", "syntaqlite_runtime.c", &result)?;
    } else {
        let result = if dialect_only {
            amalgamate::amalgamate_dialect(dialect, &dialect_path, None, None)?
        } else {
            amalgamate::amalgamate_full(dialect, &runtime, &dialect_path)?
        };
        let base = format!("syntaqlite_{dialect}");
        write_amalgamation_outputs(out, &format!("{base}.h"), &format!("{base}.c"), &result)?;
    }

    Ok(())
}
