// Copyright 2025 The syntaqlite Authors. All rights reserved.
// Licensed under the Apache License, Version 2.0.

//! Minimal C code writer for syntaqlite codegen
//!
//! Focused on emitting the specific C patterns needed for AST node generation.
//! Uses a single String buffer to minimize allocations.

use super::text_writer::TextWriterCore;

pub const AUTOGENERATED_MARKER: &str = "@generated by syntaqlite-buildtools — DO NOT EDIT";

const SQLITE_BLESSING_HEADER: &str = "\
/*
** The author disclaims copyright to this source code.  In place of
** a legal notice, here is a blessing:
**
**    May you do good and not evil.
**    May you find forgiveness for yourself and forgive others.
**    May you share freely, never taking more than you give.
**
** @generated by syntaqlite-buildtools — DO NOT EDIT
*/

";

const SYNTAQLITE_HEADER: &str = "\
// Copyright 2025 The syntaqlite Authors. All rights reserved.
// Licensed under the Apache License, Version 2.0.
//
// @generated by syntaqlite-buildtools — DO NOT EDIT

";

/// Simple C code writer with single-buffer output and indentation tracking
pub struct CWriter {
    core: TextWriterCore,
}

impl CWriter {
    // ========== Public API ==========

    pub fn new() -> Self {
        Self {
            core: TextWriterCore::new(),
        }
    }

    pub fn finish(self) -> String {
        self.core.finish()
    }

    // Basic output

    pub fn newline(&mut self) -> &mut Self {
        self.core.newline();
        self
    }

    pub fn line(&mut self, text: &str) -> &mut Self {
        self.core.line(text);
        self
    }

    /// Write a fragment (anything that implements Display)
    pub fn fragment(&mut self, fragment: &impl std::fmt::Display) -> &mut Self {
        self.core.fragment(fragment);
        self
    }

    /// Start a block (increase indentation)
    pub fn indent(&mut self) -> &mut Self {
        self.core.indent();
        self
    }

    /// End a block (decrease indentation)
    pub fn dedent(&mut self) -> &mut Self {
        self.core.dedent();
        self
    }

    // Preprocessor directives

    pub fn include_system(&mut self, header: &str) -> &mut Self {
        self.core.raw_line(&format!("#include <{}>", header));
        self
    }

    pub fn include_local(&mut self, header: &str) -> &mut Self {
        self.core.raw_line(&format!("#include \"{}\"", header));
        self
    }

    /// Emit header guard start
    pub fn header_guard_start(&mut self, guard_name: &str) {
        self.core.push_raw(&format!(
            "#ifndef {}\n#define {}\n\n",
            guard_name, guard_name
        ));
    }

    /// Emit header guard end
    pub fn header_guard_end(&mut self, guard_name: &str) {
        self.core.raw_line(&format!("#endif  // {}", guard_name));
    }

    /// Emit file header with SQLite blessing and autogenerated warning.
    /// Emit the SQLite public-domain blessing header (for files derived from SQLite's grammar).
    pub fn sqlite_file_header(&mut self) {
        self.core.push_raw(SQLITE_BLESSING_HEADER);
    }

    /// Emit the syntaqlite Apache 2.0 copyright header (for files generated from .synq definitions).
    pub fn file_header(&mut self) {
        self.core.push_raw(SYNTAQLITE_HEADER);
    }

    /// Start extern "C" block
    pub fn extern_c_start(&mut self) {
        self.core
            .push_raw("#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n");
    }

    /// End extern "C" block
    pub fn extern_c_end(&mut self) {
        self.core.push_raw("#ifdef __cplusplus\n}\n#endif\n");
    }

    /// Emit a typedef enum
    pub fn typedef_enum(&mut self, name: &str, variants: &[(&str, Option<i32>)]) {
        self.line(&format!("typedef enum {} {{", name));
        self.indent();

        for (i, (variant, value)) in variants.iter().enumerate() {
            let mut line = (*variant).to_string();
            if let Some(val) = value {
                line.push_str(&format!(" = {}", val));
            }
            if i < variants.len() - 1 {
                line.push(',');
            }
            self.line(&line);
        }

        self.dedent();
        self.line(&format!("}} {};", name));
    }

    /// Emit a typedef struct with named fields: `typedef struct Name { type1 field1; ... } Name;`
    pub fn typedef_struct(&mut self, name: &str, fields: &[(&str, &str)]) {
        self.line(&format!("typedef struct {} {{", name));
        self.indent();
        for (ty, field_name) in fields {
            self.line(&format!("{} {};", ty, field_name));
        }
        self.dedent();
        self.line(&format!("}} {};", name));
    }

    /// Emit a typedef union: `typedef union Name { type1 field1; ... } Name;`
    pub fn typedef_union(&mut self, name: &str, members: &[(&str, &str)]) {
        self.line(&format!("typedef union {} {{", name));
        self.indent();
        for (ty, member_name) in members {
            self.line(&format!("{} {};", ty, member_name));
        }
        self.dedent();
        self.line(&format!("}} {};", name));
    }

    /// Emit a typedef union with uint8_t raw + named bitfield struct for flags.
    /// `bits` is (name, bit_position) pairs.
    ///
    /// Access: `flags.bits.star`, `flags.bits.distinct`, or `flags.raw` for
    /// the packed byte. Consistent across C and C++.
    pub fn typedef_flags_union(&mut self, name: &str, bits: &[(&str, u32)]) {
        self.line(&format!("typedef union {} {{", name));
        self.indent();
        self.line("uint8_t raw;");
        self.line("struct {");
        self.indent();
        let mut next_bit = 0u32;
        for (bit_name, value) in bits {
            let bit_pos = value.trailing_zeros();
            if bit_pos > next_bit {
                self.line(&format!("uint8_t : {};", bit_pos - next_bit));
            }
            self.line(&format!("uint8_t {} : 1;", bit_name));
            next_bit = bit_pos + 1;
        }
        self.dedent();
        self.line("} bits;");
        self.dedent();
        self.line(&format!("}} {};", name));
    }

    /// Emit a list node struct: `{ tag, count, children[] }`.
    ///
    /// Uses `SYNTAQLITE_FLEXIBLE_ARRAY` to be C++ compatible: C uses `[]`,
    /// C++ uses `[1]` (a common workaround since C++ lacks flexible arrays).
    pub fn typedef_list_struct(&mut self, name: &str) {
        self.line(&format!("typedef struct {} {{", name));
        self.indent();
        self.line("uint32_t tag;");
        self.line("uint32_t count;");
        self.line("uint32_t children[SYNTAQLITE_FLEXIBLE_ARRAY];");
        self.dedent();
        self.line(&format!("}} {};", name));
    }

    /// Emit a function signature, wrapping long parameter lists.
    /// `prefix` is e.g. "static inline ", `suffix` is ";" or " {".
    pub fn func_signature(
        &mut self,
        prefix: &str,
        return_type: &str,
        name: &str,
        params: &[&str],
        suffix: &str,
    ) -> &mut Self {
        let joined = params.join(", ");
        let full = format!("{}{} {}({}){}", prefix, return_type, name, joined, suffix);
        if full.len() <= 80 {
            self.line(&full);
        } else {
            self.line(&format!("{}{} {}(", prefix, return_type, name));
            self.indent();
            for (i, param) in params.iter().enumerate() {
                let comma = if i < params.len() - 1 { "," } else { "" };
                self.line(&format!("{}{}", param, comma));
            }
            self.dedent();
            self.line(&format!("){}", suffix));
        }
        self
    }

    /// Emit a comment line
    pub fn comment(&mut self, text: &str) -> &mut Self {
        self.line(&format!("// {}", text));
        self
    }

    /// Emit a section header comment
    pub fn section(&mut self, title: &str) -> &mut Self {
        self.line(&format!("// ============ {} ============", title));
        self.newline();
        self
    }
}

impl Default for CWriter {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_basic_enum() {
        let mut w = CWriter::new();
        w.typedef_enum(
            "Color",
            &[("RED", Some(0)), ("GREEN", Some(1)), ("BLUE", Some(2))],
        );

        let output = w.finish();
        assert!(output.contains("typedef enum Color {"));
        assert!(output.contains("RED = 0,"));
        assert!(output.contains("BLUE = 2"));
    }

    #[test]
    fn test_header_guard() {
        let mut w = CWriter::new();
        w.header_guard_start("MY_HEADER_H");
        w.line("// content");
        w.header_guard_end("MY_HEADER_H");

        let output = w.finish();
        assert!(output.contains("#ifndef MY_HEADER_H"));
        assert!(output.contains("#define MY_HEADER_H"));
        assert!(output.contains("#endif  // MY_HEADER_H"));
    }
}
