// Copyright 2025 The syntaqlite Authors. All rights reserved.
// Licensed under the Apache License, Version 2.0.

use std::env;
use std::fs;
use std::path::PathBuf;
use syntaqlite_codegen_utils::c_transformer::CTransformer;

fn main() {
    // Get the path to vendored SQLite tools in this crate
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let sqlite_dir = PathBuf::from(&manifest_dir).join("sqlite");
    let tokenize_c = PathBuf::from(&manifest_dir).join("../third_party/src/sqlite/src/tokenize.c");

    let lemon_path = sqlite_dir.join("lemon.c");
    let mkkeywordhash_path = sqlite_dir.join("mkkeywordhash.c");

    println!("cargo:rerun-if-changed={}", lemon_path.display());
    println!("cargo:rerun-if-changed={}", mkkeywordhash_path.display());
    println!("cargo:rerun-if-changed={}", tokenize_c.display());
    println!(
        "cargo:rustc-env=SYNTAQLITE_SQLITE_TOKENIZE_C={}",
        tokenize_c.display()
    );

    // Compile lemon.c with main renamed to lemon_main
    cc::Build::new()
        .file(&lemon_path)
        .define("main", "lemon_main")
        .compile("lemon");

    // Transform mkkeywordhash.c to accept custom keywords
    let out_dir = env::var("OUT_DIR").unwrap();
    let modified_mkkeywordhash = PathBuf::from(&out_dir).join("mkkeywordhash_modified.c");

    transform_mkkeywordhash(&mkkeywordhash_path, &modified_mkkeywordhash)
        .expect("Failed to transform mkkeywordhash.c");

    // Compile the modified mkkeywordhash.c
    cc::Build::new()
        .file(&modified_mkkeywordhash)
        .flag_if_supported("-Wno-missing-field-initializers")
        .flag_if_supported("-Wno-unused-parameter")
        .flag_if_supported("-Wno-unused-variable")
        .flag_if_supported("-Wno-sign-compare")
        .compile("mkkeywordhash");

    println!("cargo:rerun-if-changed=build.rs");

    // Track grammar files for test rebuilds
    register_grammar_files();
    generate_base_file_tables().expect("failed to generate embedded base file tables");
}

fn register_grammar_files() {
    use std::path::PathBuf;

    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let base_dir = PathBuf::from(&manifest_dir);

    // Track the base SQLite grammar
    let sqlite_parse_y = base_dir.join("../third_party/src/sqlite/src/parse.y");
    if sqlite_parse_y.exists() {
        println!("cargo:rerun-if-changed={}", sqlite_parse_y.display());
    }

    // Track all parser action files
    let parser_actions_dir = base_dir.join("../syntaqlite/parser-actions");
    if parser_actions_dir.exists() {
        println!("cargo:rerun-if-changed={}", parser_actions_dir.display());

        if let Ok(entries) = fs::read_dir(&parser_actions_dir) {
            for entry in entries.flatten() {
                let path = entry.path();
                if path.extension().and_then(|s| s.to_str()) == Some("y") {
                    println!("cargo:rerun-if-changed={}", path.display());
                }
            }
        }
    }

    // Track parser nodes directory too
    let parser_nodes_dir = base_dir.join("../syntaqlite/parser-nodes");
    if parser_nodes_dir.exists() {
        println!("cargo:rerun-if-changed={}", parser_nodes_dir.display());
    }
}

fn generate_base_file_tables() -> Result<(), String> {
    let manifest_dir = PathBuf::from(
        env::var("CARGO_MANIFEST_DIR").map_err(|e| format!("missing CARGO_MANIFEST_DIR: {e}"))?,
    );
    let out_dir = PathBuf::from(env::var("OUT_DIR").map_err(|e| format!("missing OUT_DIR: {e}"))?);

    let y_dir = manifest_dir.join("../syntaqlite/parser-actions");
    let synq_dir = manifest_dir.join("../syntaqlite/parser-nodes");

    let y_files = list_files_with_ext(&y_dir, "y")?;
    let synq_files = list_files_with_ext(&synq_dir, "synq")?;

    let mut out = String::new();
    out.push_str("// @generated by syntaqlite-codegen/build.rs — DO NOT EDIT\n\n");
    out.push_str("pub const BASE_Y_FILES: &[(&str, &str)] = &[\n");
    for file in &y_files {
        out.push_str(&format!(
            "    (\"{file}\", include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../syntaqlite/parser-actions/{file}\"))),\n"
        ));
    }
    out.push_str("];\n\n");

    out.push_str("pub const BASE_SYNQ_FILES: &[(&str, &str)] = &[\n");
    for file in &synq_files {
        out.push_str(&format!(
            "    (\"{file}\", include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../syntaqlite/parser-nodes/{file}\"))),\n"
        ));
    }
    out.push_str("];\n");

    let dest = out_dir.join("base_files_tables.rs");
    fs::write(&dest, out).map_err(|e| format!("failed to write {}: {e}", dest.display()))?;
    println!("cargo:rerun-if-changed={}", y_dir.display());
    println!("cargo:rerun-if-changed={}", synq_dir.display());
    Ok(())
}

fn list_files_with_ext(dir: &PathBuf, ext: &str) -> Result<Vec<String>, String> {
    if !dir.is_dir() {
        return Err(format!("missing directory {}", dir.display()));
    }
    let mut files = Vec::new();
    let entries = fs::read_dir(dir).map_err(|e| format!("reading {}: {e}", dir.display()))?;
    for entry in entries {
        let entry = entry.map_err(|e| format!("reading entry in {}: {e}", dir.display()))?;
        let path = entry.path();
        if path.extension().and_then(|s| s.to_str()) != Some(ext) {
            continue;
        }
        let Some(name) = path.file_name().and_then(|s| s.to_str()) else {
            continue;
        };
        files.push(name.to_string());
    }
    files.sort();
    Ok(files)
}

fn transform_mkkeywordhash(input: &PathBuf, output: &PathBuf) -> Result<(), String> {
    let content = fs::read_to_string(input)
        .map_err(|e| format!("Failed to read {}: {}", input.display(), e))?;

    let transformed = CTransformer::new(&content)
        .remove_static("aKeywordTable")
        .add_const("Keyword aKeywordTable")
        .remove_static("nKeyword")
        .add_const("int nKeyword")
        .add_function_parameters("findById", "Keyword *aKeywordTable, int nKeyword")
        .add_function_parameters("reorder", "Keyword *aKeywordTable, int nKeyword")
        .add_function_parameters("main", "Keyword *aKeywordTable, int nKeyword")
        // Fix call sites: append keyword args after existing args
        .replace_in_function(
            "main",
            "findById(p->id)",
            "findById(p->id, aKeywordTable, nKeyword)",
        )
        .replace_in_function(
            "main",
            "findById(p->substrId)",
            "findById(p->substrId, aKeywordTable, nKeyword)",
        )
        .replace_in_function(
            "main",
            "reorder(&aKWHash[h])",
            "reorder(&aKWHash[h], aKeywordTable, nKeyword)",
        )
        // Fix recursive call in reorder function itself
        .replace_in_function(
            "reorder",
            "reorder(&aKeywordTable[i].iNext)",
            "reorder(&aKeywordTable[i].iNext, aKeywordTable, nKeyword)",
        )
        .rename_function("main", "mkkeyword_main")
        // Expose struct layout so Rust tests can verify the Keyword struct matches.
        .add_system_include("stddef.h")
        .append(concat!(
            "const size_t keyword_sizeof = sizeof(struct Keyword);\n",
            "const size_t keyword_offsetof_zName = offsetof(struct Keyword, zName);\n",
            "const size_t keyword_offsetof_zTokenType = offsetof(struct Keyword, zTokenType);\n",
            "const size_t keyword_offsetof_mask = offsetof(struct Keyword, mask);\n",
            "const size_t keyword_offsetof_priority = offsetof(struct Keyword, priority);\n",
            "const size_t keyword_offsetof_id = offsetof(struct Keyword, id);\n",
            "const size_t keyword_offsetof_hash = offsetof(struct Keyword, hash);\n",
            "const size_t keyword_offsetof_offset = offsetof(struct Keyword, offset);\n",
            "const size_t keyword_offsetof_len = offsetof(struct Keyword, len);\n",
            "const size_t keyword_offsetof_prefix = offsetof(struct Keyword, prefix);\n",
            "const size_t keyword_offsetof_longestSuffix = offsetof(struct Keyword, longestSuffix);\n",
            "const size_t keyword_offsetof_iNext = offsetof(struct Keyword, iNext);\n",
            "const size_t keyword_offsetof_substrId = offsetof(struct Keyword, substrId);\n",
            "const size_t keyword_offsetof_substrOffset = offsetof(struct Keyword, substrOffset);\n",
            "const size_t keyword_offsetof_zOrigName = offsetof(struct Keyword, zOrigName);\n",
        ))
        .finish();

    fs::write(output, transformed)
        .map_err(|e| format!("Failed to write {}: {}", output.display(), e))?;

    Ok(())
}
