// Copyright 2025 The syntaqlite Authors. All rights reserved.
// Licensed under the Apache License, Version 2.0.

//! Python codegen: generates `_enums.py` (IntEnum/IntFlag types) and
//! `_py_ast_wrap.h` (C function for building Python dicts from AST nodes).

use std::fmt::Write as _;

use crate::util::text_writer::TextWriterCore;
use crate::util::upper_snake;

use super::AstModel;

// ── Public API ───────────────────────────────────────────────────────────

pub(crate) struct PythonCodegenArtifacts {
    /// IntEnum/IntFlag types (`_enums.py`).
    pub enums: String,
    /// C header with `syntaqlite_py_wrap_node()` (`_py_ast_wrap.h`).
    pub ast_wrap_h: String,
}

/// Generate Python binding artifacts from an `AstModel`.
pub(crate) fn generate_python_artifacts(model: &AstModel<'_>) -> PythonCodegenArtifacts {
    PythonCodegenArtifacts {
        enums: model.generate_python_enums(),
        ast_wrap_h: model.generate_python_c_wrap(),
    }
}

// ── Python writer ────────────────────────────────────────────────────────

struct PyWriter {
    core: TextWriterCore,
}

impl PyWriter {
    fn new() -> Self {
        Self {
            core: TextWriterCore::new(),
        }
    }

    fn finish(self) -> String {
        self.core.finish()
    }

    fn line(&mut self, text: &str) -> &mut Self {
        self.core.line(text);
        self
    }

    fn newline(&mut self) -> &mut Self {
        self.core.newline();
        self
    }

    fn indent(&mut self) -> &mut Self {
        self.core.indent();
        self
    }

    fn dedent(&mut self) -> &mut Self {
        self.core.dedent();
        self
    }

    fn file_header(&mut self) -> &mut Self {
        self.line("# Copyright 2025 The syntaqlite Authors. All rights reserved.");
        self.line("# Licensed under the Apache License, Version 2.0.");
        self.line("#");
        self.line("# @generated by syntaqlite-buildtools — DO NOT EDIT");
        self.newline()
    }
}

impl std::fmt::Write for PyWriter {
    fn write_str(&mut self, s: &str) -> std::fmt::Result {
        self.core.write_fmt_str(s);
        Ok(())
    }
}

// ── Enums codegen ────────────────────────────────────────────────────────

impl AstModel<'_> {
    /// Generate `_enums.py` with IntEnum/IntFlag types.
    pub(crate) fn generate_python_enums(&self) -> String {
        let mut w = PyWriter::new();
        w.file_header();

        w.line("from enum import IntEnum, IntFlag");
        w.newline();
        w.newline();

        // NodeTag enum.
        w.line("class NodeTag(IntEnum):");
        w.indent();
        w.line("\"\"\"AST node type tag.\"\"\"");
        w.newline();
        w.line("NULL = 0");
        for item in self.node_like_items() {
            let name = item.name();
            let tag = self.tag_for(name);
            let _ = writeln!(w, "{} = {}", upper_snake(name), tag);
        }
        w.dedent();
        w.newline();
        w.newline();

        // Value enums.
        for entry in self.enums() {
            let _ = writeln!(w, "class {}(IntEnum):", entry.name);
            w.indent();
            for (i, v) in entry.variants.iter().enumerate() {
                let _ = writeln!(w, "{v} = {i}");
            }
            w.dedent();
            w.newline();
            w.newline();
        }

        // Flags.
        for entry in self.flags() {
            let _ = writeln!(w, "class {}(IntFlag):", entry.name);
            w.indent();
            let mut sorted: Vec<_> = entry.flags.iter().collect();
            sorted.sort_by_key(|(_, v)| *v);
            for (name, bit) in &sorted {
                let _ = writeln!(w, "{name} = {bit}");
            }
            w.dedent();
            w.newline();
            w.newline();
        }

        w.finish()
    }
}

#[cfg(test)]
mod tests {
    use crate::dialect_codegen::AstModel;
    use crate::util::synq_parser::parse_synq_file;

    #[test]
    fn enums_py() {
        let items = parse_synq_file(
            r"
            enum SortOrder { ASC DESC }
            flags SelectStmtFlags { DISTINCT = 1 }
            node Foo { x: inline Bool }
            ",
        )
        .unwrap();
        let model = AstModel::new(&items);
        let enums = model.generate_python_enums();
        assert!(enums.contains("class NodeTag(IntEnum):"), "{enums}");
        assert!(enums.contains("FOO = 1"), "{enums}");
        assert!(enums.contains("class SortOrder(IntEnum):"), "{enums}");
        assert!(
            enums.contains("class SelectStmtFlags(IntFlag):"),
            "flags\n{enums}"
        );
    }

    #[test]
    fn full_enums_from_real_synq() {
        let base_synq = crate::base_files::base_synq_files();
        let mut all_items = Vec::new();
        for (name, content) in base_synq {
            let items =
                parse_synq_file(content).unwrap_or_else(|e| panic!("parse {name} failed: {e}"));
            all_items.extend(items);
        }
        let model = AstModel::new(&all_items);
        let enums = model.generate_python_enums();
        assert!(
            enums.contains("SELECT_STMT = 50"),
            "enums missing SELECT_STMT"
        );
    }
}
