// Copyright 2025 The syntaqlite Authors. All rights reserved.
// Licensed under the Apache License, Version 2.0.
//
// @generated by syntaqlite-buildtools — DO NOT EDIT

#ifndef SYNTAQLITE_SQLITE_GRAMMAR_H
#define SYNTAQLITE_SQLITE_GRAMMAR_H


#include "syntaqlite/abstract_grammar.h"

#ifdef __cplusplus
extern "C" {
#endif

SyntaqliteGrammar syntaqlite_sqlite_grammar(void);

#ifdef __cplusplus
}
#endif

#endif  // SYNTAQLITE_SQLITE_GRAMMAR_H
