#ifndef SYNTAQLITE_SQLITE_TOKENS_H
#define SYNTAQLITE_SQLITE_TOKENS_H

#include "syntaqlite/types.h"
#define SYNTAQLITE_TK_ABORT                            1
#define SYNTAQLITE_TK_ACTION                           2
#define SYNTAQLITE_TK_AFTER                            3
#define SYNTAQLITE_TK_ANALYZE                          4
#define SYNTAQLITE_TK_ASC                              5
#define SYNTAQLITE_TK_ATTACH                           6
#define SYNTAQLITE_TK_BEFORE                           7
#define SYNTAQLITE_TK_BEGIN                            8
#define SYNTAQLITE_TK_BY                               9
#define SYNTAQLITE_TK_CASCADE                         10
#define SYNTAQLITE_TK_CAST                            11
#define SYNTAQLITE_TK_CONFLICT                        12
#define SYNTAQLITE_TK_DATABASE                        13
#define SYNTAQLITE_TK_DEFERRED                        14
#define SYNTAQLITE_TK_DESC                            15
#define SYNTAQLITE_TK_DETACH                          16
#define SYNTAQLITE_TK_EACH                            17
#define SYNTAQLITE_TK_END                             18
#define SYNTAQLITE_TK_EXCLUSIVE                       19
#define SYNTAQLITE_TK_EXPLAIN                         20
#define SYNTAQLITE_TK_FAIL                            21
#define SYNTAQLITE_TK_OR                              22
#define SYNTAQLITE_TK_AND                             23
#define SYNTAQLITE_TK_NOT                             24
#define SYNTAQLITE_TK_IS                              25
#define SYNTAQLITE_TK_ISNOT                           26
#define SYNTAQLITE_TK_MATCH                           27
#define SYNTAQLITE_TK_LIKE_KW                         28
#define SYNTAQLITE_TK_BETWEEN                         29
#define SYNTAQLITE_TK_IN                              30
#define SYNTAQLITE_TK_ISNULL                          31
#define SYNTAQLITE_TK_NOTNULL                         32
#define SYNTAQLITE_TK_NE                              33
#define SYNTAQLITE_TK_EQ                              34
#define SYNTAQLITE_TK_GT                              35
#define SYNTAQLITE_TK_LE                              36
#define SYNTAQLITE_TK_LT                              37
#define SYNTAQLITE_TK_GE                              38
#define SYNTAQLITE_TK_ESCAPE                          39
#define SYNTAQLITE_TK_ID                              40
#define SYNTAQLITE_TK_COLUMNKW                        41
#define SYNTAQLITE_TK_DO                              42
#define SYNTAQLITE_TK_FOR                             43
#define SYNTAQLITE_TK_IGNORE                          44
#define SYNTAQLITE_TK_IMMEDIATE                       45
#define SYNTAQLITE_TK_INITIALLY                       46
#define SYNTAQLITE_TK_INSTEAD                         47
#define SYNTAQLITE_TK_NO                              48
#define SYNTAQLITE_TK_PLAN                            49
#define SYNTAQLITE_TK_QUERY                           50
#define SYNTAQLITE_TK_KEY                             51
#define SYNTAQLITE_TK_OF                              52
#define SYNTAQLITE_TK_OFFSET                          53
#define SYNTAQLITE_TK_PRAGMA                          54
#define SYNTAQLITE_TK_RAISE                           55
#define SYNTAQLITE_TK_RECURSIVE                       56
#define SYNTAQLITE_TK_RELEASE                         57
#define SYNTAQLITE_TK_REPLACE                         58
#define SYNTAQLITE_TK_RESTRICT                        59
#define SYNTAQLITE_TK_ROW                             60
#define SYNTAQLITE_TK_ROWS                            61
#define SYNTAQLITE_TK_ROLLBACK                        62
#define SYNTAQLITE_TK_SAVEPOINT                       63
#define SYNTAQLITE_TK_TEMP                            64
#define SYNTAQLITE_TK_TRIGGER                         65
#define SYNTAQLITE_TK_VACUUM                          66
#define SYNTAQLITE_TK_VIEW                            67
#define SYNTAQLITE_TK_VIRTUAL                         68
#define SYNTAQLITE_TK_WITH                            69
#define SYNTAQLITE_TK_WITHOUT                         70
#define SYNTAQLITE_TK_NULLS                           71
#define SYNTAQLITE_TK_FIRST                           72
#define SYNTAQLITE_TK_LAST                            73
#define SYNTAQLITE_TK_CURRENT                         74
#define SYNTAQLITE_TK_FOLLOWING                       75
#define SYNTAQLITE_TK_PARTITION                       76
#define SYNTAQLITE_TK_PRECEDING                       77
#define SYNTAQLITE_TK_RANGE                           78
#define SYNTAQLITE_TK_UNBOUNDED                       79
#define SYNTAQLITE_TK_EXCLUDE                         80
#define SYNTAQLITE_TK_GROUPS                          81
#define SYNTAQLITE_TK_OTHERS                          82
#define SYNTAQLITE_TK_TIES                            83
#define SYNTAQLITE_TK_GENERATED                       84
#define SYNTAQLITE_TK_ALWAYS                          85
#define SYNTAQLITE_TK_WITHIN                          86
#define SYNTAQLITE_TK_MATERIALIZED                    87
#define SYNTAQLITE_TK_REINDEX                         88
#define SYNTAQLITE_TK_RENAME                          89
#define SYNTAQLITE_TK_CTIME_KW                        90
#define SYNTAQLITE_TK_IF                              91
#define SYNTAQLITE_TK_ANY                             92
#define SYNTAQLITE_TK_BITAND                          93
#define SYNTAQLITE_TK_BITOR                           94
#define SYNTAQLITE_TK_LSHIFT                          95
#define SYNTAQLITE_TK_RSHIFT                          96
#define SYNTAQLITE_TK_PLUS                            97
#define SYNTAQLITE_TK_MINUS                           98
#define SYNTAQLITE_TK_STAR                            99
#define SYNTAQLITE_TK_SLASH                          100
#define SYNTAQLITE_TK_REM                            101
#define SYNTAQLITE_TK_CONCAT                         102
#define SYNTAQLITE_TK_PTR                            103
#define SYNTAQLITE_TK_COLLATE                        104
#define SYNTAQLITE_TK_BITNOT                         105
#define SYNTAQLITE_TK_ON                             106
#define SYNTAQLITE_TK_INDEXED                        107
#define SYNTAQLITE_TK_STRING                         108
#define SYNTAQLITE_TK_JOIN_KW                        109
#define SYNTAQLITE_TK_INTEGER                        110
#define SYNTAQLITE_TK_FLOAT                          111
#define SYNTAQLITE_TK_SEMI                           112
#define SYNTAQLITE_TK_LP                             113
#define SYNTAQLITE_TK_ORDER                          114
#define SYNTAQLITE_TK_RP                             115
#define SYNTAQLITE_TK_GROUP                          116
#define SYNTAQLITE_TK_AS                             117
#define SYNTAQLITE_TK_COMMA                          118
#define SYNTAQLITE_TK_DOT                            119
#define SYNTAQLITE_TK_UNION                          120
#define SYNTAQLITE_TK_ALL                            121
#define SYNTAQLITE_TK_EXCEPT                         122
#define SYNTAQLITE_TK_INTERSECT                      123
#define SYNTAQLITE_TK_EXISTS                         124
#define SYNTAQLITE_TK_NULL                           125
#define SYNTAQLITE_TK_DISTINCT                       126
#define SYNTAQLITE_TK_FROM                           127
#define SYNTAQLITE_TK_CASE                           128
#define SYNTAQLITE_TK_WHEN                           129
#define SYNTAQLITE_TK_THEN                           130
#define SYNTAQLITE_TK_ELSE                           131
#define SYNTAQLITE_TK_TABLE                          132
#define SYNTAQLITE_TK_CONSTRAINT                     133
#define SYNTAQLITE_TK_DEFAULT                        134
#define SYNTAQLITE_TK_PRIMARY                        135
#define SYNTAQLITE_TK_UNIQUE                         136
#define SYNTAQLITE_TK_CHECK                          137
#define SYNTAQLITE_TK_REFERENCES                     138
#define SYNTAQLITE_TK_AUTOINCR                       139
#define SYNTAQLITE_TK_INSERT                         140
#define SYNTAQLITE_TK_DELETE                         141
#define SYNTAQLITE_TK_UPDATE                         142
#define SYNTAQLITE_TK_SET                            143
#define SYNTAQLITE_TK_DEFERRABLE                     144
#define SYNTAQLITE_TK_FOREIGN                        145
#define SYNTAQLITE_TK_INTO                           146
#define SYNTAQLITE_TK_VALUES                         147
#define SYNTAQLITE_TK_WHERE                          148
#define SYNTAQLITE_TK_RETURNING                      149
#define SYNTAQLITE_TK_NOTHING                        150
#define SYNTAQLITE_TK_BLOB                           151
#define SYNTAQLITE_TK_QNUMBER                        152
#define SYNTAQLITE_TK_VARIABLE                       153
#define SYNTAQLITE_TK_DROP                           154
#define SYNTAQLITE_TK_INDEX                          155
#define SYNTAQLITE_TK_ALTER                          156
#define SYNTAQLITE_TK_TO                             157
#define SYNTAQLITE_TK_ADD                            158
#define SYNTAQLITE_TK_COMMIT                         159
#define SYNTAQLITE_TK_TRANSACTION                    160
#define SYNTAQLITE_TK_SELECT                         161
#define SYNTAQLITE_TK_HAVING                         162
#define SYNTAQLITE_TK_LIMIT                          163
#define SYNTAQLITE_TK_JOIN                           164
#define SYNTAQLITE_TK_USING                          165
#define SYNTAQLITE_TK_CREATE                         166
#define SYNTAQLITE_TK_WINDOW                         167
#define SYNTAQLITE_TK_OVER                           168
#define SYNTAQLITE_TK_FILTER                         169
#define SYNTAQLITE_TK_COLUMN                         170
#define SYNTAQLITE_TK_AGG_FUNCTION                   171
#define SYNTAQLITE_TK_AGG_COLUMN                     172
#define SYNTAQLITE_TK_TRUEFALSE                      173
#define SYNTAQLITE_TK_FUNCTION                       174
#define SYNTAQLITE_TK_UPLUS                          175
#define SYNTAQLITE_TK_UMINUS                         176
#define SYNTAQLITE_TK_TRUTH                          177
#define SYNTAQLITE_TK_REGISTER                       178
#define SYNTAQLITE_TK_VECTOR                         179
#define SYNTAQLITE_TK_SELECT_COLUMN                  180
#define SYNTAQLITE_TK_IF_NULL_ROW                    181
#define SYNTAQLITE_TK_ASTERISK                       182
#define SYNTAQLITE_TK_SPAN                           183
#define SYNTAQLITE_TK_ERROR                          184
#define SYNTAQLITE_TK_SPACE                          185
#define SYNTAQLITE_TK_COMMENT                        186
#define SYNTAQLITE_TK_ILLEGAL                        187

/* syntaqlite extension: expected terminals for current parser state. */
uint32_t SynqSqliteParseExpectedTokens(void* parser, uint32_t* out_tokens, uint32_t out_cap);

/* syntaqlite extension: completion context from parser stack. */
SyntaqliteCompletionContext SynqSqliteParseCompletionContext(void* parser);
#endif /* SYNTAQLITE_SQLITE_TOKENS_H */
