-- Schema covering all tables/indexes referenced by test_statements.sql.
CREATE TABLE users(id INTEGER PRIMARY KEY, email TEXT, name TEXT, active INT, deleted_at TEXT, nickname TEXT, username TEXT, status TEXT, last_login TEXT);
CREATE TABLE orders(id INTEGER PRIMARY KEY, customer_id INT, status TEXT, total REAL, updated_at TEXT, created_at TEXT);
CREATE TABLE customers(id INTEGER PRIMARY KEY, active INT);
CREATE TABLE order_items(id INTEGER PRIMARY KEY, order_id INT, product_id INT, qty INT, price REAL);
CREATE TABLE employees(id INTEGER PRIMARY KEY, salary REAL, department TEXT, dept_id INT, active INT);
CREATE TABLE departments(id INTEGER PRIMARY KEY, name TEXT);
CREATE TABLE inventory(sku TEXT, warehouse TEXT, qty INT, price REAL, PRIMARY KEY(sku, warehouse));
CREATE UNIQUE INDEX idx_inventory_sku ON inventory(sku);
CREATE TABLE sensors(id TEXT PRIMARY KEY);
CREATE TABLE audit_log(id INTEGER PRIMARY KEY, tbl TEXT, row_id INT, old_val TEXT);
CREATE TABLE kv(key TEXT PRIMARY KEY, value TEXT);
CREATE TABLE data(id INTEGER PRIMARY KEY, value REAL);
CREATE TABLE files(id INTEGER PRIMARY KEY, path TEXT, name TEXT);
CREATE TABLE counters(name TEXT PRIMARY KEY, count INT);
CREATE TABLE products(id INTEGER PRIMARY KEY, name TEXT, price REAL, category_id INT, category TEXT, status TEXT, nickname TEXT, username TEXT);
CREATE TABLE categories(id INTEGER PRIMARY KEY, name TEXT);
CREATE TABLE sessions(id INTEGER PRIMARY KEY, user_id INT, last_active TEXT, expires_at TEXT);
CREATE TABLE archived_users(id INTEGER PRIMARY KEY, name TEXT, email TEXT);
CREATE TABLE settings(key TEXT PRIMARY KEY, value TEXT);
CREATE TABLE metrics(name TEXT, ts TEXT, value REAL, updated_count INT DEFAULT 0, PRIMARY KEY(name, ts));
CREATE TABLE transactions(id INTEGER PRIMARY KEY, category TEXT, amount REAL);
CREATE TABLE measurements(id INTEGER PRIMARY KEY, sensor_id TEXT REFERENCES sensors(id), raw_value REAL, unit TEXT DEFAULT 'celsius', calibrated REAL, recorded_at TEXT);
CREATE INDEX idx_orders_status ON orders(status);
CREATE INDEX idx_measurements_sensor ON measurements(sensor_id);
CREATE TABLE docs(id INTEGER PRIMARY KEY, title TEXT, body TEXT);
CREATE TABLE docs_json(id INTEGER PRIMARY KEY, data TEXT);
CREATE TABLE computed(a INTEGER NOT NULL, b INTEGER NOT NULL);
