// Copyright 2025 The syntaqlite Authors. All rights reserved.
// Licensed under the Apache License, Version 2.0.

//! Build-time utilities for dialect crate `build.rs` scripts.
//!
//! Provides cflag name parsing and code generation for compile-time pinning.
//! All cflag metadata is derived from the single source of truth:
//! `include/syntaqlite/sqlite_cflags.h`.

use std::fmt::Write;

/// The raw content of `sqlite_cflags.h`, embedded at compile time.
const CFLAGS_HEADER: &str = include_str!("../include/syntaqlite/sqlite_cflags.h");

/// A single cflag entry derived from the C header.
#[derive(Debug, Clone)]
pub struct CflagEntry {
    /// The suffix shared across C and Rust (e.g. `"OMIT_WINDOWFUNC"`).
    ///
    /// - C user-facing define: `SYNTAQLITE_CFLAG_OMIT_WINDOWFUNC`
    /// - C internal index:     `SYNQ_CFLAG_IDX_OMIT_WINDOWFUNC`
    /// - Rust env var:         `SYNTAQLITE_CFLAG_OMIT_WINDOWFUNC=1`
    pub suffix: String,
    /// C struct field name (e.g. `"omit_windowfunc"`).
    pub field: String,
    /// Bit index in `SyntaqliteCflags` (matches `SYNQ_CFLAG_IDX_*` constants).
    pub index: u32,
}

/// Parse all cflag entries from the embedded C header.
///
/// Reads `#define SYNQ_CFLAG_IDX_<SUFFIX> <index>` lines and derives
/// the field name from the suffix.
pub fn cflag_entries() -> Vec<CflagEntry> {
    let mut entries = Vec::new();
    for line in CFLAGS_HEADER.lines() {
        let Some(rest) = line.strip_prefix("#define SYNQ_CFLAG_IDX_") else {
            continue;
        };
        let mut parts = rest.split_whitespace();
        let Some(suffix) = parts.next() else { continue };
        if suffix == "COUNT" {
            continue;
        }
        let Some(idx_str) = parts.next() else {
            continue;
        };
        let Ok(index) = idx_str.parse::<u32>() else {
            continue;
        };
        let field = suffix.to_ascii_lowercase();
        entries.push(CflagEntry {
            suffix: suffix.to_string(),
            field,
            index,
        });
    }
    entries
}

/// Look up a cflag entry by its suffix (e.g. `"OMIT_WINDOWFUNC"`).
pub fn find_cflag<'a>(entries: &'a [CflagEntry], suffix: &str) -> Option<&'a CflagEntry> {
    entries.iter().find(|e| e.suffix == suffix)
}

/// Generate a Rust source file defining `pinned_dialect_config()`.
///
/// The function returns a `DialectConfig` with the pinned version and cflags.
pub fn generate_pinned_config_rs(version: Option<i32>, cflag_indices: &[u32]) -> String {
    let mut rs = String::new();
    writeln!(rs, "// @generated by build.rs — do not edit").unwrap();
    writeln!(rs).unwrap();
    writeln!(
        rs,
        "/// Returns a `DialectConfig` matching compile-time pinned features."
    )
    .unwrap();
    writeln!(rs, "///").unwrap();
    writeln!(
        rs,
        "/// When `pin-version` or `pin-cflags` features are enabled, the returned"
    )
    .unwrap();
    writeln!(
        rs,
        "/// config has those values hardcoded. The C code uses matching compile-time"
    )
    .unwrap();
    writeln!(
        rs,
        "/// constants, so the macros and this config always agree."
    )
    .unwrap();
    writeln!(
        rs,
        "pub fn pinned_dialect_config() -> syntaqlite_runtime::dialect::ffi::DialectConfig {{"
    )
    .unwrap();

    if version.is_none() && cflag_indices.is_empty() {
        writeln!(
            rs,
            "    syntaqlite_runtime::dialect::ffi::DialectConfig::default()"
        )
        .unwrap();
    } else {
        let ver = version.unwrap_or(i32::MAX);
        let mutability = if cflag_indices.is_empty() { "" } else { "mut " };
        writeln!(
            rs,
            "    let {mutability}config = syntaqlite_runtime::dialect::ffi::DialectConfig {{"
        )
        .unwrap();
        writeln!(rs, "        sqlite_version: {ver},").unwrap();
        writeln!(
            rs,
            "        cflags: syntaqlite_runtime::dialect::ffi::Cflags::new(),"
        )
        .unwrap();
        writeln!(rs, "    }};").unwrap();
        for &idx in cflag_indices {
            writeln!(rs, "    config.cflags.set({idx});").unwrap();
        }
        writeln!(rs, "    config").unwrap();
    }

    writeln!(rs, "}}").unwrap();
    rs
}
