use clap::{Parser, Subcommand};
use std::fs;
use std::path::Path;
use std::process;

#[derive(Parser)]
#[command(name = "syntaqlite-codegen")]
#[command(about = "SQLite grammar extraction and code generation")]
struct Args {
    #[command(subcommand)]
    command: Command,
    #[arg(short, long, global = true)]
    verbose: bool,
}

#[derive(Subcommand)]
enum Command {
    Codegen {
        #[arg(long, required = true)]
        actions_dir: String,
        #[arg(long, required = true)]
        nodes_dir: String,
        #[arg(long, required = true)]
        tokenize_c: String,
        #[arg(long, default_value = "syntaqlite-parser/csrc")]
        output_dir: String,
    },
    Lemon {
        #[arg(trailing_var_arg = true, allow_hyphen_values = true)]
        args: Vec<String>,
    },
    Mkkeyword {
        #[arg(trailing_var_arg = true, allow_hyphen_values = true)]
        args: Vec<String>,
    },
}

/// Delete any .c/.h files in `dir` whose first 512 bytes contain the autogenerated marker.
fn clean_generated_files(dir: &Path, verbose: bool) {
    let Ok(entries) = fs::read_dir(dir) else { return };
    for entry in entries.flatten() {
        let path = entry.path();
        let ext = path.extension().and_then(|e| e.to_str()).unwrap_or("");
        if ext != "c" && ext != "h" {
            continue;
        }
        // Read just the first 512 bytes to check for the marker
        let Ok(content) = fs::read_to_string(&path) else { continue };
        let prefix = &content[..content.len().min(512)];
        if prefix.contains(syntaqlite_codegen::c_writer::AUTOGENERATED_MARKER) {
            if verbose {
                eprintln!("  Removing stale generated file: {}", path.display());
            }
            let _ = fs::remove_file(&path);
        }
    }
}

fn main() {
    let args = Args::parse();

    let result = (|| -> Result<(), String> {
        match args.command {
            Command::Codegen {
                actions_dir,
                nodes_dir,
                tokenize_c,
                output_dir,
            } => {
                let temp_dir = tempfile::TempDir::new()
                    .map_err(|e| format!("Failed to create temp directory: {}", e))?;
                let work_dir = temp_dir.path().to_str()
                    .ok_or_else(|| "Invalid temp directory path".to_string())?
                    .to_string();

                // Step 0: Parse node definitions
                if args.verbose {
                    eprintln!("Parsing node definitions...");
                }
                let nodes_path = Path::new(&nodes_dir);
                let mut synq_files: Vec<_> = fs::read_dir(nodes_path)
                    .map_err(|e| format!("Failed to read {}: {}", nodes_dir, e))?
                    .filter_map(|e| {
                        let p = e.ok()?.path();
                        (p.extension()?.to_str()? == "synq").then_some(p)
                    })
                    .collect();
                synq_files.sort();
                let mut all_items = Vec::new();
                for path in &synq_files {
                    let name = path.file_name().and_then(|s| s.to_str()).unwrap_or("?");
                    let content = fs::read_to_string(path)
                        .map_err(|e| format!("{}: {}", name, e))?;
                    let items = syntaqlite_codegen::node_parser::parse_node(&content)
                        .map_err(|e| format!("{}: {}", name, e))?;
                    if args.verbose {
                        eprintln!("  {} ({} items)", name, items.len());
                    }
                    all_items.extend(items);
                }

                // Step 1: Generate parser (writes parse.c, parse.h into temp dir)
                if args.verbose {
                    eprintln!("Generating parser...");
                }
                syntaqlite_codegen::generate_parser(&actions_dir, &work_dir)?;

                // Step 2: Extract tokenizer
                if args.verbose {
                    eprintln!("Extracting tokenizer...");
                }
                let (tokenize_content, extract_result) =
                    syntaqlite_codegen::extract_tokenizer(&tokenize_c)?;

                // Step 3: Generate keyword hash
                if args.verbose {
                    eprintln!("Generating keyword hash...");
                }
                let (keyword_tables, keyword_func) =
                    syntaqlite_codegen::generate_keyword_hash(&extract_result)?;

                // Step 4: Clean stale generated files, then write outputs
                let out = Path::new(&output_dir);
                let include_dir = Path::new(&output_dir)
                    .parent()
                    .unwrap_or(Path::new("."))
                    .join("include/syntaqlite");

                for dir in [out, include_dir.as_path()] {
                    if dir.is_dir() {
                        clean_generated_files(dir, args.verbose);
                    }
                }

                fs::create_dir_all(out)
                    .map_err(|e| format!("Failed to create output directory: {}", e))?;
                fs::create_dir_all(&include_dir)
                    .map_err(|e| format!("Failed to create include directory: {}", e))?;

                if args.verbose {
                    eprintln!("Writing output files...");
                }
                fs::copy(
                    temp_dir.path().join("parse.h"),
                    include_dir.join("tokens.h"),
                ).map_err(|e| format!("Failed to write tokens.h: {}", e))?;

                // Step 4b: Generate AST code from node definitions
                let ast_nodes_h = syntaqlite_codegen::ast_codegen::generate_ast_nodes_h(&all_items);
                fs::write(include_dir.join("node.h"), ast_nodes_h)
                    .map_err(|e| format!("Failed to write node.h: {}", e))?;

                let ast_builder_h = syntaqlite_codegen::ast_codegen::generate_ast_builder_h(&all_items);
                fs::write(out.join("ast_builder.h"), ast_builder_h)
                    .map_err(|e| format!("Failed to write ast_builder.h: {}", e))?;

                let raw_parse_c = fs::read_to_string(temp_dir.path().join("parse.c"))
                    .map_err(|e| format!("Failed to read parse.c: {}", e))?;
                let (parse_c, parse_data_h) =
                    syntaqlite_codegen::split_parse_c(&raw_parse_c)?;
                fs::write(out.join("sqlite_parse.c"), parse_c)
                    .map_err(|e| format!("Failed to write sqlite_parse.c: {}", e))?;
                fs::write(out.join("sqlite_parse_data.h"), parse_data_h)
                    .map_err(|e| format!("Failed to write sqlite_parse_data.h: {}", e))?;

                fs::write(out.join("sqlite_tokenize.c"), tokenize_content)
                    .map_err(|e| format!("Failed to write sqlite_tokenize.c: {}", e))?;

                fs::write(out.join("sqlite_keyword_tables.h"), keyword_tables)
                    .map_err(|e| format!("Failed to write sqlite_keyword_tables.h: {}", e))?;

                fs::write(out.join("sqlite_keyword.c"), keyword_func)
                    .map_err(|e| format!("Failed to write sqlite_keyword.c: {}", e))?;

                // Step 5: Generate Rust bindings
                if args.verbose {
                    eprintln!("Generating Rust bindings...");
                }
                let rust_gen_dir = Path::new(&output_dir)
                    .parent()
                    .unwrap_or(Path::new("."))
                    .join("src/generated");
                fs::create_dir_all(&rust_gen_dir)
                    .map_err(|e| format!("Failed to create Rust generated directory: {}", e))?;

                let parse_h_content = fs::read_to_string(temp_dir.path().join("parse.h"))
                    .map_err(|e| format!("Failed to read parse.h: {}", e))?;
                let token_defines = syntaqlite_codegen::extract_token_defines(&parse_h_content);

                let rust_tokens = syntaqlite_codegen::ast_codegen::generate_rust_tokens(&token_defines);
                fs::write(rust_gen_dir.join("tokens.rs"), rust_tokens)
                    .map_err(|e| format!("Failed to write tokens.rs: {}", e))?;

                let rust_nodes = syntaqlite_codegen::ast_codegen::generate_rust_nodes(&all_items);
                fs::write(rust_gen_dir.join("nodes.rs"), rust_nodes)
                    .map_err(|e| format!("Failed to write nodes.rs: {}", e))?;

                fs::write(rust_gen_dir.join("mod.rs"), "pub mod nodes;\npub mod tokens;\n")
                    .map_err(|e| format!("Failed to write mod.rs: {}", e))?;

                if args.verbose {
                    eprintln!("Code generation complete");
                }

                Ok(())
            }
            Command::Lemon { args: lemon_args } => {
                if args.verbose {
                    eprintln!("Running lemon with args: {:?}", lemon_args);
                }

                syntaqlite_codegen::lemon::run_lemon(&lemon_args);
            }
            Command::Mkkeyword {
                args: mkkeyword_args,
            } => {
                if args.verbose {
                    eprintln!("Running mkkeyword with args: {:?}", mkkeyword_args);
                }

                syntaqlite_codegen::mkkeyword::run_mkkeyword(&mkkeyword_args);
            }
        }
    })();

    if let Err(e) = result {
        eprintln!("Error: {}", e);
        process::exit(1);
    }
}
