// Copyright 2025 The syntaqlite Authors. All rights reserved.
// Licensed under the Apache License, Version 2.0.

use clap::{Parser, Subcommand};
use std::fs;
use std::path::{Path, PathBuf};
use std::process;

#[derive(Parser)]
#[command(name = "syntaqlite-codegen")]
#[command(about = "SQLite grammar extraction and code generation")]
struct Args {
    #[command(subcommand)]
    command: Command,
    #[arg(short, long, global = true)]
    verbose: bool,
}

#[derive(Subcommand)]
enum Command {
    Codegen {
        #[arg(long, required = true)]
        actions_dir: String,
        #[arg(long, required = true)]
        nodes_dir: String,
        #[arg(long, default_value = "syntaqlite/csrc")]
        output_dir: String,
    },
    Lemon {
        #[arg(trailing_var_arg = true, allow_hyphen_values = true)]
        args: Vec<String>,
    },
    Mkkeyword {
        #[arg(trailing_var_arg = true, allow_hyphen_values = true)]
        args: Vec<String>,
    },
    /// Produce C amalgamation files (single-file compilation units).
    Amalgamate {
        /// Dialect name (e.g. "sqlite").
        #[arg(long, required = true)]
        dialect: String,
        /// Path to the syntaqlite-runtime crate root.
        #[arg(long, required = true)]
        runtime_dir: String,
        /// Path to the dialect crate root (e.g. syntaqlite/).
        #[arg(long, required = true)]
        dialect_dir: String,
        /// Output directory for generated files.
        #[arg(long, required = true)]
        output_dir: String,
        /// Emit only the runtime amalgamation.
        #[arg(long)]
        runtime_only: bool,
        /// Emit only the dialect amalgamation (references runtime header).
        #[arg(long)]
        dialect_only: bool,
    },
}

/// Delete any .c/.h files in `dir` whose first 512 bytes contain the autogenerated marker.
fn clean_generated_files(dir: &Path, verbose: bool) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        let ext = path.extension().and_then(|e| e.to_str()).unwrap_or("");
        if ext != "c" && ext != "h" {
            continue;
        }
        // Read just the first 512 bytes to check for the marker
        let Ok(content) = fs::read_to_string(&path) else {
            continue;
        };
        let prefix = &content[..content.len().min(512)];
        if prefix.contains(syntaqlite_codegen::AUTOGENERATED_MARKER) {
            if verbose {
                eprintln!("  Removing stale generated file: {}", path.display());
            }
            let _ = fs::remove_file(&path);
        }
    }
}

fn log_verbose(verbose: bool, message: &str) {
    if verbose {
        eprintln!("{message}");
    }
}

fn ensure_dir(path: &Path, label: &str) -> Result<(), String> {
    fs::create_dir_all(path).map_err(|e| format!("Failed to create {label}: {e}"))
}

fn write_file(path: &Path, content: impl AsRef<[u8]>) -> Result<(), String> {
    fs::write(path, content).map_err(|e| format!("Failed to write {}: {}", path.display(), e))
}

fn handle_codegen(
    actions_dir: &str,
    nodes_dir: &str,
    output_dir: &str,
    verbose: bool,
) -> Result<(), String> {
    let dialect = syntaqlite_codegen::DialectNaming::new("sqlite");

    log_verbose(verbose, "Loading grammar + node definition files...");
    let y_files = syntaqlite_codegen::read_named_files_from_dir(actions_dir, "y")?;
    let synq_files = syntaqlite_codegen::read_named_files_from_dir(nodes_dir, "synq")?;

    log_verbose(verbose, "Running unified codegen pipeline...");
    let no_keywords: Vec<String> = Vec::new();
    let request = syntaqlite_codegen::CodegenRequest {
        dialect: &dialect,
        y_files: &y_files,
        synq_files: &synq_files,
        extra_keywords: &no_keywords,
        parser_symbol_prefix: None,
        include_rust: true,
    };
    let artifacts = syntaqlite_codegen::generate_codegen_artifacts(&request)?;
    let outputs = syntaqlite_codegen::sqlite_output_manifest(&dialect, artifacts)?;

    // Step 4: Clean stale generated files, then write outputs
    let out = Path::new(output_dir);
    let include_dir = Path::new(output_dir)
        .parent()
        .unwrap_or(Path::new("."))
        .join(format!("include/{}", dialect.include_dir_name()));
    let rust_src_dir = Path::new(output_dir)
        .parent()
        .unwrap_or(Path::new("."))
        .join("src");

    for dir in [out, include_dir.as_path()] {
        if dir.is_dir() {
            clean_generated_files(dir, verbose);
        }
    }

    ensure_dir(out, "output directory")?;
    ensure_dir(&include_dir, "include directory")?;
    ensure_dir(&rust_src_dir, "Rust src directory")?;

    log_verbose(verbose, "Writing output files...");
    for output in outputs {
        let dir = match output.bucket {
            syntaqlite_codegen::OutputBucket::Include => &include_dir,
            syntaqlite_codegen::OutputBucket::DialectCsrc => out,
            syntaqlite_codegen::OutputBucket::RustSrc => &rust_src_dir,
        };
        write_file(&dir.join(output.file_name), output.content)?;
    }

    log_verbose(verbose, "Code generation complete");
    Ok(())
}

fn write_amalgamation_outputs(
    out: &Path,
    header_name: &str,
    source_name: &str,
    result: &syntaqlite_codegen::amalgamate::AmalgamateOutput,
) -> Result<(), String> {
    write_file(&out.join(header_name), &result.header)?;
    write_file(&out.join(source_name), &result.source)?;
    if let Some(ext) = &result.ext_header {
        write_file(&out.join("syntaqlite_ext.h"), ext)?;
    }
    Ok(())
}

fn handle_amalgamate(
    dialect: &str,
    runtime_dir: &str,
    dialect_dir: &str,
    output_dir: &str,
    runtime_only: bool,
    dialect_only: bool,
    verbose: bool,
) -> Result<(), String> {
    use syntaqlite_codegen::amalgamate;

    let out = Path::new(output_dir);
    ensure_dir(out, "output directory")?;

    let runtime = PathBuf::from(runtime_dir);
    let dialect_path = PathBuf::from(dialect_dir);

    if runtime_only {
        log_verbose(verbose, "Generating runtime amalgamation...");
        let result = amalgamate::amalgamate_runtime(&runtime)?;
        write_amalgamation_outputs(out, "syntaqlite_runtime.h", "syntaqlite_runtime.c", &result)?;
        log_verbose(verbose, "Wrote syntaqlite_runtime.{h,c} + syntaqlite_ext.h");
    } else {
        let (phase, result) = if dialect_only {
            (
                "Generating dialect amalgamation...",
                amalgamate::amalgamate_dialect(dialect, &dialect_path)?,
            )
        } else {
            (
                "Generating full amalgamation...",
                amalgamate::amalgamate_full(dialect, &runtime, &dialect_path)?,
            )
        };
        log_verbose(verbose, phase);
        let base = format!("syntaqlite_{dialect}");
        write_amalgamation_outputs(out, &format!("{base}.h"), &format!("{base}.c"), &result)?;
        log_verbose(verbose, &format!("Wrote {base}.{{h,c}}"));
    }

    Ok(())
}

fn main() {
    let args = Args::parse();

    let result = (|| -> Result<(), String> {
        match args.command {
            Command::Codegen {
                actions_dir,
                nodes_dir,
                output_dir,
            } => handle_codegen(&actions_dir, &nodes_dir, &output_dir, args.verbose),
            Command::Lemon { args: lemon_args } => {
                log_verbose(
                    args.verbose,
                    &format!("Running lemon with args: {:?}", lemon_args),
                );
                syntaqlite_codegen::run_lemon(&lemon_args);
            }
            Command::Mkkeyword {
                args: mkkeyword_args,
            } => {
                log_verbose(
                    args.verbose,
                    &format!("Running mkkeyword with args: {:?}", mkkeyword_args),
                );
                syntaqlite_codegen::run_mkkeyword(&mkkeyword_args);
            }
            Command::Amalgamate {
                dialect,
                runtime_dir,
                dialect_dir,
                output_dir,
                runtime_only,
                dialect_only,
            } => handle_amalgamate(
                &dialect,
                &runtime_dir,
                &dialect_dir,
                &output_dir,
                runtime_only,
                dialect_only,
                args.verbose,
            ),
        }
    })();

    if let Err(e) = result {
        eprintln!("Error: {}", e);
        process::exit(1);
    }
}
