// Copyright 2025 The syntaqlite Authors. All rights reserved.
// Licensed under the Apache License, Version 2.0.

use clap::{Parser, Subcommand};
use std::fs;
use std::path::{Path, PathBuf};
use std::process;

#[derive(Parser)]
#[command(name = "syntaqlite-codegen")]
#[command(about = "SQLite grammar extraction and code generation")]
struct Args {
    #[command(subcommand)]
    command: Command,
    #[arg(short, long, global = true)]
    verbose: bool,
}

#[derive(Subcommand)]
enum Command {
    Codegen {
        #[arg(long, required = true)]
        actions_dir: String,
        #[arg(long, required = true)]
        nodes_dir: String,
        #[arg(long, required = true)]
        tokenize_c: String,
        #[arg(long, default_value = "syntaqlite/csrc")]
        output_dir: String,
        /// Output directory for runtime engine files (tokenizer, keywords).
        /// If not set, these files are written to output_dir.
        #[arg(long)]
        runtime_csrc: Option<String>,
    },
    Lemon {
        #[arg(trailing_var_arg = true, allow_hyphen_values = true)]
        args: Vec<String>,
    },
    Mkkeyword {
        #[arg(trailing_var_arg = true, allow_hyphen_values = true)]
        args: Vec<String>,
    },
    /// Produce C amalgamation files (single-file compilation units).
    Amalgamate {
        /// Dialect name (e.g. "sqlite").
        #[arg(long, required = true)]
        dialect: String,
        /// Path to the syntaqlite-runtime crate root.
        #[arg(long, required = true)]
        runtime_dir: String,
        /// Path to the dialect crate root (e.g. syntaqlite/).
        #[arg(long, required = true)]
        dialect_dir: String,
        /// Output directory for generated files.
        #[arg(long, required = true)]
        output_dir: String,
        /// Emit only the runtime amalgamation.
        #[arg(long)]
        runtime_only: bool,
        /// Emit only the dialect amalgamation (references runtime header).
        #[arg(long)]
        dialect_only: bool,
    },
}

/// Delete any .c/.h files in `dir` whose first 512 bytes contain the autogenerated marker.
fn clean_generated_files(dir: &Path, verbose: bool) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        let ext = path.extension().and_then(|e| e.to_str()).unwrap_or("");
        if ext != "c" && ext != "h" {
            continue;
        }
        // Read just the first 512 bytes to check for the marker
        let Ok(content) = fs::read_to_string(&path) else {
            continue;
        };
        let prefix = &content[..content.len().min(512)];
        if prefix.contains(syntaqlite_codegen::c_writer::AUTOGENERATED_MARKER) {
            if verbose {
                eprintln!("  Removing stale generated file: {}", path.display());
            }
            let _ = fs::remove_file(&path);
        }
    }
}

fn log_verbose(verbose: bool, message: &str) {
    if verbose {
        eprintln!("{message}");
    }
}

fn ensure_dir(path: &Path, label: &str) -> Result<(), String> {
    fs::create_dir_all(path).map_err(|e| format!("Failed to create {label}: {e}"))
}

fn read_file(path: &Path) -> Result<String, String> {
    fs::read_to_string(path).map_err(|e| format!("Failed to read {}: {}", path.display(), e))
}

fn write_file(path: &Path, content: impl AsRef<[u8]>) -> Result<(), String> {
    fs::write(path, content).map_err(|e| format!("Failed to write {}: {}", path.display(), e))
}

fn write_files(out_dir: &Path, files: Vec<(&str, String)>) -> Result<(), String> {
    for (name, content) in files {
        write_file(&out_dir.join(name), content)?;
    }
    Ok(())
}

fn build_guarded_tokens_header(tokens_content: &str) -> String {
    format!(
        "/*\n\
         ** The author disclaims copyright to this source code.  In place of\n\
         ** a legal notice, here is a blessing:\n\
         **\n\
         **    May you do good and not evil.\n\
         **    May you find forgiveness for yourself and forgive others.\n\
         **    May you share freely, never taking more than you give.\n\
         **\n\
         ** @generated by syntaqlite-codegen — DO NOT EDIT\n\
         */\n\
         \n\
         #ifndef SYNTAQLITE_SQLITE_TOKENS_H\n\
         #define SYNTAQLITE_SQLITE_TOKENS_H\n\
         \n\
         {tokens_content}\
         \n\
         #endif  // SYNTAQLITE_SQLITE_TOKENS_H\n",
    )
}

fn parse_synq_items(
    nodes_dir: &str,
    verbose: bool,
) -> Result<Vec<syntaqlite_codegen::node_parser::Item>, String> {
    let nodes_path = Path::new(nodes_dir);
    let mut synq_files: Vec<_> = fs::read_dir(nodes_path)
        .map_err(|e| format!("Failed to read {nodes_dir}: {e}"))?
        .filter_map(|e| {
            let p = e.ok()?.path();
            (p.extension()?.to_str()? == "synq").then_some(p)
        })
        .collect();
    synq_files.sort();

    let mut all_items = Vec::new();
    for path in &synq_files {
        let name = path.file_name().and_then(|s| s.to_str()).unwrap_or("?");
        let content = fs::read_to_string(path).map_err(|e| format!("{name}: {e}"))?;
        let items = syntaqlite_codegen::node_parser::parse_node(&content)
            .map_err(|e| format!("{name}: {e}"))?;
        log_verbose(verbose, &format!("  {name} ({} items)", items.len()));
        all_items.extend(items);
    }
    Ok(all_items)
}

fn handle_codegen(
    actions_dir: &str,
    nodes_dir: &str,
    tokenize_c: &str,
    output_dir: &str,
    runtime_csrc: Option<&str>,
    verbose: bool,
) -> Result<(), String> {
    let temp_dir =
        tempfile::TempDir::new().map_err(|e| format!("Failed to create temp directory: {e}"))?;
    let work_dir = temp_dir
        .path()
        .to_str()
        .ok_or_else(|| "Invalid temp directory path".to_string())?
        .to_string();

    // Step 0: Parse node definitions
    log_verbose(verbose, "Parsing node definitions...");
    let all_items = parse_synq_items(nodes_dir, verbose)?;

    // Step 1: Generate parser (writes parse.c, parse.h into temp dir)
    log_verbose(verbose, "Generating parser...");
    syntaqlite_codegen::generate_parser(actions_dir, &work_dir)?;

    // Step 2: Extract tokenizer
    log_verbose(verbose, "Extracting tokenizer...");
    let (tokenize_content, extract_result) =
        syntaqlite_codegen::extract_tokenizer(tokenize_c, "sqlite")?;

    // Step 3: Generate keyword hash
    log_verbose(verbose, "Generating keyword hash...");
    let keyword_c = syntaqlite_codegen::generate_keyword_hash(&extract_result, "sqlite", &[])?;

    // Step 4: Clean stale generated files, then write outputs
    let out = Path::new(output_dir);
    let include_dir = Path::new(output_dir)
        .parent()
        .unwrap_or(Path::new("."))
        .join("include/syntaqlite_sqlite");
    let rust_src_dir = Path::new(output_dir)
        .parent()
        .unwrap_or(Path::new("."))
        .join("src");

    for dir in [out, include_dir.as_path()] {
        if dir.is_dir() {
            clean_generated_files(dir, verbose);
        }
    }

    ensure_dir(out, "output directory")?;
    ensure_dir(&include_dir, "include directory")?;
    ensure_dir(&rust_src_dir, "Rust src directory")?;

    // Runtime engine files (tokenizer, keywords, parse engine) go to runtime_csrc if set.
    let rt_out = runtime_csrc.map(Path::new).unwrap_or(out);
    ensure_dir(rt_out, "runtime csrc directory")?;
    if runtime_csrc.is_some() {
        clean_generated_files(rt_out, verbose);
    }

    log_verbose(verbose, "Writing output files...");
    let parse_h_path = temp_dir.path().join("parse.h");
    let parse_c_path = temp_dir.path().join("parse.c");
    let parse_h_content = read_file(&parse_h_path)?;

    write_files(
        &include_dir,
        vec![
            (
                "sqlite_tokens.h",
                build_guarded_tokens_header(&parse_h_content),
            ),
            (
                "sqlite_node.h",
                syntaqlite_codegen::ast_codegen::generate_ast_nodes_h(&all_items, "sqlite"),
            ),
            (
                "sqlite.h",
                syntaqlite_codegen::ast_codegen::generate_dialect_h("sqlite"),
            ),
        ],
    )?;

    write_files(
        out,
        vec![
            (
                "dialect_builder.h",
                syntaqlite_codegen::ast_codegen::generate_ast_builder_h(&all_items, "sqlite"),
            ),
            (
                "dialect_meta.h",
                syntaqlite_codegen::ast_codegen::generate_c_field_meta(&all_items, "sqlite"),
            ),
            (
                "dialect_fmt.h",
                syntaqlite_codegen::ast_codegen::generate_c_fmt_arrays(&all_items),
            ),
            (
                "dialect.c",
                syntaqlite_codegen::ast_codegen::generate_dialect_c("sqlite"),
            ),
            (
                "sqlite_dialect_dispatch.h",
                syntaqlite_codegen::ast_codegen::generate_dialect_dispatch_h("sqlite"),
            ),
        ],
    )?;

    write_files(
        rt_out,
        vec![
            ("sqlite_parse.c", read_file(&parse_c_path)?),
            ("sqlite_tokenize.c", tokenize_content),
            ("sqlite_keyword.c", keyword_c),
            ("sqlite_keyword.h", syntaqlite_codegen::generate_keyword_h()),
        ],
    )?;

    // Step 5: Generate Rust bindings
    log_verbose(verbose, "Generating Rust bindings...");
    let token_defines = syntaqlite_codegen::extract_token_defines(&parse_h_content);

    write_files(
        &rust_src_dir,
        vec![
            (
                "tokens.rs",
                syntaqlite_codegen::ast_codegen::generate_rust_tokens(&token_defines),
            ),
            (
                "ffi.rs",
                syntaqlite_codegen::ast_codegen::generate_rust_ffi_nodes(&all_items),
            ),
            (
                "ast.rs",
                syntaqlite_codegen::ast_codegen::generate_rust_ast(&all_items),
            ),
            (
                "lib.rs",
                syntaqlite_codegen::ast_codegen::generate_rust_lib("syntaqlite_sqlite_dialect"),
            ),
            (
                "wrappers.rs",
                syntaqlite_codegen::ast_codegen::generate_rust_wrappers(),
            ),
        ],
    )?;

    log_verbose(verbose, "Code generation complete");
    Ok(())
}

fn write_amalgamation_outputs(
    out: &Path,
    header_name: &str,
    source_name: &str,
    result: &syntaqlite_codegen::amalgamate::AmalgamateOutput,
) -> Result<(), String> {
    write_file(&out.join(header_name), &result.header)?;
    write_file(&out.join(source_name), &result.source)?;
    if let Some(ext) = &result.ext_header {
        write_file(&out.join("syntaqlite_ext.h"), ext)?;
    }
    Ok(())
}

fn handle_amalgamate(
    dialect: &str,
    runtime_dir: &str,
    dialect_dir: &str,
    output_dir: &str,
    runtime_only: bool,
    dialect_only: bool,
    verbose: bool,
) -> Result<(), String> {
    use syntaqlite_codegen::amalgamate;

    let out = Path::new(output_dir);
    ensure_dir(out, "output directory")?;

    let runtime = PathBuf::from(runtime_dir);
    let dialect_path = PathBuf::from(dialect_dir);

    if runtime_only {
        log_verbose(verbose, "Generating runtime amalgamation...");
        let result = amalgamate::amalgamate_runtime(&runtime)?;
        write_amalgamation_outputs(out, "syntaqlite_runtime.h", "syntaqlite_runtime.c", &result)?;
        log_verbose(verbose, "Wrote syntaqlite_runtime.{h,c} + syntaqlite_ext.h");
    } else {
        let (phase, result) = if dialect_only {
            (
                "Generating dialect amalgamation...",
                amalgamate::amalgamate_dialect(dialect, &dialect_path)?,
            )
        } else {
            (
                "Generating full amalgamation...",
                amalgamate::amalgamate_full(dialect, &runtime, &dialect_path)?,
            )
        };
        log_verbose(verbose, phase);
        let base = format!("syntaqlite_{dialect}");
        write_amalgamation_outputs(out, &format!("{base}.h"), &format!("{base}.c"), &result)?;
        log_verbose(verbose, &format!("Wrote {base}.{{h,c}}"));
    }

    Ok(())
}

fn main() {
    let args = Args::parse();

    let result = (|| -> Result<(), String> {
        match args.command {
            Command::Codegen {
                actions_dir,
                nodes_dir,
                tokenize_c,
                output_dir,
                runtime_csrc,
            } => handle_codegen(
                &actions_dir,
                &nodes_dir,
                &tokenize_c,
                &output_dir,
                runtime_csrc.as_deref(),
                args.verbose,
            ),
            Command::Lemon { args: lemon_args } => {
                log_verbose(
                    args.verbose,
                    &format!("Running lemon with args: {:?}", lemon_args),
                );
                syntaqlite_codegen::lemon::run_lemon(&lemon_args);
            }
            Command::Mkkeyword {
                args: mkkeyword_args,
            } => {
                log_verbose(
                    args.verbose,
                    &format!("Running mkkeyword with args: {:?}", mkkeyword_args),
                );
                syntaqlite_codegen::mkkeyword::run_mkkeyword(&mkkeyword_args);
            }
            Command::Amalgamate {
                dialect,
                runtime_dir,
                dialect_dir,
                output_dir,
                runtime_only,
                dialect_only,
            } => handle_amalgamate(
                &dialect,
                &runtime_dir,
                &dialect_dir,
                &output_dir,
                runtime_only,
                dialect_only,
                args.verbose,
            ),
        }
    })();

    if let Err(e) = result {
        eprintln!("Error: {}", e);
        process::exit(1);
    }
}
