// Copyright 2025 The syntaqlite Authors. All rights reserved.
// Licensed under the Apache License, Version 2.0.
// @generated by syntaqlite-buildtools — DO NOT EDIT

//! Static cflag metadata: name, bit index, first-seen version, categories.

/// All known compile-time flags: `(name, bit_index, min_version_int, categories)`.
///
/// - `name`: canonical flag name (e.g. `"SQLITE_OMIT_WINDOWFUNC"`).
/// - `bit_index`: position in the cflag bitfield (matches [`syntaqlite_syntax::util::SqliteFlag`]
///   discriminant). Parser flags (indices 0–21) equal their C compact `SYNQ_CFLAG_IDX_*` value.
///   Non-parser flags occupy indices 22–41.
/// - `min_version_int`: earliest observed SQLite version as `major * 1_000_000 +
///   minor * 1_000 + patch`; `0` means not observed in the audited range.
/// - `categories`: all concerns this flag affects (e.g. `&["parser", "functions"]`).
pub(crate) const CFLAG_ENTRIES: &[(&str, u32, i32, &[&str])] = &[
    ("SQLITE_OMIT_ALTERTABLE", 0, 3030001, &["parser"]),
    ("SQLITE_OMIT_ANALYZE", 1, 3030001, &["parser"]),
    ("SQLITE_OMIT_ATTACH", 2, 3030001, &["parser"]),
    ("SQLITE_OMIT_AUTOINCREMENT", 3, 3030001, &["parser"]),
    ("SQLITE_OMIT_CAST", 4, 3030001, &["parser"]),
    (
        "SQLITE_OMIT_COMPILEOPTION_DIAGS",
        22,
        3030001,
        &["functions"],
    ),
    ("SQLITE_OMIT_COMPOUND_SELECT", 5, 3030001, &["parser"]),
    ("SQLITE_OMIT_CTE", 6, 3030001, &["parser"]),
    ("SQLITE_OMIT_DATETIME_FUNCS", 23, 3030001, &["functions"]),
    ("SQLITE_OMIT_EXPLAIN", 7, 3030001, &["parser"]),
    ("SQLITE_OMIT_FLOATING_POINT", 24, 3030001, &["functions"]),
    ("SQLITE_OMIT_FOREIGN_KEY", 8, 3030001, &["parser"]),
    ("SQLITE_OMIT_GENERATED_COLUMNS", 9, 3031001, &["parser"]),
    ("SQLITE_OMIT_JSON", 25, 3038005, &["functions"]),
    ("SQLITE_OMIT_LOAD_EXTENSION", 26, 3030001, &["functions"]),
    ("SQLITE_OMIT_PRAGMA", 10, 3030001, &["parser"]),
    ("SQLITE_OMIT_REINDEX", 11, 3030001, &["parser"]),
    ("SQLITE_OMIT_RETURNING", 12, 0, &["parser"]),
    ("SQLITE_OMIT_SUBQUERY", 13, 3030001, &["parser"]),
    ("SQLITE_OMIT_TEMPDB", 14, 3030001, &["parser"]),
    ("SQLITE_OMIT_TRIGGER", 15, 3030001, &["parser"]),
    ("SQLITE_OMIT_VACUUM", 16, 3030001, &["parser"]),
    ("SQLITE_OMIT_VIEW", 17, 3030001, &["parser"]),
    (
        "SQLITE_OMIT_VIRTUALTABLE",
        18,
        3030001,
        &["parser", "vtable"],
    ),
    (
        "SQLITE_OMIT_WINDOWFUNC",
        19,
        3030001,
        &["parser", "functions"],
    ),
    ("SQLITE_ENABLE_BYTECODE_VTAB", 27, 3032003, &["vtable"]),
    ("SQLITE_ENABLE_CARRAY", 28, 3051002, &["vtable"]),
    ("SQLITE_ENABLE_DBPAGE_VTAB", 29, 3030001, &["vtable"]),
    ("SQLITE_ENABLE_DBSTAT_VTAB", 30, 3030001, &["vtable"]),
    ("SQLITE_ENABLE_FTS3", 31, 3030001, &["extensions"]),
    ("SQLITE_ENABLE_FTS4", 32, 3030001, &["extensions"]),
    ("SQLITE_ENABLE_FTS5", 33, 3030001, &["extensions"]),
    ("SQLITE_ENABLE_GEOPOLY", 34, 3030001, &["extensions"]),
    ("SQLITE_ENABLE_JSON1", 35, 3030001, &["functions"]),
    ("SQLITE_ENABLE_MATH_FUNCTIONS", 36, 3035005, &["functions"]),
    ("SQLITE_ENABLE_OFFSET_SQL_FUNC", 37, 3030001, &["functions"]),
    (
        "SQLITE_ENABLE_ORDERED_SET_AGGREGATES",
        20,
        3047002,
        &["parser", "functions"],
    ),
    ("SQLITE_ENABLE_PERCENTILE", 38, 3051002, &["functions"]),
    ("SQLITE_ENABLE_RTREE", 39, 3030001, &["extensions"]),
    ("SQLITE_ENABLE_STMTVTAB", 40, 3030001, &["vtable"]),
    (
        "SQLITE_ENABLE_UPDATE_DELETE_LIMIT",
        21,
        3030001,
        &["parser"],
    ),
    ("SQLITE_SOUNDEX", 41, 3030001, &["functions"]),
];
