// @generated by sqlite-extract — DO NOT EDIT

/// Cflag metadata: (name, index, min_version, category).
///
/// `index` is the bit index in `Cflags` (matches `SYNQ_CFLAG_IDX_*` constants).
///
/// `min_version` is the encoded SQLite version integer at which this cflag
/// first appears in the amalgamation source. Zero = not observed.
///
/// `category` groups flags by feature area for UI presentation:
/// "parser", "functions", "vtable", "extensions".
pub(crate) const CFLAG_TABLE: &[(&str, u32, i32, &str)] = &[
    ("SQLITE_OMIT_ALTERTABLE", 0, 0, "parser"),
    ("SQLITE_OMIT_ANALYZE", 1, 0, "parser"),
    ("SQLITE_OMIT_ATTACH", 2, 0, "parser"),
    ("SQLITE_OMIT_AUTOINCREMENT", 3, 0, "parser"),
    ("SQLITE_OMIT_CAST", 4, 0, "parser"),
    ("SQLITE_OMIT_COMPILEOPTION_DIAGS", 5, 3030001, "functions"),
    ("SQLITE_OMIT_COMPOUND_SELECT", 6, 0, "parser"),
    ("SQLITE_OMIT_CTE", 7, 0, "parser"),
    ("SQLITE_OMIT_DATETIME_FUNCS", 8, 3030001, "functions"),
    ("SQLITE_OMIT_EXPLAIN", 9, 0, "parser"),
    ("SQLITE_OMIT_FLOATING_POINT", 10, 0, "functions"),
    ("SQLITE_OMIT_FOREIGN_KEY", 11, 0, "parser"),
    ("SQLITE_OMIT_GENERATED_COLUMNS", 12, 0, "parser"),
    ("SQLITE_OMIT_JSON", 13, 3038005, "functions"),
    ("SQLITE_OMIT_LOAD_EXTENSION", 14, 3030001, "functions"),
    ("SQLITE_OMIT_PRAGMA", 15, 0, "parser"),
    ("SQLITE_OMIT_REINDEX", 16, 0, "parser"),
    ("SQLITE_OMIT_RETURNING", 17, 0, "parser"),
    ("SQLITE_OMIT_SUBQUERY", 18, 0, "parser"),
    ("SQLITE_OMIT_TEMPDB", 19, 0, "parser"),
    ("SQLITE_OMIT_TRIGGER", 20, 0, "parser"),
    ("SQLITE_OMIT_VACUUM", 21, 0, "parser"),
    ("SQLITE_OMIT_VIEW", 22, 0, "parser"),
    ("SQLITE_OMIT_VIRTUALTABLE", 23, 0, "vtable"),
    ("SQLITE_OMIT_WINDOWFUNC", 24, 3030001, "parser"),
    ("SQLITE_ENABLE_BYTECODE_VTAB", 25, 0, "vtable"),
    ("SQLITE_ENABLE_CARRAY", 26, 3051002, "vtable"),
    ("SQLITE_ENABLE_DBPAGE_VTAB", 27, 0, "vtable"),
    ("SQLITE_ENABLE_DBSTAT_VTAB", 28, 0, "vtable"),
    ("SQLITE_ENABLE_FTS3", 29, 3030001, "extensions"),
    ("SQLITE_ENABLE_FTS4", 30, 0, "extensions"),
    ("SQLITE_ENABLE_FTS5", 31, 3030001, "extensions"),
    ("SQLITE_ENABLE_GEOPOLY", 32, 3030001, "extensions"),
    ("SQLITE_ENABLE_JSON1", 33, 3030001, "functions"),
    ("SQLITE_ENABLE_MATH_FUNCTIONS", 34, 3035005, "functions"),
    ("SQLITE_ENABLE_OFFSET_SQL_FUNC", 35, 3030001, "functions"),
    (
        "SQLITE_ENABLE_ORDERED_SET_AGGREGATES",
        36,
        3047002,
        "functions",
    ),
    ("SQLITE_ENABLE_PERCENTILE", 37, 3051002, "functions"),
    ("SQLITE_ENABLE_RTREE", 38, 0, "extensions"),
    ("SQLITE_ENABLE_STMTVTAB", 39, 0, "vtable"),
    ("SQLITE_ENABLE_UPDATE_DELETE_LIMIT", 40, 0, "parser"),
    ("SQLITE_SOUNDEX", 41, 3030001, "functions"),
];
