// Copyright 2025 The syntaqlite Authors. All rights reserved.
// Licensed under the Apache License, Version 2.0.

//! `SQLite` dialect handle: the `dialect()` accessor.
//!
//! Builds the [`Dialect`] by combining the syntactic grammar from
//! `syntaqlite-syntax` with Rust-generated formatter statics and the
//! built-in function/schema data.

use std::sync::LazyLock;

use syntaqlite_common::roles::SemanticRole;
use syntaqlite_syntax::typed::Grammar;

use crate::dialect::{AnyDialect, TypedDialect};

// All dialect data is exported from the linked C dialect library (`dialect.c`)
// which includes `dialect_fmt.h` and `dialect_roles.h` generated by codegen.
unsafe extern "C" {
    fn syntaqlite_sqlite_fmt_string_data() -> *const u8;
    fn syntaqlite_sqlite_fmt_string_offsets() -> *const u32;
    fn syntaqlite_sqlite_fmt_string_count() -> u32;
    fn syntaqlite_sqlite_fmt_enum_display() -> *const u16;
    fn syntaqlite_sqlite_fmt_enum_display_count() -> u32;
    fn syntaqlite_sqlite_fmt_ops() -> *const u8;
    fn syntaqlite_sqlite_fmt_ops_count() -> u32;
    fn syntaqlite_sqlite_fmt_dispatch() -> *const u32;
    fn syntaqlite_sqlite_fmt_dispatch_count() -> u32;
    fn syntaqlite_sqlite_roles_data() -> *const u8;
    fn syntaqlite_sqlite_roles_count() -> u32;
}

static DIALECT: LazyLock<AnyDialect> = LazyLock::new(|| typed_dialect().erase());

/// Returns a typed `SQLite` dialect handle (`TypedDialect<Grammar>`).
///
/// Prefer this over [`dialect()`] when the grammar type is needed statically
/// (e.g. to store in a `TypedDialect<Grammar>` field or pass to a generic API).
pub(crate) fn typed_dialect() -> TypedDialect<Grammar> {
    // SAFETY: All pointers returned by the extern "C" functions point to static
    // data compiled into the binary (`dialect.c` includes the generated C headers).
    // The data lives for the entire program lifetime — effectively 'static.
    unsafe {
        TypedDialect::new(
            syntaqlite_syntax::typed::grammar(),
            syntaqlite_sqlite_fmt_string_data(),
            syntaqlite_sqlite_fmt_string_offsets(),
            syntaqlite_sqlite_fmt_string_count() as usize,
            syntaqlite_sqlite_fmt_enum_display(),
            syntaqlite_sqlite_fmt_enum_display_count() as usize,
            syntaqlite_sqlite_fmt_ops(),
            syntaqlite_sqlite_fmt_ops_count() as usize,
            syntaqlite_sqlite_fmt_dispatch(),
            syntaqlite_sqlite_fmt_dispatch_count() as usize,
            syntaqlite_sqlite_roles_data() as *const SemanticRole,
            syntaqlite_sqlite_roles_count() as usize,
        )
    }
}

/// Returns the type-erased `SQLite` dialect handle (cached).
pub(crate) fn dialect() -> AnyDialect {
    DIALECT.clone()
}
