// Copyright 2025 The syntaqlite Authors. All rights reserved.
// Licensed under the Apache License, Version 2.0.

//! SQLite dialect handle: the `dialect()` and `typed_dialect()` accessors.
//!
//! Builds the [`Dialect`] by combining the syntactic [`Grammar`] from
//! `syntaqlite-syntax` with Rust-generated formatter statics and the
//! built-in function/schema data.

use std::sync::LazyLock;

use syntaqlite_syntax::sqlite::grammar;
use syntaqlite_syntax::sqlite::SqliteNodeFamily;

use crate::dialect::handle::Dialect;
use crate::dialect::typed_dialect::TypedDialect;

// Formatter statics — generated by codegen (Step 2).
// These are declared in `crate::sqlite::fmt_statics`, which will be populated
// when `tools/run-codegen` is run after Step 2 changes to buildtools.
use crate::sqlite::fmt_statics::{
    SQLITE_FMT_DISPATCH, SQLITE_FMT_ENUM_DISPLAY, SQLITE_FMT_OPS, SQLITE_FMT_STRINGS,
};

static DIALECT: LazyLock<Dialect<'static>> = LazyLock::new(|| {
    let grammar = grammar();
    Dialect::new(
        grammar,
        SQLITE_FMT_STRINGS,
        SQLITE_FMT_ENUM_DISPLAY,
        SQLITE_FMT_OPS,
        SQLITE_FMT_DISPATCH,
        // Function extensions: injected via function catalog (see cflag_helpers).
        &[],
        // Schema contributions: populated by generated schema_statics (Step 2).
        &[],
    )
});

/// Returns the raw (untagged) SQLite dialect handle.
pub fn dialect() -> Dialect<'static> {
    *DIALECT
}

/// Returns the SQLite dialect handle tagged with [`SqliteNodeFamily`].
pub fn typed_dialect() -> TypedDialect<'static, SqliteNodeFamily> {
    TypedDialect::new(*DIALECT)
}
