// Copyright 2025 The syntaqlite Authors. All rights reserved.
// Licensed under the Apache License, Version 2.0.

//! `SQLite` dialect handle: the `dialect()` accessor.
//!
//! Builds the [`Dialect`] by combining the syntactic grammar from
//! `syntaqlite-syntax` with Rust-generated formatter statics and the
//! built-in function/schema data.

use std::sync::LazyLock;

use syntaqlite_syntax::typed::Grammar;

use crate::dialect::{AnyDialect, TypedDialect};

// Formatter statics — generated by codegen.
use crate::sqlite::fmt_statics::{
    SQLITE_FMT_DISPATCH, SQLITE_FMT_ENUM_DISPLAY, SQLITE_FMT_OPS, SQLITE_FMT_STRINGS,
};
// Semantic role table — generated by codegen.
use crate::sqlite::semantic_roles::SQLITE_SEMANTIC_ROLES;

static DIALECT: LazyLock<AnyDialect> = LazyLock::new(|| typed_dialect().erase());

/// Returns a typed `SQLite` dialect handle (`TypedDialect<Grammar>`).
///
/// Prefer this over [`dialect()`] when the grammar type is needed statically
/// (e.g. to store in a `TypedDialect<Grammar>` field or pass to a generic API).
pub(crate) fn typed_dialect() -> TypedDialect<Grammar> {
    TypedDialect::new(
        syntaqlite_syntax::typed::grammar(),
        SQLITE_FMT_STRINGS,
        SQLITE_FMT_ENUM_DISPLAY,
        SQLITE_FMT_OPS,
        SQLITE_FMT_DISPATCH,
        SQLITE_SEMANTIC_ROLES,
    )
}

/// Returns the type-erased `SQLite` dialect handle (cached).
pub(crate) fn dialect() -> AnyDialect {
    DIALECT.clone()
}
