// Copyright 2025 The syntaqlite Authors. All rights reserved.
// Licensed under the Apache License, Version 2.0.
//
// @generated by syntaqlite-buildtools — DO NOT EDIT

/// Typed AST nodes for this dialect.
///
/// Each SQL statement type (e.g. `SELECT`, `INSERT`) has a corresponding struct
/// with typed accessors for its fields. The top-level enum is [`ast::Stmt`],
/// returned by [`StatementCursor::next_statement`] and
/// [`LowLevelCursor::finish`](low_level::LowLevelCursor::finish).
pub mod ast;
mod ffi;

use std::sync::LazyLock;

use crate::dialect::ffi as dialect_ffi;
unsafe extern "C" {
    fn syntaqlite_sqlite_dialect() -> *const dialect_ffi::Dialect;
}

pub(crate) static DIALECT: LazyLock<crate::Dialect<'static>> =
    LazyLock::new(|| unsafe { crate::Dialect::from_raw(syntaqlite_sqlite_dialect()) });

/// Low-level APIs for advanced use cases (e.g. custom token feeding/tokenizing).
pub mod low_level {
    pub use crate::sqlite::tokens::TokenType;

    /// Access the dialect handle (for use with `syntaqlite` APIs).
    pub fn dialect() -> &'static crate::Dialect<'static> {
        &crate::sqlite::DIALECT
    }
}

pub use crate::ParseError;

/// Configuration types for parsers and formatters.
pub mod config {
    pub use crate::dialect::ffi::{CflagInfo, Cflags, DialectConfig, cflag_table};
    pub use crate::fmt::{FormatConfig, KeywordCase};
    pub use crate::parser::ParserConfig;
}

mod tokens;
