// Copyright 2025 The syntaqlite Authors. All rights reserved.
// Licensed under the Apache License, Version 2.0.

//! Embedded base `SQLite` grammar (.y) and node definition (.synq) files,
//! plus runtime C public headers from `syntaqlite-syntax/include/syntaqlite/`
//! and runtime engine C sources/headers from `syntaqlite-syntax/csrc/`.
//!
//! File lists are pre-generated by `sqlite-extract` and committed to
//! `src/base_files_tables.rs`. The `include_str!` calls inside that
//! file are evaluated at compile time, so cargo automatically tracks
//! changes to the actual .y/.synq files.

use std::fs;
use std::path::Path;

use super::base_files_tables::{BASE_SYNQ_FILES, BASE_Y_FILES};

/// Embedded `syntaqlite-syntax/include/syntaqlite/` headers.
///
/// Keyed by filename (e.g. `"types.h"`). These are the public runtime headers
/// that define types like `SyntaqliteSourceSpan`, `SyntaqliteParser`, etc.
/// They must be written into the amalgamation temp directory so the amalgamator
/// can collect and inline them into `syntaqlite_runtime.h` / full amalgams.
const RUNTIME_HEADERS: &[(&str, &str)] = &[
    (
        "grammar.h",
        include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../syntaqlite-syntax/include/syntaqlite/grammar.h",
        )),
    ),
    (
        "cflags.h",
        include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../syntaqlite-syntax/include/syntaqlite/cflags.h",
        )),
    ),
    (
        "config.h",
        include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../syntaqlite-syntax/include/syntaqlite/config.h",
        )),
    ),
    (
        "parser.h",
        include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../syntaqlite-syntax/include/syntaqlite/parser.h",
        )),
    ),
    (
        "incremental.h",
        include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../syntaqlite-syntax/include/syntaqlite/incremental.h",
        )),
    ),
    (
        "tokenizer.h",
        include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../syntaqlite-syntax/include/syntaqlite/tokenizer.h",
        )),
    ),
    (
        "types.h",
        include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../syntaqlite-syntax/include/syntaqlite/types.h",
        )),
    ),
];

/// Embedded `syntaqlite-syntax/include/syntaqlite_dialect/` headers.
///
/// These define the extension SPI: `synq_parse_build`, `SynqParseCtx`, arena
/// helpers, etc. They must be present in the amalgamation temp directory so
/// the amalgamator can inline them (as `ExtHeader` files) into the `.c` output.
/// Embedded `syntaqlite-syntax/csrc/` runtime C sources and internal headers.
///
/// These contain the parser and tokenizer implementations. They must be written
/// into `temp/csrc/` so the amalgamator can collect and inline them.
const RUNTIME_CSRC: &[(&str, &str)] = &[
    (
        "dialect_dispatch.h",
        include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../syntaqlite-syntax/csrc/dialect_dispatch.h",
        )),
    ),
    (
        "parser.c",
        include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../syntaqlite-syntax/csrc/parser.c",
        )),
    ),
    (
        "token_wrapped.c",
        include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../syntaqlite-syntax/csrc/token_wrapped.c",
        )),
    ),
    (
        "token_wrapped.h",
        include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../syntaqlite-syntax/csrc/token_wrapped.h",
        )),
    ),
    (
        "tokens.h",
        include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../syntaqlite-syntax/csrc/tokens.h",
        )),
    ),
    (
        "tokenizer.c",
        include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../syntaqlite-syntax/csrc/tokenizer.c",
        )),
    ),
];

const DIALECT_EXT_HEADERS: &[(&str, &str)] = &[
    (
        "arena.h",
        include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../syntaqlite-syntax/include/syntaqlite_dialect/arena.h",
        )),
    ),
    (
        "ast_builder.h",
        include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../syntaqlite-syntax/include/syntaqlite_dialect/ast_builder.h",
        )),
    ),
    (
        "dialect_macros.h",
        include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../syntaqlite-syntax/include/syntaqlite_dialect/dialect_macros.h",
        )),
    ),
    (
        "dialect_types.h",
        include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../syntaqlite-syntax/include/syntaqlite_dialect/dialect_types.h",
        )),
    ),
    (
        "sqlite_compat.h",
        include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../syntaqlite-syntax/include/syntaqlite_dialect/sqlite_compat.h",
        )),
    ),
    (
        "vec.h",
        include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../syntaqlite-syntax/include/syntaqlite_dialect/vec.h",
        )),
    ),
];

/// Write the embedded runtime headers into `dir/include/syntaqlite/`.
///
/// This populates the temp directory used by the amalgamator so that
/// `syntaqlite/types.h`, `syntaqlite/parser.h`, etc. are resolved and
/// inlined rather than stripped as unresolved includes.
///
/// # Errors
///
/// Returns an error if creating directories or writing files fails.
pub fn write_runtime_headers_to_dir(dir: &Path) -> Result<(), String> {
    let csrc_dest = dir.join("csrc");
    fs::create_dir_all(&csrc_dest).map_err(|e| format!("creating {}: {e}", csrc_dest.display()))?;
    for (name, content) in RUNTIME_CSRC {
        let path = csrc_dest.join(name);
        // Don't overwrite generated files (dialect_dispatch.h is also generated).
        if !path.exists() {
            fs::write(&path, content).map_err(|e| format!("writing {}: {e}", path.display()))?;
        }
    }

    let runtime_dest = dir.join("include").join("syntaqlite");
    fs::create_dir_all(&runtime_dest)
        .map_err(|e| format!("creating {}: {e}", runtime_dest.display()))?;
    for (name, content) in RUNTIME_HEADERS {
        let path = runtime_dest.join(name);
        fs::write(&path, content).map_err(|e| format!("writing {}: {e}", path.display()))?;
    }

    let ext_dest = dir.join("include").join("syntaqlite_dialect");
    fs::create_dir_all(&ext_dest).map_err(|e| format!("creating {}: {e}", ext_dest.display()))?;
    for (name, content) in DIALECT_EXT_HEADERS {
        let path = ext_dest.join(name);
        fs::write(&path, content).map_err(|e| format!("writing {}: {e}", path.display()))?;
    }

    Ok(())
}

/// Returns all base `.y` action files (filename, contents) in alphabetical order.
#[must_use]
pub const fn base_y_files() -> &'static [(&'static str, &'static str)] {
    BASE_Y_FILES
}

/// Returns all base `.synq` node definition files (filename, contents) in alphabetical order.
#[must_use]
pub const fn base_synq_files() -> &'static [(&'static str, &'static str)] {
    BASE_SYNQ_FILES
}

/// Merge base files with extension files.
///
/// Base files come first in their original order. Extension files are always
/// appended after all base files, sorted alphabetically among themselves.
/// Extensions cannot override base files — they are purely additive.
///
/// Ordering guarantee: all base file slots come before all extension slots.
/// This ensures that Lemon assigns token IDs to extension-specific terminals
/// only after all base `SQLite` terminals have been numbered.
#[must_use]
pub fn merge_file_sets(
    base: &[(&str, &str)],
    extensions: &[(String, String)],
) -> Vec<(String, String)> {
    let mut result: Vec<(String, String)> = base
        .iter()
        .map(|(name, content)| (name.to_string(), content.to_string()))
        .collect();

    let mut ext_sorted = extensions.to_vec();
    ext_sorted.sort_by(|(a, _), (b, _)| a.cmp(b));
    result.extend(ext_sorted);

    result
}

#[cfg(test)]
mod tests {
    use super::RUNTIME_HEADERS;

    fn runtime_header(name: &str) -> &'static str {
        RUNTIME_HEADERS
            .iter()
            .find_map(|(n, content)| (*n == name).then_some(*content))
            .unwrap_or_else(|| panic!("missing embedded runtime header: {name}"))
    }

    #[test]
    fn merge_file_sets_base_always_before_extensions() {
        use super::merge_file_sets;
        let base = &[("a.y", "base_a"), ("z.y", "base_z")];
        let ext = vec![
            ("b.y".to_string(), "ext_b".to_string()),
            ("aaa.y".to_string(), "ext_aaa".to_string()),
        ];
        let merged = merge_file_sets(base, &ext);
        // Base files come first in their original order, then extension files sorted.
        assert_eq!(merged[0], ("a.y".to_string(), "base_a".to_string()));
        assert_eq!(merged[1], ("z.y".to_string(), "base_z".to_string()));
        assert_eq!(merged[2], ("aaa.y".to_string(), "ext_aaa".to_string()));
        assert_eq!(merged[3], ("b.y".to_string(), "ext_b".to_string()));
    }

    #[test]
    fn merge_file_sets_same_name_does_not_override_base() {
        use super::merge_file_sets;
        let base = &[("shared.y", "base_content"), ("ztokens.y", "sentinel")];
        let ext = vec![("shared.y".to_string(), "ext_content".to_string())];
        let merged = merge_file_sets(base, &ext);
        // Base file is unchanged; extension file is appended as a separate entry.
        assert_eq!(
            merged[0],
            ("shared.y".to_string(), "base_content".to_string())
        );
        assert_eq!(merged[1], ("ztokens.y".to_string(), "sentinel".to_string()));
        assert_eq!(
            merged[2],
            ("shared.y".to_string(), "ext_content".to_string())
        );
    }

    #[test]
    fn parser_header_uses_new_constructor_names() {
        let h = runtime_header("parser.h");
        assert!(h.contains("syntaqlite_parser_create("));
        assert!(h.contains("syntaqlite_parser_create_with_grammar("));
        assert!(h.contains("SyntaqliteParser* p = syntaqlite_parser_create(NULL);"));
        assert!(h.contains("#ifndef SYNTAQLITE_OMIT_SQLITE_API"));
    }

    #[test]
    fn tokenizer_header_uses_new_constructor_names() {
        let h = runtime_header("tokenizer.h");
        assert!(h.contains("syntaqlite_tokenizer_create("));
        assert!(h.contains("syntaqlite_tokenizer_create_with_grammar("));
        assert!(h.contains("SyntaqliteTokenizer* tok = syntaqlite_tokenizer_create(NULL);"));
        assert!(h.contains("#ifndef SYNTAQLITE_OMIT_SQLITE_API"));
        assert!(!h.contains("syntaqlite_create_sqlite_tokenizer("));
    }
}
