// Copyright 2025 The syntaqlite Authors. All rights reserved.
// Licensed under the Apache License, Version 2.0.

//! Generates `cflags.rs` files for the `SqliteFlag` and `SqliteSyntaxFlag` enums,
//! and the legacy `cflag_entries.rs` static metadata table.
//!
//! Both flag enums are generated from [`super::cflag_registry::CFLAG_REGISTRY`]:
//!
//! - `SqliteFlag` (42 variants) → `syntaqlite/src/sqlite/cflags.rs`
//! - `SqliteSyntaxFlag` (22 parser-only variants) → `syntaqlite-syntax/src/sqlite/cflags.rs`
//!
//! Each enum is self-describing: variants carry their own name, categories,
//! and `from_name` lookup via `impl` methods backed by internal `const` arrays.

use std::fmt::Write as _;

use serde::Deserialize;

use super::cflag_registry::CFLAG_REGISTRY;
use super::functions_codegen::cflag_index;
use super::pascal_case;

// ── JSON schema ──────────────────────────────────────────────────────────────

#[derive(Deserialize)]
struct VersionCflagsFile {
    cflags: Vec<CflagEntry>,
}

#[derive(Deserialize)]
struct CflagEntry {
    name: String,
    since: String,
    categories: Vec<String>,
}

// ── Version encoding ─────────────────────────────────────────────────────────

/// Convert a version string like `"3.38.5"` to an integer using `SQLite`'s encoding
/// (`major * 1_000_000 + minor * 1_000 + patch`). `"0"` or unrecognised strings
/// return `0`.
fn version_string_to_int(s: &str) -> i32 {
    if s == "0" {
        return 0;
    }
    let parts: Vec<&str> = s.splitn(3, '.').collect();
    if parts.len() < 2 {
        return 0;
    }
    let major: i32 = parts[0].parse().unwrap_or(0);
    let minor: i32 = parts[1].parse().unwrap_or(0);
    let patch: i32 = if parts.len() >= 3 {
        parts[2].parse().unwrap_or(0)
    } else {
        0
    };
    major * 1_000_000 + minor * 1_000 + patch
}

// ── Flag variant name ─────────────────────────────────────────────────────────

/// Derive the Rust `PascalCase` variant name from a `SQLITE_*` flag name.
///
/// Strips the `"SQLITE_"` prefix and applies `pascal_case`, e.g.
/// `"SQLITE_OMIT_WINDOWFUNC"` → `"OmitWindowfunc"`.
fn variant_name(sqlite_name: &str) -> String {
    let suffix = sqlite_name.strip_prefix("SQLITE_").unwrap_or(sqlite_name);
    pascal_case(suffix)
}

// ── SqliteFlag codegen ────────────────────────────────────────────────────────

/// Generate `syntaqlite/src/sqlite/cflags.rs` containing the `SqliteFlag` enum.
///
/// All 42 flags from [`CFLAG_REGISTRY`] are emitted in index order with
/// self-describing `impl` methods: `name()`, `categories()`, `from_name()`,
/// and the crate-internal `all()`.
pub(crate) fn generate_sqlite_flag_rs() -> String {
    let mut out = String::new();
    out.push_str("// Copyright 2025 The syntaqlite Authors. All rights reserved.\n");
    out.push_str("// Licensed under the Apache License, Version 2.0.\n");
    out.push_str("// @generated by syntaqlite-buildtools — DO NOT EDIT\n\n");
    out.push_str("//! Compile-time feature flags for the `SQLite` dialect.\n\n");

    out.push_str("use syntaqlite_syntax::util::SqliteSyntaxFlag;\n\n");

    out.push_str("/// A compile-time feature flag for the `SQLite` dialect.\n");
    out.push_str("///\n");
    out.push_str("/// Pass a variant to [`crate::util::SqliteFlags::has`],\n");
    out.push_str(
        "/// [`crate::util::SqliteFlags::with`], or [`crate::util::SqliteFlags::without`].\n",
    );
    out.push_str("///\n");
    out.push_str("/// Parser-level flags (discriminants 0–21) correspond 1-to-1 with\n");
    out.push_str("/// [`SqliteSyntaxFlag`] and the C compact `SYNQ_CFLAG_IDX_*` values.\n");
    out.push_str("#[repr(u32)]\n");
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub enum SqliteFlag {\n");
    for &(name, idx, _) in CFLAG_REGISTRY {
        let variant = variant_name(name);
        writeln!(out, "    /// `{name}`\n    {variant} = {idx},").expect("write to String");
    }
    out.push_str("}\n\n");

    out.push_str("impl SqliteFlag {\n");

    // ALL array
    out.push_str("    const ALL: &'static [Self] = &[\n");
    for &(name, _, _) in CFLAG_REGISTRY {
        writeln!(out, "        Self::{},", variant_name(name)).expect("write to String");
    }
    out.push_str("    ];\n\n");

    // NAMES array
    out.push_str("    const NAMES: &'static [&'static str] = &[\n");
    for &(name, _, _) in CFLAG_REGISTRY {
        writeln!(out, "        \"{name}\",").expect("write to String");
    }
    out.push_str("    ];\n\n");

    // CATEGORIES array
    out.push_str("    const CATEGORIES: &'static [&'static [&'static str]] = &[\n");
    for &(_, _, cats) in CFLAG_REGISTRY {
        let cats_str: Vec<String> = cats.iter().map(|c| format!("\"{c}\"")).collect();
        writeln!(out, "        &[{}],", cats_str.join(", ")).expect("write to String");
    }
    out.push_str("    ];\n\n");

    out.push_str(
        r#"    /// The canonical `SQLITE_*` flag name (e.g. `"SQLITE_OMIT_WINDOWFUNC"`).
    pub fn name(self) -> &'static str {
        Self::NAMES[self as usize]
    }

    /// Which concerns this flag affects (e.g. `"parser"`, `"functions"`, `"vtable"`).
    pub fn categories(self) -> &'static [&'static str] {
        Self::CATEGORIES[self as usize]
    }

    /// Look up a flag by its canonical `SQLITE_*` name.
    ///
    /// Returns `None` if `s` is not a known flag name.
    pub fn from_name(s: &str) -> Option<Self> {
        Self::ALL.iter().copied().find(|f| f.name() == s)
    }

    /// All known flags in stable index order.
    pub(crate) fn all() -> &'static [Self] {
        Self::ALL
    }

    /// Returns `true` if this flag affects the C parser grammar.
    pub(crate) fn is_parser_flag(self) -> bool {
        (self as u32) < 22
    }

    /// The corresponding [`SqliteSyntaxFlag`], if this is a parser-level flag.
    pub(crate) fn as_syntax_flag(self) -> Option<SqliteSyntaxFlag> {
        if self.is_parser_flag() {
            SqliteSyntaxFlag::from_index(self as u32)
        } else {
            None
        }
    }
}
"#,
    );
    out
}

/// Write the `SqliteFlag` enum to `output_path`.
///
/// # Errors
///
/// Returns an error if writing fails.
pub(crate) fn write_sqlite_flag_rs(output_path: &str) -> Result<(), String> {
    use std::fs;
    use std::path::Path;
    let content = generate_sqlite_flag_rs();
    let out = Path::new(output_path);
    if let Some(parent) = out.parent() {
        fs::create_dir_all(parent).map_err(|e| format!("creating output directory: {e}"))?;
    }
    fs::write(out, content).map_err(|e| format!("writing {}: {e}", out.display()))?;
    eprintln!("wrote {output_path}");
    Ok(())
}

// ── SqliteSyntaxFlag codegen ──────────────────────────────────────────────────

/// Generate `syntaqlite-syntax/src/sqlite/cflags.rs` containing `SqliteSyntaxFlag`.
///
/// Only the 22 parser-category flags from [`CFLAG_REGISTRY`] are emitted,
/// in index order (discriminants 0–21 matching `SYNQ_CFLAG_IDX_*` in `cflags.h`).
pub(crate) fn generate_syntax_flag_rs() -> String {
    let parser_flags: Vec<(&str, u32)> = CFLAG_REGISTRY
        .iter()
        .filter(|(_, _, cats)| cats.contains(&"parser"))
        .map(|&(name, idx, _)| (name, idx))
        .collect();

    let mut out = String::new();
    out.push_str("// Copyright 2025 The syntaqlite Authors. All rights reserved.\n");
    out.push_str("// Licensed under the Apache License, Version 2.0.\n");
    out.push_str("// @generated by syntaqlite-buildtools — DO NOT EDIT\n\n");
    out.push_str("//! Parser-level compile-time flags for the `SQLite` dialect.\n\n");

    out.push_str("/// A parser-level compile-time feature flag for the `SQLite` dialect.\n");
    out.push_str("///\n");
    out.push_str("/// Each variant corresponds to a `SYNQ_CFLAG_IDX_*` constant in `cflags.h`.\n");
    out.push_str("/// The discriminant equals the C compact index (0–21).\n");
    out.push_str("///\n");
    out.push_str("/// Pass a variant to [`crate::util::SqliteSyntaxFlags::has`] or\n");
    out.push_str("/// [`crate::util::SqliteSyntaxFlags::with`].\n");
    out.push_str("///\n");
    out.push_str("/// For the full 42-flag set use `syntaqlite::util::SqliteFlag`.\n");
    out.push_str("#[repr(u32)]\n");
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub enum SqliteSyntaxFlag {\n");
    for &(name, idx) in &parser_flags {
        let variant = variant_name(name);
        writeln!(out, "    /// `{name}`\n    {variant} = {idx},").expect("write to String");
    }
    out.push_str("}\n\n");

    out.push_str("impl SqliteSyntaxFlag {\n");

    // ALL
    out.push_str("    const ALL: &'static [Self] = &[\n");
    for &(name, _) in &parser_flags {
        writeln!(out, "        Self::{},", variant_name(name)).expect("write to String");
    }
    out.push_str("    ];\n\n");

    // NAMES
    out.push_str("    const NAMES: &'static [&'static str] = &[\n");
    for &(name, _) in &parser_flags {
        writeln!(out, "        \"{name}\",").expect("write to String");
    }
    out.push_str("    ];\n\n");

    out.push_str(
        r#"    /// The canonical `SQLITE_*` flag name (e.g. `"SQLITE_OMIT_WINDOWFUNC"`).
    pub fn name(self) -> &'static str {
        Self::NAMES[self as usize]
    }

    /// Look up a parser flag by its canonical `SQLITE_*` name.
    ///
    /// Returns `None` if `s` is not a known parser flag name.
    pub fn from_name(s: &str) -> Option<Self> {
        Self::ALL.iter().copied().find(|f| f.name() == s)
    }

    /// Look up a parser flag by its compact C index (0–21).
    ///
    /// Returns `None` if `idx` is out of range.
    pub(crate) fn from_index(idx: u32) -> Option<Self> {
        Self::ALL.get(idx as usize).copied()
    }

    /// All known parser flags in stable index order.
    pub(crate) fn all() -> &'static [Self] {
        Self::ALL
    }
}
"#,
    );
    out
}

/// Write the `SqliteSyntaxFlag` enum to `output_path`.
///
/// # Errors
///
/// Returns an error if writing fails.
pub(crate) fn write_syntax_flag_rs(output_path: &str) -> Result<(), String> {
    use std::fs;
    use std::path::Path;
    let content = generate_syntax_flag_rs();
    let out = Path::new(output_path);
    if let Some(parent) = out.parent() {
        fs::create_dir_all(parent).map_err(|e| format!("creating output directory: {e}"))?;
    }
    fs::write(out, content).map_err(|e| format!("writing {}: {e}", out.display()))?;
    eprintln!("wrote {output_path}");
    Ok(())
}

// ── Legacy cflag_entries.rs codegen ──────────────────────────────────────────

/// Read `version_cflags.json` from `json_path`, generate `cflag_entries.rs`,
/// and write it to `output_path` (creating parent directories as needed).
///
/// # Errors
///
/// Returns an error if reading, parsing, or writing fails.
pub(crate) fn write_cflag_entries_file(json_path: &str, output_path: &str) -> Result<(), String> {
    use std::fs;
    use std::path::Path;

    let json = fs::read_to_string(json_path).map_err(|e| format!("reading {json_path}: {e}"))?;
    let content = generate_cflag_entries(&json)?;
    let out = Path::new(output_path);
    if let Some(parent) = out.parent() {
        fs::create_dir_all(parent).map_err(|e| format!("creating output directory: {e}"))?;
    }
    fs::write(out, content).map_err(|e| format!("writing {}: {e}", out.display()))?;
    eprintln!("wrote {output_path}");
    Ok(())
}

/// Generate the `cflag_entries.rs` Rust source from `version_cflags.json` content.
///
/// The `bit_index` values in the output match the `SqliteFlag` discriminants, which
/// are assigned so that parser flags (indices 0–21) equal their C compact indices
/// from `SYNQ_CFLAG_IDX_*`. Non-parser flags occupy indices 22–41.
///
/// # Errors
///
/// Returns an error if JSON parsing fails or an unknown cflag name is encountered.
pub(crate) fn generate_cflag_entries(json_content: &str) -> Result<String, String> {
    let file: VersionCflagsFile = serde_json::from_str(json_content)
        .map_err(|e| format!("parsing version_cflags.json: {e}"))?;

    let mut out = String::new();
    out.push_str("// Copyright 2025 The syntaqlite Authors. All rights reserved.\n");
    out.push_str("// Licensed under the Apache License, Version 2.0.\n");
    out.push_str("// @generated by syntaqlite-buildtools — DO NOT EDIT\n");
    out.push('\n');
    out.push_str("//! Static cflag metadata: name, bit index, first-seen version, categories.\n");
    out.push('\n');
    out.push_str(
        "/// All known compile-time flags: `(name, bit_index, min_version_int, categories)`.\n",
    );
    out.push_str("///\n");
    out.push_str("/// - `name`: canonical flag name (e.g. `\"SQLITE_OMIT_WINDOWFUNC\"`).\n");
    out.push_str(
        "/// - `bit_index`: position in the cflag bitfield (matches [`syntaqlite_syntax::util::SqliteFlag`]\n",
    );
    out.push_str(
        "///   discriminant). Parser flags (indices 0–21) equal their C compact `SYNQ_CFLAG_IDX_*` value.\n",
    );
    out.push_str("///   Non-parser flags occupy indices 22–41.\n");
    out.push_str(
        "/// - `min_version_int`: earliest observed SQLite version as `major * 1_000_000 +\n",
    );
    out.push_str("///   minor * 1_000 + patch`; `0` means not observed in the audited range.\n");
    out.push_str(
        "/// - `categories`: all concerns this flag affects (e.g. `&[\"parser\", \"functions\"]`).\n",
    );
    out.push_str("#[expect(dead_code, reason = \"used in tests and future callers\")]\n");
    out.push_str("pub(crate) const CFLAG_ENTRIES: &[(&str, u32, i32, &[&str])] = &[\n");

    for entry in &file.cflags {
        let index = cflag_index(&entry.name)
            .ok_or_else(|| format!("unknown cflag '{}' in version_cflags.json", entry.name))?;
        let ver_int = version_string_to_int(&entry.since);
        let cats: Vec<String> = entry
            .categories
            .iter()
            .map(|c| format!("\"{c}\""))
            .collect();
        writeln!(
            out,
            "    (\"{}\", {}, {}, &[{}]),",
            entry.name,
            index,
            ver_int,
            cats.join(", ")
        )
        .expect("write to String cannot fail");
    }

    out.push_str("];\n");
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn version_zero_returns_zero() {
        assert_eq!(version_string_to_int("0"), 0);
    }

    #[test]
    fn version_encoding() {
        assert_eq!(version_string_to_int("3.35.5"), 3_035_005);
        assert_eq!(version_string_to_int("3.30.1"), 3_030_001);
    }

    #[test]
    fn generate_from_minimal_json() {
        // OMIT_WINDOWFUNC is a parser flag; its new index is 19 (C compact 19).
        let json = r#"{"cflags":[{"name":"SQLITE_OMIT_WINDOWFUNC","since":"3.30.1","categories":["parser","functions"]}]}"#;
        let out = generate_cflag_entries(json).unwrap();
        assert!(
            out.contains("(\"SQLITE_OMIT_WINDOWFUNC\", 19, 3030001, &[\"parser\", \"functions\"])")
        );
    }

    #[test]
    fn math_functions_gets_non_parser_index() {
        // ENABLE_MATH_FUNCTIONS is non-parser; its index is 36 in the new scheme.
        let json = r#"{"cflags":[{"name":"SQLITE_ENABLE_MATH_FUNCTIONS","since":"3.35.5","categories":["functions"]}]}"#;
        let out = generate_cflag_entries(json).unwrap();
        assert!(out.contains("(\"SQLITE_ENABLE_MATH_FUNCTIONS\", 36, 3035005, &[\"functions\"])"));
    }
}
