// Copyright 2025 The syntaqlite Authors. All rights reserved.
// Licensed under the Apache License, Version 2.0.

//! Generates `cflag_entries.rs` — the static cflag metadata table for `syntaqlite`.
//!
//! Reads `version_cflags.json` (from `sqlite-vendored/data/`) and emits a
//! `CFLAG_ENTRIES` constant: `&[(&str, u32, i32, &[&str])]` where each tuple is
//! `(name, bit_index, min_version_int, categories)`.
//!
//! The `bit_index` values are the `SqliteFlag` discriminants, which are assigned
//! so that parser flags (those in the "parser" category) match the C compact
//! indices (0–21) used by `SYNQ_CFLAG_IDX_*` in `cflags.h`. Non-parser flags
//! occupy indices 22–41. This means no translation table is needed between
//! `SqliteFlags` (Rust u64 bitset) and `SqliteSyntaxFlags` (C CCflags).

use std::fmt::Write as _;

use serde::Deserialize;

use super::functions_codegen::cflag_index;

// ── JSON schema ──────────────────────────────────────────────────────────────

#[derive(Deserialize)]
struct VersionCflagsFile {
    cflags: Vec<CflagEntry>,
}

#[derive(Deserialize)]
struct CflagEntry {
    name: String,
    since: String,
    categories: Vec<String>,
}

// ── Version encoding ─────────────────────────────────────────────────────────

/// Convert a version string like `"3.38.5"` to an integer using SQLite's encoding
/// (`major * 1_000_000 + minor * 1_000 + patch`). `"0"` or unrecognised strings
/// return `0`.
fn version_string_to_int(s: &str) -> i32 {
    if s == "0" {
        return 0;
    }
    let parts: Vec<&str> = s.splitn(3, '.').collect();
    if parts.len() < 2 {
        return 0;
    }
    let major: i32 = parts[0].parse().unwrap_or(0);
    let minor: i32 = parts[1].parse().unwrap_or(0);
    let patch: i32 = if parts.len() >= 3 {
        parts[2].parse().unwrap_or(0)
    } else {
        0
    };
    major * 1_000_000 + minor * 1_000 + patch
}

// ── Public API ───────────────────────────────────────────────────────────────

/// Read `version_cflags.json` from `json_path`, generate `cflag_entries.rs`,
/// and write it to `output_path` (creating parent directories as needed).
///
/// # Errors
///
/// Returns an error if reading, parsing, or writing fails.
pub(crate) fn write_cflag_entries_file(json_path: &str, output_path: &str) -> Result<(), String> {
    use std::fs;
    use std::path::Path;

    let json = fs::read_to_string(json_path).map_err(|e| format!("reading {json_path}: {e}"))?;
    let content = generate_cflag_entries(&json)?;
    let out = Path::new(output_path);
    if let Some(parent) = out.parent() {
        fs::create_dir_all(parent).map_err(|e| format!("creating output directory: {e}"))?;
    }
    fs::write(out, content).map_err(|e| format!("writing {}: {e}", out.display()))?;
    eprintln!("wrote {output_path}");
    Ok(())
}

/// Generate the `cflag_entries.rs` Rust source from `version_cflags.json` content.
///
/// The `bit_index` values in the output match the `SqliteFlag` discriminants, which
/// are assigned so that parser flags (indices 0–21) equal their C compact indices
/// from `SYNQ_CFLAG_IDX_*`. Non-parser flags occupy indices 22–41.
///
/// # Errors
///
/// Returns an error if JSON parsing fails or an unknown cflag name is encountered.
pub(crate) fn generate_cflag_entries(json_content: &str) -> Result<String, String> {
    let file: VersionCflagsFile = serde_json::from_str(json_content)
        .map_err(|e| format!("parsing version_cflags.json: {e}"))?;

    let mut out = String::new();
    out.push_str("// Copyright 2025 The syntaqlite Authors. All rights reserved.\n");
    out.push_str("// Licensed under the Apache License, Version 2.0.\n");
    out.push_str("// @generated by syntaqlite-buildtools — DO NOT EDIT\n");
    out.push('\n');
    out.push_str("//! Static cflag metadata: name, bit index, first-seen version, categories.\n");
    out.push('\n');
    out.push_str(
        "/// All known compile-time flags: `(name, bit_index, min_version_int, categories)`.\n",
    );
    out.push_str("///\n");
    out.push_str("/// - `name`: canonical flag name (e.g. `\"SQLITE_OMIT_WINDOWFUNC\"`).\n");
    out.push_str(
        "/// - `bit_index`: position in the cflag bitfield (matches [`syntaqlite_syntax::util::SqliteFlag`]\n",
    );
    out.push_str(
        "///   discriminant). Parser flags (indices 0–21) equal their C compact `SYNQ_CFLAG_IDX_*` value.\n",
    );
    out.push_str("///   Non-parser flags occupy indices 22–41.\n");
    out.push_str(
        "/// - `min_version_int`: earliest observed SQLite version as `major * 1_000_000 +\n",
    );
    out.push_str("///   minor * 1_000 + patch`; `0` means not observed in the audited range.\n");
    out.push_str(
        "/// - `categories`: all concerns this flag affects (e.g. `&[\"parser\", \"functions\"]`).\n",
    );
    out.push_str("#[expect(dead_code, reason = \"used in tests and future callers\")]\n");
    out.push_str("pub(crate) const CFLAG_ENTRIES: &[(&str, u32, i32, &[&str])] = &[\n");

    for entry in &file.cflags {
        let index = cflag_index(&entry.name)
            .ok_or_else(|| format!("unknown cflag '{}' in version_cflags.json", entry.name))?;
        let ver_int = version_string_to_int(&entry.since);
        let cats: Vec<String> = entry
            .categories
            .iter()
            .map(|c| format!("\"{c}\""))
            .collect();
        writeln!(
            out,
            "    (\"{}\", {}, {}, &[{}]),",
            entry.name,
            index,
            ver_int,
            cats.join(", ")
        )
        .expect("write to String cannot fail");
    }

    out.push_str("];\n");
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn version_zero_returns_zero() {
        assert_eq!(version_string_to_int("0"), 0);
    }

    #[test]
    fn version_encoding() {
        assert_eq!(version_string_to_int("3.35.5"), 3_035_005);
        assert_eq!(version_string_to_int("3.30.1"), 3_030_001);
    }

    #[test]
    fn generate_from_minimal_json() {
        // OMIT_WINDOWFUNC is a parser flag; its new index is 19 (C compact 19).
        let json = r#"{"cflags":[{"name":"SQLITE_OMIT_WINDOWFUNC","since":"3.30.1","categories":["parser","functions"]}]}"#;
        let out = generate_cflag_entries(json).unwrap();
        assert!(
            out.contains("(\"SQLITE_OMIT_WINDOWFUNC\", 19, 3030001, &[\"parser\", \"functions\"])")
        );
    }

    #[test]
    fn math_functions_gets_non_parser_index() {
        // ENABLE_MATH_FUNCTIONS is non-parser; its index is 36 in the new scheme.
        let json = r#"{"cflags":[{"name":"SQLITE_ENABLE_MATH_FUNCTIONS","since":"3.35.5","categories":["functions"]}]}"#;
        let out = generate_cflag_entries(json).unwrap();
        assert!(out.contains("(\"SQLITE_ENABLE_MATH_FUNCTIONS\", 36, 3035005, &[\"functions\"])"));
    }
}
