// Copyright 2025 The syntaqlite Authors. All rights reserved.
// Licensed under the Apache License, Version 2.0.

//! Generates `cflags.rs` files for the `SqliteFlag` and `SqliteSyntaxFlag` enums.
//!
//! Both flag enums are generated from [`super::cflag_registry::CFLAG_REGISTRY`]:
//!
//! - `SqliteFlag` (42 variants) → `syntaqlite/src/sqlite/cflags.rs`
//! - `SqliteSyntaxFlag` (22 parser-only variants) → `syntaqlite-syntax/src/sqlite/cflags.rs`
//!
//! Each enum is self-describing: variants carry their own name, categories,
//! and `from_name` lookup via `impl` methods backed by internal `const` arrays.

use std::collections::HashMap;
use std::fmt::Write as _;

use super::cflag_registry::CFLAG_REGISTRY;
use super::pascal_case;

// ── Version map ───────────────────────────────────────────────────────────────

/// Load a `name → min_version_int` map from a `version_cflags.json` file.
///
/// The JSON must have the shape `{ "cflags": [{ "name": "...", "since": "3.x.y" }, ...] }`.
/// `"since": "0"` maps to `0`. Malformed or missing entries default to `0`.
///
/// # Errors
///
/// Returns an error if the file cannot be read or the JSON is invalid.
pub(crate) fn load_version_map(path: &str) -> Result<HashMap<String, u32>, String> {
    let content = std::fs::read_to_string(path).map_err(|e| format!("reading {path}: {e}"))?;
    let json: serde_json::Value =
        serde_json::from_str(&content).map_err(|e| format!("parsing {path}: {e}"))?;
    let mut map = HashMap::new();
    if let Some(cflags) = json.get("cflags").and_then(|v| v.as_array()) {
        for entry in cflags {
            let name = entry.get("name").and_then(|v| v.as_str()).unwrap_or("");
            let since = entry.get("since").and_then(|v| v.as_str()).unwrap_or("0");
            let version_int = parse_since(since);
            map.insert(name.to_string(), version_int);
        }
    }
    Ok(map)
}

fn parse_since(s: &str) -> u32 {
    if s == "0" {
        return 0;
    }
    let parts: Vec<u32> = s.split('.').filter_map(|p| p.parse().ok()).collect();
    match parts.as_slice() {
        [major, minor, patch] => major * 1_000_000 + minor * 1_000 + patch,
        _ => 0,
    }
}

// ── Version helpers ───────────────────────────────────────────────────────────

/// Map a version integer (e.g. `3030001`) to a `SqliteVersion::V3_NN` expression.
///
/// `0` (unknown/predates tracking) maps to the oldest tracked version (`V3_12`).
/// Only the major+minor components are used; patch is ignored.
fn version_to_variant(v: u32) -> String {
    if v == 0 {
        return "SqliteVersion::V3_12".to_string();
    }
    let minor = (v / 1_000) % 1_000;
    format!("SqliteVersion::V3_{minor}")
}

// ── Flag variant name ─────────────────────────────────────────────────────────

/// Derive the Rust `PascalCase` variant name from a `SQLITE_*` flag name.
///
/// Strips the `"SQLITE_"` prefix and applies `pascal_case`, e.g.
/// `"SQLITE_OMIT_WINDOWFUNC"` → `"OmitWindowfunc"`.
fn variant_name(sqlite_name: &str) -> String {
    let suffix = sqlite_name.strip_prefix("SQLITE_").unwrap_or(sqlite_name);
    pascal_case(suffix)
}

// ── SqliteFlag codegen ────────────────────────────────────────────────────────

/// Generate `syntaqlite/src/sqlite/cflags.rs` containing the `SqliteFlag` enum.
///
/// All 42 flags from [`CFLAG_REGISTRY`] are emitted in index order with
/// self-describing `impl` methods: `name()`, `categories()`, `from_name()`, `all()`,
/// and optionally `min_version_int()` when `version_map` is provided.
pub(crate) fn generate_sqlite_flag_rs(version_map: Option<&HashMap<String, u32>>) -> String {
    let mut out = String::new();
    out.push_str("// Copyright 2025 The syntaqlite Authors. All rights reserved.\n");
    out.push_str("// Licensed under the Apache License, Version 2.0.\n");
    out.push_str("// @generated by syntaqlite-buildtools — DO NOT EDIT\n\n");
    out.push_str("//! Compile-time feature flags for the `SQLite` dialect.\n\n");

    if version_map.is_some() {
        out.push_str("use syntaqlite_syntax::util::{SqliteSyntaxFlag, SqliteVersion};\n\n");
    } else {
        out.push_str("use syntaqlite_syntax::util::SqliteSyntaxFlag;\n\n");
    }
    out.push_str("/// A compile-time feature flag for the `SQLite` dialect.\n");
    out.push_str("///\n");
    out.push_str("/// Pass a variant to [`crate::util::SqliteFlags::has`],\n");
    out.push_str(
        "/// [`crate::util::SqliteFlags::with`], or [`crate::util::SqliteFlags::without`].\n",
    );
    out.push_str("#[repr(u32)]\n");
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub enum SqliteFlag {\n");
    for &(name, idx, _) in CFLAG_REGISTRY {
        let variant = variant_name(name);
        writeln!(out, "    /// `{name}`\n    {variant} = {idx},").expect("write to String");
    }
    out.push_str("}\n\n");

    out.push_str("impl SqliteFlag {\n");

    // ALL array
    out.push_str("    const ALL: &'static [Self] = &[\n");
    for &(name, _, _) in CFLAG_REGISTRY {
        writeln!(out, "        Self::{},", variant_name(name)).expect("write to String");
    }
    out.push_str("    ];\n\n");

    // NAMES array
    out.push_str("    const NAMES: &'static [&'static str] = &[\n");
    for &(name, _, _) in CFLAG_REGISTRY {
        writeln!(out, "        \"{name}\",").expect("write to String");
    }
    out.push_str("    ];\n\n");

    // CATEGORIES array
    out.push_str("    const CATEGORIES: &'static [&'static [&'static str]] = &[\n");
    for &(_, _, cats) in CFLAG_REGISTRY {
        let cats_str: Vec<String> = cats.iter().map(|c| format!("\"{c}\"")).collect();
        writeln!(out, "        &[{}],", cats_str.join(", ")).expect("write to String");
    }
    out.push_str("    ];\n\n");

    // MIN_VERSIONS array (only when version map is provided)
    if let Some(map) = version_map {
        out.push_str("    const MIN_VERSIONS: &'static [SqliteVersion] = &[\n");
        for &(name, _, _) in CFLAG_REGISTRY {
            let v = map.get(name).copied().unwrap_or(0);
            let variant = version_to_variant(v);
            writeln!(out, "        {variant}, // {name}").expect("write to String");
        }
        out.push_str("    ];\n\n");
    }

    out.push_str(
        r#"    /// The canonical `SQLITE_*` flag name (e.g. `"SQLITE_OMIT_WINDOWFUNC"`).
    pub fn name(self) -> &'static str {
        Self::NAMES[self as usize]
    }

    /// Which concerns this flag affects (e.g. `"parser"`, `"functions"`, `"vtable"`).
    pub fn categories(self) -> &'static [&'static str] {
        Self::CATEGORIES[self as usize]
    }

    /// Look up a flag by its canonical `SQLITE_*` name.
    ///
    /// Returns `None` if `s` is not a known flag name.
    pub fn from_name(s: &str) -> Option<Self> {
        Self::ALL.iter().copied().find(|f| f.name() == s)
    }

    /// All known flags in stable index order.
    pub fn all() -> &'static [Self] {
        Self::ALL
    }

"#,
    );

    // min_version() — only emitted when version map is provided
    if version_map.is_some() {
        out.push_str(
            r"    /// The minimum `SQLite` version at which this flag is known to exist.
    pub fn min_version(self) -> SqliteVersion {
        Self::MIN_VERSIONS[self as usize]
    }

",
        );
    }

    out.push_str(
        r"    /// The corresponding [`SqliteSyntaxFlag`], if this is a parser-level flag.
    pub(crate) fn as_syntax_flag(self) -> Option<SqliteSyntaxFlag> {
        match self {
",
    );
    // Emit one arm per parser-category flag; all others map to None.
    for &(name, _, cats) in CFLAG_REGISTRY {
        if cats.contains(&"parser") {
            let v = variant_name(name);
            writeln!(out, "            Self::{v} => Some(SqliteSyntaxFlag::{v}),")
                .expect("write to String");
        }
    }
    out.push_str("            _ => None,\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n");
    out
}

/// Write the `SqliteFlag` enum to `output_path`.
///
/// # Errors
///
/// Returns an error if writing fails.
pub(crate) fn write_sqlite_flag_rs(
    output_path: &str,
    version_map: Option<&HashMap<String, u32>>,
) -> Result<(), String> {
    use std::fs;
    use std::path::Path;
    let content = generate_sqlite_flag_rs(version_map);
    let out = Path::new(output_path);
    if let Some(parent) = out.parent() {
        fs::create_dir_all(parent).map_err(|e| format!("creating output directory: {e}"))?;
    }
    fs::write(out, content).map_err(|e| format!("writing {}: {e}", out.display()))?;
    eprintln!("wrote {output_path}");
    Ok(())
}

// ── SqliteSyntaxFlag codegen ──────────────────────────────────────────────────

/// Generate `syntaqlite-syntax/src/sqlite/cflags.rs` containing `SqliteSyntaxFlag`.
///
/// Only the 22 parser-category flags from [`CFLAG_REGISTRY`] are emitted,
/// in index order (discriminants 0–21 matching `SYNQ_CFLAG_IDX_*` in `cflags.h`).
pub(crate) fn generate_syntax_flag_rs() -> String {
    let parser_flags: Vec<(&str, u32)> = CFLAG_REGISTRY
        .iter()
        .filter(|(_, _, cats)| cats.contains(&"parser"))
        .map(|&(name, idx, _)| (name, idx))
        .collect();

    let mut out = String::new();
    out.push_str("// Copyright 2025 The syntaqlite Authors. All rights reserved.\n");
    out.push_str("// Licensed under the Apache License, Version 2.0.\n");
    out.push_str("// @generated by syntaqlite-buildtools — DO NOT EDIT\n\n");
    out.push_str("//! Parser-level compile-time flags for the `SQLite` dialect.\n\n");

    out.push_str("/// A parser-level compile-time feature flag for the `SQLite` dialect.\n");
    out.push_str("///\n");
    out.push_str("/// Each variant corresponds to a `SYNQ_CFLAG_IDX_*` constant in `cflags.h`.\n");
    out.push_str("/// The discriminant equals the C compact index (0–21).\n");
    out.push_str("///\n");
    out.push_str("/// Pass a variant to [`crate::util::SqliteSyntaxFlags::has`] or\n");
    out.push_str("/// [`crate::util::SqliteSyntaxFlags::with`].\n");
    out.push_str("///\n");
    out.push_str("/// For the full 42-flag set use `syntaqlite::util::SqliteFlag`.\n");
    out.push_str("#[repr(u32)]\n");
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub enum SqliteSyntaxFlag {\n");
    for &(name, idx) in &parser_flags {
        let variant = variant_name(name);
        writeln!(out, "    /// `{name}`\n    {variant} = {idx},").expect("write to String");
    }
    out.push_str("}\n\n");

    out.push_str("impl SqliteSyntaxFlag {\n");

    // ALL
    out.push_str("    const ALL: &'static [Self] = &[\n");
    for &(name, _) in &parser_flags {
        writeln!(out, "        Self::{},", variant_name(name)).expect("write to String");
    }
    out.push_str("    ];\n\n");

    // NAMES
    out.push_str("    const NAMES: &'static [&'static str] = &[\n");
    for &(name, _) in &parser_flags {
        writeln!(out, "        \"{name}\",").expect("write to String");
    }
    out.push_str("    ];\n\n");

    out.push_str(
        r#"    /// The canonical `SQLITE_*` flag name (e.g. `"SQLITE_OMIT_WINDOWFUNC"`).
    pub fn name(self) -> &'static str {
        Self::NAMES[self as usize]
    }

    /// Look up a parser flag by its canonical `SQLITE_*` name.
    ///
    /// Returns `None` if `s` is not a known parser flag name.
    pub fn from_name(s: &str) -> Option<Self> {
        Self::ALL.iter().copied().find(|f| f.name() == s)
    }

}

"#,
    );
    out
}

/// Write the `SqliteSyntaxFlag` enum to `output_path`.
///
/// # Errors
///
/// Returns an error if writing fails.
pub(crate) fn write_syntax_flag_rs(output_path: &str) -> Result<(), String> {
    use std::fs;
    use std::path::Path;
    let content = generate_syntax_flag_rs();
    let out = Path::new(output_path);
    if let Some(parent) = out.parent() {
        fs::create_dir_all(parent).map_err(|e| format!("creating output directory: {e}"))?;
    }
    fs::write(out, content).map_err(|e| format!("writing {}: {e}", out.display()))?;
    eprintln!("wrote {output_path}");
    Ok(())
}
