// Copyright 2025 The syntaqlite Authors. All rights reserved.
// Licensed under the Apache License, Version 2.0.

//! Shared utility helpers used by codegen modules.

pub mod c_extractor;
pub mod c_transformer;
pub mod grammar_parser;

pub mod synq_parser;

pub(crate) mod self_subcommand;

pub(crate) mod text_writer;

pub(crate) mod c_writer;

pub(crate) mod rust_writer;

pub(crate) mod tool_run;

pub(crate) mod mkkeywordhash_parser;

/// Convert PascalCase to snake_case.
pub fn pascal_to_snake(name: &str) -> String {
    let mut out = String::new();
    for (i, c) in name.chars().enumerate() {
        if c.is_uppercase() && i > 0 {
            out.push('_');
        }
        out.push(c.to_ascii_lowercase());
    }
    out
}

/// Convert PascalCase to UPPER_SNAKE_CASE.
pub fn upper_snake(name: &str) -> String {
    pascal_to_snake(name).to_uppercase()
}

/// Marker string embedded in generated files.
pub const AUTOGENERATED_MARKER: &str = "@generated by syntaqlite-buildtools — DO NOT EDIT";

pub mod functions_codegen;

/// Convert snake_case to PascalCase.
pub fn pascal_case(s: &str) -> String {
    s.split('_')
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(c) => c.to_uppercase().to_string() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}
