// Copyright 2025 The syntaqlite Authors. All rights reserved.
// Licensed under the Apache License, Version 2.0.

// Top-level configuration for syntaqlite.
//
// Usage:
//   // Pure defaults:
//   SyntaqliteConfig config = SYNTAQLITE_CONFIG_DEFAULT;
//   SyntaqliteTokenizer* tok = syntaqlite_tokenizer_create(&config);
//
//   // Custom allocator:
//   SyntaqliteConfig config = SYNTAQLITE_CONFIG_DEFAULT;
//   config.mem.xMalloc = my_malloc;
//   config.mem.xFree = my_free;
//
//   // Parser with tracing:
//   SyntaqliteConfig config = SYNTAQLITE_CONFIG_DEFAULT;
//   config.parser.trace = 1;
//   SyntaqliteParser* p = syntaqlite_parser_create(&config);
//
//   // Dialect extension (static linking):
//   SyntaqliteConfig config = SYNTAQLITE_CONFIG_DEFAULT;
//   config.extension = libsql_dialect_extension();
//
//   // Dialect extension (dynamic loading):
//   SyntaqliteConfig config = SYNTAQLITE_CONFIG_DEFAULT;
//   config.extension = syntaqlite_load_extension("./libsql_dialect.so", NULL);
//
// ABI stability:
//   Always initialize with SYNTAQLITE_CONFIG_DEFAULT. New fields are only ever
//   appended at the end of each struct. The sz fields record struct sizes the
//   caller was compiled against. When syntaqlite sees a smaller sz than it
//   expects, it knows the caller predates the newer fields and uses safe
//   defaults for them. This means you can upgrade syntaqlite without
//   recompiling your code.

#ifndef SYNTAQLITE_CONFIG_H
#define SYNTAQLITE_CONFIG_H

#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

// Custom allocator for all syntaqlite-internal allocations. Both fields must
// be set together — setting only one is an error. When both are NULL (the
// default), syntaqlite uses the standard malloc/free.
typedef struct SyntaqliteMemMethods {
  void* (*xMalloc)(size_t);  // Allocate size bytes. Must not return NULL.
  void (*xFree)(void*);      // Free a pointer returned by xMalloc.
} SyntaqliteMemMethods;

// Opaque handle to a dialect extension (extra keywords, grammar rules, AST
// node types) generated by the syntaqlite codegen tooling. Extensions are
// additive — the base SQLite grammar is always included.
typedef struct SyntaqliteDialectExtension SyntaqliteDialectExtension;

// --- Tokenizer config ---

// Tokenizer-specific options. Currently reserved for future use.
typedef struct SyntaqliteTokenizerConfig {
  size_t sz;  // sizeof(SyntaqliteTokenizerConfig). Do not modify.
  // --- new fields go here ---
} SyntaqliteTokenizerConfig;

#define SYNTAQLITE_TOKENIZER_CONFIG_DEFAULT {sizeof(SyntaqliteTokenizerConfig)}

// --- Parser config ---

// Parser-specific options. The parser uses a tokenizer internally, so the
// tokenizer config is embedded here.
typedef struct SyntaqliteParserConfig {
  size_t sz;  // sizeof(SyntaqliteParserConfig). Do not modify.

  // Tokenizer options used by the parser's internal tokenizer.
  SyntaqliteTokenizerConfig tokenizer;

  // If nonzero, record every token so the formatter can reconstruct comments
  // and whitespace. Required before calling syntaqlite_format_stmt().
  int collect_tokens;

  // If nonzero, enable Lemon parser tracing on stderr (debug builds only;
  // ignored in release).
  int trace;

  // --- new fields go here ---
} SyntaqliteParserConfig;

#define SYNTAQLITE_PARSER_CONFIG_DEFAULT \
  {sizeof(SyntaqliteParserConfig), SYNTAQLITE_TOKENIZER_CONFIG_DEFAULT, 0, 0}

// --- Top-level config ---

// Top-level configuration struct. Always initialize with
// SYNTAQLITE_CONFIG_DEFAULT, then override individual fields as needed. Do not
// zero-initialize or memset — the sz fields must be set correctly for ABI
// compatibility.
typedef struct SyntaqliteConfig {
  // Size of this struct as seen by the caller. Set automatically by
  // SYNTAQLITE_CONFIG_DEFAULT. Do not modify.
  size_t sz;

  // Custom allocator. Leave as {NULL, NULL} to use malloc/free.
  SyntaqliteMemMethods mem;

  // Dialect extension. NULL means pure SQLite grammar.
  const SyntaqliteDialectExtension* extension;

  // Tokenizer-specific options.
  SyntaqliteTokenizerConfig tokenizer;

  // Parser-specific options (includes its own tokenizer config).
  SyntaqliteParserConfig parser;

  // --- new fields go here ---
} SyntaqliteConfig;

// Default initializer. Always use this to create a SyntaqliteConfig.
#define SYNTAQLITE_CONFIG_DEFAULT                                           \
  {sizeof(SyntaqliteConfig), {NULL, NULL}, NULL,                            \
   SYNTAQLITE_TOKENIZER_CONFIG_DEFAULT, SYNTAQLITE_PARSER_CONFIG_DEFAULT}

// --- Extension loading ---

// Load a dialect extension from a shared library at runtime.
//
// lib_path:    Path to the .so/.dylib/.dll containing the extension.
// entry_point: Name of the entry-point symbol. NULL uses the default
//              convention: the library's basename with "_dialect_extension"
//              appended (e.g. "libsql_dialect.so" →
//              "libsql_dialect_extension").
//
// Returns a pointer to the extension, or NULL on failure.
const SyntaqliteDialectExtension* syntaqlite_load_extension(
    const char* lib_path,
    const char* entry_point);

#ifdef __cplusplus
}
#endif

#endif  // SYNTAQLITE_CONFIG_H
