// Copyright 2025 The syntaqlite Authors. All rights reserved.
// Licensed under the Apache License, Version 2.0.
//
// @generated by syntaqlite-buildtools — DO NOT EDIT

#![allow(clippy::type_complexity, missing_docs)]

use crate::ast::{AnyNodeId, GrammarNodeType, TypedNodeList};
use crate::grammar::TypedGrammar;

/// Base variants of `LiteralType`. Used for exhaustive pattern matching in generic code.
/// Grammar extensions that add variants beyond this set return `None` from `LiteralTypeLike::kind`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LiteralTypeKind {
    Integer,
    Float,
    String,
    Blob,
    Null,
    Current,
    Qnumber,
}

/// Trait for `LiteralType`-compatible values. Dialects may define their own type and implement this.
pub trait LiteralTypeLike: Copy + PartialEq + Eq + std::fmt::Debug {
    fn as_str(&self) -> &'static str;
    /// Match against base `LiteralTypeKind` variants. Returns `None` for dialect-specific extensions.
    fn kind(&self) -> Option<LiteralTypeKind>;
}

/// Base variants of `BinaryOp`. Used for exhaustive pattern matching in generic code.
/// Grammar extensions that add variants beyond this set return `None` from `BinaryOpLike::kind`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BinaryOpKind {
    Plus,
    Minus,
    Star,
    Slash,
    Rem,
    Lt,
    Gt,
    Le,
    Ge,
    Eq,
    Ne,
    And,
    Or,
    BitAnd,
    BitOr,
    Lshift,
    Rshift,
    Concat,
    Ptr,
}

/// Trait for `BinaryOp`-compatible values. Dialects may define their own type and implement this.
pub trait BinaryOpLike: Copy + PartialEq + Eq + std::fmt::Debug {
    fn as_str(&self) -> &'static str;
    /// Match against base `BinaryOpKind` variants. Returns `None` for dialect-specific extensions.
    fn kind(&self) -> Option<BinaryOpKind>;
}

/// Base variants of `UnaryOp`. Used for exhaustive pattern matching in generic code.
/// Grammar extensions that add variants beyond this set return `None` from `UnaryOpLike::kind`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum UnaryOpKind {
    Minus,
    Plus,
    BitNot,
    Not,
}

/// Trait for `UnaryOp`-compatible values. Dialects may define their own type and implement this.
pub trait UnaryOpLike: Copy + PartialEq + Eq + std::fmt::Debug {
    fn as_str(&self) -> &'static str;
    /// Match against base `UnaryOpKind` variants. Returns `None` for dialect-specific extensions.
    fn kind(&self) -> Option<UnaryOpKind>;
}

/// Base variants of `CompoundOp`. Used for exhaustive pattern matching in generic code.
/// Grammar extensions that add variants beyond this set return `None` from `CompoundOpLike::kind`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CompoundOpKind {
    Union,
    UnionAll,
    Intersect,
    Except,
}

/// Trait for `CompoundOp`-compatible values. Dialects may define their own type and implement this.
pub trait CompoundOpLike: Copy + PartialEq + Eq + std::fmt::Debug {
    fn as_str(&self) -> &'static str;
    /// Match against base `CompoundOpKind` variants. Returns `None` for dialect-specific extensions.
    fn kind(&self) -> Option<CompoundOpKind>;
}

/// Base variants of `IsOp`. Used for exhaustive pattern matching in generic code.
/// Grammar extensions that add variants beyond this set return `None` from `IsOpLike::kind`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum IsOpKind {
    Is,
    IsNot,
    IsNull,
    NotNull,
    IsNotDistinct,
    IsDistinct,
}

/// Trait for `IsOp`-compatible values. Dialects may define their own type and implement this.
pub trait IsOpLike: Copy + PartialEq + Eq + std::fmt::Debug {
    fn as_str(&self) -> &'static str;
    /// Match against base `IsOpKind` variants. Returns `None` for dialect-specific extensions.
    fn kind(&self) -> Option<IsOpKind>;
}

/// Base variants of `ForeignKeyAction`. Used for exhaustive pattern matching in generic code.
/// Grammar extensions that add variants beyond this set return `None` from `ForeignKeyActionLike::kind`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ForeignKeyActionKind {
    NoAction,
    SetNull,
    SetDefault,
    Cascade,
    Restrict,
}

/// Trait for `ForeignKeyAction`-compatible values. Dialects may define their own type and implement this.
pub trait ForeignKeyActionLike: Copy + PartialEq + Eq + std::fmt::Debug {
    fn as_str(&self) -> &'static str;
    /// Match against base `ForeignKeyActionKind` variants. Returns `None` for dialect-specific extensions.
    fn kind(&self) -> Option<ForeignKeyActionKind>;
}

/// Base variants of `GeneratedColumnStorage`. Used for exhaustive pattern matching in generic code.
/// Grammar extensions that add variants beyond this set return `None` from `GeneratedColumnStorageLike::kind`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum GeneratedColumnStorageKind {
    Virtual,
    Stored,
}

/// Trait for `GeneratedColumnStorage`-compatible values. Dialects may define their own type and implement this.
pub trait GeneratedColumnStorageLike: Copy + PartialEq + Eq + std::fmt::Debug {
    fn as_str(&self) -> &'static str;
    /// Match against base `GeneratedColumnStorageKind` variants. Returns `None` for dialect-specific extensions.
    fn kind(&self) -> Option<GeneratedColumnStorageKind>;
}

/// Base variants of `ColumnConstraintType`. Used for exhaustive pattern matching in generic code.
/// Grammar extensions that add variants beyond this set return `None` from `ColumnConstraintTypeLike::kind`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ColumnConstraintTypeKind {
    Default,
    NotNull,
    PrimaryKey,
    Unique,
    Check,
    References,
    Collate,
    Generated,
    Null,
}

/// Trait for `ColumnConstraintType`-compatible values. Dialects may define their own type and implement this.
pub trait ColumnConstraintTypeLike: Copy + PartialEq + Eq + std::fmt::Debug {
    fn as_str(&self) -> &'static str;
    /// Match against base `ColumnConstraintTypeKind` variants. Returns `None` for dialect-specific extensions.
    fn kind(&self) -> Option<ColumnConstraintTypeKind>;
}

/// Base variants of `TableConstraintType`. Used for exhaustive pattern matching in generic code.
/// Grammar extensions that add variants beyond this set return `None` from `TableConstraintTypeLike::kind`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TableConstraintTypeKind {
    PrimaryKey,
    Unique,
    Check,
    ForeignKey,
}

/// Trait for `TableConstraintType`-compatible values. Dialects may define their own type and implement this.
pub trait TableConstraintTypeLike: Copy + PartialEq + Eq + std::fmt::Debug {
    fn as_str(&self) -> &'static str;
    /// Match against base `TableConstraintTypeKind` variants. Returns `None` for dialect-specific extensions.
    fn kind(&self) -> Option<TableConstraintTypeKind>;
}

/// Base variants of `Materialized`. Used for exhaustive pattern matching in generic code.
/// Grammar extensions that add variants beyond this set return `None` from `MaterializedLike::kind`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MaterializedKind {
    Default,
    Materialized,
    NotMaterialized,
}

/// Trait for `Materialized`-compatible values. Dialects may define their own type and implement this.
pub trait MaterializedLike: Copy + PartialEq + Eq + std::fmt::Debug {
    fn as_str(&self) -> &'static str;
    /// Match against base `MaterializedKind` variants. Returns `None` for dialect-specific extensions.
    fn kind(&self) -> Option<MaterializedKind>;
}

/// Base variants of `ConflictAction`. Used for exhaustive pattern matching in generic code.
/// Grammar extensions that add variants beyond this set return `None` from `ConflictActionLike::kind`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ConflictActionKind {
    Default,
    Rollback,
    Abort,
    Fail,
    Ignore,
    Replace,
}

/// Trait for `ConflictAction`-compatible values. Dialects may define their own type and implement this.
pub trait ConflictActionLike: Copy + PartialEq + Eq + std::fmt::Debug {
    fn as_str(&self) -> &'static str;
    /// Match against base `ConflictActionKind` variants. Returns `None` for dialect-specific extensions.
    fn kind(&self) -> Option<ConflictActionKind>;
}

/// Base variants of `RaiseType`. Used for exhaustive pattern matching in generic code.
/// Grammar extensions that add variants beyond this set return `None` from `RaiseTypeLike::kind`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RaiseTypeKind {
    Ignore,
    Rollback,
    Abort,
    Fail,
}

/// Trait for `RaiseType`-compatible values. Dialects may define their own type and implement this.
pub trait RaiseTypeLike: Copy + PartialEq + Eq + std::fmt::Debug {
    fn as_str(&self) -> &'static str;
    /// Match against base `RaiseTypeKind` variants. Returns `None` for dialect-specific extensions.
    fn kind(&self) -> Option<RaiseTypeKind>;
}

/// Base variants of `DropObjectType`. Used for exhaustive pattern matching in generic code.
/// Grammar extensions that add variants beyond this set return `None` from `DropObjectTypeLike::kind`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DropObjectTypeKind {
    Table,
    Index,
    View,
    Trigger,
}

/// Trait for `DropObjectType`-compatible values. Dialects may define their own type and implement this.
pub trait DropObjectTypeLike: Copy + PartialEq + Eq + std::fmt::Debug {
    fn as_str(&self) -> &'static str;
    /// Match against base `DropObjectTypeKind` variants. Returns `None` for dialect-specific extensions.
    fn kind(&self) -> Option<DropObjectTypeKind>;
}

/// Base variants of `AlterOp`. Used for exhaustive pattern matching in generic code.
/// Grammar extensions that add variants beyond this set return `None` from `AlterOpLike::kind`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AlterOpKind {
    RenameTable,
    RenameColumn,
    DropColumn,
    AddColumn,
}

/// Trait for `AlterOp`-compatible values. Dialects may define their own type and implement this.
pub trait AlterOpLike: Copy + PartialEq + Eq + std::fmt::Debug {
    fn as_str(&self) -> &'static str;
    /// Match against base `AlterOpKind` variants. Returns `None` for dialect-specific extensions.
    fn kind(&self) -> Option<AlterOpKind>;
}

/// Base variants of `TransactionType`. Used for exhaustive pattern matching in generic code.
/// Grammar extensions that add variants beyond this set return `None` from `TransactionTypeLike::kind`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TransactionTypeKind {
    Deferred,
    Immediate,
    Exclusive,
}

/// Trait for `TransactionType`-compatible values. Dialects may define their own type and implement this.
pub trait TransactionTypeLike: Copy + PartialEq + Eq + std::fmt::Debug {
    fn as_str(&self) -> &'static str;
    /// Match against base `TransactionTypeKind` variants. Returns `None` for dialect-specific extensions.
    fn kind(&self) -> Option<TransactionTypeKind>;
}

/// Base variants of `TransactionOp`. Used for exhaustive pattern matching in generic code.
/// Grammar extensions that add variants beyond this set return `None` from `TransactionOpLike::kind`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TransactionOpKind {
    Begin,
    Commit,
    Rollback,
}

/// Trait for `TransactionOp`-compatible values. Dialects may define their own type and implement this.
pub trait TransactionOpLike: Copy + PartialEq + Eq + std::fmt::Debug {
    fn as_str(&self) -> &'static str;
    /// Match against base `TransactionOpKind` variants. Returns `None` for dialect-specific extensions.
    fn kind(&self) -> Option<TransactionOpKind>;
}

/// Base variants of `SavepointOp`. Used for exhaustive pattern matching in generic code.
/// Grammar extensions that add variants beyond this set return `None` from `SavepointOpLike::kind`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SavepointOpKind {
    Savepoint,
    Release,
    RollbackTo,
}

/// Trait for `SavepointOp`-compatible values. Dialects may define their own type and implement this.
pub trait SavepointOpLike: Copy + PartialEq + Eq + std::fmt::Debug {
    fn as_str(&self) -> &'static str;
    /// Match against base `SavepointOpKind` variants. Returns `None` for dialect-specific extensions.
    fn kind(&self) -> Option<SavepointOpKind>;
}

/// Base variants of `SortOrder`. Used for exhaustive pattern matching in generic code.
/// Grammar extensions that add variants beyond this set return `None` from `SortOrderLike::kind`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SortOrderKind {
    Asc,
    Desc,
}

/// Trait for `SortOrder`-compatible values. Dialects may define their own type and implement this.
pub trait SortOrderLike: Copy + PartialEq + Eq + std::fmt::Debug {
    fn as_str(&self) -> &'static str;
    /// Match against base `SortOrderKind` variants. Returns `None` for dialect-specific extensions.
    fn kind(&self) -> Option<SortOrderKind>;
}

/// Base variants of `NullsOrder`. Used for exhaustive pattern matching in generic code.
/// Grammar extensions that add variants beyond this set return `None` from `NullsOrderLike::kind`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum NullsOrderKind {
    None,
    First,
    Last,
}

/// Trait for `NullsOrder`-compatible values. Dialects may define their own type and implement this.
pub trait NullsOrderLike: Copy + PartialEq + Eq + std::fmt::Debug {
    fn as_str(&self) -> &'static str;
    /// Match against base `NullsOrderKind` variants. Returns `None` for dialect-specific extensions.
    fn kind(&self) -> Option<NullsOrderKind>;
}

/// Base variants of `JoinType`. Used for exhaustive pattern matching in generic code.
/// Grammar extensions that add variants beyond this set return `None` from `JoinTypeLike::kind`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum JoinTypeKind {
    Comma,
    Inner,
    Left,
    Right,
    Full,
    Cross,
    NaturalInner,
    NaturalLeft,
    NaturalRight,
    NaturalFull,
}

/// Trait for `JoinType`-compatible values. Dialects may define their own type and implement this.
pub trait JoinTypeLike: Copy + PartialEq + Eq + std::fmt::Debug {
    fn as_str(&self) -> &'static str;
    /// Match against base `JoinTypeKind` variants. Returns `None` for dialect-specific extensions.
    fn kind(&self) -> Option<JoinTypeKind>;
}

/// Base variants of `TriggerTiming`. Used for exhaustive pattern matching in generic code.
/// Grammar extensions that add variants beyond this set return `None` from `TriggerTimingLike::kind`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TriggerTimingKind {
    Before,
    After,
    InsteadOf,
}

/// Trait for `TriggerTiming`-compatible values. Dialects may define their own type and implement this.
pub trait TriggerTimingLike: Copy + PartialEq + Eq + std::fmt::Debug {
    fn as_str(&self) -> &'static str;
    /// Match against base `TriggerTimingKind` variants. Returns `None` for dialect-specific extensions.
    fn kind(&self) -> Option<TriggerTimingKind>;
}

/// Base variants of `TriggerEventType`. Used for exhaustive pattern matching in generic code.
/// Grammar extensions that add variants beyond this set return `None` from `TriggerEventTypeLike::kind`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TriggerEventTypeKind {
    Delete,
    Insert,
    Update,
}

/// Trait for `TriggerEventType`-compatible values. Dialects may define their own type and implement this.
pub trait TriggerEventTypeLike: Copy + PartialEq + Eq + std::fmt::Debug {
    fn as_str(&self) -> &'static str;
    /// Match against base `TriggerEventTypeKind` variants. Returns `None` for dialect-specific extensions.
    fn kind(&self) -> Option<TriggerEventTypeKind>;
}

/// Base variants of `ExplainMode`. Used for exhaustive pattern matching in generic code.
/// Grammar extensions that add variants beyond this set return `None` from `ExplainModeLike::kind`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ExplainModeKind {
    Explain,
    QueryPlan,
}

/// Trait for `ExplainMode`-compatible values. Dialects may define their own type and implement this.
pub trait ExplainModeLike: Copy + PartialEq + Eq + std::fmt::Debug {
    fn as_str(&self) -> &'static str;
    /// Match against base `ExplainModeKind` variants. Returns `None` for dialect-specific extensions.
    fn kind(&self) -> Option<ExplainModeKind>;
}

/// Base variants of `PragmaForm`. Used for exhaustive pattern matching in generic code.
/// Grammar extensions that add variants beyond this set return `None` from `PragmaFormLike::kind`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PragmaFormKind {
    Bare,
    Eq,
    Call,
}

/// Trait for `PragmaForm`-compatible values. Dialects may define their own type and implement this.
pub trait PragmaFormLike: Copy + PartialEq + Eq + std::fmt::Debug {
    fn as_str(&self) -> &'static str;
    /// Match against base `PragmaFormKind` variants. Returns `None` for dialect-specific extensions.
    fn kind(&self) -> Option<PragmaFormKind>;
}

/// Base variants of `AnalyzeOrReindexOp`. Used for exhaustive pattern matching in generic code.
/// Grammar extensions that add variants beyond this set return `None` from `AnalyzeOrReindexOpLike::kind`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AnalyzeOrReindexOpKind {
    Analyze,
    Reindex,
}

/// Trait for `AnalyzeOrReindexOp`-compatible values. Dialects may define their own type and implement this.
pub trait AnalyzeOrReindexOpLike: Copy + PartialEq + Eq + std::fmt::Debug {
    fn as_str(&self) -> &'static str;
    /// Match against base `AnalyzeOrReindexOpKind` variants. Returns `None` for dialect-specific extensions.
    fn kind(&self) -> Option<AnalyzeOrReindexOpKind>;
}

/// Base variants of `FrameType`. Used for exhaustive pattern matching in generic code.
/// Grammar extensions that add variants beyond this set return `None` from `FrameTypeLike::kind`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FrameTypeKind {
    None,
    Range,
    Rows,
    Groups,
}

/// Trait for `FrameType`-compatible values. Dialects may define their own type and implement this.
pub trait FrameTypeLike: Copy + PartialEq + Eq + std::fmt::Debug {
    fn as_str(&self) -> &'static str;
    /// Match against base `FrameTypeKind` variants. Returns `None` for dialect-specific extensions.
    fn kind(&self) -> Option<FrameTypeKind>;
}

/// Base variants of `FrameBoundType`. Used for exhaustive pattern matching in generic code.
/// Grammar extensions that add variants beyond this set return `None` from `FrameBoundTypeLike::kind`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FrameBoundTypeKind {
    UnboundedPreceding,
    ExprPreceding,
    CurrentRow,
    ExprFollowing,
    UnboundedFollowing,
}

/// Trait for `FrameBoundType`-compatible values. Dialects may define their own type and implement this.
pub trait FrameBoundTypeLike: Copy + PartialEq + Eq + std::fmt::Debug {
    fn as_str(&self) -> &'static str;
    /// Match against base `FrameBoundTypeKind` variants. Returns `None` for dialect-specific extensions.
    fn kind(&self) -> Option<FrameBoundTypeKind>;
}

/// Base variants of `FrameExclude`. Used for exhaustive pattern matching in generic code.
/// Grammar extensions that add variants beyond this set return `None` from `FrameExcludeLike::kind`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FrameExcludeKind {
    None,
    NoOthers,
    CurrentRow,
    Group,
    Ties,
}

/// Trait for `FrameExclude`-compatible values. Dialects may define their own type and implement this.
pub trait FrameExcludeLike: Copy + PartialEq + Eq + std::fmt::Debug {
    fn as_str(&self) -> &'static str;
    /// Match against base `FrameExcludeKind` variants. Returns `None` for dialect-specific extensions.
    fn kind(&self) -> Option<FrameExcludeKind>;
}

/// Trait for `AggregateFunctionCallFlags`-compatible flags. Dialects may define their own type and implement this.
pub trait AggregateFunctionCallFlagsLike:
    Copy + PartialEq + Eq + Default + std::fmt::Debug
{
    fn distinct(&self) -> bool;
}

/// Trait for `CreateTableStmtFlags`-compatible flags. Dialects may define their own type and implement this.
pub trait CreateTableStmtFlagsLike: Copy + PartialEq + Eq + Default + std::fmt::Debug {
    fn without_rowid(&self) -> bool;
    fn strict(&self) -> bool;
}

/// Trait for `FunctionCallFlags`-compatible flags. Dialects may define their own type and implement this.
pub trait FunctionCallFlagsLike: Copy + PartialEq + Eq + Default + std::fmt::Debug {
    fn distinct(&self) -> bool;
    fn star(&self) -> bool;
}

/// Trait for `ResultColumnFlags`-compatible flags. Dialects may define their own type and implement this.
pub trait ResultColumnFlagsLike: Copy + PartialEq + Eq + Default + std::fmt::Debug {
    fn star(&self) -> bool;
}

/// Trait for `SelectStmtFlags`-compatible flags. Dialects may define their own type and implement this.
pub trait SelectStmtFlagsLike: Copy + PartialEq + Eq + Default + std::fmt::Debug {
    fn distinct(&self) -> bool;
}

/// Trait for the generic `Node` enum wrapper.
pub trait NodeLike<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
}

/// Accessor trait for `AggregateFunctionCall` nodes.
pub trait AggregateFunctionCallView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn func_name(&self) -> &'a str;
    fn flags(&self) -> <Self::Ast as AstTypes<'a>>::AggregateFunctionCallFlags;
    fn args(
        &self,
    ) -> Option<
        TypedNodeList<'a, <Self::Ast as AstTypes<'a>>::Grammar, <Self::Ast as AstTypes<'a>>::Expr>,
    >;
    fn orderby(
        &self,
    ) -> Option<
        TypedNodeList<
            'a,
            <Self::Ast as AstTypes<'a>>::Grammar,
            <Self::Ast as AstTypes<'a>>::OrderingTerm,
        >,
    >;
    fn filter_clause(&self) -> Option<<Self::Ast as AstTypes<'a>>::Expr>;
    fn over_clause(&self) -> Option<<Self::Ast as AstTypes<'a>>::WindowDef>;
}

/// Accessor trait for `OrderedSetFunctionCall` nodes.
pub trait OrderedSetFunctionCallView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn func_name(&self) -> &'a str;
    fn flags(&self) -> <Self::Ast as AstTypes<'a>>::AggregateFunctionCallFlags;
    fn args(
        &self,
    ) -> Option<
        TypedNodeList<'a, <Self::Ast as AstTypes<'a>>::Grammar, <Self::Ast as AstTypes<'a>>::Expr>,
    >;
    fn orderby_expr(&self) -> Option<<Self::Ast as AstTypes<'a>>::Expr>;
    fn filter_clause(&self) -> Option<<Self::Ast as AstTypes<'a>>::Expr>;
    fn over_clause(&self) -> Option<<Self::Ast as AstTypes<'a>>::WindowDef>;
}

/// Accessor trait for `CastExpr` nodes.
pub trait CastExprView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn expr(&self) -> Option<<Self::Ast as AstTypes<'a>>::Expr>;
    fn type_name(&self) -> &'a str;
}

/// Accessor trait for `ColumnRef` nodes.
pub trait ColumnRefView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn column(&self) -> &'a str;
    fn table(&self) -> &'a str;
    fn schema(&self) -> &'a str;
}

/// Accessor trait for `CompoundSelect` nodes.
pub trait CompoundSelectView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn op(&self) -> <Self::Ast as AstTypes<'a>>::CompoundOp;
    fn left(&self) -> Option<<Self::Ast as AstTypes<'a>>::Select>;
    fn right(&self) -> Option<<Self::Ast as AstTypes<'a>>::Select>;
}

/// Accessor trait for `SubqueryExpr` nodes.
pub trait SubqueryExprView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn select(&self) -> Option<<Self::Ast as AstTypes<'a>>::Select>;
}

/// Accessor trait for `ExistsExpr` nodes.
pub trait ExistsExprView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn select(&self) -> Option<<Self::Ast as AstTypes<'a>>::Select>;
}

/// Accessor trait for `InExpr` nodes.
pub trait InExprView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn negated(&self) -> bool;
    fn operand(&self) -> Option<<Self::Ast as AstTypes<'a>>::Expr>;
    fn source(&self) -> Option<<Self::Ast as AstTypes<'a>>::InExprSource>;
}

/// Accessor trait for `IsExpr` nodes.
pub trait IsExprView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn op(&self) -> <Self::Ast as AstTypes<'a>>::IsOp;
    fn left(&self) -> Option<<Self::Ast as AstTypes<'a>>::Expr>;
    fn right(&self) -> Option<<Self::Ast as AstTypes<'a>>::Expr>;
}

/// Accessor trait for `BetweenExpr` nodes.
pub trait BetweenExprView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn negated(&self) -> bool;
    fn operand(&self) -> Option<<Self::Ast as AstTypes<'a>>::Expr>;
    fn low(&self) -> Option<<Self::Ast as AstTypes<'a>>::Expr>;
    fn high(&self) -> Option<<Self::Ast as AstTypes<'a>>::Expr>;
}

/// Accessor trait for `LikeExpr` nodes.
pub trait LikeExprView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn negated(&self) -> bool;
    fn operand(&self) -> Option<<Self::Ast as AstTypes<'a>>::Expr>;
    fn pattern(&self) -> Option<<Self::Ast as AstTypes<'a>>::Expr>;
    fn escape(&self) -> Option<<Self::Ast as AstTypes<'a>>::Expr>;
}

/// Accessor trait for `CaseExpr` nodes.
pub trait CaseExprView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn operand(&self) -> Option<<Self::Ast as AstTypes<'a>>::Expr>;
    fn else_expr(&self) -> Option<<Self::Ast as AstTypes<'a>>::Expr>;
    fn whens(
        &self,
    ) -> Option<
        TypedNodeList<
            'a,
            <Self::Ast as AstTypes<'a>>::Grammar,
            <Self::Ast as AstTypes<'a>>::CaseWhen,
        >,
    >;
}

/// Accessor trait for `CaseWhen` nodes.
pub trait CaseWhenView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn when_expr(&self) -> Option<<Self::Ast as AstTypes<'a>>::Expr>;
    fn then_expr(&self) -> Option<<Self::Ast as AstTypes<'a>>::Expr>;
}

/// Accessor trait for `ForeignKeyClause` nodes.
pub trait ForeignKeyClauseView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn ref_table(&self) -> &'a str;
    fn ref_columns(
        &self,
    ) -> Option<
        TypedNodeList<'a, <Self::Ast as AstTypes<'a>>::Grammar, <Self::Ast as AstTypes<'a>>::Expr>,
    >;
    fn on_delete(&self) -> <Self::Ast as AstTypes<'a>>::ForeignKeyAction;
    fn on_update(&self) -> <Self::Ast as AstTypes<'a>>::ForeignKeyAction;
    fn is_deferred(&self) -> bool;
}

/// Accessor trait for `ColumnConstraint` nodes.
pub trait ColumnConstraintView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn kind(&self) -> <Self::Ast as AstTypes<'a>>::ColumnConstraintType;
    fn constraint_name(&self) -> &'a str;
    fn onconf(&self) -> <Self::Ast as AstTypes<'a>>::ConflictAction;
    fn sort_order(&self) -> <Self::Ast as AstTypes<'a>>::SortOrder;
    fn is_autoincrement(&self) -> bool;
    fn collation_name(&self) -> &'a str;
    fn generated_storage(&self) -> <Self::Ast as AstTypes<'a>>::GeneratedColumnStorage;
    fn default_expr(&self) -> Option<<Self::Ast as AstTypes<'a>>::Expr>;
    fn check_expr(&self) -> Option<<Self::Ast as AstTypes<'a>>::Expr>;
    fn generated_expr(&self) -> Option<<Self::Ast as AstTypes<'a>>::Expr>;
    fn fk_clause(&self) -> Option<<Self::Ast as AstTypes<'a>>::ForeignKeyClause>;
}

/// Accessor trait for `ColumnDef` nodes.
pub trait ColumnDefView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn column_name(&self) -> &'a str;
    fn type_name(&self) -> &'a str;
    fn constraints(
        &self,
    ) -> Option<
        TypedNodeList<
            'a,
            <Self::Ast as AstTypes<'a>>::Grammar,
            <Self::Ast as AstTypes<'a>>::ColumnConstraint,
        >,
    >;
}

/// Accessor trait for `TableConstraint` nodes.
pub trait TableConstraintView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn kind(&self) -> <Self::Ast as AstTypes<'a>>::TableConstraintType;
    fn constraint_name(&self) -> &'a str;
    fn onconf(&self) -> <Self::Ast as AstTypes<'a>>::ConflictAction;
    fn is_autoincrement(&self) -> bool;
    fn pk_columns(
        &self,
    ) -> Option<
        TypedNodeList<
            'a,
            <Self::Ast as AstTypes<'a>>::Grammar,
            <Self::Ast as AstTypes<'a>>::OrderingTerm,
        >,
    >;
    fn fk_columns(
        &self,
    ) -> Option<
        TypedNodeList<'a, <Self::Ast as AstTypes<'a>>::Grammar, <Self::Ast as AstTypes<'a>>::Expr>,
    >;
    fn check_expr(&self) -> Option<<Self::Ast as AstTypes<'a>>::Expr>;
    fn fk_clause(&self) -> Option<<Self::Ast as AstTypes<'a>>::ForeignKeyClause>;
}

/// Accessor trait for `CreateTableStmt` nodes.
pub trait CreateTableStmtView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn table_name(&self) -> &'a str;
    fn schema(&self) -> &'a str;
    fn is_temp(&self) -> bool;
    fn if_not_exists(&self) -> bool;
    fn flags(&self) -> <Self::Ast as AstTypes<'a>>::CreateTableStmtFlags;
    fn columns(
        &self,
    ) -> Option<
        TypedNodeList<
            'a,
            <Self::Ast as AstTypes<'a>>::Grammar,
            <Self::Ast as AstTypes<'a>>::ColumnDef,
        >,
    >;
    fn table_constraints(
        &self,
    ) -> Option<
        TypedNodeList<
            'a,
            <Self::Ast as AstTypes<'a>>::Grammar,
            <Self::Ast as AstTypes<'a>>::TableConstraint,
        >,
    >;
    fn as_select(&self) -> Option<<Self::Ast as AstTypes<'a>>::Select>;
}

/// Accessor trait for `CteDefinition` nodes.
pub trait CteDefinitionView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn cte_name(&self) -> &'a str;
    fn materialized(&self) -> <Self::Ast as AstTypes<'a>>::Materialized;
    fn columns(
        &self,
    ) -> Option<
        TypedNodeList<'a, <Self::Ast as AstTypes<'a>>::Grammar, <Self::Ast as AstTypes<'a>>::Expr>,
    >;
    fn select(&self) -> Option<<Self::Ast as AstTypes<'a>>::Select>;
}

/// Accessor trait for `WithClause` nodes.
pub trait WithClauseView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn recursive(&self) -> bool;
    fn ctes(
        &self,
    ) -> Option<
        TypedNodeList<
            'a,
            <Self::Ast as AstTypes<'a>>::Grammar,
            <Self::Ast as AstTypes<'a>>::CteDefinition,
        >,
    >;
    fn select(&self) -> Option<<Self::Ast as AstTypes<'a>>::Select>;
}

/// Accessor trait for `DeleteStmt` nodes.
pub trait DeleteStmtView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn table(&self) -> Option<<Self::Ast as AstTypes<'a>>::TableRef>;
    fn where_clause(&self) -> Option<<Self::Ast as AstTypes<'a>>::Expr>;
    fn orderby(
        &self,
    ) -> Option<
        TypedNodeList<
            'a,
            <Self::Ast as AstTypes<'a>>::Grammar,
            <Self::Ast as AstTypes<'a>>::OrderingTerm,
        >,
    >;
    fn limit_clause(&self) -> Option<<Self::Ast as AstTypes<'a>>::LimitClause>;
}

/// Accessor trait for `SetClause` nodes.
pub trait SetClauseView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn column(&self) -> &'a str;
    fn columns(
        &self,
    ) -> Option<
        TypedNodeList<'a, <Self::Ast as AstTypes<'a>>::Grammar, <Self::Ast as AstTypes<'a>>::Expr>,
    >;
    fn value(&self) -> Option<<Self::Ast as AstTypes<'a>>::Expr>;
}

/// Accessor trait for `UpdateStmt` nodes.
#[allow(clippy::wrong_self_convention)]
pub trait UpdateStmtView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn conflict_action(&self) -> <Self::Ast as AstTypes<'a>>::ConflictAction;
    fn table(&self) -> Option<<Self::Ast as AstTypes<'a>>::TableRef>;
    fn setlist(
        &self,
    ) -> Option<
        TypedNodeList<
            'a,
            <Self::Ast as AstTypes<'a>>::Grammar,
            <Self::Ast as AstTypes<'a>>::SetClause,
        >,
    >;
    fn from_clause(&self) -> Option<<Self::Ast as AstTypes<'a>>::TableSource>;
    fn where_clause(&self) -> Option<<Self::Ast as AstTypes<'a>>::Expr>;
    fn orderby(
        &self,
    ) -> Option<
        TypedNodeList<
            'a,
            <Self::Ast as AstTypes<'a>>::Grammar,
            <Self::Ast as AstTypes<'a>>::OrderingTerm,
        >,
    >;
    fn limit_clause(&self) -> Option<<Self::Ast as AstTypes<'a>>::LimitClause>;
}

/// Accessor trait for `InsertStmt` nodes.
pub trait InsertStmtView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn conflict_action(&self) -> <Self::Ast as AstTypes<'a>>::ConflictAction;
    fn table(&self) -> Option<<Self::Ast as AstTypes<'a>>::TableRef>;
    fn columns(
        &self,
    ) -> Option<
        TypedNodeList<'a, <Self::Ast as AstTypes<'a>>::Grammar, <Self::Ast as AstTypes<'a>>::Expr>,
    >;
    fn source(&self) -> Option<<Self::Ast as AstTypes<'a>>::Select>;
}

/// Accessor trait for `BinaryExpr` nodes.
pub trait BinaryExprView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn op(&self) -> <Self::Ast as AstTypes<'a>>::BinaryOp;
    fn left(&self) -> Option<<Self::Ast as AstTypes<'a>>::Expr>;
    fn right(&self) -> Option<<Self::Ast as AstTypes<'a>>::Expr>;
}

/// Accessor trait for `UnaryExpr` nodes.
pub trait UnaryExprView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn op(&self) -> <Self::Ast as AstTypes<'a>>::UnaryOp;
    fn operand(&self) -> Option<<Self::Ast as AstTypes<'a>>::Expr>;
}

/// Accessor trait for `Literal` nodes.
pub trait LiteralView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn literal_type(&self) -> <Self::Ast as AstTypes<'a>>::LiteralType;
    fn source(&self) -> &'a str;
}

/// Accessor trait for `FunctionCall` nodes.
pub trait FunctionCallView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn func_name(&self) -> &'a str;
    fn flags(&self) -> <Self::Ast as AstTypes<'a>>::FunctionCallFlags;
    fn args(
        &self,
    ) -> Option<
        TypedNodeList<'a, <Self::Ast as AstTypes<'a>>::Grammar, <Self::Ast as AstTypes<'a>>::Expr>,
    >;
    fn filter_clause(&self) -> Option<<Self::Ast as AstTypes<'a>>::Expr>;
    fn over_clause(&self) -> Option<<Self::Ast as AstTypes<'a>>::WindowDef>;
}

/// Accessor trait for `Variable` nodes.
pub trait VariableView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn source(&self) -> &'a str;
}

/// Accessor trait for `CollateExpr` nodes.
pub trait CollateExprView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn expr(&self) -> Option<<Self::Ast as AstTypes<'a>>::Expr>;
    fn collation(&self) -> &'a str;
}

/// Accessor trait for `RaiseExpr` nodes.
pub trait RaiseExprView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn raise_type(&self) -> <Self::Ast as AstTypes<'a>>::RaiseType;
    fn error_message(&self) -> Option<<Self::Ast as AstTypes<'a>>::Expr>;
}

/// Accessor trait for `QualifiedName` nodes.
pub trait QualifiedNameView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn object_name(&self) -> &'a str;
    fn schema(&self) -> &'a str;
}

/// Accessor trait for `DropStmt` nodes.
pub trait DropStmtView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn object_type(&self) -> <Self::Ast as AstTypes<'a>>::DropObjectType;
    fn if_exists(&self) -> bool;
    fn target(&self) -> Option<<Self::Ast as AstTypes<'a>>::QualifiedName>;
}

/// Accessor trait for `AlterTableStmt` nodes.
pub trait AlterTableStmtView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn op(&self) -> <Self::Ast as AstTypes<'a>>::AlterOp;
    fn target(&self) -> Option<<Self::Ast as AstTypes<'a>>::QualifiedName>;
    fn new_name(&self) -> &'a str;
    fn old_name(&self) -> &'a str;
}

/// Accessor trait for `TransactionStmt` nodes.
pub trait TransactionStmtView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn op(&self) -> <Self::Ast as AstTypes<'a>>::TransactionOp;
    fn trans_type(&self) -> <Self::Ast as AstTypes<'a>>::TransactionType;
}

/// Accessor trait for `SavepointStmt` nodes.
pub trait SavepointStmtView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn op(&self) -> <Self::Ast as AstTypes<'a>>::SavepointOp;
    fn savepoint_name(&self) -> &'a str;
}

/// Accessor trait for `ResultColumn` nodes.
pub trait ResultColumnView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn flags(&self) -> <Self::Ast as AstTypes<'a>>::ResultColumnFlags;
    fn alias(&self) -> &'a str;
    fn expr(&self) -> Option<<Self::Ast as AstTypes<'a>>::Expr>;
}

/// Accessor trait for `SelectStmt` nodes.
#[allow(clippy::wrong_self_convention)]
pub trait SelectStmtView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn flags(&self) -> <Self::Ast as AstTypes<'a>>::SelectStmtFlags;
    fn columns(
        &self,
    ) -> Option<
        TypedNodeList<
            'a,
            <Self::Ast as AstTypes<'a>>::Grammar,
            <Self::Ast as AstTypes<'a>>::ResultColumn,
        >,
    >;
    fn from_clause(&self) -> Option<<Self::Ast as AstTypes<'a>>::TableSource>;
    fn where_clause(&self) -> Option<<Self::Ast as AstTypes<'a>>::Expr>;
    fn groupby(
        &self,
    ) -> Option<
        TypedNodeList<'a, <Self::Ast as AstTypes<'a>>::Grammar, <Self::Ast as AstTypes<'a>>::Expr>,
    >;
    fn having(&self) -> Option<<Self::Ast as AstTypes<'a>>::Expr>;
    fn orderby(
        &self,
    ) -> Option<
        TypedNodeList<
            'a,
            <Self::Ast as AstTypes<'a>>::Grammar,
            <Self::Ast as AstTypes<'a>>::OrderingTerm,
        >,
    >;
    fn limit_clause(&self) -> Option<<Self::Ast as AstTypes<'a>>::LimitClause>;
    fn window_clause(
        &self,
    ) -> Option<
        TypedNodeList<
            'a,
            <Self::Ast as AstTypes<'a>>::Grammar,
            <Self::Ast as AstTypes<'a>>::NamedWindowDef,
        >,
    >;
}

/// Accessor trait for `OrderingTerm` nodes.
pub trait OrderingTermView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn expr(&self) -> Option<<Self::Ast as AstTypes<'a>>::Expr>;
    fn sort_order(&self) -> <Self::Ast as AstTypes<'a>>::SortOrder;
    fn nulls_order(&self) -> <Self::Ast as AstTypes<'a>>::NullsOrder;
}

/// Accessor trait for `LimitClause` nodes.
pub trait LimitClauseView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn limit(&self) -> Option<<Self::Ast as AstTypes<'a>>::Expr>;
    fn offset(&self) -> Option<<Self::Ast as AstTypes<'a>>::Expr>;
}

/// Accessor trait for `TableRef` nodes.
pub trait TableRefView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn table_name(&self) -> &'a str;
    fn schema(&self) -> &'a str;
    fn alias(&self) -> &'a str;
}

/// Accessor trait for `SubqueryTableSource` nodes.
pub trait SubqueryTableSourceView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn select(&self) -> Option<<Self::Ast as AstTypes<'a>>::Select>;
    fn alias(&self) -> &'a str;
}

/// Accessor trait for `JoinClause` nodes.
pub trait JoinClauseView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn join_type(&self) -> <Self::Ast as AstTypes<'a>>::JoinType;
    fn left(&self) -> Option<<Self::Ast as AstTypes<'a>>::TableSource>;
    fn right(&self) -> Option<<Self::Ast as AstTypes<'a>>::TableSource>;
    fn on_expr(&self) -> Option<<Self::Ast as AstTypes<'a>>::Expr>;
    fn using_columns(
        &self,
    ) -> Option<
        TypedNodeList<'a, <Self::Ast as AstTypes<'a>>::Grammar, <Self::Ast as AstTypes<'a>>::Expr>,
    >;
}

/// Accessor trait for `JoinPrefix` nodes.
pub trait JoinPrefixView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn source(&self) -> Option<<Self::Ast as AstTypes<'a>>::TableSource>;
    fn join_type(&self) -> <Self::Ast as AstTypes<'a>>::JoinType;
}

/// Accessor trait for `TriggerEvent` nodes.
pub trait TriggerEventView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn event_type(&self) -> <Self::Ast as AstTypes<'a>>::TriggerEventType;
    fn columns(
        &self,
    ) -> Option<
        TypedNodeList<'a, <Self::Ast as AstTypes<'a>>::Grammar, <Self::Ast as AstTypes<'a>>::Expr>,
    >;
}

/// Accessor trait for `CreateTriggerStmt` nodes.
pub trait CreateTriggerStmtView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn trigger_name(&self) -> &'a str;
    fn schema(&self) -> &'a str;
    fn is_temp(&self) -> bool;
    fn if_not_exists(&self) -> bool;
    fn timing(&self) -> <Self::Ast as AstTypes<'a>>::TriggerTiming;
    fn event(&self) -> Option<<Self::Ast as AstTypes<'a>>::TriggerEvent>;
    fn table(&self) -> Option<<Self::Ast as AstTypes<'a>>::QualifiedName>;
    fn when_expr(&self) -> Option<<Self::Ast as AstTypes<'a>>::Expr>;
    fn body(
        &self,
    ) -> Option<
        TypedNodeList<'a, <Self::Ast as AstTypes<'a>>::Grammar, <Self::Ast as AstTypes<'a>>::Stmt>,
    >;
}

/// Accessor trait for `CreateVirtualTableStmt` nodes.
pub trait CreateVirtualTableStmtView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn table_name(&self) -> &'a str;
    fn schema(&self) -> &'a str;
    fn module_name(&self) -> &'a str;
    fn if_not_exists(&self) -> bool;
    fn module_args(&self) -> &'a str;
}

/// Accessor trait for `PragmaStmt` nodes.
pub trait PragmaStmtView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn pragma_name(&self) -> &'a str;
    fn schema(&self) -> &'a str;
    fn value(&self) -> &'a str;
    fn pragma_form(&self) -> <Self::Ast as AstTypes<'a>>::PragmaForm;
}

/// Accessor trait for `AnalyzeOrReindexStmt` nodes.
pub trait AnalyzeOrReindexStmtView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn target_name(&self) -> &'a str;
    fn schema(&self) -> &'a str;
    fn kind(&self) -> <Self::Ast as AstTypes<'a>>::AnalyzeOrReindexOp;
}

/// Accessor trait for `AttachStmt` nodes.
pub trait AttachStmtView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn filename(&self) -> Option<<Self::Ast as AstTypes<'a>>::Expr>;
    fn db_name(&self) -> Option<<Self::Ast as AstTypes<'a>>::Expr>;
    fn key(&self) -> Option<<Self::Ast as AstTypes<'a>>::Expr>;
}

/// Accessor trait for `DetachStmt` nodes.
pub trait DetachStmtView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn db_name(&self) -> Option<<Self::Ast as AstTypes<'a>>::Expr>;
}

/// Accessor trait for `VacuumStmt` nodes.
pub trait VacuumStmtView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn schema(&self) -> &'a str;
    fn filename(&self) -> Option<<Self::Ast as AstTypes<'a>>::Expr>;
}

/// Accessor trait for `ExplainStmt` nodes.
pub trait ExplainStmtView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn explain_mode(&self) -> <Self::Ast as AstTypes<'a>>::ExplainMode;
    fn stmt(&self) -> Option<<Self::Ast as AstTypes<'a>>::Stmt>;
}

/// Accessor trait for `CreateIndexStmt` nodes.
pub trait CreateIndexStmtView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn index_name(&self) -> &'a str;
    fn schema(&self) -> &'a str;
    fn table_name(&self) -> &'a str;
    fn is_unique(&self) -> bool;
    fn if_not_exists(&self) -> bool;
    fn columns(
        &self,
    ) -> Option<
        TypedNodeList<
            'a,
            <Self::Ast as AstTypes<'a>>::Grammar,
            <Self::Ast as AstTypes<'a>>::OrderingTerm,
        >,
    >;
    fn where_clause(&self) -> Option<<Self::Ast as AstTypes<'a>>::Expr>;
}

/// Accessor trait for `CreateViewStmt` nodes.
pub trait CreateViewStmtView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn view_name(&self) -> &'a str;
    fn schema(&self) -> &'a str;
    fn is_temp(&self) -> bool;
    fn if_not_exists(&self) -> bool;
    fn column_names(
        &self,
    ) -> Option<
        TypedNodeList<'a, <Self::Ast as AstTypes<'a>>::Grammar, <Self::Ast as AstTypes<'a>>::Expr>,
    >;
    fn select(&self) -> Option<<Self::Ast as AstTypes<'a>>::Select>;
}

/// Accessor trait for `ValuesClause` nodes.
pub trait ValuesClauseView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn rows(
        &self,
    ) -> Option<
        TypedNodeList<
            'a,
            <Self::Ast as AstTypes<'a>>::Grammar,
            TypedNodeList<
                'a,
                <Self::Ast as AstTypes<'a>>::Grammar,
                <Self::Ast as AstTypes<'a>>::Expr,
            >,
        >,
    >;
}

/// Accessor trait for `FrameBound` nodes.
pub trait FrameBoundView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn bound_type(&self) -> <Self::Ast as AstTypes<'a>>::FrameBoundType;
    fn expr(&self) -> Option<<Self::Ast as AstTypes<'a>>::Expr>;
}

/// Accessor trait for `FrameSpec` nodes.
pub trait FrameSpecView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn frame_type(&self) -> <Self::Ast as AstTypes<'a>>::FrameType;
    fn exclude(&self) -> <Self::Ast as AstTypes<'a>>::FrameExclude;
    fn start_bound(&self) -> Option<<Self::Ast as AstTypes<'a>>::FrameBound>;
    fn end_bound(&self) -> Option<<Self::Ast as AstTypes<'a>>::FrameBound>;
}

/// Accessor trait for `WindowDef` nodes.
pub trait WindowDefView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn base_window_name(&self) -> &'a str;
    fn partition_by(
        &self,
    ) -> Option<
        TypedNodeList<'a, <Self::Ast as AstTypes<'a>>::Grammar, <Self::Ast as AstTypes<'a>>::Expr>,
    >;
    fn orderby(
        &self,
    ) -> Option<
        TypedNodeList<
            'a,
            <Self::Ast as AstTypes<'a>>::Grammar,
            <Self::Ast as AstTypes<'a>>::OrderingTerm,
        >,
    >;
    fn frame(&self) -> Option<<Self::Ast as AstTypes<'a>>::FrameSpec>;
}

/// Accessor trait for `NamedWindowDef` nodes.
pub trait NamedWindowDefView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn window_name(&self) -> &'a str;
    fn window_def(&self) -> Option<<Self::Ast as AstTypes<'a>>::WindowDef>;
}

/// Accessor trait for `FilterOver` nodes.
pub trait FilterOverView<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn node_id(&self) -> AnyNodeId;
    fn filter_expr(&self) -> Option<<Self::Ast as AstTypes<'a>>::Expr>;
    fn over_def(&self) -> Option<<Self::Ast as AstTypes<'a>>::WindowDef>;
    fn over_name(&self) -> &'a str;
}

/// Pattern-matching variants for `Select`.
#[derive(Clone, Copy)]
pub enum SelectKind<'a, A: AstTypes<'a>> {
    SelectStmt(A::SelectStmt),
    CompoundSelect(A::CompoundSelect),
    WithClause(A::WithClause),
    ValuesClause(A::ValuesClause),
    Other(A::Node),
}

/// Pattern-matching variants for `InExprSource`.
#[derive(Clone, Copy)]
pub enum InExprSourceKind<'a, A: AstTypes<'a>> {
    ExprList(TypedNodeList<'a, A::Grammar, A::Expr>),
    SubqueryExpr(A::SubqueryExpr),
    Other(A::Node),
}

/// Pattern-matching variants for `Expr`.
#[derive(Clone, Copy)]
pub enum ExprKind<'a, A: AstTypes<'a>> {
    BinaryExpr(A::BinaryExpr),
    UnaryExpr(A::UnaryExpr),
    Literal(A::Literal),
    ColumnRef(A::ColumnRef),
    Variable(A::Variable),
    FunctionCall(A::FunctionCall),
    AggregateFunctionCall(A::AggregateFunctionCall),
    OrderedSetFunctionCall(A::OrderedSetFunctionCall),
    CastExpr(A::CastExpr),
    CollateExpr(A::CollateExpr),
    CaseExpr(A::CaseExpr),
    IsExpr(A::IsExpr),
    BetweenExpr(A::BetweenExpr),
    LikeExpr(A::LikeExpr),
    InExpr(A::InExpr),
    SubqueryExpr(A::SubqueryExpr),
    ExistsExpr(A::ExistsExpr),
    RaiseExpr(A::RaiseExpr),
    Other(A::Node),
}

/// Pattern-matching variants for `Stmt`.
#[derive(Clone, Copy)]
pub enum StmtKind<'a, A: AstTypes<'a>> {
    SelectStmt(A::SelectStmt),
    CompoundSelect(A::CompoundSelect),
    ValuesClause(A::ValuesClause),
    WithClause(A::WithClause),
    InsertStmt(A::InsertStmt),
    UpdateStmt(A::UpdateStmt),
    DeleteStmt(A::DeleteStmt),
    CreateTableStmt(A::CreateTableStmt),
    CreateIndexStmt(A::CreateIndexStmt),
    CreateViewStmt(A::CreateViewStmt),
    CreateTriggerStmt(A::CreateTriggerStmt),
    CreateVirtualTableStmt(A::CreateVirtualTableStmt),
    DropStmt(A::DropStmt),
    AlterTableStmt(A::AlterTableStmt),
    TransactionStmt(A::TransactionStmt),
    SavepointStmt(A::SavepointStmt),
    PragmaStmt(A::PragmaStmt),
    AnalyzeOrReindexStmt(A::AnalyzeOrReindexStmt),
    AttachStmt(A::AttachStmt),
    DetachStmt(A::DetachStmt),
    VacuumStmt(A::VacuumStmt),
    ExplainStmt(A::ExplainStmt),
    Other(A::Node),
}

/// Pattern-matching variants for `TableSource`.
#[derive(Clone, Copy)]
pub enum TableSourceKind<'a, A: AstTypes<'a>> {
    TableRef(A::TableRef),
    SubqueryTableSource(A::SubqueryTableSource),
    JoinClause(A::JoinClause),
    JoinPrefix(A::JoinPrefix),
    Other(A::Node),
}

/// Abstract access trait for `Select`.
pub trait SelectLike<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn kind(&self) -> SelectKind<'a, Self::Ast>;
}

/// Abstract access trait for `InExprSource`.
pub trait InExprSourceLike<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn kind(&self) -> InExprSourceKind<'a, Self::Ast>;
}

/// Abstract access trait for `Expr`.
pub trait ExprLike<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn kind(&self) -> ExprKind<'a, Self::Ast>;
}

/// Abstract access trait for `Stmt`.
pub trait StmtLike<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn kind(&self) -> StmtKind<'a, Self::Ast>;
}

/// Abstract access trait for `TableSource`.
pub trait TableSourceLike<'a>: Copy {
    type Ast: AstTypes<'a>;
    fn kind(&self) -> TableSourceKind<'a, Self::Ast>;
}

/// Bundle trait associating all AST types for a dialect.
pub trait AstTypes<'a>: 'a {
    type Grammar: TypedGrammar;
    type Node: NodeLike<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type Select: SelectLike<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type InExprSource: InExprSourceLike<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type Expr: ExprLike<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type Stmt: StmtLike<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type TableSource: TableSourceLike<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type AggregateFunctionCall: AggregateFunctionCallView<'a, Ast = Self>
        + Copy
        + GrammarNodeType<'a>;
    type OrderedSetFunctionCall: OrderedSetFunctionCallView<'a, Ast = Self>
        + Copy
        + GrammarNodeType<'a>;
    type CastExpr: CastExprView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type ColumnRef: ColumnRefView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type CompoundSelect: CompoundSelectView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type SubqueryExpr: SubqueryExprView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type ExistsExpr: ExistsExprView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type InExpr: InExprView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type IsExpr: IsExprView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type BetweenExpr: BetweenExprView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type LikeExpr: LikeExprView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type CaseExpr: CaseExprView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type CaseWhen: CaseWhenView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type ForeignKeyClause: ForeignKeyClauseView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type ColumnConstraint: ColumnConstraintView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type ColumnDef: ColumnDefView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type TableConstraint: TableConstraintView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type CreateTableStmt: CreateTableStmtView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type CteDefinition: CteDefinitionView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type WithClause: WithClauseView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type DeleteStmt: DeleteStmtView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type SetClause: SetClauseView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type UpdateStmt: UpdateStmtView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type InsertStmt: InsertStmtView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type BinaryExpr: BinaryExprView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type UnaryExpr: UnaryExprView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type Literal: LiteralView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type FunctionCall: FunctionCallView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type Variable: VariableView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type CollateExpr: CollateExprView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type RaiseExpr: RaiseExprView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type QualifiedName: QualifiedNameView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type DropStmt: DropStmtView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type AlterTableStmt: AlterTableStmtView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type TransactionStmt: TransactionStmtView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type SavepointStmt: SavepointStmtView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type ResultColumn: ResultColumnView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type SelectStmt: SelectStmtView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type OrderingTerm: OrderingTermView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type LimitClause: LimitClauseView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type TableRef: TableRefView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type SubqueryTableSource: SubqueryTableSourceView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type JoinClause: JoinClauseView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type JoinPrefix: JoinPrefixView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type TriggerEvent: TriggerEventView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type CreateTriggerStmt: CreateTriggerStmtView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type CreateVirtualTableStmt: CreateVirtualTableStmtView<'a, Ast = Self>
        + Copy
        + GrammarNodeType<'a>;
    type PragmaStmt: PragmaStmtView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type AnalyzeOrReindexStmt: AnalyzeOrReindexStmtView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type AttachStmt: AttachStmtView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type DetachStmt: DetachStmtView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type VacuumStmt: VacuumStmtView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type ExplainStmt: ExplainStmtView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type CreateIndexStmt: CreateIndexStmtView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type CreateViewStmt: CreateViewStmtView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type ValuesClause: ValuesClauseView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type FrameBound: FrameBoundView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type FrameSpec: FrameSpecView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type WindowDef: WindowDefView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type NamedWindowDef: NamedWindowDefView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type FilterOver: FilterOverView<'a, Ast = Self> + Copy + GrammarNodeType<'a>;
    type LiteralType: LiteralTypeLike;
    type BinaryOp: BinaryOpLike;
    type UnaryOp: UnaryOpLike;
    type CompoundOp: CompoundOpLike;
    type IsOp: IsOpLike;
    type ForeignKeyAction: ForeignKeyActionLike;
    type GeneratedColumnStorage: GeneratedColumnStorageLike;
    type ColumnConstraintType: ColumnConstraintTypeLike;
    type TableConstraintType: TableConstraintTypeLike;
    type Materialized: MaterializedLike;
    type ConflictAction: ConflictActionLike;
    type RaiseType: RaiseTypeLike;
    type DropObjectType: DropObjectTypeLike;
    type AlterOp: AlterOpLike;
    type TransactionType: TransactionTypeLike;
    type TransactionOp: TransactionOpLike;
    type SavepointOp: SavepointOpLike;
    type SortOrder: SortOrderLike;
    type NullsOrder: NullsOrderLike;
    type JoinType: JoinTypeLike;
    type TriggerTiming: TriggerTimingLike;
    type TriggerEventType: TriggerEventTypeLike;
    type ExplainMode: ExplainModeLike;
    type PragmaForm: PragmaFormLike;
    type AnalyzeOrReindexOp: AnalyzeOrReindexOpLike;
    type FrameType: FrameTypeLike;
    type FrameBoundType: FrameBoundTypeLike;
    type FrameExclude: FrameExcludeLike;
    type AggregateFunctionCallFlags: AggregateFunctionCallFlagsLike;
    type CreateTableStmtFlags: CreateTableStmtFlagsLike;
    type FunctionCallFlags: FunctionCallFlagsLike;
    type ResultColumnFlags: ResultColumnFlagsLike;
    type SelectStmtFlags: SelectStmtFlagsLike;
}
