// Copyright 2025 The syntaqlite Authors. All rights reserved.
// Licensed under the Apache License, Version 2.0.

// Forward declarations for the lemon-generated parser API.
// The implementation lives in sqlite_parse.c (autogenerated by lemon
// with %name SyntaqliteParse).

#ifndef SYNTAQLITE_SQLITE_PARSER_H
#define SYNTAQLITE_SQLITE_PARSER_H

#include <stddef.h>
#include <stdio.h>

#include "csrc/parser.h"

#ifdef __cplusplus
extern "C" {
#endif

void* SyntaqliteParseAlloc(void* (*mallocProc)(size_t));
void SyntaqliteParseInit(void* parser);
void SyntaqliteParseFinalize(void* parser);
void SyntaqliteParseFree(void* parser, void (*freeProc)(void*));
void SyntaqliteParse(void* parser, int token_type, SyntaqliteToken minor,
                     SynqParseCtx* pCtx);
#ifndef NDEBUG
void SyntaqliteParseTrace(FILE* trace_file, char* prompt);
#endif

#ifdef __cplusplus
}
#endif

#endif  // SYNTAQLITE_SQLITE_PARSER_H
