#define SYNTAQLITE_TK_SEMI                             1
#define SYNTAQLITE_TK_EXPLAIN                          2
#define SYNTAQLITE_TK_QUERY                            3
#define SYNTAQLITE_TK_PLAN                             4
#define SYNTAQLITE_TK_BEGIN                            5
#define SYNTAQLITE_TK_TRANSACTION                      6
#define SYNTAQLITE_TK_DEFERRED                         7
#define SYNTAQLITE_TK_IMMEDIATE                        8
#define SYNTAQLITE_TK_EXCLUSIVE                        9
#define SYNTAQLITE_TK_COMMIT                          10
#define SYNTAQLITE_TK_END                             11
#define SYNTAQLITE_TK_ROLLBACK                        12
#define SYNTAQLITE_TK_SAVEPOINT                       13
#define SYNTAQLITE_TK_RELEASE                         14
#define SYNTAQLITE_TK_TO                              15
#define SYNTAQLITE_TK_TABLE                           16
#define SYNTAQLITE_TK_CREATE                          17
#define SYNTAQLITE_TK_IF                              18
#define SYNTAQLITE_TK_NOT                             19
#define SYNTAQLITE_TK_EXISTS                          20
#define SYNTAQLITE_TK_TEMP                            21
#define SYNTAQLITE_TK_LP                              22
#define SYNTAQLITE_TK_RP                              23
#define SYNTAQLITE_TK_AS                              24
#define SYNTAQLITE_TK_COMMA                           25
#define SYNTAQLITE_TK_WITHOUT                         26
#define SYNTAQLITE_TK_ABORT                           27
#define SYNTAQLITE_TK_ACTION                          28
#define SYNTAQLITE_TK_AFTER                           29
#define SYNTAQLITE_TK_ANALYZE                         30
#define SYNTAQLITE_TK_ASC                             31
#define SYNTAQLITE_TK_ATTACH                          32
#define SYNTAQLITE_TK_BEFORE                          33
#define SYNTAQLITE_TK_BY                              34
#define SYNTAQLITE_TK_CASCADE                         35
#define SYNTAQLITE_TK_CAST                            36
#define SYNTAQLITE_TK_CONFLICT                        37
#define SYNTAQLITE_TK_DATABASE                        38
#define SYNTAQLITE_TK_DESC                            39
#define SYNTAQLITE_TK_DETACH                          40
#define SYNTAQLITE_TK_EACH                            41
#define SYNTAQLITE_TK_FAIL                            42
#define SYNTAQLITE_TK_OR                              43
#define SYNTAQLITE_TK_AND                             44
#define SYNTAQLITE_TK_IS                              45
#define SYNTAQLITE_TK_ISNOT                           46
#define SYNTAQLITE_TK_MATCH                           47
#define SYNTAQLITE_TK_LIKE_KW                         48
#define SYNTAQLITE_TK_BETWEEN                         49
#define SYNTAQLITE_TK_IN                              50
#define SYNTAQLITE_TK_ISNULL                          51
#define SYNTAQLITE_TK_NOTNULL                         52
#define SYNTAQLITE_TK_NE                              53
#define SYNTAQLITE_TK_EQ                              54
#define SYNTAQLITE_TK_GT                              55
#define SYNTAQLITE_TK_LE                              56
#define SYNTAQLITE_TK_LT                              57
#define SYNTAQLITE_TK_GE                              58
#define SYNTAQLITE_TK_ESCAPE                          59
#define SYNTAQLITE_TK_ID                              60
#define SYNTAQLITE_TK_COLUMNKW                        61
#define SYNTAQLITE_TK_DO                              62
#define SYNTAQLITE_TK_FOR                             63
#define SYNTAQLITE_TK_IGNORE                          64
#define SYNTAQLITE_TK_INITIALLY                       65
#define SYNTAQLITE_TK_INSTEAD                         66
#define SYNTAQLITE_TK_NO                              67
#define SYNTAQLITE_TK_KEY                             68
#define SYNTAQLITE_TK_OF                              69
#define SYNTAQLITE_TK_OFFSET                          70
#define SYNTAQLITE_TK_PRAGMA                          71
#define SYNTAQLITE_TK_RAISE                           72
#define SYNTAQLITE_TK_RECURSIVE                       73
#define SYNTAQLITE_TK_REPLACE                         74
#define SYNTAQLITE_TK_RESTRICT                        75
#define SYNTAQLITE_TK_ROW                             76
#define SYNTAQLITE_TK_ROWS                            77
#define SYNTAQLITE_TK_TRIGGER                         78
#define SYNTAQLITE_TK_VACUUM                          79
#define SYNTAQLITE_TK_VIEW                            80
#define SYNTAQLITE_TK_VIRTUAL                         81
#define SYNTAQLITE_TK_WITH                            82
#define SYNTAQLITE_TK_NULLS                           83
#define SYNTAQLITE_TK_FIRST                           84
#define SYNTAQLITE_TK_LAST                            85
#define SYNTAQLITE_TK_CURRENT                         86
#define SYNTAQLITE_TK_FOLLOWING                       87
#define SYNTAQLITE_TK_PARTITION                       88
#define SYNTAQLITE_TK_PRECEDING                       89
#define SYNTAQLITE_TK_RANGE                           90
#define SYNTAQLITE_TK_UNBOUNDED                       91
#define SYNTAQLITE_TK_EXCLUDE                         92
#define SYNTAQLITE_TK_GROUPS                          93
#define SYNTAQLITE_TK_OTHERS                          94
#define SYNTAQLITE_TK_TIES                            95
#define SYNTAQLITE_TK_GENERATED                       96
#define SYNTAQLITE_TK_ALWAYS                          97
#define SYNTAQLITE_TK_MATERIALIZED                    98
#define SYNTAQLITE_TK_REINDEX                         99
#define SYNTAQLITE_TK_RENAME                         100
#define SYNTAQLITE_TK_CTIME_KW                       101
#define SYNTAQLITE_TK_ANY                            102
#define SYNTAQLITE_TK_BITAND                         103
#define SYNTAQLITE_TK_BITOR                          104
#define SYNTAQLITE_TK_LSHIFT                         105
#define SYNTAQLITE_TK_RSHIFT                         106
#define SYNTAQLITE_TK_PLUS                           107
#define SYNTAQLITE_TK_MINUS                          108
#define SYNTAQLITE_TK_STAR                           109
#define SYNTAQLITE_TK_SLASH                          110
#define SYNTAQLITE_TK_REM                            111
#define SYNTAQLITE_TK_CONCAT                         112
#define SYNTAQLITE_TK_PTR                            113
#define SYNTAQLITE_TK_COLLATE                        114
#define SYNTAQLITE_TK_BITNOT                         115
#define SYNTAQLITE_TK_ON                             116
#define SYNTAQLITE_TK_INDEXED                        117
#define SYNTAQLITE_TK_STRING                         118
#define SYNTAQLITE_TK_JOIN_KW                        119
#define SYNTAQLITE_TK_CONSTRAINT                     120
#define SYNTAQLITE_TK_DEFAULT                        121
#define SYNTAQLITE_TK_NULL                           122
#define SYNTAQLITE_TK_PRIMARY                        123
#define SYNTAQLITE_TK_UNIQUE                         124
#define SYNTAQLITE_TK_CHECK                          125
#define SYNTAQLITE_TK_REFERENCES                     126
#define SYNTAQLITE_TK_AUTOINCR                       127
#define SYNTAQLITE_TK_INSERT                         128
#define SYNTAQLITE_TK_DELETE                         129
#define SYNTAQLITE_TK_UPDATE                         130
#define SYNTAQLITE_TK_SET                            131
#define SYNTAQLITE_TK_DEFERRABLE                     132
#define SYNTAQLITE_TK_FOREIGN                        133
#define SYNTAQLITE_TK_DROP                           134
#define SYNTAQLITE_TK_UNION                          135
#define SYNTAQLITE_TK_ALL                            136
#define SYNTAQLITE_TK_EXCEPT                         137
#define SYNTAQLITE_TK_INTERSECT                      138
#define SYNTAQLITE_TK_SELECT                         139
#define SYNTAQLITE_TK_VALUES                         140
#define SYNTAQLITE_TK_DISTINCT                       141
#define SYNTAQLITE_TK_DOT                            142
#define SYNTAQLITE_TK_FROM                           143
#define SYNTAQLITE_TK_JOIN                           144
#define SYNTAQLITE_TK_USING                          145
#define SYNTAQLITE_TK_ORDER                          146
#define SYNTAQLITE_TK_GROUP                          147
#define SYNTAQLITE_TK_HAVING                         148
#define SYNTAQLITE_TK_LIMIT                          149
#define SYNTAQLITE_TK_WHERE                          150
#define SYNTAQLITE_TK_RETURNING                      151
#define SYNTAQLITE_TK_INTO                           152
#define SYNTAQLITE_TK_NOTHING                        153
#define SYNTAQLITE_TK_FLOAT                          154
#define SYNTAQLITE_TK_BLOB                           155
#define SYNTAQLITE_TK_INTEGER                        156
#define SYNTAQLITE_TK_VARIABLE                       157
#define SYNTAQLITE_TK_CASE                           158
#define SYNTAQLITE_TK_WHEN                           159
#define SYNTAQLITE_TK_THEN                           160
#define SYNTAQLITE_TK_ELSE                           161
#define SYNTAQLITE_TK_INDEX                          162
#define SYNTAQLITE_TK_ALTER                          163
#define SYNTAQLITE_TK_ADD                            164
#define SYNTAQLITE_TK_WINDOW                         165
#define SYNTAQLITE_TK_OVER                           166
#define SYNTAQLITE_TK_FILTER                         167
#define SYNTAQLITE_TK_COLUMN                         168
#define SYNTAQLITE_TK_AGG_FUNCTION                   169
#define SYNTAQLITE_TK_AGG_COLUMN                     170
#define SYNTAQLITE_TK_TRUEFALSE                      171
#define SYNTAQLITE_TK_FUNCTION                       172
#define SYNTAQLITE_TK_UPLUS                          173
#define SYNTAQLITE_TK_UMINUS                         174
#define SYNTAQLITE_TK_TRUTH                          175
#define SYNTAQLITE_TK_REGISTER                       176
#define SYNTAQLITE_TK_VECTOR                         177
#define SYNTAQLITE_TK_SELECT_COLUMN                  178
#define SYNTAQLITE_TK_IF_NULL_ROW                    179
#define SYNTAQLITE_TK_ASTERISK                       180
#define SYNTAQLITE_TK_SPAN                           181
#define SYNTAQLITE_TK_ERROR                          182
#define SYNTAQLITE_TK_QNUMBER                        183
#define SYNTAQLITE_TK_SPACE                          184
#define SYNTAQLITE_TK_COMMENT                        185
#define SYNTAQLITE_TK_ILLEGAL                        186
