// Copyright 2025 The syntaqlite Authors. All rights reserved.
// Licensed under the Apache License, Version 2.0.

//! Bootstrap command implementations.
//!
//! Each struct corresponds to one subcommand of the `syntaqlite-buildtools` binary.
//! The binary's `main.rs` constructs these structs and calls `.run()`.

use std::fs;
use std::io::Read;
use std::path::Path;

use crate::codegen_api::{
    AUTOGENERATED_MARKER, DialectCodegenJob, DialectNaming, MacroStyle, read_named_files_from_dir,
};
use crate::output_resolver::OutputLayout;

// Hardcoded workspace paths for the internal SQLite dialect.
const SQLITE_DIALECT_CRATE: &str = "syntaqlite-syntax";
const SQLITE_SHARED_CRATE: &str = "syntaqlite-syntax";
const SQLITE_FUNCTIONS_CATALOG: &str = "syntaqlite/src/sqlite/functions_catalog.rs";
const SQLITE_CFLAGS_RS: &str = "syntaqlite/src/sqlite/cflags.rs";
const SYNTAX_CFLAGS_RS: &str = "syntaqlite-syntax/src/sqlite/cflags.rs";

fn write_file(path: &Path, content: impl AsRef<[u8]>) -> Result<(), String> {
    fs::write(path, content).map_err(|e| format!("Failed to write {}: {}", path.display(), e))
}

fn ensure_dir(path: &Path, label: &str) -> Result<(), String> {
    fs::create_dir_all(path).map_err(|e| format!("Failed to create {label}: {e}"))
}

/// Delete any .c/.h files in `dir` whose first 512 bytes contain the autogenerated marker.
fn clean_generated_files(dir: &Path) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        let ext = path.extension().and_then(|e| e.to_str()).unwrap_or("");
        if ext != "c" && ext != "h" {
            continue;
        }
        let Ok(mut file) = fs::File::open(&path) else {
            continue;
        };
        let mut buf = [0u8; 512];
        let n = file.read(&mut buf).unwrap_or(0);
        let prefix = std::str::from_utf8(&buf[..n]).unwrap_or("");
        if prefix.contains(AUTOGENERATED_MARKER) {
            let _ = fs::remove_file(&path);
        }
    }
}

fn read_source(dir: &Path, name: &str) -> Result<String, String> {
    let path = dir.join(name);
    fs::read_to_string(&path).map_err(|e| format!("reading {}: {e}", path.display()))
}

// ── SqliteCodegen ─────────────────────────────────────────────────────────────

/// Regenerate the internal `SQLite` dialect C sources and Rust bindings (stage 2).
pub struct SqliteCodegen {
    /// Directory containing `.y` grammar action files.
    pub actions_dir: String,
    /// Directory containing `.synq` node definitions.
    pub nodes_dir: String,
}

impl SqliteCodegen {
    /// Run the command.
    ///
    /// # Errors
    ///
    /// Returns an error if codegen or file I/O fails.
    pub fn run(&self) -> Result<(), String> {
        let dialect = DialectNaming::new("sqlite");
        let y_files = read_named_files_from_dir(&self.actions_dir, "y")?;
        let synq_files = read_named_files_from_dir(&self.nodes_dir, "synq")?;

        let layout = OutputLayout::for_sqlite(
            Path::new("."),
            SQLITE_DIALECT_CRATE,
            SQLITE_SHARED_CRATE,
            dialect.name(),
            &dialect.include_dir_name(),
        );

        // Clean stale generated C/H files from C output directories.
        let csrc_dir = Path::new(SQLITE_DIALECT_CRATE).join("csrc/sqlite");
        let include_dir =
            Path::new(SQLITE_DIALECT_CRATE).join(format!("include/{}", dialect.include_dir_name()));
        let shared_include_dir =
            Path::new(SQLITE_SHARED_CRATE).join(format!("include/{}", dialect.include_dir_name()));
        for dir in [&csrc_dir, &include_dir, &shared_include_dir] {
            if dir.is_dir() {
                clean_generated_files(dir);
            }
        }

        DialectCodegenJob::new(&dialect, &y_files, &synq_files)
            .open_for_extension()
            .with_macro_style(MacroStyle::Rust)
            .with_rust("crate")
            .write_to(
                &layout,
                &|dir| ensure_dir(dir, "output directory"),
                &|path, content| write_file(path, content),
            )
    }
}

// ── SqliteParserCodegen ───────────────────────────────────────────────────────

/// Regenerate internal Rust artifacts for the `SQLite` parser crate (stage 1b).
pub struct SqliteParserCodegen {
    /// Path to functions.json. When provided, generates `functions_catalog.rs`.
    pub functions_json: Option<String>,
    /// Path to `version_cflags.json`. When provided, emits `MIN_VERSIONS` into cflags.rs.
    pub version_cflags_json: Option<String>,
}

impl SqliteParserCodegen {
    /// Run the command.
    ///
    /// # Errors
    ///
    /// Returns an error if codegen or file I/O fails.
    pub fn run(&self) -> Result<(), String> {
        // Load version map from JSON if provided.
        let version_map = self
            .version_cflags_json
            .as_deref()
            .map(crate::util::cflag_entries_codegen::load_version_map)
            .transpose()?;

        // Always regenerate both flag enums from the stable CFLAG_REGISTRY.
        crate::util::cflag_entries_codegen::write_sqlite_flag_rs(
            SQLITE_CFLAGS_RS,
            version_map.as_ref(),
        )?;
        crate::util::cflag_entries_codegen::write_syntax_flag_rs(SYNTAX_CFLAGS_RS)?;

        if let Some(json_path) = &self.functions_json {
            crate::util::functions_codegen::write_functions_catalog_file(
                json_path,
                SQLITE_FUNCTIONS_CATALOG,
            )?;
        }

        Ok(())
    }
}

// ── SqliteExtract ─────────────────────────────────────────────────────────────

/// Extract C fragments from raw `SQLite` source (stage 1).
pub struct SqliteExtract {
    /// Path to the `SQLite` source tree root (containing `src/` and `tool/`).
    pub sqlite_src: String,
    /// Output directory for vendored files.
    pub output_dir: String,
    /// Path to the parser-actions directory (containing `.y` files).
    pub actions_dir: String,
    /// Path to the parser-nodes directory (containing `.synq` files).
    pub nodes_dir: String,
}

impl SqliteExtract {
    /// Run the command.
    ///
    /// # Errors
    ///
    /// Returns an error if source files cannot be read or output cannot be written.
    pub fn run(&self) -> Result<(), String> {
        let root = Path::new(&self.sqlite_src);
        if !root.is_dir() {
            return Err(format!("{} is not a directory", self.sqlite_src));
        }

        let src = root.join("src");
        let tool_dir = root.join("tool");
        let out = Path::new(&self.output_dir);
        let sources_dir = out.join("sources");
        let fragments_dir = sources_dir.join("fragments");
        let data_dir = out.join("data");

        for dir in [&sources_dir, &fragments_dir, &data_dir] {
            fs::create_dir_all(dir).map_err(|e| format!("creating {}: {e}", dir.display()))?;
        }

        eprintln!("Vendoring SQLite tool sources...");
        for filename in &["lemon.c", "lempar.c", "mkkeywordhash.c"] {
            let src_path = tool_dir.join(filename);
            let dest_path = sources_dir.join(filename);
            fs::copy(&src_path, &dest_path).map_err(|e| {
                format!(
                    "copying {} -> {}: {e}",
                    src_path.display(),
                    dest_path.display()
                )
            })?;
            eprintln!("  {filename}");
        }

        eprintln!("Transforming mkkeywordhash.c...");
        let mkkeywordhash_c = read_source(&tool_dir, "mkkeywordhash.c")?;
        crate::extract::mkkeywordhash::write_modified_mkkeywordhash(
            &mkkeywordhash_c,
            &sources_dir.join("mkkeywordhash_modified.c"),
        )?;

        eprintln!("Extracting tokenizer fragments...");
        let tokenize_c = read_source(&src, "tokenize.c")?;
        let global_c = read_source(&src, "global.c")?;
        let sqliteint_h = read_source(&src, "sqliteInt.h")?;
        let fragments =
            crate::extract::tokenizer::extract_fragments(&tokenize_c, &global_c, &sqliteint_h)?;
        crate::extract::tokenizer::write_fragments(&fragments, &fragments_dir)?;

        eprintln!("Extracting keyword cflag data...");
        let cflags = crate::extract::keywords_and_parser::extract_keyword_cflags(&mkkeywordhash_c)?;
        crate::extract::keywords_and_parser::write_keyword_cflags(
            &cflags,
            &data_dir.join("cflags.json"),
        )?;

        eprintln!("Generating base_files_tables.rs...");
        let codegen_crate_dir = Path::new(&self.output_dir)
            .parent()
            .ok_or("output_dir has no parent")?;
        let tables_path = codegen_crate_dir.join("src/base_files_tables.rs");
        crate::extract::base_files::write_base_files_tables(
            Path::new(&self.actions_dir),
            Path::new(&self.nodes_dir),
            codegen_crate_dir,
            &tables_path,
        )?;

        eprintln!("Stage 1 complete. Output: {}", out.display());
        Ok(())
    }
}

// ── UpdateData ────────────────────────────────────────────────────────────────

/// Audit cflag availability and extract the function catalog from amalgamations.
///
/// Runs both phases in sequence:
///   1. Scan each amalgamation for cflag references → `version_cflags.json`.
///   2. Compile each amalgamation and query `PRAGMA function_list` → `functions.json`.
pub struct UpdateData {
    /// Directory containing amalgamations.
    pub amalgamation_dir: String,
    /// Output path for the cflag audit JSON (`version_cflags.json`).
    pub version_cflags_output: String,
    /// Output path for the function catalog JSON (`functions.json`).
    pub functions_output: String,
}

impl UpdateData {
    /// Run the command.
    ///
    /// # Errors
    ///
    /// Returns an error if amalgamation scanning, compilation, or file writing fails.
    pub fn run(&self) -> Result<(), String> {
        let amal_path = Path::new(&self.amalgamation_dir);
        if !amal_path.is_dir() {
            return Err(format!("{} is not a directory", self.amalgamation_dir));
        }

        eprintln!("Phase 1: Auditing cflags...");
        crate::extract::functions::audit_version_cflags(
            amal_path,
            Path::new(&self.version_cflags_output),
        )?;

        eprintln!("Phase 2: Extracting function catalog...");
        crate::extract::functions::extract_function_catalog(
            amal_path,
            Path::new(&self.version_cflags_output),
            Path::new(&self.functions_output),
        )
        .map(|_| ())
    }
}

// ── AnalyzeVersions ───────────────────────────────────────────────────────────

/// Analyze multiple `SQLite` source versions to find fragment variants.
pub struct AnalyzeVersions {
    /// Directory containing per-version `SQLite` source trees.
    pub sqlite_source_dir: String,
    /// Output directory for variant files.
    pub output_dir: String,
}

impl AnalyzeVersions {
    /// Run the command.
    ///
    /// # Errors
    ///
    /// Returns an error if source directories cannot be read or output cannot be written.
    pub fn run(&self) -> Result<(), String> {
        let source_dir = Path::new(&self.sqlite_source_dir);
        let out_dir = Path::new(&self.output_dir);

        fs::create_dir_all(out_dir).map_err(|e| format!("failed to create output dir: {e}"))?;

        let analysis = crate::version_analysis::analyze_versions(source_dir, out_dir)?;

        let json = serde_json::to_string_pretty(&analysis)
            .map_err(|e| format!("JSON serialization failed: {e}"))?;
        println!("{json}");

        eprintln!(
            "Analysis complete: {} versions, {} fragments analyzed",
            analysis.versions.len(),
            analysis.fragments.len()
        );
        for (name, frag) in &analysis.fragments {
            let errors = if frag.errors.is_empty() {
                String::new()
            } else {
                format!(", {} errors", frag.errors.len())
            };
            eprintln!("  {name}: {} variant(s){errors}", frag.variants.len());
        }
        eprintln!(
            "  keywords: {} total, {} addition points",
            analysis.keywords.total_keywords_latest,
            analysis.keywords.additions.len()
        );
        if let Some(ref grammar) = analysis.grammar {
            eprintln!(
                "  grammar: {} versions parsed, {} change points, {} errors",
                grammar.per_version.len(),
                grammar.diffs.len(),
                grammar.errors.len()
            );
        }
        eprintln!("Variant files written to {}", out_dir.display());

        if let Some(ref grammar) = analysis.grammar {
            let report = crate::version_analysis::grammar::format_grammar_report(grammar);
            let report_path = out_dir.join("grammar_report.md");
            fs::write(&report_path, &report)
                .map_err(|e| format!("write {}: {e}", report_path.display()))?;
            eprintln!("Grammar report written to {}", report_path.display());
        }

        Ok(())
    }
}
