// Copyright 2025 The syntaqlite Authors. All rights reserved.
// Licensed under the Apache License, Version 2.0.

// Shared modules (needed by both stage 1 and stage 2/3).
pub mod util;

// Stage 1: extraction from raw SQLite source (feature-gated).
#[cfg(feature = "sqlite-extract")]
pub mod extract;

// Stage 2/3: codegen pipeline (feature-gated).
#[cfg(feature = "codegen-pipeline")]
pub mod dialect_codegen;

#[cfg(feature = "codegen-pipeline")]
pub(crate) mod parser_tools;

// Re-export parser_tools submodules at crate root for API stability.
#[cfg(feature = "codegen-pipeline")]
pub use parser_tools::{amalgamate, base_files};

// SQLite-specific output routing (feature-gated).
#[cfg(feature = "sqlite-codegen")]
pub mod sqlite;

#[cfg(feature = "version-analysis")]
pub mod version_analysis;

#[cfg(feature = "grammar-verify")]
pub(crate) mod grammar_verify;

// --- Codegen pipeline types and functions (stage 2/3) ---

#[cfg(feature = "codegen-pipeline")]
mod codegen_api {
    use std::fs;

    pub const AUTOGENERATED_MARKER: &str = crate::util::c_writer::AUTOGENERATED_MARKER;

    use crate::parser_tools::{
        grammar_codegen, keyword_hash, mkkeyword, parser_pipeline, sqlite_fragments,
        tokenizer_assembly,
    };
    use crate::*;

    #[derive(Debug, Clone)]
    pub struct DialectNaming {
        name: String,
    }

    impl DialectNaming {
        pub fn new(name: impl Into<String>) -> Self {
            Self { name: name.into() }
        }

        pub fn name(&self) -> &str {
            &self.name
        }

        pub fn include_dir_name(&self) -> String {
            format!("syntaqlite_{}", self.name)
        }

        pub fn tokens_header_guard(&self) -> String {
            format!("SYNTAQLITE_{}_TOKENS_H", self.name.to_uppercase())
        }

        pub fn tokens_header_name(&self) -> String {
            format!("{}_tokens.h", self.name)
        }

        pub fn node_header_name(&self) -> String {
            format!("{}_node.h", self.name)
        }

        pub fn dialect_header_name(&self) -> String {
            format!("{}.h", self.name)
        }

        pub fn dialect_dispatch_header_name(&self) -> String {
            format!("{}_dialect_dispatch.h", self.name)
        }

        pub fn dialect_symbol_fn_name(&self) -> String {
            format!("syntaqlite_{}_dialect", self.name)
        }

        pub fn parser_symbol_prefix(&self) -> String {
            format!("Synq{}Parse", util::pascal_case(&self.name))
        }

        pub fn guarded_tokens_header(&self, tokens_content: &str) -> String {
            let guard = self.tokens_header_guard();
            format!(
                "/*\n\
                 ** The author disclaims copyright to this source code.  In place of\n\
                 ** a legal notice, here is a blessing:\n\
                 **\n\
                 **    May you do good and not evil.\n\
                 **    May you find forgiveness for yourself and forgive others.\n\
                 **    May you share freely, never taking more than you give.\n\
                 **\n\
                 ** @generated by syntaqlite-buildtools — DO NOT EDIT\n\
                 */\n\
                 \n\
                 #ifndef {guard}\n\
                 #define {guard}\n\
                 \n\
                 {tokens_content}\
                 \n\
                 #endif  // {guard}\n",
            )
        }
    }

    pub struct RustCodegenArtifacts {
        pub tokens_rs: String,
        pub ffi_rs: String,
        pub ast_rs: String,
        /// Shared AST trait definitions. Only generated for the internal syntaqlite
        /// crate; external dialect crates import from `syntaqlite::ast_traits`.
        pub ast_traits_rs: Option<String>,
        pub lib_rs: String,
        pub wrappers_rs: String,
        pub build_rs: String,
        pub cargo_toml: String,
        pub functions_catalog_rs: Option<String>,
    }

    pub struct CodegenArtifacts {
        pub parse_h: String,
        pub parse_api_h: String,
        pub parse_c: String,
        pub tokenize_c: String,
        pub keyword_c: String,
        pub keyword_h: String,
        pub ast_nodes_h: String,
        pub ast_builder_h: String,
        pub dialect_meta_h: String,
        pub dialect_fmt_h: String,
        pub dialect_tokens_h: String,
        pub dialect_c: String,
        pub dialect_h: String,
        pub dialect_dispatch_h: String,
        pub rust: Option<RustCodegenArtifacts>,
    }

    /// Parse `#define SYNTAQLITE_TK_NAME VALUE` lines from lemon's parse.h output.
    /// Returns structured `(name, value)` pairs where name is the short name (e.g. "ABORT").
    pub fn extract_token_defines(parse_h: &str) -> Vec<(String, u32)> {
        let mut tokens = Vec::new();
        for line in parse_h.lines() {
            let line = line.trim();
            if let Some(rest) = line.strip_prefix("#define SYNTAQLITE_TK_") {
                let mut parts = rest.split_whitespace();
                if let (Some(name), Some(value_str)) = (parts.next(), parts.next()) {
                    if let Ok(value) = value_str.parse::<u32>() {
                        tokens.push((name.to_string(), value));
                    }
                }
            }
        }
        tokens
    }

    pub struct TokenizerExtractResult {
        pub char_map: String,
        pub upper_to_lower: String,
    }

    pub struct CodegenRequest<'a> {
        pub dialect: &'a DialectNaming,
        pub y_files: &'a [(String, String)],
        pub synq_files: &'a [(String, String)],
        pub extra_keywords: &'a [String],
        pub parser_symbol_prefix: Option<&'a str>,
        pub include_rust: bool,
        /// Crate name for `Cargo.toml` (e.g. `"syntaqlite"`, `"syntaqlite-libsql"`).
        /// Only used when `include_rust` is true.
        pub crate_name: Option<&'a str>,
        /// Base .synq files for extension builds. When present, base items get
        /// pinned tags and extension items get tags after the base range.
        /// When `None`, all items from `synq_files` are treated as base.
        pub base_synq_files: Option<&'a [(&'a str, &'a str)]>,
        /// When `true`, the generated `Node<'a>` enum gets an `Other { id, tag }`
        /// variant for unknown tags (dialect extension support). When `false`,
        /// unknown tags are unreachable.
        pub open_for_extension: bool,
        /// Include path prefixes for `dialect.c`. Defaults to `""` for both
        /// internal and public — suitable for external dialect crates where
        /// all headers live in a single output directory.
        pub dialect_c_includes: dialect_codegen::DialectCIncludes<'a>,
    }

    /// Return the set of token names that are keywords in the base SQLite table.
    pub fn base_keyword_token_names() -> std::collections::HashSet<String> {
        mkkeyword::base_keyword_token_names()
    }

    /// Extract terminal symbols (potential keywords) from extension `.y` grammar files.
    pub fn extract_terminals_from_y(extension_y_contents: &[&str]) -> Vec<String> {
        use std::collections::HashSet;

        let mut terminals: HashSet<String> = HashSet::new();

        for content in extension_y_contents {
            let grammar = match util::grammar_parser::LemonGrammar::parse(content) {
                Ok(g) => g,
                Err(_) => continue,
            };

            for tok in &grammar.tokens {
                if is_keyword_like(tok.name) {
                    terminals.insert(tok.name.to_string());
                }
            }

            for fb in &grammar.fallbacks {
                for tok in &fb.tokens {
                    if is_keyword_like(tok) {
                        terminals.insert(tok.to_string());
                    }
                }
            }

            for rule in &grammar.rules {
                for sym in &rule.rhs {
                    if is_keyword_like(sym.name) && sym.name != "ID" {
                        terminals.insert(sym.name.to_string());
                    }
                }
            }
        }

        terminals.into_iter().collect()
    }

    fn is_keyword_like(name: &str) -> bool {
        name.len() >= 2 && name.chars().all(|c| c.is_ascii_uppercase())
    }

    #[cfg(test)]
    mod tests {
        use std::collections::BTreeSet;

        #[test]
        fn extract_terminals_collects_rhs_tokens_but_excludes_id() {
            let y = r#"
%token PERFETTO MACRO.
%fallback ID PERFETTO MODULE.
cmd ::= INCLUDE PERFETTO MODULE ID DOT ID.
cmd ::= CREATE PERFETTO MACRO ID LP RP AS ANY.
"#;
            let got: BTreeSet<String> = super::extract_terminals_from_y(&[y]).into_iter().collect();
            let want: BTreeSet<String> = [
                "ANY", "AS", "CREATE", "DOT", "INCLUDE", "LP", "MACRO", "MODULE", "PERFETTO", "RP",
            ]
            .into_iter()
            .map(str::to_string)
            .collect();
            assert_eq!(got, want);
            assert!(!got.contains("ID"));
        }
    }

    /// Concatenate in-memory .y file contents (already sorted by caller).
    pub fn concatenate_y_contents(files: &[(String, String)]) -> Result<Vec<u8>, String> {
        parser_pipeline::concatenate_y_contents(files)
    }

    /// Generate parser from in-memory .y file contents (merged base + extensions).
    pub fn generate_parser_from_contents(
        y_files: &[(String, String)],
        parser_name: &str,
        output_dir: &str,
    ) -> Result<(), String> {
        parser_pipeline::generate_parser_from_contents(y_files, parser_name, output_dir)
    }

    pub fn extract_grammar(input_path: &str, output_path: Option<&str>) -> Result<(), String> {
        grammar_codegen::extract_grammar(input_path, output_path)
    }

    pub fn generate_parser(
        actions_dir: &str,
        parser_name: &str,
        output_dir: &str,
    ) -> Result<(), String> {
        parser_pipeline::generate_parser(actions_dir, parser_name, output_dir)
    }

    fn parse_synq_items(
        synq_files: &[(String, String)],
    ) -> Result<Vec<util::synq_parser::Item>, String> {
        let mut all_items = Vec::new();
        for (name, content) in synq_files {
            let items =
                util::synq_parser::parse_synq_file(content).map_err(|e| format!("{name}: {e}"))?;
            all_items.extend(items);
        }
        Ok(all_items)
    }

    pub fn generate_codegen_artifacts(
        request: &CodegenRequest<'_>,
    ) -> Result<CodegenArtifacts, String> {
        let parser_name = request.parser_symbol_prefix.unwrap_or("SynqSqliteParse");

        let all_items = parse_synq_items(request.synq_files)?;

        // For extension builds, parse base and extension items separately.
        // Both vecs must outlive the AstModel, so declare them here.
        let base_items_owned: Vec<util::synq_parser::Item>;
        let ext_items_owned: Vec<util::synq_parser::Item>;

        let ast_model = if let Some(base_synq) = request.base_synq_files {
            let base_owned: Vec<(String, String)> = base_synq
                .iter()
                .map(|(n, c)| (n.to_string(), c.to_string()))
                .collect();
            base_items_owned = parse_synq_items(&base_owned)?;

            let base_names: std::collections::HashSet<&str> =
                base_synq.iter().map(|(n, _)| *n).collect();
            let ext_files: Vec<(String, String)> = request
                .synq_files
                .iter()
                .filter(|(n, _)| !base_names.contains(n.as_str()))
                .map(|(n, c)| (n.clone(), c.clone()))
                .collect();
            ext_items_owned = if ext_files.is_empty() {
                Vec::new()
            } else {
                parse_synq_items(&ext_files)?
            };

            dialect_codegen::AstModel::new_with_extensions(&base_items_owned, &ext_items_owned)
                .map_err(|e| format!("extension validation: {e}"))?
        } else {
            dialect_codegen::AstModel::new(&all_items)
        };

        let work_dir = tempfile::TempDir::new()
            .map_err(|e| format!("Failed to create temp directory: {e}"))?;
        parser_pipeline::generate_parser_from_contents(
            request.y_files,
            parser_name,
            work_dir.path().to_string_lossy().as_ref(),
        )?;
        let parse_h = fs::read_to_string(work_dir.path().join("parse.h"))
            .map_err(|e| format!("Failed to read parse.h: {e}"))?;
        let parse_c = fs::read_to_string(work_dir.path().join("parse.c"))
            .map_err(|e| format!("Failed to read parse.c: {e}"))?;

        // Assemble tokenizer and keyword hash from pre-extracted fragments.
        let fragments = sqlite_fragments::load();
        let (tokenize_c, extract_result) = tokenizer_assembly::assemble(
            &fragments,
            request.dialect.name(),
            &request.dialect_c_includes,
        )?;
        let keyword_c = keyword_hash::generate(
            &extract_result,
            &fragments,
            request.dialect.name(),
            request.extra_keywords,
        )?;
        let keyword_h = keyword_hash::generate_keyword_h();

        let ast_nodes_h =
            dialect_codegen::generate_ast_nodes_header(&ast_model, request.dialect.name());
        let ast_builder_h =
            dialect_codegen::generate_ast_builder_header(&ast_model, request.dialect.name());
        let dialect_meta_h = {
            let mut meta =
                dialect_codegen::generate_c_field_metadata(&ast_model, request.dialect.name())
                    .map_err(|e| e.to_string())?;
            let schema = dialect_codegen::generate_c_schema_contributions(&ast_model);
            if !schema.is_empty() {
                // Insert schema contributions before the header guard end.
                let guard_end = "#endif  // SYNTAQLITE_DIALECT_META_H";
                if let Some(pos) = meta.find(guard_end) {
                    meta.insert_str(pos, &schema);
                } else {
                    meta.push_str(&schema);
                }
            }
            meta
        };
        let dialect_fmt_h =
            dialect_codegen::generate_c_fmt_tables(&ast_model).map_err(|e| e.to_string())?;
        let token_defines = extract_token_defines(&parse_h);
        // Build keyword set from the base mkkeywordhash table + dialect extra keywords.
        let mut keyword_names = base_keyword_token_names();
        for kw in request.extra_keywords {
            keyword_names.insert(kw.to_uppercase());
        }
        let dialect_tokens_h =
            dialect_codegen::generate_token_categories_header(&token_defines, Some(&keyword_names));
        let parse_api_h =
            dialect_codegen::generate_parse_h(request.dialect.name(), &request.dialect_c_includes);
        let dialect_c = dialect_codegen::generate_dialect_c(
            request.dialect.name(),
            Some(&token_defines),
            &request.dialect_c_includes,
        );
        let dialect_h = dialect_codegen::generate_dialect_h(request.dialect.name());
        let dialect_dispatch_h =
            dialect_codegen::generate_dialect_dispatch_h(request.dialect.name());

        let rust = if request.include_rust {
            // For the internal syntaqlite crate, generated files use `crate::` paths.
            // For external dialect crates, they use `syntaqlite::` as an external dep.
            // For the internal syntaqlite crate, generated files live under
            // src/sqlite/ and use `crate::` / `crate::sqlite::ffi` paths.
            // For external dialect crates, they're at src/ and use
            // `syntaqlite::` / `crate::ffi` paths.
            let is_internal = request.crate_name == Some("syntaqlite");
            let crate_prefix = if is_internal { "crate" } else { "syntaqlite" };
            let ffi_path = if is_internal {
                "crate::sqlite::ffi"
            } else {
                "crate::ffi"
            };
            Some(RustCodegenArtifacts {
                tokens_rs: dialect_codegen::generate_rust_tokens(&token_defines[..]),
                ffi_rs: dialect_codegen::generate_rust_ffi_nodes(&ast_model, crate_prefix),
                ast_rs: dialect_codegen::generate_rust_ast(
                    &ast_model,
                    crate_prefix,
                    ffi_path,
                    request.dialect.name(),
                    request.open_for_extension,
                ),
                ast_traits_rs: if is_internal {
                    Some(dialect_codegen::generate_ast_traits(&ast_model))
                } else {
                    None
                },
                lib_rs: dialect_codegen::generate_rust_lib(
                    &request.dialect.dialect_symbol_fn_name(),
                ),
                wrappers_rs: dialect_codegen::generate_rust_wrappers(),
                build_rs: dialect_codegen::generate_rust_build_rs(request.dialect.name()),
                cargo_toml: dialect_codegen::generate_cargo_toml(
                    request.crate_name.unwrap_or(request.dialect.name()),
                ),
                functions_catalog_rs: None,
            })
        } else {
            None
        };

        Ok(CodegenArtifacts {
            parse_h,
            parse_api_h,
            parse_c,
            tokenize_c,
            keyword_c,
            keyword_h,
            ast_nodes_h,
            ast_builder_h,
            dialect_meta_h,
            dialect_fmt_h,
            dialect_tokens_h,
            dialect_c,
            dialect_h,
            dialect_dispatch_h,
            rust,
        })
    }

    pub fn read_named_files_from_dir(
        dir: &str,
        ext: &str,
    ) -> Result<Vec<(String, String)>, String> {
        let dir_path = std::path::Path::new(dir);
        if !dir_path.is_dir() {
            return Err(format!("{dir} is not a directory"));
        }

        let mut files: Vec<(String, String)> = fs::read_dir(dir_path)
            .map_err(|e| format!("Failed to read directory {dir}: {e}"))?
            .filter_map(|entry| {
                let path = entry.ok()?.path();
                if path.extension()?.to_str()? == ext {
                    let name = path.file_name()?.to_str()?.to_string();
                    let content = fs::read_to_string(&path).ok()?;
                    Some((name, content))
                } else {
                    None
                }
            })
            .collect();
        files.sort_by(|a, b| a.0.cmp(&b.0));
        Ok(files)
    }
}

#[cfg(feature = "codegen-pipeline")]
pub use codegen_api::*;

// --- SQLite-specific API (stage 2/3, sqlite-codegen only) ---

// Lemon and mkkeyword subprocess entry points — needed by any binary that
// calls generate_codegen_artifacts(), which spawns `current_exe() lemon/mkkeyword`.
#[cfg(feature = "codegen-pipeline")]
mod codegen_subcommands {
    use crate::parser_tools::{lemon, mkkeyword};

    pub fn run_lemon(args: &[String]) -> ! {
        lemon::run_lemon(args)
    }

    pub fn run_mkkeyword(args: &[String]) -> ! {
        mkkeyword::run_mkkeyword(args)
    }
}

#[cfg(feature = "codegen-pipeline")]
pub use codegen_subcommands::*;
